### ISSUE TITLE
"argument of type 'datetime.date' is not iterable" error when passing date var

### ISSUE THREAD

**Issue by tomekzbrozek** [fishtown-analytics/dbt#1003]
### Issue description
I expected the date (`2018-09-13`) to be passed as date var to my model's query, but received an error. I noticed that when I pass it as a string (but only in double quotes, like `"2018-09-13"`, it works fine.

### Results
See above / below.

### System information
The output of `dbt --version`:
```
installed version: 0.10.1
   latest version: 0.11.0
```

The operating system you're running on:
Mac OS High Sierra 10.13.4

The python version you're using (probably the output of `python --version`)
3.6.2

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

I spoke with Drew Bain on Slack group, and this info might be useful for anyone who tries to investigate this issue:

"
drew.banin [3 hours ago]
I’m trying to reproduce this locally but it actually fails for me with a _different_ issue! I get:
```Encountered an error:
datetime.date(2018, 1, 1) is not JSON serializable```

drew.banin [3 hours ago]
So, dbt definitely doesn’t like that this thing comes through as a date instead of a string. I think that conversion actually happens when yaml parses your `dbt_project.yml` file, not inside of dbt itself

drew.banin [3 hours ago]
One other idea comes to mind though — can you try something like this?
```{% set start_date = var('start_date').isoformat() %}```

tomek [3 hours ago]
didn’t work with the isoformat neither :disappointed:
"

**Comment by drewbanin** [comment]
thanks @tomekzbrozek! We'll take a look!

**Comment by beckjake** [comment]
I get very different behavior here - I'm not saying it's good or desirable behavior, but:
```
$ cat models/x.sql
{% set start_date = var('start_date') %}
select {{ start_date }} as when
$ dbt run --vars "{start_date: '2018-09-13'}" # or '{start_date: "2018-09-13"}', or '{start_date: 2018-09-13}, etc
Running with dbt=0.13.0
Found 1 models, 0 tests, 1 archives, 0 analyses, 101 macros, 0 operations, 0 seed files, 1 sources

08:54:29 | Concurrency: 2 threads (target='default')
08:54:29 |
08:54:29 | 1 of 1 START view model dbt_postgres.x............................... [RUN]
08:54:29 | 1 of 1 OK created view model dbt_postgres.x.......................... [CREATE VIEW in 0.08s]
08:54:29 |
08:54:29 | Finished running 1 view models in 0.41s.
$ psql -c 'select * from dbt_postgres.x'
 when
------
 1996
(1 row)
```

So, what database is this? What do the models/macros in question actually look like to trigger this error? Is this even an issue anymore? We do [serialize `date`s properly now](https://github.com/fishtown-analytics/dbt/blob/8270c85ffd0fe04310449e8fa75bb98b5b20a5a5/core/dbt/utils.py#L445-L456), so maybe it's fixed?

**Comment by drewbanin** [comment]
@beckjake haha, i think the problem with your example is just that you're missing quotes in x.sql! 

```
2018 - 09 - 13 = 1996
```

I gave this a spin too - it definitely looks like we're serializing dates correctly now. Closing this one as fixed :)
