### ISSUE TITLE
backtrace is printed to the CLI if exception is raised before logger is initialized

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1015]
I didn't catch this originally, but it looks like error logging behavior changed during the configuration object PR. Specifically, this line: https://github.com/fishtown-analytics/dbt/blame/dev/guion-bluford/dbt/main.py#L96

We definitely shouldn't throw away the backtrace if logging isn't yet initialized, but I think we can do better than printing a backtrace to the terminal. I'm curious if we can either initialize logging earlier, or suppress backtraces for exceptions raised by dbt directly, like validation errors. I'm open to keeping backtraces for unhandled exceptions

**Comment by beckjake** [comment]
Ugh, I added that during debugging and forgot to remove it.

You basically can't build the logger until you've parsed the config object (it is one place where the default log directory is set). So on any errors related to config parsing you must lose the stacktrace unless you dump it to stdout/stderr.

Maybe the log directory should not be project-configurable.

**Comment by cmcarthur** [comment]
only print stack traces on unhandled errors, dbt-generated errors can just be printed normally
