### ISSUE TITLE
Make printer width configurable

### ISSUE THREAD

**Issue by jon-rtr** [fishtown-analytics/dbt#1026]
### Feature description

When executing, `dbt run`, I find that the printer width (hardcoded to 80) is too small given the length of my schema and table names. I would like to make this configurable so that the results (RUN, SUCCESS, FAIL, SKIP) align in a column on the right-hand side instead of being staggered.

Here is the relevant line:
https://github.com/fishtown-analytics/dbt/blob/6454a81593e0311ac1d796b43f95a32cb8be4b53/dbt/ui/printer.py#L62

### Example

default width of 80
```
11:02:57 | Concurrency: 4 threads (target='stg_dbt')
11:02:57 | 
11:02:57 | 1 of 3 START table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_DAILY_TEMP.... [RUN]
11:07:23 | 1 of 3 OK created table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_DAILY_TEMP [SUCCESS 1 in 265.90s]
11:07:23 | 2 of 3 START table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_DAILY [RUN]
11:07:58 | 2 of 3 OK created table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_DAILY [SUCCESS 1 in 34.27s]
11:07:58 | 3 of 3 START table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_MONTHLY [RUN]
11:08:18 | 3 of 3 OK created table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_MONTHLY [SUCCESS 1 in 20.77s]
11:08:18 | 
11:08:18 | Finished running 3 table models in 327.56s.
```

hand-updated width of 120
```
11:02:57 | Concurrency: 4 threads (target='stg_dbt')
11:02:57 | 
11:02:57 | 1 of 3 START table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_DAILY_TEMP............................................ [RUN]
11:07:23 | 1 of 3 OK created table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_DAILY_TEMP....................................... [SUCCESS 1 in 265.90s]
11:07:23 | 2 of 3 START table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_DAILY..................................... [RUN]
11:07:58 | 2 of 3 OK created table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_DAILY................................ [SUCCESS 1 in 34.27s]
11:07:58 | 3 of 3 START table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_MONTHLY................................... [RUN]
11:08:18 | 3 of 3 OK created table model DBT_SCRATCH_PUBLIC.TOTAL_UNIT_TIME_SERIES_MONTHLY.............................. [SUCCESS 1 in 20.77s]
11:08:18 | 
11:08:18 | Finished running 3 table models in 327.56s.
```

### Who will this benefit?

Anyone else who has long names and wants more readable console output.

**Comment by drewbanin** [comment]
hah, this is a great idea @jon-rtr! I've wanted to improve the stdout for a while, possibly also doing something like [this](https://smallguysit.com/index.php/2017/12/16/overwriting-line-console-output-python/) to collapse the RUN and SUCCESS lines, but I can't think of a good way to do that with multithreading. I think expanding the output width is a good start :)

**Comment by jon-rtr** [comment]
Sounds good.

I would also love to have this same output emitted as JSON, a la snowplow analytics, so that I can run analyses on our pipelines (how meta).

We use Splunk, so maybe that emission could be configurable? Maybe it starts as a separate file that can then be forwarded to an arbitrary endpoint using a small amount of glue code?

**Comment by drewbanin** [comment]
Fixed in https://github.com/fishtown-analytics/dbt/pull/1459 via https://github.com/fishtown-analytics/dbt/pull/1247
