### ISSUE TITLE
Error creating my first project

### ISSUE THREAD

**Issue by asakchhamawi** [fishtown-analytics/dbt#1029]
It's my first time using dbt and have installed python, git for windows and dbt. 

Then I am trying to create my first project but getting an error below. Please help. 

C:\Users\>dbt init [Marketing]
Creating dbt configuration folder at C:\Users\r631115\.dbt
Encountered an error:
[WinError 3] The system cannot find the path specified: 'Marketing\\.git'

**Comment by drewbanin** [comment]
Hi @asakchhamawi - I'm very happy to help you get set up with dbt, but we tend to use GitHub for issue and feature tracking. Have you checked out the [dbt slack](http://slack.getdbt.com)? If you're able to join in there, you can feel free to post in the support channel and I'll happily help you out!

Thanks!
