### ISSUE TITLE
compilation errors in ephemeral models skip downstream models

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1037]
### Issue description
If a compilation error occurs in an ephemeral model, downstream models will be `skip`'d with no information about the original error. Instead, dbt should surface the error message from the ephemeral model.

### Results
Models downstream of the ephemeral models are skipped, but no error is shown for the ephemeral model.

### System information
0.11+

**Comment by beckjake** [comment]
Fixed in #1053
