### ISSUE TITLE
Add ability to document macros

### ISSUE THREAD

**Issue by dwallace0723** [fishtown-analytics/dbt#1041]
### Feature description
Currently, dbt's native [documentation](https://docs.getdbt.com/docs/documentation) functionality is built around the concept of documenting _models_. it would be equally as useful to have the ability to document _macros_. 

### Who will this benefit?
Anyone who leverages macros, especially within a large data org.

**Comment by ArvindEnvoy** [comment]
👍

**Comment by drewbanin** [comment]
Thanks @dwallace0723. I figure we can:
1. Enumerate the macros defined in a project
2. Expose the macro code
3. Expose models that call that macro

Do you imagine also writing markdown docs for macros? Or do you think that inline comments are sufficient? We don't currently have a mechanism for documenting macros, and I don't think it would make sense to extend the `schema.yml` syntax.

Maybe there's a tie-in here: https://github.com/fishtown-analytics/dbt/issues/979?

**Comment by dwallace0723** [comment]
@drewbanin I do think there is a tie-in to #979. I think documenting the macro inline via a docs block would be a perfectly fine solution here.

**Comment by Fokko** [comment]
Looking for this as well :-)

**Comment by beckjake** [comment]
Fixed in #2068

**Comment by Fokko** [comment]
Sweet! 👏
