### ISSUE TITLE
Remove Relation.table_name field

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1044]
## (Anti-)Feature
Remove the `table_name` field from relations.

### Feature description
Currently relations have a `table_name` field distinct from `identifier`, that is actually always the same as its `identifier` field. In the past it was used for temp table things but now it has no reason to exist, and adds some level of complexity.

Up for consideration on removal: the backwards-compatibility properites of `name` and `table`.

### Who will this benefit?
Anyone trying to understand the adapter/relation interface and behavior, maintainers trying to keep things behaving the same.

**Comment by drewbanin** [comment]
this was removed in v0.15.0
