### ISSUE TITLE
Limit IP Address binding and ssl - dbt docs serve

### ISSUE THREAD

**Issue by tony-caffe** [fishtown-analytics/dbt#1045]
Please make sure to fill out either the issue template or the feature template and delete the other one!

## Feature

When issuing dbt docs serve command, dbt binds to 0.0.0.0. This allows all ips on the server to host this web page. Also, HTTP is only used for this service as well.

### Feature description
It would be nice to have more control, if not full control, over the internal web servers, which I dont know what software this even uses to host, but I would like to host this in my own already setup apache on CentOS to host this static page myself. Having user auth and HTTPS for this would be a nice way to secure this page, whether hosted internal ip or external ip. Documentation does not help in this configuration nor focus on security. I would prefer to not send this data to S3 and keep it within the web server locally.

### Results
if you issue ss -l command, it will show all interfaces set to 8080.

### System information
The output of `dbt --version`:
```
installed version: 0.11.1
   latest version: 0.11.1

Up to date!
```

The operating system you're running on: Amazon Linux

The python version you're using (probably the output of `python --version`): Python 2.7.14

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

```
$ dbt docs serve
Serving docs at 0.0.0.0:8080
To access from your browser, navigate to http://localhost:8080.
Press Ctrl+C to exit.
```

### Who will this benefit?
Any ORG that wants security and control out of the box by overriding the defaults.

**Comment by cmcarthur** [comment]
hi @tony-caffe, this is intended to be a simple way to serve up the docs site. You can run a webserver of your choice out of the `target/` directory of your dbt project after `dbt docs generate` for right now.

we'll still take a look at this issue, just wanted to let you know that there's a workaround here

**Comment by drewbanin** [comment]
Hi @tony-caffe - thanks for a great question. You can check out relevant documentation here:
**dbt docs command reference**: https://docs.getdbt.com/v0.11/reference#docs
**dbt docs guide**: https://docs.getdbt.com/v0.11/docs/documentation-website#section-hosting-the-documentation-site

^ I linked specifically to more information about hosting the docs, but the rest of that guide explores the different components of dbt's documentation functionality, and should help clarify the "static site" nature of the docs.

I'd recommend generating docs in the same flow you use to deploy your models. If you're issuing `dbt run ...` from cron, then it could be a good idea to append a `dbt docs generate` command to the script you're using. That way, your docs are always up-to-date with the state of your warehouse.

You also mentioned:
> It would be nice to have more control, if not full control, over the internal web servers, which I dont know what software this even uses to host, but I would like to host this in my own already setup apache on CentOS to host this static page myself.

dbt uses a webserver that's built-in to Python -- the code is [here](https://github.com/fishtown-analytics/dbt/blob/dev/guion-bluford/dbt/task/serve.py#L28) if you want to take a look. This is pretty light-weight, and indeed, it's really only intended for local development.

If you already have a webserver running, then you're in good shape! Simply copy the the `*.json` files and the `index.html` file in your `target/` directory to a path that's served by Apache, and then you should be able to view the docs in your browser. There are no moving parts here, and there's no backend process running -- `dbt docs serve` simply serves up the `index.html` page and the associated `.json` files.

Finally, you noted: 
> Having user auth and HTTPS for this would be a nice way to secure this page, whether hosted internal ip or external ip

I totally agree here, but I think this is outside the scope of what dbt can/should provide. I'm _super_ interested in providing great documentation around this bit of dbt functionality, and some more practical examples for deploying the docs would be really helpful here too.

I'm very happy to discuss any of these points, and I'll have a chat with @cmcarthur about the topics you raised in this issue as well. Thanks!

**Comment by tony-caffe** [comment]
Thank you! I set up a cron to run the dbt generate and I symlinked the data to an apache vhost directory, adjusted some permissions and I was able to secure the access.

**Comment by drewbanin** [comment]
I've updated the docs around hosting the documentation site and added a callout regarding the security of the development `dbt docs serve` webserver: https://docs.getdbt.com/docs/documentation-website#section-deploying-the-documentation-site

Going to close this, but happy to discuss if anyone has any questions

**Comment by tony-caffe** [comment]
If you need some help with Apache 2.4.x setup, here is a stripped down version of my vhost config to assist.

# Symlink to custom or apache directory
```
ln -s /path/to/dbt/target /var/www/html/dbt
```

# Crontab Example
```
50 23 * * * dbt docs --target /path/to/dbt/data_models/ generate
```

# Example Vhost for Apache 2.4.x
```
$ cat /etc/httpd/conf.d/dbt.conf
Listen {Specific-IP}:{Sample-common-port-8080}

<VirtualHost {Specific-IP}:{Sample-common-port-8080}>
	DocumentRoot "/var/www/html"
        ServerName {Specific-IP-or-Server-Domain-Name}/dbt
        # Custom Log File for vhost:
        ErrorLog /var/log/dbt/error.log
        CustomLog /var/log/dbt/access.log combined
	<Directory "/var/www/html">
                Options +Indexes +FollowSymLinks +MultiViews
		#DirectoryIndex index.html
                AllowOverride All
                Require all granted
        </Directory>
        SSLEngine on
        SSLCertificateFile /path/to/ssl.crt
        SSLCertificateKeyFile /path/to/ssl.key
</VirtualHost>
```
