### ISSUE TITLE
`dbt --help` should be more helpful

### ISSUE THREAD

**Issue by mikekaminsky** [fishtown-analytics/dbt#1058]
### Issue description

`dbt --help` is not actually super helpful. It'd be great it (at least) `dbt --help` listed basic descriptions for all of the commands (`init`, `clean` `debug`) etc. 

### Results
```
usage: dbt: data build tool [-h] [--version] [-d] [-S]
                            {init,clean,debug,deps,archive,run,compile,docs,seed,test}
                            ...

positional arguments:
  {init,clean,debug,deps,archive,run,compile,docs,seed,test}

optional arguments:
  -h, --help            show this help message and exit
  --version             Show version information
  -d, --debug           Display debug logging during dbt execution. Useful for
                                debugging and making bug reports.
  -S, --strict          Run schema validations at runtime. This will surface
                                bugs in dbt, but may incur a performance penalty.
```

### System information
The output of `dbt --version`:
```
installed version: 0.11.1
   latest version: 0.11.1
```

### Who will this benefit?

New users and people just getting started with DBT.  It's also helpful for experienced users who may not have been keeping up with all of the new features. Additionally, as we add more commands and the syntax gets more complex, it's nice to have a solid reference on the command line so you don't have to open up the docs in a browser.

**Comment by drewbanin** [comment]
Fixed in #1060
