### ISSUE TITLE
throw a better error when a user tries to archive a nonexistent table

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1066]
### Issue description
If a user tries to archive a non-existent table, dbt shows an error like:
```
Relation None not found!
```

Instead, this should show the name of the relation which was not found. It should also contextualize that this error occurred during archival.

### Results
Saw:
```
Relation None not found!
```

Would like:
```
Error while running archive:
The relation to archive, `{schema}.{table}` was not found! Check that the relation exists, and that your user has permissions to select from this relation,
```

### System information
The output of `dbt --version`:
```
0.11.x
```

**Comment by beckjake** [comment]
A fun side effect of the new archive blocks feature is that this is magically fixed! 🎉 

Because archives are now queries instead of configured, dbt just takes the raw query and tries to perform it, and the database gives you a pretty helpful error (well, I think so!):
```
Completed with 1 errors:

Database Error in archive foo (archives/test.sql)
  relation "not_a_schema.not_a_table" does not exist
  LINE 8:     select * from not_a_schema.not_a_table where status = 'c...
```
