### ISSUE TITLE
Full BigQuery load errors are neither logged nor displayed for dbt seed

### ISSUE THREAD

**Issue by joshtemple** [fishtown-analytics/dbt#1076]
### Issue description
Upon running `dbt seed` for a specific CSV file, the load to BigQuery fails. dbt prints the output as follows:
```
  Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the error stream for more details.
```

Unfortunately, this message doesn't provide the root cause of the error (i.e. the issues encountered loading the CSV file). I don't see any additional detail in `dbt.log` beyond what's printed.

I've used the BigQuery Python SDK before for load jobs, and this looks like the output from `job.result()`. However, the job object has an additional attribute called `errors`, which contains the detailed description of the load error. In this past I've handled this with a try/catch block on job creation that raises the full error when a generic API exception is caught. I believe this is what should be logged or surfaced to the user. Happy to attempt a PR if you can point me roughly to where this code lives in dbt!

### System information
The output of `dbt --version`:
```
installed version: 0.11.0
   latest version: 0.11.1
```

The operating system you're running on: Mac OS Mojave

The python version you're using (probably the output of `python --version`) Python 3.4.3

**Comment by drewbanin** [comment]
Thanks for the report @joshtemple!

**Comment by joshtemple** [comment]
@drewbanin, would you mind pointing me to where this code exists in dbt? I'd be happy to attempt a fix, I think it would be relatively quick.

**Comment by beckjake** [comment]
@joshtemple this is the python code that loads csvs into bigquery: https://github.com/fishtown-analytics/dbt/blob/dev/guion-bluford/dbt/adapters/bigquery/impl.py#L604-L621

That error message must come from bigquery itself, I don't see it anywhere in dbt.

**Comment by joshtemple** [comment]
Cool, thanks @beckjake. I've submitted #1079 to address this.
