### ISSUE TITLE
make the hub site work!

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#1095]
TODO:
- [x] Create a process to update the hub site index (with a PR) when new releases are cut for known packages
- [x] Update documentation to encourage the use of the hub site
- [x] Backfill package versions into the hub site index

**Comment by drewbanin** [comment]
closing this as the hub site is now functionally working! There's a cron job that updates the hub site from new github releases every hour. Sufficient for now, but worthy of further investment in the future.
