### ISSUE TITLE
Add a mechanism for "wrapping" SQL across materializations

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1096]
### Feature description
dbt should make it possible/easy to wrap the model sql that gets executed in a materialization.

Use cases:
 - inject a git hash and invocation timestamp into incremental models
 - add `where _fivetran_deleted is not null` to all base models
 - add `limit 0` for only CI runs
 - inject a comment to the top of every model (using vars)

Some questions:
- Where should this live?
- In each materialization?
- Or should it be handled by dbt?
- What's a tenable syntax for defining these wrappers?
- Can there be multiple levels of wrapping?

### Implementation

In order for this to be really useful, users should be able to apply a wrapper macro to whole groups of models all at once. As such, I think a reasonable implementation is to specify a `wrap_sql` config in `dbt_project.yml`. This `wrap_sql` parameter can either be a string, or a list of strings, indicating the name of the macro(s) to call. Eg:

```
models:
  my_project:
    base:
      materialized: view
      wrap_sql: [filter_deleted, add_user]
```

Example macros:

**Option 1: Supply the model as an argument**
```
{% macro filter_deleted(model) %}

select * from (
  {{ model.compiled_sql }} -- or similar
) as sbq

where not sbq.is_deleted

{% endmacro %}
```

**Option 2: Just supply `sql` as an argument**
```
{% macro add_user(sql) %}

-- Run by: {{ target.user }}
-- example 2: 
{{ sql }}

{% endmacro %}
```

I'm not certain where the best place to call these macros is, nor do I have super strong opinions on the exact interface for these macros. Whatever we choose, we should be really explicit about what the context is :)

**Comment by drewbanin** [comment]
closing due to lack of interest

**Comment by kconvey** [comment]
Bummed to see this one closed! A use case I found for it is having a collection of models to run, which you sometimes want to apply a filter to, but it would be tedious to modify all of them (i.e. `SELECT * FROM {{ model.compiled_sql }} as wrapped WHERE wrapped.id > 1000`
