### ISSUE TITLE
use `create or replace table` in Snowflake table materialization

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1101]
### Feature description
dbt should use the `create or replace table` syntax in its Snowflake table materialization.

Presently, dbt's Snowflake table materialization runs by:
1. creating a table with a tmp suffix
2. renaming the old table out of the way
3. renaming the new table into place

Since Snowflake's transactions aren't serializable, a query issued against Snowflake between steps 2 and 3 will result in an error.

Instead, dbt should use `create or replace table` for tables (as it currently does for [views](https://github.com/fishtown-analytics/dbt/blob/371e8b438ab0939f000e3844162c50644f19d6d8/dbt/include/global_project/macros/materializations/view/bq_snowflake_view.sql#L22)) to atomically replace a table.

### Who will this benefit?
Snowflake users who run dbt frequently

**Comment by bastienboutonnet** [comment]
working snowflake adaptor for this. discussed with @drewbanin will be submitting PR soon 🎉

**Comment by drewbanin** [comment]
Fixed in #1409
