### ISSUE TITLE
support mssql as an adapter

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1115]
### Feature description
dbt should work with [mssql](https://www.microsoft.com/en-us/sql-server/sql-server-2016). Someone familiar with mssql should fill out [this survey](https://github.com/fishtown-analytics/dbt/wiki/New-Adapter-Information-Sheet) and paste the results in here.

### Who will this benefit?
mssql users

**Comment by pietrocasella** [comment]
https://gist.github.com/pietrocasella/5f2fa08dc62d607c1201a2409ec96e12

**Comment by nielsenbe** [comment]
I'd be willing to take this project on.  I'm a SQL Server expert (literally a Microsoft Certified Solution Expert in SQL Server).  I've read through the Adapter and contributing docs.

**Comment by drewbanin** [comment]
@nielsenbe great! I think @cmcarthur should have been in touch with you about next steps. This is super exciting :)

**Comment by feriksen** [comment]
@nielsenbe - I'd be more then happy to contribute as well, Think I've forgotten more T-SQL, DMV's and information_schema + sys tables then most people care to know. Been doing ms sql since 6.5...

Was/am looking into the documentation for building an adapter myself, and am working my way through the existing base sql adapter etc to get an idea of what is required.

**Comment by mdunndata** [comment]
has anyone made any progress on this?  I'm starting to poke around a bit, but feel a bit out of my depth, and I don't want to duplicate work others have already done.

**Comment by jornh** [comment]
@mdunndata - see some first few steps by @nielsenbe with currently 5 commits at https://github.com/nielsenbe/dbt/commits/dev/stephen-girard

**Comment by jacobm001** [comment]
I have a 1.0 release of an mssql adapter working. It has passed all the tests on the integration test suite.

https://github.com/jacobm001/dbt-mssql

**Comment by drewbanin** [comment]
FYI for plugin maintainers: #1655

**Comment by drewbanin** [comment]
well, I suppose in a lot of ways, this issue is complete :)

Closing, deferring to
- https://github.com/jacobm001/dbt-mssql
- https://github.com/mikaelene/dbt-sqlserver
