### ISSUE TITLE
Add helper methods for setting pre-and post-hooks

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1125]
### Feature description
See also https://github.com/fishtown-analytics/dbt/issues/558

Presently, in-model hook definitions need to be set in a `{{ config() }}` block. This isn't the most natural place for long-form SQL. Instead, dbt should provide a set of helper macros for setting pre- and post- hooks. For example:

```
{{ config(materialized='table') }}

{{ post_hook("grant select on {{ this }}" to db_reader") }}
{{ post_hook(some_complex_macro()} }}
```

This will also be a nice interface for inclusion in higher-level macros.

### Who will this benefit?
Users with many model-specific hooks.

**Comment by jakebiesinger** [comment]
IMHO, variables would probably handle this more easily and without work from you:

```SQL
{% set post_hook %}
  {% for role in ['db_reader', 'db_writer'] %}
    grant select on {{ this }} to {{ role }}
  {% endfor %}
{% endset %}

{{ config({ 'materialized': 'table', 'post-hook': post_hook}) }}
```

probably deserves an update to your documentation though, since folks may not know about multi-line `set` blocks.
