### ISSUE TITLE
Watch command for dbt run

### ISSUE THREAD

**Issue by epkatz** [fishtown-analytics/dbt#1126]
### Feature description
I want a watch command for `dbt run`. 
I imagine this would work similar to something like nodemon in node. When writing code, it's often helpful to have an immediate watch and reload cycle. 

### Who will this benefit?
Anyone who needs to continuously run `dbt run` when making changes to see whether the changes took effect.

**Comment by epkatz** [comment]
e.g. https://nodemon.io/

**Comment by drewbanin** [comment]
Thanks for the request @epkatz!

Do you think that every time a model is saved, dbt should re-run that model? I imagine this could be a neat workflow, but it might be pretty taxing for the database. I think the nodemon/livereload workflow works _really_ well in web dev contexts, but I'm not sure how well it would hold up if a rebuild takes more then a couple of seconds.

Curious to hear your thoughts about the logistics of how this could work

**Comment by drewbanin** [comment]
Going to close this one out @epkatz, but happy to reopen if you can get back to me with some more info
