### ISSUE TITLE
Snowflake quoting not working for archive tables in 0.12

### ISSUE THREAD

**Issue by foundinblank** [fishtown-analytics/dbt#1130]
Edit: Drew Banin 3/23/19

Todo: Confirm that archival abides by the quoting config specified in `dbt_project.yml`

If this is the case, then I believe we can close this issue

-----
Original issue:

## Issue
`dbt archive` on Snowflake now throws an error due to quoting (I think) in 0.12.

### Issue description
dbt archive looks for uppercase schema/table names but in dbt_project.yml, `source_table` and `source_schema` are lowercase. This wasn't a problem in <= 0.11 but is now a problem in 0.12. Maybe it forgot about the model quoting settings in dbt_project_yml? Or something else. 

**Changing `source_schema` and `source_table` to uppercase in dbt_project.yml resolves the error.** 

### Results
```
Compilation Error in archive people_archived (dbt_project.yml)
When searching for a relation, dbt found an approximate match. Instead of guessing 
which relation to use, dbt will move on. Please delete analytics.people, or rename it to be less ambiguous.
Searched for: ANALYTICS.PEOPLE
Found: analytics.people

> in macro materialization_archive_default (macros/materializations/archive/archive.sql)
> called by archive people_archived (dbt_project.yml)
```

### System information
The output of `dbt --version`:
```
installed version: 0.12.0
   latest version: 0.12.0
```

**Comment by drewbanin** [comment]
Hey @foundinblank - thanks for the report! I don't believe this code has changed since 0.11.0, but we can definitely take a look.

I'm glad that you found a workaround in uppercasing the table names in `dbt_project.yml`. We're pretty due for an overhaul of [archival](https://github.com/fishtown-analytics/dbt/issues?q=is%3Aissue+is%3Aopen+label%3Aarchive).

If you can dig up any more info about what happened here, or if this issue persists, definitely let us know!

**Comment by drewbanin** [comment]
Archives in >= 0.14.0 will be defined from `select` statements. Quoting should be handled by:
1. using source quoting appropriately
2. quoting the source table name as needed

I never got to the bottom of which change happened here (sorry @foundinblank!) but the recommend approach is to case archive source table/schema/database exactly as they appear in the database when defining them in the `dbt_project.yml` file
