### ISSUE TITLE
dbt compile / run is really slow

### ISSUE THREAD

**Issue by luck02** [fishtown-analytics/dbt#1137]
Please make sure to fill out either the issue template or the feature template and delete the other one!

## Issue
when I issue a `dbt run --models etc.folders` or `dbt run ...` it takes as much as a minute or three to complete.

### Issue description
`dbt run --models etc.model` or `dbt compile --models etc.model`

### Results
There are about 65 models in that directory and I would expect those to run in a reasonable time (5-15 seconds?) 

It actually takes closer to 2-3 minutes.

### System information
The output of `dbt --version`:
```
installed version: 0.11.1
   latest version: 0.12.1
```

The operating system you're running on:
`OSX 10.13.6 (17G2307)`

The python version you're using (probably the output of `python --version`)
`Python 2.7.10`
### Steps to reproduce
run dbt compile / run in a larger project.

In this case we have about 400 models total in the project, and about 65 in the folder I'm trying to compile.  

### Ask:
Is this normal execution time and is expected?  It's problematic as we're working with some autogenerated models and I'm trying to exclude the generated files that came out with issues (unrelated problem).  DBT only compiles to the first failure which means I have to wait a couple of minutes for my feedback loop.  

Are there any changes  I could make that would expedite my execution?  Thanks!

--edit-- 
I am aware that v0.12.11 is released and we'll upgrade soon-ish... However our production is still on 0.11.1 and I'd like to be in sync with prod.  However is 0.12 has improvements that will help I'd definitely move now.

**Comment by luck02** [comment]
hrm, 12.1 isn't available on brew just yet.

**Comment by luck02** [comment]
Ok, @drewbanin 12.1 is much faster, thanks for the headsup!

**Comment by drewbanin** [comment]
@luck02 awesome, glad to hear it! We're making speed one of our priorities going forwards. More to come on that front with https://github.com/fishtown-analytics/dbt/pull/1128 and https://github.com/fishtown-analytics/dbt/pull/1020

**Comment by luck02** [comment]
I mean, don't get me wrong, it's not super fast either but it's much better...  Still on the slow side.  Thanks for helping me out!

**Comment by Savbrom** [comment]
Hi guys, I was wondering if anybody could help me. When running the klaviyo package for dbt and setting the lookback window to 7 days (336 hours),  all dbt models are executed except the last one. Visual Studio Code stops running before all models could be built. Any suggestions?
