### ISSUE TITLE
Populate RDBMS Object Comment schema.yml Description

### ISSUE THREAD

**Issue by norton120** [fishtown-analytics/dbt#1170]
### Feature description
The description key in schema.yml files is currently used to populate DBT docs. This feature would be to materialize the description values in the RDBMS as object comments (the "comment" value in `information_schema.columns` for columns, `information_schema.tables` for tables etc). 

### Who will this benefit?
Persisting this information into the RDBMS will make it possible to query this additional table meta - so BI tools can easily build consumer-facing rich data catalogs.

**Comment by norton120** [comment]
Bonus points: I typically build out JSON formatted strings in the db comments with keys like "comment", "grain" (for tables), "repo version added" - it could be interesting to do the same thing here, maybe populate a JSON object string with "description" and "schema tests" - so BI users can easily review the tests applied to the data set.

**Comment by drewbanin** [comment]
See also: #1031

**Comment by drewbanin** [comment]
Closing in favor of https://github.com/fishtown-analytics/dbt/issues/1031
