### ISSUE TITLE
tab-complete arguments to --models and --exclude

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1197]
### Feature description
dbt should support tab-completion of model names in the `--models` and `--exclude` CLI arguments. This may prove difficult as dbt would need to know about all of the models on disk in order to provide completion suggestions. One option may be to use the manifest as a cache of existing model names. That would work well in many cases, but would also exclude brand-new models.

The `--models` and `--exclude` flags also accept `tag:` qualifiers. I'm unsure if the first version of this needs to account for tags, but that would certainly be nice!

### Who will this benefit?
dbt users are increasingly implementing standards around how they name models. A very typical model may be named `stg_server_event_active_pings`, which is a whole lot of typing! dbt should encourage the use of descriptive model names, and the requirement to type out the exact model name when providing `--models` is a chore.

**Comment by mikekaminsky** [comment]
Huge fan of this! In case it's helpful, here's how it was implemented in our similar-to-DBT project at Harry's: [link](https://github.com/harrystech/arthur-redshift-etl/blob/b76a5cd21ba230a386358bdd852969ac88bd6799/etc/arthur_completion.sh)

**Comment by joshtemple** [comment]
Since dbt is using `argparse`, any thoughts on using the [argcomplete](https://argcomplete.readthedocs.io/en/latest/) library as a means of accomplishing this?

**Comment by drewbanin** [comment]
Hey @mikekaminsky @joshtemple - check out this repo: https://github.com/fishtown-analytics/dbt-completion.bash

This works super well on macOS + Bash, but might need some more love to get it working in other OS's or shells! Wanted to give you guys a sneak preview for commenting on the issue -- will post about this in Slack at some point tomorrow :)
