### ISSUE TITLE
dbt cross-source dependency conflicts

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1213]
## Issue
dbt packages don't (always? ever?) properly compare versions when the same packages come from two different sources.

### Issue description
Imagine a case where a project's pacakges.yml look like this:

```
packages:
 - package: fishtown-analytics/dbt-utils
   version: 0.1.19
 - local: ../other-package
```

And then `../other-package/packages.yml` looks like this:

```
packages:
 - git: https://github.com/fishtown-analytics/dbt-utils
    revision: 0.0.1
```

Doing `dbt deps` will result in both of those dependencies being downloaded!

dbt will happily decide to download both the `git` and `package` versions of dbt-utils, put them both into the directory in dependency resolution order.

### Results
note: as of my writing this, the hubsite exposes the wrong value for the `name` field, so you get both `dbt_utils` and `dbt-utils`. I'll discuss it as if that were fixed.

dbt downloaded both `dbt-utils`, and then put them both in the `dbt_modules` folder, with the second (git) version overwriting the first (hubsite) version. In particular, the version specified in the child dependency wins.

I expected dbt to throw an error about incompatible versions when it encountered the second dependency with the same project name. Something like this:

```
Version error for package fishtown-analytics/dbt-utils: Could not find a satisfactory version from 
options: ['=0.1.19', '=0.0.1']
```

Or equally reasonable, something like this that tells me I can't mix and match:

```
Compatibility error for package fishtown-anaylytics/dbt-utils: A package with this name already exists from a different source type ({'git': 'https://github.com/fishtown-analytics/dbt-utils', 'revision': '0.0.1'})
```

### System information
dbt >= 0.12.2
Any OS

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

**Comment by beckjake** [comment]
Once the hubsite is updated, we get this (much better) error:
```
Encountered an error
Found duplicate project dbt_utils. This occurs when a dependency has the same project name as some other dependency.
```

That's good enough!

**Comment by louisguitton** [comment]
> note: as of my writing this, the hubsite exposes the wrong value for the name field, so you get both dbt_utils and dbt-utils. I'll discuss it as if that were fixed.

That `dbt-utils` tricked me and was raising the errors. When I switched it to `dbt_utils` everything was fine.
I get that you want to be backward compatible and keep the old spelling on the hub, but just want to point that I just ran into this and most likely other people are as well.
