### ISSUE TITLE
Jinja variables not shared across DBT models

### ISSUE THREAD

**Issue by MarcelvanVliet** [fishtown-analytics/dbt#1235]
### Issue description
I'm working with the salesforce model you have created in github.
When a variable such as:
```{%- set history_fields = [
    'probability',
    'stage_name',
    'forecast_category',
    'amount',
    'expected_revenue',
    'currency_iso_code'
    ] -%}
```
is defined in a model e.g. sf_opportunity_history_unioned.sql and a second model such as sf_opportunity_history_daily.sql refers to it, DBT does not appear to be able to reference the variable in the second model, causing the Jinja templating in the second model to not work as intended.

Additionally when defining a new variable and attempting to reference the original variables such as:
```{%- set next_models_template_columns = history_fields + custom_fields -%}```
Then the DBT compile fails with Encountered an error:
```Compilation Error in model sf_opportunity_history_daily (models/transform/sf_opportunity_history_daily.sql)
  'history_fields' is undefined
```

### Results
DBT variables were not available between models as expected from using the Salesforce model.

### System information
The output of `dbt --version`:
```
installed version: 0.12.2
   latest version: 0.12.2

Up to date!
```

The operating system you're running on:
Mac Mojave 10.14.1
The python version you're using (probably the output of `python --version`)
Python 3.5.0 :: Continuum Analytics, Inc.

### Steps to reproduce
As above

**Comment by drewbanin** [comment]
hey @MarcelvanVliet - variables like [history_fields](https://github.com/fishtown-analytics/salesforce/blob/42f606016a87d9cb51003efafd8a26c7229fad31/models/transform/sf_opportunity_history_unioned.sql#L1) are scoped locally to the model where they're defined. The behavior you're seeing is intended, and I don't think there's a bug here.

I think that we'll want continue to scope these variables locally, though dbt does have a higher-level concept of `var`s which you can find out more about [here](https://docs.getdbt.com/docs/using-variables). These are similar to the functionality you're looking for, but they're not exactly the same. For one: variables are scoped _down_ in the dependency tree, so if your project includes the salesforce package, there's no way for your project to reference the variables defined inside of the salesforce package. That is: the variables are pushed _down_, not _up_ to parent packages.

I'd be interested in exploring how we can push variables _up_, but I don't know that we currently have an issue for that. Going to close this issue out insofar as we don't intend to make the change you're asking for here, but very happy to discuss other ways to accomplish this type of workflow!
