### ISSUE TITLE
dbt should only create schemas for models that are being run

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1239]
### Issue description
dbt creates all of the schemas for models in a project, even if only a subset of the models have been selected with `--models`. Instead, dbt should only create the schemas for models which are invoked in a given run.

### Results
dbt created every custom schema defined in a dbt project, even though I only selected one model with `--models`.

### System information
dbt version: 0.13.0-a1
python version: 3.7.2
python path: /Users/drew/fishtown/dbt/env/bin/python3
os info: Darwin-18.2.0-x86_64-i386-64bit

Note: This affects versions before 0.13.0-a1, and appears to affect at least 0.12.1 and 0.12.2 (but possibly older versions too)

### Steps to reproduce
1. drop all of the schemas in your test database
2. create the following models
```
-- models/model_1.sql

{{ config(schema='schema_1') }}

select 1 as id
```

```
-- models/model_2.sql

{{ config(schema='schema_2') }}

select 1 as id
```

```
-- models/model_3.sql

{{ config(schema='schema_3') }}

select 1 as id
```

3. Invoke only a single model:
```
dbt run --model model_1
```

4. Observe that schemas `schema_1`, `schema_2`, and `schema_3` have been created

**Comment by clausherther** [comment]
We create a few models for specific purposes in separate Snowflake database (call it other_db) from the rest of the analytical data warehouse. However, we manage this from the same dbt repo we use for the DW to reuse code and base models. 
When we run a job for just these models (--target other_db), it creates all the schemas in the other_db database, not just the one we need for these particular models.
