### ISSUE TITLE
Add CLI flag to toggle warnings as errors

### ISSUE THREAD

**Issue by kingfink** [fishtown-analytics/dbt#1243]
### Feature description
We're running `dbt compile` as part of our CI process. Unfortunately when we get `WARNING`s (i.e. schema test can't find the model), they are ignored. Users should be able to add a CLI flag to count warnings as errors (i.e. `-werror` [here](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html))

To get around this today, we run a bash script that contains:

```
#!/bin/sh

n=`grep 'WARNING' /app/dbt/logs/dbt.log | wc -l`

if [ $n -gt 0 ]
then
    echo $n compile warnings
    exit 1
fi
```

### Who will this benefit?
This would benefit anyone who wants to run checks as part of their dbt CI process. Helps ensure tests in production are being run.

**Comment by clausherther** [comment]
This would also be great to have exposed in dbt Cloud, so jobs don't "fail" silently when there's nothing to do. This is sometimes the case after well-meant reorg efforts that change model locations and leave `-m model` filters grabbing empties.

**Comment by drewbanin** [comment]
@clausherther yeah, i picture this being a CLI flag (just like `-werror` as shown above). This would make the behavior consistent across local development, dbt cloud, or any other deployments of dbt.

I think we'll need to do some find/replace to make sure we catch all of the warnings, but I don't think this will be too gnarly an issue
