### ISSUE TITLE
Support model selection syntax for sources

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1256]
## Feature
dbt should support running dependents of 'sources' from the model selection syntax, as described at the bottom of #814 

### Feature description
Currently sources don't actually participate in the graph at all, so that's the first thing to do. Once that's done, add a new selector filter and implementation.

### Who will this benefit?
This will help flesh out the sources feature.

**Comment by drewbanin** [comment]
We have a decent mechanism in place for handling custom "selector filters" [here](https://github.com/fishtown-analytics/dbt/blob/dev/stephen-girard/core/dbt/graph/selector.py#L162). While it's not super difficult to just keep adding entries to this dict, I'm super open to doing this differently if there's some better mechanism you can think of.

One thing to note: We support model selection in the dbt docs site, which means that I have to re-implement any model selection logic in JS :p. I don't _love_ that long-term, but I think it's ok for now.

Lmk if there's anything in here that I can clarify!
