### ISSUE TITLE
Feature: Command line output after dbt clean

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#1261]
At the moment when you `dbt clean`, there's no output to tell you it was successful.
Something like this would be helpful:
```
Cleaning target/*
 Cleaned target/*

Cleaning dbt_modules/*
 Cleaned dbt_modules/*
```
I think this could be a really good issue for a newcomer!

**Comment by clrcrl** [comment]
@kasanchez – would you be interested in taking this one? It's only a few lines of code to add!

**Comment by kasanchez** [comment]
yes!

**Comment by kasanchez** [comment]
passing this to Emilie :)
