### ISSUE TITLE
dbt_project.yml materilized option not working

### ISSUE THREAD

**Issue by rrbarbosa** [fishtown-analytics/dbt#1265]
### Issue description
Setting `materialized: table` on the models `source-paths` have not effect.

### Results
All modes in a `source-paths` folder to be materialized as tables.

### System information
The output of `dbt --version`:
```
installed version: 0.12.2
   latest version: 0.12.2

Up to date!
```

The operating system you're running on: MacOS Mojave  10.14.2

The python version you're using (probably the output of `python --version`): 3.7.2

Backend-database: Redshift

### Steps to reproduce

1. create a new project with `dbt init my_project`
2. edit`my_project/dbt_project.yml` and replace the last line with `materliazed: table`.
3. run `dbt run`
4. check that `my_first_dbt_model` is created as a view

**Comment by drewbanin** [comment]
Hi @rrbarbosa - good point! When you run `dbt init`, dbt will just clone this [starter dbt project](https://github.com/fishtown-analytics/dbt-starter-project).

I can see the config you're referring to in `dbt_project.yml` [here](https://github.com/fishtown-analytics/dbt-starter-project/blob/master/dbt_project.yml#L35).

The reason this doesn't work how you're expecting is that the `my_first_dbt_model` has an in-model config defined [here](https://github.com/fishtown-analytics/dbt-starter-project/blob/master/models/example/my_first_dbt_model.sql#L7). Configs defined inside of a model (with the `{{ config(...) }}` block) will override configs specified in `dbt_project.yml`.

You can find more information about how dbt applies configurations to models [in the docs](https://docs.getdbt.com/docs/configuring-models). 

I'll leave this issue open, as it would be good to make this less confusing for new dbt users! Thanks for making an issue :)

**Comment by rrbarbosa** [comment]
I've actually experience this in another project, and I thought this was a simple way to reproduced. But, yes, updating the model to remove the `config()` block made everything work as planned. 

I'll see if I can reproduce the issue.

**Comment by drewbanin** [comment]
Ok. To be clear: these configs are working as intended. In-model configs take precedence over the configs specified in `dbt_project.yml`. The action required here it to update the `dbt-starter-project` repo to be less confusing for new users.

**Comment by rrbarbosa** [comment]
@drewbanin I figured out what my original issue was: a typo. I had `materialzed` in my config file, that's why it seemed that the option was not taking effect. 

Validating the `dbt_project.yml` config would be a nice feature to have. Thanks for the quick responses 🥇
