### ISSUE TITLE
Variable of array type is appended not overridden

### ISSUE THREAD

**Issue by pavel-popov** [fishtown-analytics/dbt#1268]
### Issue description
If a variable has array type and defined both in `dbt_project.yml` and in the model file itself then the rendered value is a concatenation of two arrays. 

### Results
I have this in my `dbt_project.yml`:
```
models:
    analytics:
        delivery:
            materialized: incremental
            vars:
                cluster_by: ["qt"]
```

then in the model config section I set this:
```
{{
  config({
    "vars": {
      "cluster_by": ["dt", "event"],
    },
    "post-hook": "{{ bootstrap() }}"    
  })
}}
```

In the `bootstrap` macro invoked from post-hook in the model I get this interpolation of variable `cluster_by`:

```
{{- log("setting clustering of '%s' by '%s'"|
        format(this.name, var('cluster_by') | join(', ')), True) -}}
```
Result:
```
setting clustering of 'report' by 'dt, event, qt'
```

So variables appended, not overridden.

Slack message: https://getdbt.slack.com/archives/C2JRRQDTL/p1548798802509200

### System information
The output of `dbt --version`:
```
installed version: 0.12.2
   latest version: 0.12.2

Up to date!
```

The operating system you're running on:
macOS Mojave

The python version you're using (probably the output of `python --version`):
```
Python 3.6.4
```

### Steps to reproduce
See Results section.

**Comment by drewbanin** [comment]
Thanks for the report @pavel-popov. This is pretty interesting! Until very recently (0.12.2?) setting vars from a `{{ config(...) }}` actually didn't work _at all_. While I'm glad it works in some capacity, I'd agree with you that the demonstrated behavior is incorrect here.

Variable definitions should clobber existing variable definitions defined at a less specific scope. This is indeed the behavior for primitive values (like ints, strings, etc). For non-primitives, the behavior looks like:
- lists/tuples are extended with more specifically scoped vars
- dicts are update with more specifically scoped vars

I imagine this issue isn't specific to `{{ config(vars=...) }}` var definitions, and i bet we'll see the behavior with variables defined in `dbt_project.yml`, eg:

```
models:
  vars:
    my_var: [1,2,3]
  my_project:
    vars:
      my_var: [4,5,6]
```

**Comment by drewbanin** [comment]
variables are defined at the root-level of the `dbt_project.yml` file in dbt v0.17.0. As a result, variables no longer participate in folder-based hierarchical configuration, so this won't be an issue going forwards. Closing this!
