### ISSUE TITLE
Use information schema tables in BigQuery

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1275]
### Feature description
BigQuery recently added support for an `INFORMATION_SCHEMA` [in beta at the time of this writing](https://cloud.google.com/bigquery/docs/information-schema-intro).

When these tables become more mature (and we're confident they won't change in breaking ways) dbt should make use of them instead of using the BQ API directly. This will help keep things consistent across adapters, and will likely help us delete a whole bunch of code

**Comment by drewbanin** [comment]
@beckjake this should be closed by https://github.com/fishtown-analytics/dbt/pull/1881, yeah?

**Comment by beckjake** [comment]
I think so!
