### ISSUE TITLE
Create -t flag as alias for dbt run --target

### ISSUE THREAD

**Issue by foundinblank** [fishtown-analytics/dbt#1281]
I love the `-m` flag as an alias for `--models` (in #1161) but now it's completely messed up my muscle memory for `--target`! I'm now repeatedly typing `-target` instead of `--target` when I want to run dbt on production.

**Comment by aescay** [comment]
Made a quick fix to support this, you can view the status on this PR https://github.com/fishtown-analytics/dbt/pull/2057

**Comment by aescay** [comment]
Will go out with the 0.15.2 release, closing this now!
