### ISSUE TITLE
Infer schema from query (not a relation)

### ISSUE THREAD

**Issue by foundinblank** [fishtown-analytics/dbt#1282]
This is a port of [Issue #118 from dbt-utils](https://github.com/fishtown-analytics/dbt-utils/issues/118) - see discussion over there for more details. This sort of create/drop view in mid-execution functionality seems to be necessary in order to make cool things like using the star macro with CTEs. Posting it here for issue tracking. 

## Original issue below
So the star macro works great - but only with tables or views. It won't work for CTEs referenced within the same data model (.sql file).

@drewbanin's two ideas:

> 1. executed the subquery with `limit 0`, inspecting the returned columns
> 2. creating a view, inspecting the resulting columns
> 
> neither of those sound super appealing to me though 😕

Michael Kaminsky's idea:

> DBT _could_ create a view with limit 0, inspect the catalog, and then drop the view

**Comment by drewbanin** [comment]
see [get_columns_in_query](https://github.com/fishtown-analytics/dbt/blob/e51c942e91a94936f68f2965963d3b46f1257658/core/dbt/include/global_project/macros/adapters/common.sql#L31-L45) here. We probably won't document this macro externally for a while (it's subject to change without notice), but you can copy it into your own project and tweak it to suit your needs.

Closing this one
