### ISSUE TITLE
sql_where configs in dbt_project.yml are rendered, breaking `{{ this }}`

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1284]
## Issue
`sql_where` clauses in model configs are rendered during project parsing, and they should definitely not be!

Another victim of #1033 

### Issue description
When dbt is rendering the project `models` section, we skip rendering hooks and vars (they will be rendered as nodes later). We should do the same for `sql_where`.

### Results
What happened? 

With a model like this:
```
{{ config(schema='schema_2', materialized='incremental') }}

select 1 as id
```

And a dbt_project.yml like this:
```
name: 'minimal'
version: '1.0'
profile: 'local'

models:
    minimal:
        sql_where: id > (SELECT max(id) FROM {{ this }})
```

I ran `dbt run` twice and got an error like this the second time:
```
Database Error in model model_2 (models/model_2.sql)
  syntax error at or near ")"
  LINE 13:          where (id > (SELECT max(id) FROM ))
                                                     ^
  compiled SQL at target/compiled/minimal/model_2.sql
```

This would still work if I put the sql_where in the config() call.

What did you expect to happen?

I expected something to be there after the `FROM` clause!

### System information
The output of `dbt --version`: `0.12.2`

The operating system you're running on:
any

The python version you're using (probably the output of `python --version`)
any

**Comment by drewbanin** [comment]
I think this was spotted in the wild over here: https://getdbt.slack.com/archives/C2JRRQDTL/p1549307083593400

nice catch!

**Comment by drewbanin** [comment]
are there other fields that are also victims of 1033? I don't think so, but worth confirming

**Comment by beckjake** [comment]
For a short time, the whole `vars` block was a victim (#1047). I didn't think there were any more when we fixed that, but here we are again!

**Comment by drewbanin** [comment]
`sql_where` has been removed from dbt. Closing.
