### ISSUE TITLE
Cleanup usage string in `--help`

### ISSUE THREAD

**Issue by pavel-popov** [fishtown-analytics/dbt#1289]
### Feature description
Currently, we have this:

```
❯ dbt --help
usage: dbt: data build tool [-h] [--version] [-r RECORD_TIMING_INFO] [-d] [-S]
                            {init,clean,debug,deps,archive,run,compile,docs,seed,test}
                            ...

```

But that `dbt: data build tool` is mixed with the flags so is clearly misleading.
The proposal is to remove `: data build tool` from the help.

### Who will this benefit?
Everyone

**Comment by drewbanin** [comment]
Thanks @pavel-popov - feel free to send over a PR!
