### ISSUE TITLE
Remove graph.gpickle file

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1304]
### Feature description
The `graph.gpickle` file has been superseded by well-defined compilation artifacts like `manifest.json`, `run_results.json`, and `catalog.json`. In the next minor release, dbt should stop generating this `.gpickle` file. Instead, dbt should provide helper methods in its API that accept a manifest and return a networkx graph. Alternatively, we can write helper scripts and just include them in the documentation.

As a part of this change, we should document the `.json` assets produced by dbt, providing a contract for their use.

**Comment by alex-gable** [comment]
just calling out that the only reference implementation of an introspective airflow dag has a dependency on this object for its introspection.

https://gist.github.com/adamhaney/916a21b0adcabef4038c38e3ac96a36f

**Comment by drewbanin** [comment]
Thanks for the heads up @alex-gable! The only gpickle-aware part of that file is:
```
    G = nx.read_gpickle('/home/airflowuser/project/graph.gpickle')
```

Everything after this operates on a `networkx` graph. It would definitely be good for us to provide some method (likely in dbt) that can deserialize a `manifest.json` file into a networkx graph. The rest of the code should work as-is after that :)

**Comment by drewbanin** [comment]
this isn't really hurting anyone. We may choose to remove it in the future, but we'd want to supply equivalently helpful tooling around the `manifest.json` file when we do. So, closing this one until that becomes a priority
