### ISSUE TITLE
Test Suite speedup - seed once

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1311]
## Feature
Improve the speed of the test suites by creating a collection of seeds at the start of each test, and having tests `source` them

### Feature description
Currently, most tests do:
 - a `dbt seed` of some sort or runs actual seed SQL
 - a `dbt run` that creates models that `ref` those seeds
 - the actual interesting test happens on or in those models

A lot of the seeds are identical across multiple tests, and where they aren't many of them don't care about what data they have at all and the seeds are just trivial one-offs.

Obviously we still need a couple tests that make sure ref'ing a seed and the various seed configuration settings work, but for the most part it's pretty repetitive to be seeding the same data over and over. Instead, dbt's integraition suite should build out a schema with a collection of useful seeds at run start time, and probably generate an appropriate `sources` block for tests to use in a schema.yml file.

This will let us skip a ton of `dbt seed` invocations during tests, which should cut down on runtime quite a bit.

### Who will this benefit?
https://www.youtube.com/watch?v=Vhh_GeBPOhs

**Comment by drewbanin** [comment]
I knew what that youtube link was before i even clicked it :)

Don't imagine this is something we plan to do in the next 6 months. If it is, we can certainly re-open the issue. For now, closing
