### ISSUE TITLE
RPC server does not work on windows

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1315]
## Issue
The new RPC server in #1301 will crash on start for windows. We should fix that!

### Issue description
`dbt rpc` crashes with an error on windows, saying `Your platform does not support forking`. I would like to think we just have to change some flag to werkzeug's `run_simple` to get threaded mode. We should fix this, or if that's too hard we should at least give a better error!

**Comment by drewbanin** [comment]
@beckjake should we just close this one and document that windows is unsupported?
