### ISSUE TITLE
ability to set target-path to a dynamic value

### ISSUE THREAD

**Issue by Vamanan** [fishtown-analytics/dbt#1320]
### Feature description
It would be nice to set `target-path` to a dynamic value. For eg: `target_<current_time>`

Currently target-path can be assigned to the value of a variable that is passed as a command line argument. However, since command line args are parsed as simple strings, the value of such a variable cannot be dynamic.

### Who will this benefit?
The target directory contains run stats in its `run_results.json` file. If one were to automate the process of parsing this file after every run for alarming/monitoring, then it is important to not have one run's stats overwrite another before it is parsed. This can be prevented by "versioning" each run by the target directory name which would be a function of current timestamp.

**Comment by drewbanin** [comment]
thanks for the report @Vamanan! Let's solve this by adding the `modules` dict to the minimal compilation context. That would let you do something like:
```
target-path: "target_{{ modules.datetime.datetime.now().strftime(...) }}"
```

We could conceivably also add static context variables like `run_started_at` and `invocation_id`, which are reasonable and i think doable here.

Prioritized for the Wilt Chamberlain release, pending any unforeseen issues with this approach.
