### ISSUE TITLE
Use alter table statement to resize varchar columns on Redshift

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1323]
Stub issue while I investigate this question

- dbt currently copies, drops, and swaps columns to change varchar sizes (for incremental models and archives?)
- can we instead use the **brand new** `alter table...` functionality to resize columns instead?
- what are the benefits of this approach? Is it faster / less error prone?
- what are cases where it would not work? eg. changing cols from strings --> ints. Did this work previously

**Comment by mplovepop** [comment]
Also for `dbt seed`

**Comment by drewbanin** [comment]
Ah, Redshift. Check the constraints, via https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html

> You can’t alter a column with compression encodings BYTEDICT, RUNLENGTH, TEXT255, or TEXT32K.
> You can't alter columns with default values.
> You can't alter columns with UNIQUE, PRIMARY KEY, or FOREIGN KEY.
> You can't alter columns inside a multi-statement block (BEGIN...END).

Of these, the lack of in-transaction support is really a non-starter. Why even build this feature? Until this can happen inside of a transaction, we can't implement it in dbt.
