### ISSUE TITLE
profile.yml links to a sample profile URL that 404's

### ISSUE THREAD

**Issue by seisvelas** [fishtown-analytics/dbt#1344]
### Issue description
`profiles.yml` suggests browsing to https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml to view an example profile. This url is defined as the variable `SAMPLE_PROFILES_YML_FILE` in [line 13](https://github.com/fishtown-analytics/dbt/blob/1e5308db31edb5d8cf9e74e1c6c3b5c333379228/core/dbt/task/init.py#L13) of [dbt/core/dbt/task/init.py](https://github.com/fishtown-analytics/dbt/blob/1e5308db31edb5d8cf9e74e1c6c3b5c333379228/core/dbt/task/init.py). This URL does not work.

### Results
I get a 404 error when I try to browse to the suggested URL,
https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml

### System information
The output of `dbt --version`:
```
installed version: 0.12.2
   latest version: 0.12.2

Up to date!
```

Operating System: 64bit Ubuntu

Python version:
Python 2.7.12

### Steps to reproduce

1. Get URL of sample profile from `~/.dbt/profiles.yml`
```
someOne@someWhere:/$ grep "sample" ~/.dbt/profiles.yml -B 1
# For more information on how to configure this file, please see:
# https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml
```

2. Browse to URL 

3. See 404 error

**Comment by drewbanin** [comment]
Thanks for the report @seisvelas!
