### ISSUE TITLE
Support specifying specific data tests with "dbt test --data"

### ISSUE THREAD

**Issue by tayloramurphy** [fishtown-analytics/dbt#1357]
### Feature description
I'd like to be able to run:

`dbt test --data my_custom_test` 

This would be useful when building new custom tests so I don't have to run all of them when testing. And it would encourage more testing since it's easier to iterate

### Who will this benefit?
Everybody who uses custom tests!

**Comment by drewbanin** [comment]
the syntax is a little funny (we'll fix this in the future) but you can now do:

```
dbt test --data --models tests/my_test.sql
```

in dbt >= v0.17.0

This file-path based selector works for models too :)

**Comment by llarbodiere** [comment]
Hello,
Any update on the synthax ? :)

**Comment by jtcohen6** [comment]
@llarbodiere I'd encourage you to check out [the docs on node selection](https://docs.getdbt.com/reference/node-selection/syntax), in particular:
- [the `test_type` method](https://docs.getdbt.com/reference/node-selection/methods#the-test_type-method)
- [test selection examples](https://docs.getdbt.com/reference/node-selection/test-selection-examples)

**Comment by llarbodiere** [comment]
Perfect thanks a lot ! :)
