### ISSUE TITLE
Snowflake: Enable choosing a warehouse at runtime

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#1358]
### Feature description

There are cases where you want a set of models in your project to run on a different Snowflake warehouse so that it completes more quickly. Right now you can do that with hacks involving multiple profiles or environment variables across multiple runs, but it would be easier to use if this was more configurable.

My best guess at how to implement this is to add a `warehouse` model config that can be specified in dbt_project.yml or in a config block. I think this field should be rendered so that it's configurable in dev vs. prod. When set, it will override the Snowflake warehouse to use for that model.

I *think* that would be difficult because of how model configs work, and how connections are established. (We can switch the warehouse after the connection is established, so maybe it's not a problem?) But, if that's a problem, I could imagine setting this at the run level, too. So every model for a given run would execute on a custom warehouse.

**Comment by krishbox** [comment]
@cmcarthur, another approach to do this would be to use a pre-hook with a USE WAREHOUSE query_wh;
