### ISSUE TITLE
Fail with nonzero exit code if run-operation task encounters an unhandled exception

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1377]
### Issue description
If a run-operation macro fails with an exception (ie. unable to connect to database, invalid SQL, etc), dbt should exit with a nonzero exit code. Moreover, run-operations should generally go through a similar code-path to models, seeds, etc, such that this happens automatically.

### Results
The info logs showed that an exception had occurred, but the task exited with exit code = 0

### System information
The output of `dbt --version`:
```
0.13.0
```

**Comment by Topsboom** [comment]
Hello, please tell me what the error is or what needs to be done ?
![image](https://user-images.githubusercontent.com/82534313/114753197-d8d19580-9d5f-11eb-9716-a94ee56eda90.png)
![image](https://user-images.githubusercontent.com/82534313/114753219-e129d080-9d5f-11eb-97c1-fb50ce261ff0.png)

**Comment by Topsboom** [comment]
System task exited with non-zero code.

**Comment by jtcohen6** [comment]
@Topsboom It's not clear to me what's represented in the screenshots above. What is [Arena](https://sso.kpi.fei.tuke.sk/login?service=https%3A%2F%2Farena.kpi.fei.tuke.sk%2Fcas-login%3Fnext%3D%252Fspartan%252Frounds)? Are you calling `dbt run-operation` commands from there?
