### ISSUE TITLE
View created successfully, but dbt reported negative execution time

### ISSUE THREAD

**Issue by Chryzanthemum** [fishtown-analytics/dbt#1386]
## Issue
View Time very very incorrect

### Issue description
In general terms, please describe the issue. What command did you run?

dbt run --models created a view in negative time.

### Results
What happened? What did you expect to happen?

See the attached picture.

### System information
The output of `dbt --version`:
```
0.12.2
```

The operating system you're running on:
Sierra 10.12.6

The python version you're using (probably the output of `python --version`)

Python 3.6.8 :: Anaconda custom (64-bit)

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

Can't reproduce, works fine now.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

Honestly not a big deal, just funny, but may indicate underlying problems with how time is calculated in dbt? 

![image](https://user-images.githubusercontent.com/12651625/55515771-63437280-5639-11e9-9946-ebcfeb56c40a.png)

**Comment by cmcarthur** [comment]
@Chryzanthemum hey, thanks for opening the issue. Is it possible that your machine's clock was out of sync? The timestamps on those log messages indicates that your system clock went back two seconds while that view was executing. If the clock is moving backwards, it will be pretty hard for dbt to calculate the time correctly :)

**Comment by drewbanin** [comment]
this is almost certainly a clock issue! closing
