### ISSUE TITLE
Error in dbt run sample model on presto

### ISSUE THREAD

**Issue by rmgpinto** [fishtown-analytics/dbt#1399]
Please make sure to fill out either the issue template or the feature template and delete the other one!

### Issue description
I'm testing dbt for presto.
Just ran:
```
$ dbt init test
$ cd test && dbt run
```

### Results
```
Running with dbt=0.13.0
Found 1 models, 0 tests, 0 archives, 0 analyses, 96 macros, 0 operations, 0 seed files, 0 sources

13:18:07 | Concurrency: 4 threads (target='dev')
13:18:07 | 
13:18:07 | 1 of 1 START view model data_warehouse.my_first_dbt_model............ [RUN]
13:18:09 | 1 of 1 ERROR creating view model data_warehouse.my_first_dbt_model... [ERROR in 1.05s]
13:18:09 | 
13:18:09 | Finished running 1 view models in 7.50s.

Completed with 1 errors:

Runtime Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
  PrestoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Unsupported combination of operations in a single transaction", query_id=20190414_131810_00009_qvqzx)

Done. PASS=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
The output of `dbt --version`:
```
installed version: 0.13.0
   latest version: 0.13.0

Up to date!
```

The operating system you're running on:
docker image: `amazonlinux`

The python version you're using (probably the output of `python --version`)
```
$ python3 --version
Python 3.7.2
```

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

**Comment by drewbanin** [comment]
Thanks for the report @rmgpinto! Do you mind re-opening this issue in the [dbt-presto](https://github.com/fishtown-analytics/dbt-presto) repo? If you could also include the relevant portion of your `logs/dbt.log` file, that would be very helpful too. I see that the error is `Unsupported combination of operations in a single transaction` and I'm curious which statements dbt is running that results in this error.

Finally, when you re-open the issue in the dbt-presto repo, can you include your version of Spark? Thanks!
