### ISSUE TITLE
lookup schemas in a case-insensitive way

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1411]
### Issue description
Snowflake information schema queries should be case-insensitive, but the Snowflake plugin does not override the default implementation of [list_schemas](https://github.com/fishtown-analytics/dbt/blob/da4c135e23b9f12607811745cb184ae81d5ebd26/core/dbt/include/global_project/macros/adapters/common.sql#L192) which is case-sensitive.

We should either change the default implementation of `list_schemas` to be case-insensitive, or we should override the Snowflake implementation to do a case-insensitive lookup. Let's also scan for other case-sensitive default implementations that aren't overridden by the Snowflake plugin.

### Results
Given `schema: my_schema` in `profiles.yml`,  dbt furnishes the following `list_schemas` query on Snowflake:

```
select distinct schema_name
    from dw_dev.information_schema.schemata
    where catalog_name = 'my_schema'
```

dbt uses this query to determine which schemas already exist, circumventing a `create schema if not exists  ...` query. This issue probably only manifests in an error if the dbt user does not have permissions to create a new schema.

### System information
The output of `dbt --version`:
```
0.13.0
```

**Comment by beckjake** [comment]
Fixed in #1412
