### ISSUE TITLE
Add load timestamp for dbt seed

### ISSUE THREAD

**Issue by joshtemple** [fishtown-analytics/dbt#1434]
### Feature description
It would be useful if the tables generated by the `dbt seed` command added a metadata timestamp column to the table upon creation that marked the time in UTC when the table was created.

I'm open to naming suggestions here, maybe `_dbt_created_at` or `_dbt_loaded_at`. I would also recommend prepending an underscore to whatever name chosen so it's clear the column is dbt-added. Take your pick!

### Who will this benefit?
This is generally useful for knowledge and testing of data staleness, but can also be helpful for improving intelligent query caching policies for downstream tools.

**Comment by drewbanin** [comment]
Hey @joshtemple - cool idea! I like this (and think it's a good idea) but I feel funny about adding something like this to `dbt seed` and not all of the other tables that dbt creates (eg models, archives). 

If you're looking to implement this for yourself, you could probably override the [`seed` materialization](https://github.com/fishtown-analytics/dbt/blob/dev/wilt-chamberlain/core/dbt/include/global_project/macros/materializations/seed/seed.sql#L116) to add an extra column in the `create_csv_table` macro, then update `basic_load_csv_rows` to set that column to something like `getdate()` or `current_timestamp()`.

A cheaper version of this would use post-hooks to add a column and then `update` it with a timestamp :)

If we were to incorporate this functionality directly into dbt, I'd probably recommend mutating the DataFrame generated from the seed CSV. If we did this, I'd want to expose the configuration to the user, such that they could add other meta columns like the git commit SHA that was checked out when the seed ran, or the database user, or similar. We could do all of these things with configs + env vars, for instance. I think it's a lot more compelling to give tools like this to users than it is to build one-off features! 

Let me know what you think about all of this

**Comment by drewbanin** [comment]
Closing this as stale - don't think we have any intentions of prioritizing this in the next 6 months.

**Comment by yeykawb** [comment]
@drewbanin Circling back to this issue - I'm trying to build a post-hook to my seed but I can't seem to make it work fully. The dbt_project.yml throws syntax error when adding +post-hook: to the seed section. Do you have any resource on how to achieve this? I suppose the ALTER TABLE should include some check to see whether the column is already created or not.

**Comment by nevdelap** [comment]
I'm wondering about how to update a seed file that is joined in a model that is being incrementally updated such that it will work without having to manually intervene at deployment. It seems like this would be the solution, because it could work similarly to a column giving an ingest or event time.
