### ISSUE TITLE
use JSONSchema $schema for dbt contracts (via dataclasses + jsonschema-dataclasses)

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1447]
## Feature
dbt should use the `$schema` and `$ref` tags of JSONSchema instead of the current `deep_merge` and manually-referencing dicts.

### Feature description
We should convert our json schema contracts to have `$schema` values pointing at publicly accessible URLs, use the `$ref` feature to link behavior of our internal JSON schemas, and modify our `APIObject` and its descendants to take advantage of it.

We can start by specifying just the outermost "layers" of the schema and add the references as we go along. We should do something like `iglu` uses and define a decent versioned self-describing format. An example iglu schema is [here](https://github.com/snowplow/iglu-central/blob/master/schemas/com.amazon.aws.lambda/java_context/jsonschema/1-0-0)

We should support namespacing, and give dbt-core a separate namespace from any plugins (like adapters!) or dbt-cloud.

We also will want to specify credential contracts on a per-adapter basis, and adapter-specific configurations at some point (currently we just allow anything).

Serialization should include the schema value so we can try to do deserialization into dbt objects based on the schema.

### Who will this benefit?
Anyone consuming `dbt` json output, dbt Cloud, developers

**Comment by cmcarthur** [comment]
use a mix of dataclasses + https://github.com/s-knibbs/dataclasses-jsonschema to generate a JSON schema document for all of dbt's internal dbt objects

**Comment by cmcarthur** [comment]
should we generate & write out the json schema document to the target path?

**Comment by beckjake** [comment]
Fixed in #1589
