### ISSUE TITLE
DB2 adapter

### ISSUE THREAD

**Issue by tglunde** [fishtown-analytics/dbt#1467]
### Feature description
adding a new adapter to interact with dbt on db2/blu warehouse

### Who will this benefit?
using dbt on db2 data warehouse implementations.

**Comment by drewbanin** [comment]
Hey @tglunde! Copy/pasting this for anyone else who stumbles upon this issue :)

If this is something you're interested in working on, you can check out the dbt database [information sheet](https://github.com/fishtown-analytics/dbt/wiki/New-Adapter-Information-Sheet). The answers to these questions are frequently useful when building a new [database adapter](https://docs.getdbt.com/docs/building-a-new-adapter).

**Comment by drewbanin** [comment]
closing this one - out of scope for core
