### ISSUE TITLE
dbt generates an awful error message if you have a bad version in your project file

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1469]
## Issue
dbt does not give good error messages about errors in `dbt_project.yml`

### Issue description
running `dbt compile` with a dbt_project.yml like this:

```
name: 'x'
version: 'v1.0.0'
profile: 'local'
```

Results in this error:
```
Running with dbt=0.14.0-a1
Encountered an error while reading the project:
  ERROR: Runtime Error
  Runtime Error
    Invalid arguments passed to "Project" instance: version.'v1.0.0' is not valid under any of the given schemas
Encountered an error:
Runtime Error
  Could not run dbt
```

That's not very helpful, and even very smart/competent dbt users are going to get lost here.

### Results
I expect to get back _something_ with `dbt_project.yml`, or even better an absolute path to the file that failed to parse. I only know this is a malformed dbt_project.yml because I know what generates this message. If I had dependencies, I'd have had to go through all of them!

I think a good start would be that if we get an error while parsing a file like this, we should report:

 - the filepath to the file of sadness, assuming it came from a file and not internally (in that case, there is probably something wrong internally in dbt, eek)
 - the json path to the key that failed (✅, thank you jsonschema!)
 - the value that failed (✅, thank you jsonschema!)
 - extra credit: provide some sort of generic wrapper for jsonschema validation errors that handles this problem ("if there's a problem with the `version` field, emit an error like this: ...")
 - extra extra credit: in the case of dependencies, spit out the `packages.yml` entry in question (extrax3 credit: handle dependency chains)

Some of this is kind of hard because we will have to augment/massage the exception we get from jsonschema, but even just the filepath would be less disappointing.

### System information
dbt version: 0.13.1, 0.14.0, I assume lots of other versions

The operating system you're running on:
N/A, this is cross-platform

The python version you're using (probably the output of `python --version`)
N/A, this is cross-version

### Steps to reproduce
```
$ cat dbt_project.yml
name: 'minimal'
version: 'v1.0.0'
profile: 'local'
$ dbt compile
```

**Comment by drewbanin** [comment]
ha... is this any better?
```
Encountered an error while reading the project:
  ERROR: Runtime Error
  at path []: 'v1.0' does not match '^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)(\\.(?:0|[1-9]\\d*))?$
```

I'm closing a lot of issues tonight... but.... let's leave this one open :)

**Comment by cgopalan** [comment]
The latest version gives this message for `dbt compile`:
```
Running with dbt=0.19.0
Encountered an error while reading the project:
  ERROR: Runtime Error
  at path ['version']: 'v1.0.0' is not valid under any of the given schemas

Error encountered in /path/to/dbt_project.yml
Encountered an error:
Runtime Error
  Could not run dbt
```
Seems like there's more clarity now.

**Comment by cgopalan** [comment]
Is this an issue still @drewbanin ? Please see my comments above.

**Comment by jtcohen6** [comment]
@cgopalan I agree, I think the error message provided in v0.19.0 is a lot clearer. Do you feel like you had enough information to know what had gone wrong, and where to go to fix it?

**Comment by cgopalan** [comment]
@jtcohen6 oh this was not my issue. I was just triaging the issue and checking if I could in a PR for this, but while trying to simulate this, I saw that the latest version of dbt did not have the same issue as what was raised. IOW, I was wondering if this issue can just be closed?

**Comment by jtcohen6** [comment]
@cgopalan Oh, nice! I really appreciate all the contributing you've been doing lately :)

I agree, while the error still isn't _perfect_, I think it's much better than it used to be. I'm going to close this for the time being.

**Comment by cgopalan** [comment]
> @cgopalan Oh, nice! I really appreciate all the contributing you've been doing lately :)
> 
> I agree, while the error still isn't _perfect_, I think it's much better than it used to be. I'm going to close this for the time being.

@jtcohen6 you are welcome! We use dbt at the organization that I am in, and love it. So I thought I would help out :)

**Comment by jadenguyen0128** [comment]
I have the same issue while trying to upgrade dbt to v 0.19.0 with dbt compile. Any suggestion to tackle this? I have looked at this upgrading document https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-19-0

1) Here is the details of our dbt_project.yml
`name: 'project_name'
version: '0.19.0'

# config-version: 2

profile: 'project_name'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]`

2) The dbt error message.
`Running with dbt=0.19.0
Encountered an error while reading the project:
  ERROR: Runtime Error
  Invalid config version: 1, expected 2

Error encountered in /tmp/jobs/45307298/target/dbt_project.yml
Runtime Error
  Could not run dbt`

**Comment by togobingi** [comment]
Your `dbt_project.yml` file should look like this at the top:
```

name: 'project_name'
version: '1.0.0' #This is the version of your project and it isn't used by dbt

config-version: 2 #This is important as it unlocks new dbt features
```

I had a similar error message as the comment above and solved it by making sure my `packages.yml` file included the code below only:

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
```

I only needed `dbt_utils`. I initially included the git repo URL to dbt_utils and that threw the error message.

**Comment by jadenguyen0128** [comment]
Hi @togobingi 
Thank you for your detailed response. Yes, I resolved this by upgrading packages.yml up to date. With that, I was able to upgrade my dbt version to the latest version.
