### ISSUE TITLE
new and old sytle archives clobber each other

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1480]
## Issue
Archives have no duplicate detection in the manifest like other refables

dbt should error on duplicates, especially duplicate archive names, at parse time.

### Issue description

In 0.14.0, we have a new archive definition feature where you declare archives in `{% archive NAME %}...{% endarchive %}` blocks, and we made archives refable. But I didn't update the graph loader code to detect duplicates, so there are two annoying consequences:

 - If you have an archive defined in dbt_project.yml and an archive with the same name as its `target_table` defined in an archives/*.sql file, the former will always "win", silently
 - Duplicates where the archive name matches a model name will be detected, but only at `ref` time instead of parse time

### System information
dbt 0.14.0a1
any OS
any Python

### Steps to reproduce

in `dbt_project.yml`:

```
archive:
  - source_schema: dbt_jbeck
    target_schema: dbt_jbeck
    tables:
      - source_table: x
        target_table: x_archive
        updated_at: date
        unique_key: id
```

in `archives/x_archive.sql`:

```
{% archive x_archive %}
    {{
        config({'target_database': 'DBT_TEST', 'target_schema': 'dbt_jbeck', 'updated_at': 'date', 'strategy': 'timestamp', 'unique_key': 'id'})
    }}
    select * from DBT_TEST.dbt_jbeck.x
{% endarchive %}
```

Run dbt archive:
```
$ dbt archive
Running with dbt=0.14.0-a1
Found 1 models, 2 tests, 1 archives, 0 analyses, 107 macros, 0 operations, 2 seed files, 1 sources
14:12:24 | Concurrency: 4 threads (target='snowflake')
14:12:24 |
14:12:24 | 1 of 1 START archive x_archive --> DBT_TEST.dbt_jbeck.x_archive...... [RUN]
14:13:29 | 1 of 1 OK archived x_archive --> DBT_TEST.dbt_jbeck.x_archive........ [SUCCESS 100 in 64.21s]
14:13:29 |
14:13:29 | Finished running 1 archives in 81.02s.
```

**Comment by drewbanin** [comment]
Good catch @beckjake! Yes, let's add dupe-detection into the loader.

This is probably a less common case, but we also check for duplicate database/schema/identifier identifiers. This check ensures that two models aren't aliases to the same destination relation.

Do we need to do something special to include archives in this check? I imagine that would be especially appropriate since you can specify the target database/schema/table for archives explicitly

**Comment by beckjake** [comment]
@drewbanin I thought that we didn't handle this, but I think that might already work already:
https://github.com/fishtown-analytics/dbt/blob/73607b85b7825b7fca01a340c52469317eaeae7a/core/dbt/loader.py#L184 - this gets called (eventually) by `GraphLoader.load_all` That means the only case we miss is when unique IDs generated by the two archive parsers collide, which should be a pretty easy fix!
