### ISSUE TITLE
Parallelize integration tests

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1492]
## Feature
Parallelize integration tests so they don't all run in the same directory

### Feature description
Currently, our integration tests can't be parallelized because each one runs in the root directory. We should run dbt out of a temp directory, add symlinks or something, etc. Then we can use [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) or some equivalent to run in parallel.

### Who will this benefit?
I don't want to sit around waiting for bigquery/snowflake.

**Comment by drewbanin** [comment]
Amazing

**Comment by beckjake** [comment]
Fixed in #1527
