### ISSUE TITLE
Rename "archives" to "snapshots"

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1497]
### Feature description
"Snapshot" is a more common name for this class of functionality than "Archive". We should rename:
- `archive` blocks to `snapshot` blocks
- `dbt archive` to `dbt snapshot`
- The resource type
- general `s/archive/snapshot` in the dbt codebase
- documentation at docs.getdbt.com (Drew)
- update the archive migration script accordingly

**Comment by cmcarthur** [comment]
@drewbanin should we also make `dbt archive` return a message that the command is now `dbt snapshot`?

**Comment by drewbanin** [comment]
Yep. Let's make it a deprecation warning - we can also link right to the docs in the message
