### ISSUE TITLE
Deprecate Python 2.7, require Python 3.6 / 3.7?

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#1501]
Prospective issue (we may not do this imminently, just opening this for discussion).

Pros:
- use dataclasses for better schema management, {de,}serialization
- be a good citizen of the Python ecosystem
- make multiprocessing things easier
- increase of Python 2.7 specific problems in dbt?

Concerns:
- Check RHEL / CentOS default version
- painful for a decent number of users (esp. windows?) (looks like ~10% of dbt users are using 2.7)

Tie-ins:
- single-line installer

**Comment by heisencoder** [comment]
Would it be possible to defer this work until the end of year when Python 2 is deprecated across the whole Python community?  We're providing dbt as a library for other teams, and some are still on Python 2.

**Comment by beckjake** [comment]
This is slated for dbt 0.15.x, not 0.14.x - we don't have a formal release date planned for that, but 0.14.x will only feature a big annoying warning.

**Comment by heisencoder** [comment]
Okay -- sounds good.  We'll start to get serious about Python 2 deprecation in the next quarter or so.

**Comment by beckjake** [comment]
Resolved by #1535
