### ISSUE TITLE
Support models with same names across different packages

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#1502]
Today, model namespacing looks different than macro namespacing. When calling macros, there's a notion of precedence. So, `{{ mymacro() }}` will search:

- First, in the local package
- Then, in the "global" package (includes in dbt repo)
- Then, package-specific lookups if `package.mymacro` syntax is used

We can / should use a similar notion of namespace precedence with models. This would let us support multiple models of the same name in packages, allowing us to generate docs for projects built into different namespaces with overlapping model names.

**Comment by drewbanin** [comment]
closing in favor of the discussion in #1269
