### ISSUE TITLE
[Wilt Chamberlain] Snapshot updates

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1510]
### Issue description
This issue is a collection of changes and questions that came up during the testing of Snapshots for the 0.14.0 release.

**Checklist**:
- [ ] Snapshot schemas are searched in `dbt run` invocations. Is that correct / necessary?
- [ ] Snapshots do not work with source columns that _must_ be quoted. The initial snapshot will succeed (create table as) but subsequent snapshots appear to fail.
- [ ] Let's normalize the stdout for a snapshot job. This can just print the relation name, much like the output for `dbt run`.

**Comment by beckjake** [comment]
> Snapshot schemas are searched in `dbt run` invocations. Is that correct / necessary?

Sort of. Snapshot schemas must be part of the cache for `get_or_create_relation` to work, and the snapshot materialization uses that. dbt doesn't currently have a concept of filling the cache differently based on what type of task you're running, so I don't think it makes sense to avoid snapshot schema searches during `dbt run` - it would break `dbt snapshot`. Splitting that apart seems like a pretty big project.

> Snapshots do not work with source columns that must be quoted. The initial snapshot will succeed (create table as) but subsequent snapshots appear to fail.

This is actually really hard, I think.
