### ISSUE TITLE
[Wilt Chamberlain] Add severity configs to custom data tests

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1512]
### Feature description
This is a nice-to-have if it's easy to implement. Custom data tests should be configurable with a `severity` as with schema tests.

I'm imagining:
```
{{ config(severity='warn') }}

select ...
```

Though I'm not certain how configs work with custom data tests currently. If this is involved, then we should do it in a future release.

### Who will this benefit?
custom data test users

**Comment by beckjake** [comment]
This actually already works if you do:

```
{{ config(severity='WARN') }}
```

But dbt is very particular about the casing. Is that all you want me to do, fix that?

**Comment by drewbanin** [comment]
yes! That's awesome :)

Sure, if you don't mind making it case-insensitive and adding a test, then I think we can call this one a Feature 🌟
