### ISSUE TITLE
[Wilt Chamberlain] Change snapshot --models flag to --select

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1517]
### Feature description
The functionality of the `--models` flag to the `snapshot` command is perfect. We should just rename it to `--select`, as this flag selects snapshots, not models.

### Who will this benefit?
Consistency!

**Comment by beckjake** [comment]
Should this be on both `dbt archive` and `dbt snapshot`, or just snapshot?

**Comment by drewbanin** [comment]
I think just `dbt snapshot`, right? We should probably leave `dbt archive` as is, though i will add: it's very ok if it makes more sense to change it for both!

**Comment by beckjake** [comment]
Fixed in #1520
