### ISSUE TITLE
Support JUnit XML output from `dbt test`

### ISSUE THREAD

**Issue by assaflavi** [fishtown-analytics/dbt#1528]
### Feature description

`dbt test` generates a summary of test results to standard output.  It can potentially generate a 
JUnit XML report with all the tests that failed.

### Who will this benefit?

Engineers who run schema and/or data tests as part of a CI/CD pipeline. Having the output in the standard JUnit format would allow tracking results of individual tests over time.

**Comment by assaflavi** [comment]
Regarding implementation, I propose to integrate the `test` flow with `pytest`, which already implements JUnit XML output:
https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files

pytest can also be a solid basis for #1357, and perhaps other test-framework-y features in the future.

**Comment by drewbanin** [comment]
Hey @assaflavi - cool idea! What kinds of tools do you use to consume JUnit XML reports?

**Comment by assaflavi** [comment]
I often use Jenkins' Test Results Analyzer plugin:
https://wiki.jenkins.io/display/JENKINS/Test+Results+Analyzer+Plugin

**Comment by drewbanin** [comment]
Got it, thanks!

My instinct is that dbt probably shouldn't target this xml format directly. Instead, I think it would be great if we could publish a jsonschema for the test results that get rendered into `target/run_results.json`. I imagine there's some mechanism to translate this test artifact into the JUnit XML output format pretty readily.

I really like the idea of having a canonical format for these artifacts, then making it super easy to translate it for integrations with other tools. Do you buy that?

**Comment by drewbanin** [comment]
We don't have any plans to prioritize this, and I think that targeting this particular xml format is probably out of scope for dbt. Going to close, but happy to discuss further if anyone is interested.

**Comment by magni-** [comment]
> Instead, I think it would be great if we could publish a jsonschema for the test results that get rendered into `target/run_results.json`

Is there a separate issue open for this? I too would like a way to easily output a JUnit report for my CI environment (in my case, [CircleCI](https://circleci.com/docs/2.0/collect-test-data/) rather than Jenkins)

**Comment by jtcohen6** [comment]
@magni- You can see documentation and schemas for all stable JSON artifacts:
- https://docs.getdbt.com/reference/artifacts/dbt-artifacts
- https://schemas.getdbt.com/

**Comment by chasleslr** [comment]
I also was hoping for dbt to support this given that it acts as the test runner and that is a typical feature for test runners in any language.

I created this small CLI tool that converts run results into jUnit XML for anyone that lands here looking for this as well!

https://github.com/chasleslr/dbt-junitxml

**Comment by Cquad** [comment]
> I also was hoping for dbt to support this given that it acts as the test runner and that is a typical feature for test runners in any language.
> 
> I created this small CLI tool that converts run results into jUnit XML for anyone that lands here looking for this as well!
> 
> https://github.com/chasleslr/dbt-junitxml

It's a great tool, do you plan to work on it ? There is a PR opened for 2 years to support newer dbt schema.

**Comment by megetron3** [comment]
Here is a thumb up for the feature. 

Since DBT supports unittests there is a real need for this JUnit Xml report file.

This file may be used in any CI/CD when the PR is failed dues to failing tests and might be really helpfull.

**Comment by megetron3** [comment]
for those who needs asap a script to convert the current test results:
```
import json
import os
from junit_xml import TestSuite, TestCase

# Load dbt run results
result_file_path = 'target/run_results.json'

with open(result_file_path) as f:
    run_results = json.load(f)

# Create a list of test cases
test_cases = []

for result in run_results['results']:
    # Extract relevant data for each test
    test_name = result['unique_id']
    status = result['status']
    execution_time = result['execution_time']
    error_message = result.get('message', '')

    # Create a test case
    test_case = TestCase(name=test_name, elapsed_sec=execution_time)

    if status == 'fail':
        test_case.add_failure_info(message=error_message)
    
    # Append test case to list
    test_cases.append(test_case)

# Create test suites and add test cases
test_suite = TestSuite("dbt_tests", test_cases)

# Output JUnit XML to a file
with open('target/junit_report.xml', 'w') as f:
    TestSuite.to_file(f, [test_suite])

print("JUnit report generated at target/junit_report.xml")

```

**Comment by hienqnguyen** [comment]
If you've gotton this far down, this might be of interest to you as well :) https://github.com/slidoapp/dbt-coverage

**Comment by BenLiyanage** [comment]
Why did this get closed?
