### ISSUE TITLE
Allow source runs to run first node of DAG without `+`

### ISSUE THREAD

**Issue by eogilvy12** [fishtown-analytics/dbt#1548]
## Feature
Allow source runs to run first node of DAG without `+`.

### Feature description
`dbt run --models source:name_of_source` will not run the models that directly reference the source. You need to add a `+` to the run which will run everything, including downstream models. I noticed this when switching over a project to use sources and I just wanted to make sure the staging models could run.

### Who will this benefit?
This is not high priority in any way but seems to be how it would work.

**Comment by drewbanin** [comment]
Thanks for the request @eogilvy12 :)

**Comment by krishbox** [comment]
@eogilvy12, @drewbanin, I'll take a shot at this one.  Hope I can find the relevant parts to change in the source!

**Comment by drewbanin** [comment]
Thanks @krishbox! How are you planning on implementing this one?

**Comment by drewbanin** [comment]
closing this issue as stale, but picking up the discussion in https://github.com/fishtown-analytics/dbt/issues/1548
