### ISSUE TITLE
[Wilt Chamberlain] Jinja's StrictUndefined is too noisy

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1554]
This is a catch-all ticket for issues around the change to using `StrictUndefined` in the v0.14.0 prerelease.

Issues:
- Warnings are generated for every evaluation of an `undefined` variable, which can be super noisy (and not super helpful)
- The return value from `load_result()` is treated as undefined
- The `results` context variable in the `on-run-end` hook context is treated as undefined
- This appears to somehow generate other types of warnings, eg:
```
-- this code results in the warning below
{{ "," if not loop.last }}

Compilation warning in model my_model (models/my_model.sql):
        the inline if-expression on line 1 evaluated to false and no else section was defined.
```

Questions to answer:
- should we make the StrictUndefined warning code smarter about how many times it warns for the same issue?
- what can we do to reduce the noise around some classes of very common warnings (see above)
- should we disable this (or hide it behind a flag) for v0.14.0, then revisit for the future?

**Comment by beckjake** [comment]
>The return value from load_result() is treated as undefined

This is because during parse-time, `load_result()` is guaranteed to return None. We can either mangle `load_result` to return something like:
```
agate_table = dbt.clients.agate_helper.empty_table()
AttrDict({status: '', data: dbt.clients.agate_helper.as_matrix(agate_table), table: agate_table})
```

in the case where `name` isn't in `sql_results`.

**Comment by beckjake** [comment]
>should we make the StrictUndefined warning code smarter about how many times it warns for the same issue?

yes, 100% - probably just cache the text string of the warning on a per-run basis sort of like we do with warnings.

**Comment by beckjake** [comment]
> The results context variable in the on-run-end hook context is treated as undefined

Looking into this next - maybe the same as the issue with `load_result`? That would make the never warn during parsing thing more compelling!

**Comment by beckjake** [comment]
I'm actually unable to reproduce the issue with `results`:

$ cat dbt_project.yml
name: 'minimal'
version: '1.0.0'
profile: 'local'
on-run-end:
    - "{{ log('Got ' ~ results | length ~ ' results', info=True) }}"
$ dbt run
Running with dbt=0.14.0-a1
Got 0 results
Found 3 models, 5 tests, 0 snapshots, 0 analyses, 211 macros, 1 operations, 1 seed files, 1 sources

12:46:07 | Concurrency: 2 threads (target='default')
12:46:07 |
12:46:07 | 1 of 2 START view model dbt_postgres.x............................... [RUN]
12:46:07 | 2 of 2 START view model dbt_postgres.z............................... [RUN]
12:46:07 | 1 of 2 OK created view model dbt_postgres.x.......................... [CREATE VIEW in 0.12s]
12:46:07 | 2 of 2 OK created view model dbt_postgres.z.......................... [CREATE VIEW in 0.11s]
12:46:07 |
12:46:07 | Running 1 on-run-end hook
Got 2 results
12:46:07 | 1 of 1 START hook: minimal.on-run-end.0.............................. [RUN]
12:46:07 | 1 of 1 OK hook: minimal.on-run-end.0................................. [OK in 0.00s]
12:46:07 |
12:46:07 |
12:46:07 | Finished running 2 view models, 1 hooks in 0.56s.
```

**Comment by beckjake** [comment]
For the `results` issue, it's a problem with the fact that `compile` compiles all executable nodes (which hooks are) - we should add a special case for that, and probably should have when we added results to the `on-run-end` hook context. The same goes for `schemas`.

**Comment by drewbanin** [comment]
see #1389 #1559
