### ISSUE TITLE
Compilation error when searching for a relation

### ISSUE THREAD

**Issue by snehaharchwani01** [fishtown-analytics/dbt#1555]
## Issue
Compilation error when searching for a relation

### Issue description

I have been using `get_relation` to determine if the relation exists in the schema or not. However, I am getting a run-time error (described as compilation error). 

Command: `dbt run --models address_xf`

Here's a code snippet of `address_xf`
```
{%- set source_relation = adapter.get_relation(
      database= target.database,
      schema= target.schema,
      identifier='address') -%}

{% if source_relation is none %}
    {% set address_columns_list = [] %}
{% else %}
    {% set address_columns_list = adapter.get_columns_in_relation(source_relation) -%}
{% endif %}
```

quoting  config in `dbt_project.yml`
```
quoting:
    identifier: false
    schema: false
```

### Results
I got a compilation error: 
```
Compilation Error in model “address_xf” 
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete database.schema.model, or rename it to be less ambiguous.
  Searched for: DATABASE.SCHEMA.ADDRESS
  Found: database.schema.address
```

### System information
The output of `dbt --version`:
```
0.13.0
```

The operating system you're running on:
```
macOS Mojave
version 10.14.5
```

The python version you're using (probably the output of `python --version`)
```
Python 2.7.15
```
### Steps to reproduce

1. Create a base model but do not add this model to the schema 
2. Use `get_relation` for base_model in the transformed model (as described above)
3. `dbt clean -> dbt deps -> dbt seed -> dbt compile -> dbt run --models my_models`

**Additional notes:** 
- All the base and transformed models are materialized as views. 
- This mainly happens only when the transformed models are created for the first time in an existing or a new schema. If the base models are created/updated prior to using adapters in transformed models, there are no run-time errors. 
- The subsequent runs don't reproduce these run-time errors 
- I tried to change the case of `database/schema/identifier` using `|upper/ |lower`, however, it did return the same compilation error.

**Comment by drewbanin** [comment]
Thanks for the really thoughtful writeup @snehaharchwani01! We'll take a look :)

**Comment by drewbanin** [comment]
@snehaharchwani01 a fix for this was made in #1558 which will ship with dbt v0.14.0. Thanks for your help in diagnosing this issue!

**Comment by TravisDunlop** [comment]
hello fishtown friends!  I think I am getting the same error from this issue, but on Redshift.

### System information
The output of dbt --version:
`0.14.0`

The operating system you're running on:
`macOS Mojave
version 10.14.5`

The python version you're using (probably the output of python --version)
`Python 3.7.4`

database:
`redshift`

### Steps to reproduce:
1. set `DBT_SCHEMA` to something in with capitals in it 
1. execute this command twice `dbt run --models some_small_model`. Encounter error below:

```
Compilation Error in model some_small_model (models/warehouse/some_small_model.sql)
  When searching for a relation, dbt found an approximate match. Instead of guessing 
  which relation to use, dbt will move on. Please delete "warehouse"."warehouse_thisisatest"."some_small_model", or rename it to be less ambiguous.
  Searched for: "warehouse"."warehouse_ThisIsATest"."some_small_model"
  Found: "warehouse"."warehouse_thisisatest"."some_small_model"
```

If I had to hazard a guess, we probably need to add in something to the redshift relation adaptor like Jake did in #1558?

**Comment by drewbanin** [comment]
Hey @TravisDunlop - check out this thread: https://github.com/fishtown-analytics/dbt/issues/1557#issuecomment-505031300

My recommendation would be to not use upper cased schema or table names on Redshift, as Redshift will lower-case those identifiers anyway.

I'm happy to keep #1557 open and solve this problem with either a better error message, or a case-insensitive schema/table lookup.

**Comment by ijdev** [comment]
Hi @drewbanin  I think I'm hvaing the same issue as well.

When ever I do `dbt run` for the second time I get a compilation error:
```
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete database.schema.table, or rename it to be less ambiguous.
  Searched for: database.database.database
  Found: database.schema.table
```

Using:
```
Windows 11 
python version 3.9.1
dbt version: 1.0.1
dbt-core
dbt-sqlserver
```
