### ISSUE TITLE
replace instances of dbt.exceptions with exceptions

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1569]
### Issue description
Some [default implementations of dbt macros](https://github.com/fishtown-analytics/dbt/blob/31f20348c9ffa07cdb00174b66df9ee0ef78cf6e/core/dbt/include/global_project/macros/adapters/common.sql#L226-L229) reference `dbt.exceptions` instead of `exceptions`, leading to errors like
```
'dict object' has no attribute 'exceptions'.
```

In many (all?) of these cases, the macro is raising a "not implemented" exception, so this is a low-impact bug, but one worth fixing for sure.

### Results
dbt raises the incorrect error message

### System information
The output of `dbt --version`:
```
0.13.1
```

### Steps to reproduce
This only really happens when you try to build a new adapter.
1. create a new adapter
2. don't implement methods like `list_relations_without_caching`
3. run dbt

**Comment by aminamos** [comment]
Hi @drewbanin, if I look at this, which branch should I fork from? Apologies if this was addressed in the [contributing](https://github.com/fishtown-analytics/dbt/blob/dev/0.14.1/CONTRIBUTING.md) file and I missed it. Thank you!

**Comment by drewbanin** [comment]
Hey @aminamos - our current development branch is `dev/0.14.1`. I'd branch off of there in your fork for the PR!

I'll have a think about how to better document this. Let me know if you have any questions as you dig into it!

**Comment by aminamos** [comment]
I submitted an initial pull request with the fixed macros to make sure I am on the right track. I do have one question: should I update the Python files as well?

**Comment by drewbanin** [comment]
Hey @aminamos - I'll follow up on this in the PR!
