### ISSUE TITLE
support persist_docs on all plugins

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1573]
# Feature

Meta-issue tracking the implementation of this feature for all plugins:
 - [x] pg/redshift https://github.com/fishtown-analytics/dbt/issues/2333
 - [x] snowflake https://github.com/fishtown-analytics/dbt/issues/2334
 - [x] bigquery https://github.com/fishtown-analytics/dbt/issues/2335

**Comment by ashley-sherwood** [comment]
+1!

Snowflake does offers dollar-quoted string constants which ensure that an arbitrary string is taken literally `$$they look like this, it's pretty cool, and the ' will be literal$$`

https://docs.snowflake.net/manuals/sql-reference/data-types-text.html#dollar-quoted-string-constants

Is that helpful here?

**Comment by drewbanin** [comment]
Hey @ashley-sherwood - that's _incredibly_ helpful! I didn't know you could do this on Snowflake :)

Looks like something similar is possible on Redshift/Postgres too: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS

I think this is enough info to unblock this issue for sure. Are you interested in submitting a PR for Snowflake? Would be happy to help however I can!

Thanks for the info!

**Comment by drewbanin** [comment]
persist docs is shipping for all core plugins (at the relation and column level, where possible/applicable) in v0.17.0 🎉
