### ISSUE TITLE
Remove archive block handling

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1580]
## Feature
Remove support for the archive block (and therefore remove the snapshot migration task)

### Feature description

In Wilt Chamberlain, we removed support for archives and rename them to "snapshots". As part of that, we disabled support for the "archive" configuration, but kept configuration-level support if a special flag is passed. That flag is used exclusively by the migration task.

In Louisa May Alcott we should remove that parser support for real, which entails removing the task. It will mean that anyone upgrading from <0.14.x to >=0.15.x will have to stop at 0.14.x and run the migration script. That seems fair to me!

### Who will this benefit?
Me - it's one less thing to convert to dataclasses.

**Comment by drewbanin** [comment]
Closed by #1581
