### ISSUE TITLE
Add CLI option to exclude specific schema/custom tests

### ISSUE THREAD

**Issue by jmak123** [fishtown-analytics/dbt#1586]
Please make sure to fill out either the issue template or the feature template and delete the other one!

## Feature
Add CLI option to exclude specific schema/custom tests
### Feature description
Currently dbt does not allow using `tags` with tests. Suggest adding functionality to tag tests like model to allow using `exclude` in `dbt test`. 
Also recommend modifying existing `dbt compile` output behaviour to generate names (and scripts) of tests in folder `target` so users can access those names and use `exclude` on them more easily.

### Who will this benefit?
Some tests take significant time to complete and adding `tags` functionality would give users more flexibility with test scheduling.

**Comment by drewbanin** [comment]
Thanks for making this issue @jmak123! Check out this semi-related discussion: https://discourse.getdbt.com/t/pre-proposal-column-tags/433/4

**Comment by beckjake** [comment]
Fixed in #2039 - added tags on columns (which push down to all tests for a given column) and tests themselves.
