### ISSUE TITLE
Investigate what role Tasks can play on Snowflake

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1598]
### Feature description
Snowflake has recently released support for [Tasks](https://docs.snowflake.net/manuals/user-guide/tasks.html) and [Streams](https://docs.snowflake.net/manuals/user-guide/streams.html)

Let's use this issue to understand how dbt can leverage tasks and streams to better transform data in the warehouse.

Some questions:
 - Are tasks a viable mechanism for implementing table / incremental models on Snowflake?
 - Are tasks sensible in dbt's environment-aware world? Should every dbt user get their own copies of tasks?
 - How do streams fit in here? I recall reading that tasks could be triggered by streams - is that actually the case? And is it desirable?
 - What would the MVP of support for tasks/streams look like in dbt? How do we define if it's "better" than the status quo?

**Comment by darthburrito** [comment]
@drewbanin  - do you have someone working working on this already? if not i would like to volunteer my time to look into this.

**Comment by drewbanin** [comment]
Hey @darthburrito - I haven't spent too much time looking at this! I'd be very grateful if you could give this some thought and report back here!

**Comment by darthburrito** [comment]
@drewbanin - sounds good!

**Comment by jannekeskitalopaf** [comment]
Any progress on this? I'm planning to implement incremental models using Snowflake streams. I don't envision much use for tasks thou considering how DBT works.

**Comment by drewbanin** [comment]
@jannekeskitalopaf I'd love to hear more about how you're planning on using streams! No developments on our end here, but certainly would love to kick-start the conversation.

**Comment by jannekeskitalopaf** [comment]
Basically, I'm planning to use a pre-hook to create a stream object for a source table, like "stream__<source_name>". Then I'll use my own implementation of the ref() -function to replace the source table with the stream -object if "is_incremental() == True". That's the general plan.

Of course I already hit a problem with this. We expose raw variant data only as views and streams can't be created on top of views. So, this incremental method might become usefull only in special cases where the value gained overweighs the drawbacks of exposing raw variant data to dbt models.

**Comment by drewbanin** [comment]
tasks probably aren't a great compilation target for dbt, but streams remain a compelling idea around incremental models. Closing this issue as no action is required at present
