### ISSUE TITLE
dbt should throw a compilation error for shared resource paths

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#1606]
### Issue description
If resources are configured to have the same path, dbt doesn't throw any sort of error.
e.g.
```
# dbt_project.yml
source-paths: ["models"]
test-paths: ["models"]
```
### Results
When you `dbt compile` it runs fine. If you `dbt test --data`, you'll get errors back because the select statements return rows.

### Expected results
This should throw an error:
```
source-paths: ["models"]
test-paths: ["models"]
```
As should this 
```
source-paths: ["models"]
test-paths: ["models/tests"]
```

This should not:
```
source-paths: ["resources/models"]
test-paths: ["resources/tests"]
```

### System information
dbt version 0.14.0

**Comment by beckjake** [comment]
It's probably worth noting for whoever ends up implementing this that `docs-paths` can and by default does overlap with `source-paths` (or really, anything, since it looks for `.md` instead of `.sql`)

**Comment by drewbanin** [comment]
I'd like these paths to go away long-term. Things like the `{% snapshot %}` blocks + #184 will mean that each resource will define what type of resource it is. We already do this for `{% docs %}` blocks, and it would be good to think about how to do it for custom data tests too! The really cool benefit of this approach is that multiple resource types can live inside of the same file (if desired).

I'd be in favor of renaming these paths more sensibly (#1607) than adding yet more logic around path names

**Comment by clrcrl** [comment]
OK! Happy for you to close in that case :)
