### ISSUE TITLE
raise minimum google-cloud-bigquery version

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1620]
### Issue description
dbt-bigquery requires `'google-cloud-bigquery>=1.0.0,<2'` in [setup.py](https://github.com/fishtown-analytics/dbt/blob/dev/0.14.1/plugins/bigquery/setup.py#L33). Some bigquery-focused functionality (like specifying a `location`) requires a more recent version of google-cloud-bigquery (at least 1.5.0 in this case). We should figure out the minimum version of google-cloud-bigquery required, then set that as the lower bound for the dep.

### Results
This particular error manifested as:
```
  >__init__() got an unexpected keyword argument 'location'
```

because the user had google-cloud-bigquery 1.4.0 installed. This version does not support the `location` keyword argument.

**Comment by beckjake** [comment]
As a datapoint, I have `1.5.0` installed and my tests all seem to pass ok.

**Comment by drewbanin** [comment]
we're up to `>1.15.0` now, closing: https://github.com/fishtown-analytics/dbt/blob/e51c942e91a94936f68f2965963d3b46f1257658/plugins/bigquery/setup.py#L33
