### ISSUE TITLE
Seed compilation fails with non-ascii character in v0.14.0 

### ISSUE THREAD

**Issue by brian-bk** [fishtown-analytics/dbt#1632]
## Issue

Dbt seed fails if seed file contains a special character. This is new in v0.14.0, in v0.13.1 it was working for us. This looks like https://github.com/fishtown-analytics/dbt/issues/1616 could be related.

### Issue description
When running `dbt seed`, dbt fails with output:
```
Encountered an error:
Compilation Error in seed nonascii (data/nonascii.csv)
  'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)
```

### System information
The output of `dbt --version`:
```
installed version: 0.14.0
   latest version: 0.14.0
```

OS: MacOS
Python version: 2.7

### Steps to reproduce
Here's a sample csv:
[nonascii.csv.zip](https://github.com/fishtown-analytics/dbt/files/3433083/nonascii.csv.zip)

It has contents:
```
id
Uh – Oh
```
(note the `–` is not a plain `-`)

**Comment by drewbanin** [comment]
Thanks for the report @brian-bk -- I think that #1452 might be relevant here. We'll check it out!
