### ISSUE TITLE
Allow metadata/labels key for entities in schema.yml and sources.yml

### ISSUE THREAD

**Issue by arkady-emelyanov** [fishtown-analytics/dbt#1635]
## Feature 

Allow metadata/labels key for entities in schema.yml and sources.yml

### Feature description

Allow `labels` key with arbitrary content, so the external scripts could use schema.yml and sources.yml for advanced processing on more granular level.

Possible candidate is `tags`, but, it could only be used on models and it can be only defined on `dbt_project` level.

Here is the proposed syntax:

schema.yml
```
models:
  - name: my_model
    description: model descriptions
+   labels:
+      - "my_model custom tag"

	columns:
       - name: column_name
         description: colum description
+        labels:
+          - "column custom tag"
+          - "{{ my_column_helper_value('column_name') }}"
```

sources.yml
```
sources:
   - name: source_name
     description: source description
+    labels:
+      - "source associated tag"
     tables:
       - name: source_table
         description: source table description
+        labels:
+          - "source table tag"         
```

### Who will this benefit?

Developers/DevOps who want to add some sort of logic-oriented automation on top of dbt.

**Comment by drewbanin** [comment]
Hey @arkady-emelyanov - check out these similar issues:
 - https://github.com/fishtown-analytics/dbt/issues/1362
 - https://github.com/fishtown-analytics/dbt/issues/1586

Do you mind closing this issue and following up on one of the issues listed here? Let me know if you think this issue is meaningfully different than either of these.

Thanks!

**Comment by arkady-emelyanov** [comment]
@drewbanin, your right, will follow up on #1362, as a-more-or-less closer to my thoughts. Thanks.
