### ISSUE TITLE
exception name typo

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1640]
## Issue

There's a typo in the exception name [here](https://github.com/fishtown-analytics/dbt/blob/e30ba80d6aa93ca1540eff333dfe4385aa851d22/core/dbt/task/list.py#L100) found by a user examining our code. It should say `InternalException`. I don't think it's actually reachable, but it's good to have a real error if we do hit it.

### System information
The output of `dbt --version`:
```
0.14.1
```

**Comment by drewbanin** [comment]
closed by #1672
