### ISSUE TITLE
dbt sometimes writes a `.user.yml` and ignores configs

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1645]
## Issue
If you pass dbt a relative path to `--profiles-dir` or the `DBT_PROFILES_DIR` environment variable and execute from a subdirectory, dbt will look for the user cookie and profiles.yml in different places (the latter correct, the former incorrect).

### Results
What happened? What did you expect to happen?
I got a `./profiles/.user.yml` and my settings were ignored. I expected my settings to be respected or to receive an error, and to not have a new file.

Suggested fixes:
My preference: don't allow users to run dbt from subdirectories.
Other option: defer loading of the user config until after we've found `dbt_project.yml`.

### System information
The output of `dbt --version`:
```
0.14.0
```

The operating system you're running on:
Any

The python version you're using (probably the output of `python --version`)
Any

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

1) Make a dbt project in `${project_root}`
2) put your profiles.yml in  `${project_root}/profiles`
3) Make a subdirectory (`${project_root}/models`) and cd into it
4) Run dbt with the relative path to the profiles directory as an argument to `--profiles-dir`: `dbt run --profiles-dir profiles`
5) You will now have a `${project_root}/models/profiles/.user.yml` with cookie information. Also, any settings in your `profiles.yml` won't be respected.

**Comment by drewbanin** [comment]
Let's definitely preserve the behavior where you can execute dbt from subdirs of the project. Let's instead pursue this approach:
>  defer loading of the user config until after we've found dbt_project.yml
