### ISSUE TITLE
Better error messaging for malformed source/ref inputs

### ISSUE THREAD

**Issue by ryantuck** [fishtown-analytics/dbt#1660]
## Feature

Catch malformed inputs to `source()` and `ref()` functions and elegantly bubble up to end user.

### Current error messaging is non-obvious

had a colleague who is new to dbt encounter the following cryptic error today:
```
__call__() missing 1 required positional argument: ‘table_name’
```
my hunch, knowing a good amount about dbt, was that this was related to a malformed `source()` call, was correct, as he only passed one arg into that fn instead of two:
```
{{ source('some_table') }}
vs
{{ source('my_schema', 'some_table') }}
```
even with the `--debug` flag, this was difficult to track down

### Request

It seems like these sorts of errors could be caught and communicated more effectively (I can't imagine my colleague is the first or last one to make this mistake), to output something like:
```
ERROR: source() function requires two arguments, but received only one
    in models/my_model/some_table.sql (line 51)
    >>>   from {{ source('my_table') }}
```

### Who will this benefit?

This will benefit any user who mistakenly leaves out a schema designation in her `source()` usage, or mistakenly includes a schema designation in a `ref()` call.

**Comment by drewbanin** [comment]
Thanks @ryantuck - great idea, and should be straightforward to implement. Is this something you're interested in contributing a fix for?

**Comment by ryantuck** [comment]
@drewbanin I'll see how much time I have on a night or a weekend coming up to see what I can do :)

**Comment by abronner** [comment]
+1
