### ISSUE TITLE
Improve dbt-integration-tests

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1685]
Stub issue, to be completed in more detail. There are some new dbt plugins out there in the wild, and lots of new ones in the works too. The [dbt-integration-tests](http://github.com/fishtown-analytics/dbt-integration-tests) project is a super high-leverage way to:
1. help contributors develop functioning dbt plugins
2. help contributors manage upgrades to new versions of dbt
3. programatically determine the supported featureset of a plugin (seed, snapshot, test, etc)

**Comment by jtcohen6** [comment]
I'm closing this in favor of #2492. `dbt-integration-tests` has had a good run, but it can't take us where we ultimately want to go.
