### ISSUE TITLE
Issues with regex looking for eligible model names not finding uppercase extensions (e.g. ".SQL")

### ISSUE THREAD

**Issue by jrandrews** [fishtown-analytics/dbt#1702]
### Describe the bug

There is some inconsistent behavior between running dbt on Windows and running it on MacOS/Linux. On Windows, filenames are not case-sensitive. So if one has a model with a filename of "MY_EXAMPLE_MODEL.SQL" then a `dbt run` will pick this model up. But then transferring and running the model on a non-Windows machine will result in the model not being found or executed. On the other hand, "MY_EXAMPLE_MODEL.sql" works on any OS environment.

I'm not sure whether this is intentional behavior or not. Is the goal to only process lower-case models? Or is it supposed to be anything regardless of case even in case-sensitive filesystems?

### Steps To Reproduce
create a model named "example.SQL" and execute `dbt run` on a Mac -- no models will be found. Change the model name to "example.sql" and the model will be found.

### Expected behavior
Models named .SQL, .sql, .Sql, basically, [Ss][Qq][Ll] in regex, will be found and processed.

### System information
**Which database are you using dbt with?**
-Snowflake

**The output of `dbt --version`:**
```
0.14.1-rc1
```

**The operating system you're using:**
Validated on MacOS Mojave 10.14.5 and Windows 10

**The output of `python --version`:**
Python 2.7.10

**Comment by drewbanin** [comment]
closed by https://github.com/fishtown-analytics/dbt/pull/2263
