### ISSUE TITLE
Allow packages to be installed outside of project directory

### ISSUE THREAD

**Issue by gnilrets** [fishtown-analytics/dbt#1710]
### Describe the feature
When someone installs a dbt package, the package code is installed in the dbt_modules directory in the main project directory.  We should be able to install dbt packages outside of our dbt project directory, much in the same way that pip packages are installed in a conda environment.

The end user would make use of this feature either through a flag set at runtime:
````
dbt deps --package-dir=/mypackagedir
dbt run --package-dir=/mypackagedir
````

Or through an environment variable:
````
export DBT_PACKAGE_DIR=/mypackagedir
dbt deps
dbt run
````

### Describe alternatives you've considered
You can almost get this effect by by creating your own dbt packages directory outside of the project, and then putting your packages.yml file there along with a dummy dbt_project.yml file.  Then run `dbt deps` in that package directory, and then symbolically link your project's `dbt_modules` directory to that package directory.

### Additional context
I'm building a docker container for my team to use to run dbt.  We make use of the dbt-utils package.  When the containers start up, they mount the developer's host directory into the container.  The developer can then use whatever editor they want to use to make changes to files on the host machine, and then quickly run dbt in the container.

The problem I'm running into is how to deal with packages.  I could commit the package code into my git repository.  But including code we don't maintain in our repository feels wrong, wasteful, and open to abuse. 

The symlink think seems to work for Macs, but I don't think it would work for developers using Windows.

If I could install packages elsewhere, then I could install them in the container as part of the docker build process, and then set the DBT_PACKAGE_DIR environment variable.  Then our team wouldn't have to think about packages.

### Who will this benefit?
People building managed containers for their team to run dbt (along with other tools specific to the team).

**Comment by drewbanin** [comment]
> The symlink thing seems to work for Macs, but I don't think it would work for developers using Windows.

Dang, my first thought seeing this issue was "symlinks!" but I think you might be right - Windows indeed does not support symlinks. 

I think I understand the majority of your use case, but I do have a couple of questions here.

Are you able to mount the user's package dir on their host machine to some known path in the docker container? I'm a docker novice, so I'm unsure if that's possible/recommended, but I imagine you could mount eg. `/mypackagedir` on the host machine (or `c:\mypackagedir` for Windows) to some consistent location like `/opt/dbt/packages/` on the docker container.

From there, you can use the [local package specification](https://docs.getdbt.com/docs/package-management#section-how-do-i-add-a-package-to-my-project-) to declare a package from a path in the docker container. If the docker container supports symlinks, then any changes made in the host machine will be incorporated into subsequent dbt runs.

Let me know if I'm missing something critical there. I'm not so opposed to supporting a `DBT_PACKAGE_DIR` env var or a `--package-dir` flag, but if this can be done in user-space, then I'd prefer not to implement it!

**Comment by gnilrets** [comment]
Local packages don't quite work because they still end up being installed in the project's `dbt_modules` path.

My current workaround should work for windows users too.

I've got a `.dummy_dbt_project.yml` file (not sure if this is totally necessary):
```
# This is a dummy profile used to install packages inside of the docker container
name: 'packager'
version: '1.0'
```

In the Dockerfile, I build the dbt packages using by copying the dummy profile and packages.yml to a location exclusively within the container:
```
RUN mkdir -p /dbt_packages
COPY dbt/.dummy_dbt_project.yml /dbt_packages/dbt_project.yml
COPY dbt/packages.yml /dbt_packages/packages.yml
RUN cd /dbt_packages \
    && dbt deps
```

Then when the docker image starts up, it runs a script called `image-start.sh` which creates the symlink in the container:
```
#!/bin/bash

ln -sfn /dbt_packages/dbt_modules dbt/dbt_modules
# ... other startup stuff, including JupyterLab.  Users then run dbt within a Jupyter terminal.
```

**Comment by drewbanin** [comment]
Ok, thanks for the further explanation!

One other approach comes to mind that might be worth mentioning here: can you just set your `modules-path` in `dbt_project.yml` to be an env var? You can default this to something like `dbt_modules` - I think that should work work! It might look like:

```yml
# dbt_project.yml

name: my_project
version: 1.0.0

...

modules-path: "{{ env_var('DBT_MODULES_DIR', 'dbt_modules') }}"
```

If you set the `DBT_MODULES_DIR` env var to a path like `/mypackagedir` then I think this will 'just work' for both `dbt deps` and `dbt run`.

Lmk!

**Comment by gnilrets** [comment]
Actually, `modules-path` is exactly what I was looking for originally.  I must have missed it as an option.  Thanks Drew!

**Comment by drewbanin** [comment]
woohoo! Super glad to hear that. Going to close out this issue :)

**Comment by swiatek25** [comment]
@drewbanin It seems it does not work in the newest version (1.4.5), does it?

**Comment by friendofasquid** [comment]
Two things.

First, for those coming on after dbt 1.7, this should be `packages-install-path` in `dbt_project.yml`, so something like this:

```
packages-install-path: "{{ env_var('DBT_PACKAGES_DIR', 'dbt_packages') }}"
```

Second, @drewbanin — would be great if this was supported as environment variable without the need to add this to dbt_project. But this continues to be a fine work-around.

My use case is bundling the deps into a docker image without all the other dbt code. When the volume with my code is mounted, it is, by default, just overwriting where `dbt deps` put its code.

My Dockerfile currently looks like this:

```
WORKDIR /workspace/dbt
COPY dbt/packages.yml .
COPY dbt/profiles.yml .
COPY dbt/dbt_project.yml .

RUN DBT_PROJECT_DIR=. DBT_PROFILES_DIR=. dbt deps
```
