### ISSUE TITLE
Add Copy Grants to Options in Table and View Materialization's

### ISSUE THREAD

**Issue by Carolus-Holman** [fishtown-analytics/dbt#1744]
### Add Copy Grants to View and Table Config Statement
Typically with Snowflake Tables and Views we use a Copy Grants switch to maintain grants on current View and Tables in Snowflake. Adding this will alleviate some of the Post-Hook commands to add Grants to existing objects. If the object has no grants this is ignored by snowflake.

### Alternative Approach using Post-Hooks
Adding Post-Hook Events to Re-Apply Grants. `grant select on table to role myrole`
### Snowflake Feature Only
This feature is for the Snowflake Adapter only. If developers are not responsible for maintaining security (as in roles, as we should all be thinking about security) this would alleviate additional work by the Administrator by maintaining the current security on the object

### Benefits?
This will benefit Developers and Admins when maintaining current access permissions to an object. Also it will help to create objects that need to maintain roles and are re-initialized outside of DBT. The Copy Grants switch will be present in the DDL of the Snowflake object when viewing the source through the GET_DDL command or viewing the View source.

### Sample Code Output
`CREATE OR REPLACE View myView 
/* Added Copy Grants Here */
COPY GRANTS as 
(
Select 1 as Id
);`

**Comment by drewbanin** [comment]
fixed by #1747
