### ISSUE TITLE
Macros execute commented out SQL, in my case creating a circular reference 

### ISSUE THREAD

**Issue by jonniepeller** [fishtown-analytics/dbt#1756]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

### Steps To Reproduce
Create a macro with the following code, and try to build any model
```
-- To use, call {{ my_macro() }}
{% macro my_macro() %}
	'order by 1'
{% endmacro %}
```

### Expected behavior
The first line to be ignored because it's an SQL file, so `--` should be ignored

### Screenshots and log output
```Encountered an error:
maximum recursion depth exceeded while calling a Python object```

### System information
**Which database are you using dbt with?**
Redshift

**The output of `dbt --version`:**
```
installed version: 0.13.0
   latest version: 0.14.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**
Mac OSX 10.14.6

**The output of `python --version`:**
Python 3.6.8

### Additional context
Add any other context about the problem here.

**Comment by drewbanin** [comment]
hey @jonniepeller - dbt doesn't know anything about sql comments. Any jinja code inside of comments like:
```
-- {{ my_macro() }}
```
or
`/*
  {{ my_macro() }}
*/
```

will indeed be evaluated by dbt. To ignore jinja code, try using [jinja comments](https://jinja.palletsprojects.com/en/2.10.x/templates/#comments): 
```
{# 
  {{ my_macro() }}
#}
```

**Comment by jonniepeller** [comment]
Thanks for clarifying @drewbanin :)

I think the misleading part is that it needs to be an SQL file. Could be worth removing that requirement or switching them to a different file extension?

**Comment by drewbanin** [comment]
hey @jonniepeller - what file extension were you using if not `.sql`?

**Comment by jonniepeller** [comment]
@drewbanin I'm using `.sql` as per the [docs](https://docs.getdbt.com/docs/macros)

```
To use macros, add a macro-paths config entry to your dbt_project.yml file. Macro files must use the .sql file extension.
```

Since it's not actually SQL that is stored in these files, I was thinking it might be better to not require `.sql` extension or do `.jinja` or something.

Definitely not the end of the world, it's just that my colleague and I have both made this mistake.

**Comment by drewbanin** [comment]
ah! Sure - that makes sense. Check out [this issue](https://github.com/fishtown-analytics/dbt/issues/1681) -- I think a good course of action would be to let users configure the file extensions for these types of resources. Strictly speaking, dbt models aren't _really_ SQL files either -- it's definitely reasonable to name them `.jinja.sql`, or similar!

**Comment by jonniepeller** [comment]
Thanks @drewbanin :)
