### ISSUE TITLE
Configuration blocks in snapshots fail when values contain ENV variables

### ISSUE THREAD

**Issue by swettk** [fishtown-analytics/dbt#1764]
### Describe the bug
When a config block like

```
 {{
config(
target_database='{{ env_var("DBT_TARGET_DATABASE") }}',
target_schema='snapshots',
unique_key='id',
 strategy='timestamp',
updated_at='updated_at_utc',
)
 }}
```

is utilized in a snapshot an error of `dbt.exceptions.CompilationException: Compilation Error in macro list_relations_without_caching (macros/adapters/common.sql)
  Env var required but not provided: 'dbt_target_database'` is realized.

### Steps To Reproduce
Configure a snapshot using an environment variable.

### Expected behavior
Successful snapshot creation.

### Screenshots and log output
See error message.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.2
   latest version: 0.14.2

Up to date!
```

**The operating system you're using:**
Linux - 4.19.0-5-amd64 
**The output of `python --version`:**
Python 3.6.5

**Comment by drewbanin** [comment]
Hey @swettk - check out the thread here: https://github.com/fishtown-analytics/dbt/issues/1712

**Comment by swettk** [comment]
Thanks @drewbanin !
