### ISSUE TITLE
Flag to fail on incorrect model name

### ISSUE THREAD

**Issue by mgoldbas** [fishtown-analytics/dbt#1765]
### Describe the feature
Have a flag that will raise an error when passing models to dbt run and the model does not exist

### Describe alternatives you've considered
- A test run that will check to see that the models you passed exist
- An additional script to check the models exist in DBT

### Additional context
While passing several models to DBT, the engineer that builds the model may misspell the model. Thus the script will run, but there will be no indication that the model that is misspelled is missing or incorrect. 

### Who will this benefit?
Users running DBT in production environments

**Comment by drewbanin** [comment]
Hey @mgoldbas - good idea!

dbt currently supports a `--warn-error` flag that will cause warnings to be raised as errors. We can make dbt emit a warning if a model specified in the `--models` selector does not exist. I think that this new warning in conjunction with `--warn-error` might address your use case.

Do you think that would work?

**Comment by drewbanin** [comment]
closing in favor of https://github.com/fishtown-analytics/dbt/issues/2115
