### ISSUE TITLE
Ability to deserialize json/yml in a env var

### ISSUE THREAD

**Issue by whisperstream** [fishtown-analytics/dbt#1789]
### Describe the feature
Some times we might want to store more complex information in a variable than just a single value.  I have a use case where I want to save a list of roles along with some meta-data as an env variable containing a serialized json string value

Currently I don't think there's a way to deserialize that string easily because dbt doesn't expose the json/yml modules.

Ideally I'd have:
`ENV_VAR_XYZ={"x":1, "y":2, "z":[3, 4, 5]}`

and in dbt I'd be able to do:

{% set my_data_dict = json.loads( env_var('ENV_VAR_XYZ') ) %}

### Describe alternatives you've considered
Currently, I have to create my own basic serializer/deserializer and store values like this:
x=1;y=2;z=3,4,5

But that's messy and error prone

### Additional context
Not database specific, I also submitted this issue https://github.com/fishtown-analytics/dbt/issues/1755 for adding regex to dbt, but I'm wondering if a better feature might be to have a way for people to specify the python modules they want exposed?  This is obviously a lot more complicated, but maybe worth discussing how it could be done?  In the meatime this request is to expose the json or yaml (I don't mind which - is there a preference?) libraries to the jinja context in the same way as the proposed regex module will be added (when I get my PR in). 

### Who will this benefit?
Anyone with more complex data structure processing requirements

**Comment by drewbanin** [comment]
Hey @whisperstream - check out the new docs on [fromjson](https://docs.getdbt.com/docs/fromjson) and [tojson](https://docs.getdbt.com/docs/tojson). These have been around in dbt for a while now, but we never documented them! That's fixed now :)

**Comment by whisperstream** [comment]
sweet, thanks!

**Comment by litturahul** [comment]
Is there a way that we can load JSON file? I see we can convert the JSON string to a dictionary using fromjson. but are there anyways for passing the file path to the fromjson or any other method to handle json files?
