### ISSUE TITLE
missing bullets for tojson, fromjson, debug in Jinja context documentation

### ISSUE THREAD

**Issue by whisperstream** [fishtown-analytics/dbt#1796]
### Describe the bug
missing bullets for tojson, fromjson, debug in Jinja context documentation (see image)

<img width="886" alt="Screen Shot 2019-09-30 at 9 33 46 AM" src="https://user-images.githubusercontent.com/3216061/65898225-e4b85b00-e365-11e9-9cc3-b829f72d78b1.png">

### Steps To Reproduce
Go to https://docs.getdbt.com/docs/jinja-context

### Expected behavior
That side menu lines up with bullets

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ x] other (specify: documentation)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by drewbanin** [comment]
thanks for the heads up @whisperstream! You can actually submit a suggestion directly in the docs site -- are you interested in doing that? If not, we can certainly update it :)
