### ISSUE TITLE
Snapshots with non-null valid to dates for current records

### ISSUE THREAD

**Issue by poidra02** [fishtown-analytics/dbt#1802]
Hey All-

I'm curious as to one would go about implementing snapshots with valid to dates (maybe configurable) of 3000-01-01 or 9999-12-31, and non overlapping effective and expiration dates.

I've seen warehouses handle this differently over the years, and a number of them go with artificially high valid to dates so one can add a clause like this: where some_date between effective_date and expiration_date.  To grab current records, you would just set some_date to today or greater depending on the date/time grain.

Obviously, with the null valid to dates this will would still pick up records in the past, but you'd need to have different filters to grab current records (I know, I know, you can just grab null expiration dates, but when you have SCD 2s, training end users how to use them causes me to want to have consistent ways of doing this across history).

Those same warehouses are ones that have an aversion to nulls in general, but that's probably a religious debate for another day.

So, I would love some pointers on a. how would one get some custom snapshots like this off the ground and b. assuming that's successful/doable, would there be interest in adopting this as an option more formally at some later point.

Any thoughts!  Thanks a bunch for the help.

**Comment by drewbanin** [comment]
hey @poidra02 - what do you think about making dbt models which `coalesce` the `dbt_valid_to` date to some time period way-off in the future? You could just create a view model which selects from the snapshot (using `ref()`) and make other cosmetic changes to the table if you need to.

dbt's snapshot internals use the `null` value in `dbt_valid_to` to actually process the type 2 SCDs, so making these fields non-null might be a non-trivial amount of work. I haven't actually checked out what's involved here, so it could be easier than I'm making it out to be.

We have not yet documented the interface for snapshot strategies, as it may change in breaking ways in near-term future versions of dbt. If you're ok with that, you can experiment with custom snapshot strategies by adding a new macro to your `macros/` directory that contains a macro called `snapshot_<strategy name here>_strategy`. Here's an example from the dbt internals:

https://github.com/fishtown-analytics/dbt/blob/31e085b7df015eac92faee4912fa481d1085c4b9/core/dbt/include/global_project/macros/materializations/snapshot/strategies.sql#L66-L82

You can set your strategy to be whatever value you pick for `<strategy name here>` -- dbt should use that particular strategy when executing snapshots.

**Comment by drewbanin** [comment]
closing this due to lack of interest. Snapshots can be post-processed in a model if need be!

**Comment by nathan-protempo** [comment]
I was looking for an answer to the same question - I was considering creating my own strategy that took a config value to use as the valid to date for current rows, however @drewbanin 's suggestion of using a view materialization that substitutes the NULL value in the view SQL will work just as well, and I'd rather avoid creating custom code that may well break in future releases of dbt.
