### ISSUE TITLE
Add CLI option to print all error's compiled SQL

### ISSUE THREAD

**Issue by vitorbaptista** [fishtown-analytics/dbt#1803]
### Describe the feature
A new flag to `dbt test` that prints the compiled SQL files of the test failures automatically, to help debugging the errors. This is specially useful for CI tests, as the user can't simply open the file from its filepath.

### Describe alternatives you've considered
Adding a `cat target/compiled/**/*.sql` or similar after `dbt test` is run. But this would print all compiled test files, which would be too noisy.

### Who will this benefit?
Users that run dbt on a CI. They would not only have the list of tests that failed, but also their SQL code, to help debug the failure.

**Comment by drewbanin** [comment]
Thanks for the suggestion @vitorbaptista! Sure, I think this is a great idea. What kind of flag do you have in mind?

We've talked about adding a `--verbose` flag before (#619) -- do you think it would make sense to use a catch-all flag like this, or a specific flag like `--show-test-sql-on-failure`? I imagine the latter would lead to a whole lot of one-off flags like this

**Comment by drewbanin** [comment]
closing this in favor of #1173 -- these schema test blocks will have enough info to emit helpful error messages about why they failed
