### ISSUE TITLE
`tuple index out of range` in custom schema tests with `select *`

### ISSUE THREAD

**Issue by abronner** [fishtown-analytics/dbt#1808]
if a custom schema test returns the result of `select *` instead of `select count(*)`, and the query returns 0 records, then the test fails with the error message: `tuple index out of range`. 

schema tests should return a single row with a single column that contains the count of failures. if `select *` returns 0 records, dbt hits `tuple index out of range` when it tries to grab the first column in the first row of that result set.

to reproduce, add the following test to your model:
```
{% macro test_my_custom_schema_test(model, column_name) %}

SELECT * from {{ model }} WHERE 1=0

{% endmacro %}
```
result of `dbt test`: 
```
Completed with 1 errors:

tuple index out of range
```
please add a better error message when a test returns a different result than what is expected.

**Comment by drewbanin** [comment]
Thanks @abronner! Agreed, a better error message here would be a great addition.

I just put a `good first issue` label on this issue - please let me know if it's something you'd be interested in contributing a fix for! I think the patch should be pretty self-contained :)

Thanks!
