### ISSUE TITLE
RPC method to translate dbt CLI strings into RPC tasks

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1811]
The rpc server provides methods like `run`, `compile`, `test`, etc. These methods accept a `params:` dictionary that configures the nature of the task. The dbt rpc server should make it possible to translate a CLI string (eg. `dbt run --models abc+`) into a method query. In this case, that would look like:
```
{
  "method": "run",
  "params": {
    "models": "abc+"
  }
}
```

There are broadly two ways we can accomplish this:
1. Add a new method (eg. `run_dbt_task`) which accepts a CLI-string and proxies the request to the appropriate task (and returns the delegated response). 
2. Add a new method which accepts a CLI-string and returns a parsed representation of the command, which can be used to query the appropriate method

Of these, I think the first approach would be preferable (avoid an extra round-trip) if it doesn't make the RPC server implementation too convoluted. What say you @beckjake?

**Comment by beckjake** [comment]
I think it's easier to just take a string, we can feed it directly to argparse and translate the `cls` value into its RPC equivalent or something.

I do wish we'd had this design from the start, I would have designed it to be easier to support this behavior.

**Comment by drewbanin** [comment]
Cool, that sounds great. Are you thinking we'd just provide a single task which accepts each of `dbt {run/test/snapshot/etc}`? Or are we still going to have an RPC method for each task?

Agreed - this was definitely an oversight on my part.

**Comment by beckjake** [comment]
I'm not sure yet, but my idea is:

 - an RPC-specific argument parser that raises a dbt exception on `exit` and a mechanism to choose the parser class in `parse_args`
 - some way for RPC tasks to take either the existing dictionaries or a parsed `args` object
 - A new RPC task that takes in a string, builds an argparse.args, and uses the `cls` attribute of the parsed args to decide which "real" RPC task to delegate to

This way involves the least possible amount of code rewriting, I think.

**Comment by beckjake** [comment]
Can we just strip the leading "dbt" out of method calls, so the RPC call looks something like:
```
{"method": "cli_args", "params": "run --models abc+"}
```
It's not a big difference, but its not like we're going to validate that initial name anyway and there's no real reason to send it... I know you're executing dbt :)

**Comment by drewbanin** [comment]
@beckjake sure - that works for me. In the case of multi-tiered commands like `docs generate`, would the method just be `docs.generate` still?

And would this `params` string take the place of the existing `params` block? Are there any non-dbt parameters (like `timeout` or similar) that we'd want to represent in the rpc request but not pass through to dbt's argparser?

I largely buy this, just want to make sure we have the details right

**Comment by beckjake** [comment]
sorry, I was hasty writing that, this is more accurate:
```
{
  "method": "cli_args",
  "params": {
    "cli": "docs generate --no-compile",
    "timeout": 1000,
  }
}
```

I'm going to take `cli`, pass it to `shlex.parse()`, pass that to `parse_args` with a special flag to use a different parser that raises an exception instead of calling sys.exit on error, and then add an default `rpc_method` to every class. Then we'll compare that `rpc_method` to the method name. So it'll be `docs generate` on the API side.

**Comment by drewbanin** [comment]
:+1:  :+1:  :+1:  :+1:
