### ISSUE TITLE
printer.print_run_result_error should log to warning or error instead of info

### ISSUE THREAD

**Issue by heisencoder** [fishtown-analytics/dbt#1818]
dbt.ui.printer.print_run_result_error only uses logger.info to display the messages.  However, these should be logged at either the error or warning level depending on the is_warning parameter.

**Comment by drewbanin** [comment]
Hey @heisencoder - I buy that! Feel free to send through a PR for the change if you're so inclined; I'd happily merge it :)

**Comment by heisencoder** [comment]
Coming shortly...

**Comment by drewbanin** [comment]
this was fixed in #1823 - thanks @heisencoder! :D
