### ISSUE TITLE
Agate type inference is too clever

### ISSUE THREAD

**Issue by sjwhitworth** [fishtown-analytics/dbt#1825]
### Describe the bug
We’re trying to set a value from a {% call statement %} and within the call, one line is SELECT 0 AS my_value...and it then treats it as a boolean (false) in the returned values. 

The same happens if we try SELECT 1 AS my_value, but as soon as we do SELECT 2 AS my_value it treats it like a number (as it should).

### Steps To Reproduce
Create a call statement that selects 0, or 1. false, and true respectively will be returned.

### Expected behavior
0, or 1 to be returned, as integers.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.0-a1
  latest version: 0.14.2
Your version of dbt is ahead of the latest release!
```

FYI, we run a fork, but that shouldn't have affected anything here.

**The operating system you're using:**

Mojave

**The output of `python --version`:**

Python 3.7.1

### Additional context
We'd love a quick fix for this, even if it's ugly!

**Comment by beckjake** [comment]
[This line](https://github.com/fishtown-analytics/dbt/blob/2815b33b0ae1bc2c08650213b01338a0a669050e/core/dbt/clients/agate_helper.py#L49]) should have a `column_types=DEFAULT_TYPE_TESTER` parameter, just like line 32 above it.
