### ISSUE TITLE
Look in all source folders for .yml and .md files

### ISSUE THREAD

**Issue by r-hempenstall** [fishtown-analytics/dbt#1832]
### Describe the bug
When running dbt, it looks inside the models folder for `.yml` and `.md` files but does not look inside the `snapshots` folder. This is a bit ugly when trying to specify the sources for snapshots as the queries and the snapshots and their documentation end up in different sections of the project.

### Steps To Reproduce
Create a `.yml` file specifying a source for a snapshot in the `snapshots` folder. It won't be picked up by dbt and instead you'll get an error about not being able to find the source.

### Expected behavior
When I run the snapshot function I would expect the steps described above to compile and create my snapshot using the correct source.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.3
```

**The operating system you're using:**
```
macOS Mojave
```

**The output of `python --version`:**
```
Python 2.7.10
```

### Additional context
Link to Slack discussion: https://getdbt.slack.com/archives/C0VLZPLAE/p1571144500103000

**Comment by beckjake** [comment]
Fixed in #2058
