### ISSUE TITLE
Snapshots with check option - allow custom date field to be used when setting dbt_date_from and dbt_date_to fields.

### ISSUE THREAD

**Issue by james-the-first** [fishtown-analytics/dbt#1844]
### Overview of Change
Essentially we would like to be able to supply the following config so that a snapshot with check strategy honours the updated_at field that we supply when setting the dbt_date_from/to fields.
```
 {{
        config(
          target_database='analytics',
          target_schema='snapshots',
          unique_key='id',
          strategy='check',
          updated_at='updated_at',
        )
    }}
```

We would like to use the snapshot feature to manage type 2 changes on our dimensions (products, customers etc).  

We need to use check mode (not timestamp) so we can look for record attributes that change (as well as new/deleted records).

In our staging layer we have a dw_load_datetime column on every staged dimension that represents when the data was processed.  This is the timestamp from Airflow and importantly it allows us to replay historic runs (e.g. reload data for the past 3 days).

Question - can we tell dbt to use this dw_load_datetime in the snapshot when setting the dbt_date_from and dbt_date_to fields?

Currently dbt uses the current time to do this. We can see you support this use case when in timestamp mode - but we weren’t sure why this couldn’t also apply in check mode?

**Comment by PJGaetan** [comment]
Hello, first time contributor here, I've started to look into the issue.

I feel like the only change should be [here](https://github.com/fishtown-analytics/dbt/blob/8d39ef16b67fcc3c30e8a18751b4e64831ec9aaf/core/dbt/include/global_project/macros/materializations/snapshot/strategies.sql#L147). I would get the `updated_at` option, the same way `invalidate_hard_deletes` [is](https://github.com/fishtown-analytics/dbt/blob/8d39ef16b67fcc3c30e8a18751b4e64831ec9aaf/core/dbt/include/global_project/macros/materializations/snapshot/strategies.sql#L136).

I'm not sure what kind of tests needs to be added.
I see how to add a test to check if the new option is working correctly.
But how to assert that rows have been invalidated with `updated_at` and not the current timestamp ?

**Comment by jtcohen6** [comment]
@PJGaetan I think that's right! You could replace the line you've identified with:
```sql
{% set updated_at = config.get('updated_at', snapshot_string_as_time(now)) %}
```

As far as testing this change, we already have a number of integration tests related to 'check' strategy snapshots in [`test/integration/004_simple_snapshot_test`](https://github.com/fishtown-analytics/dbt/blob/develop/test/integration/004_simple_snapshot_test). In particular:
- [`test_simple_snapshot.py::TestCheckCols`](https://github.com/fishtown-analytics/dbt/blob/8d39ef16b67fcc3c30e8a18751b4e64831ec9aaf/test/integration/004_simple_snapshot_test/test_simple_snapshot.py#L537)
- [`test_simple_snapshot.py::TestConfiguredCheckCols`](https://github.com/fishtown-analytics/dbt/blob/8d39ef16b67fcc3c30e8a18751b4e64831ec9aaf/test/integration/004_simple_snapshot_test/test_simple_snapshot.py#L561)
- [`test_simple_snapshot.py::TestCheckColsBigquery`](https://github.com/fishtown-analytics/dbt/blob/8d39ef16b67fcc3c30e8a18751b4e64831ec9aaf/test/integration/004_simple_snapshot_test/test_simple_snapshot.py#L580)
- [`test_snapshot_check_cols.py::TestSimpleSnapshotFiles`](https://github.com/fishtown-analytics/dbt/blob/8d39ef16b67fcc3c30e8a18751b4e64831ec9aaf/test/integration/004_simple_snapshot_test/test_snapshot_check_cols.py#L5)

I think a test for this could be as simple as copying/adapting one of those. After ensuring that the source table being snapshotted contains a date/timestamp column (the existing ones may not), create a snapshot with both the 'check' strategy and `updated_at` config set, run it, and confirm the `dbt_updated_at` column value in the resulting snapshot table matches the `updated_at` column value from the initial table being snapshotted.
