### ISSUE TITLE
Add `quote` parameter to `accepted_values` test

### ISSUE THREAD

**Issue by clausherther** [fishtown-analytics/dbt#1873]
### Describe the feature
Currently only character values can be tested in the built-in `accepted_values` test. 

Relevant code from `accepted_values.sql`
```
select
        value_field

    from all_values
    where value_field not in (
        {% for value in values -%}

            '{{ value }}' {% if not loop.last -%} , {%- endif %}

        {%- endfor %}
    )
```
To support testing both accepted numeric and character values, we should make quoting the values optional. 

### Additional context
https://getdbt.slack.com/archives/C2JRRQDTL/p1572299083481900
Per a Slack conversations with Claire and Drew, this should not break existing uses of this test.
Drew suggested added a `quote` parameter, the default of which should be `true`, which is the current behavior.

## Proposed change
```
{% set quote_values = kwargs.get('quote', True) %}
```
``` sql   
    select
        value_field

    from all_values
    where value_field not in (
        {% for value in values -%}
            {% if quote_values == True -%}
            '{{ value }}'
            {%- else -%}
            {{ value }}
            {%- endif -%}
            {%- if not loop.last -%},{%- endif %}
        {%- endfor %}
    )
```
### Who will this benefit?
All users that use the `accepted_values` test.

**Comment by clrcrl** [comment]
You can change `{% if quote_values == True -%}` to be `{% if quote_values -%}`

**Comment by clausherther** [comment]
Wasn't sure how that worked in Jinja, thx!
