### ISSUE TITLE
Enable hooks for snapshots

### ISSUE THREAD

**Issue by DGaulke** [fishtown-analytics/dbt#1880]
### Describe the feature
Enable hooks for snapshots

### Describe alternatives you've considered
I wrote python code to apply specified indexes to snapshotted tables (if they don't already exist), and tied it into our job infrastructure.

### Additional context
For transactional databases (i.e. databases that support indexes)

### Who will this benefit?
Snapshot tables can grow rapidly, and indexes help. It would be nice to define and implement them in the same location as the snapshot configuration rather than applying them manually after the table is created.

**Comment by drewbanin** [comment]
This was added in https://github.com/fishtown-analytics/dbt/pull/1759 via https://github.com/fishtown-analytics/dbt/issues/1613, to be released in dbt v0.15.0 in November :)
