### ISSUE TITLE
Flagging duplicate macros

### ISSUE THREAD

**Issue by amychen1776** [fishtown-analytics/dbt#1891]
### Describe the feature
Requesting for dbt to provide an error message when there are macros with the same name.

### Describe alternatives you've considered
N/A

### Additional context
This isn't database specific. 

### Who will this benefit?
My use case was that I was fixing a macro and copied and pasted it to another file. I forgot to delete the incorrect macro of the same name when I was done. When the model called for the macro, it actually just pulled in the old version of the macro.  This is just a suggestion of idiot proofing things that can be missed.

**Comment by drewbanin** [comment]
This is a _great_ suggestion - I just ran into this today too.

dbt allows you to override macros from an imported package (like how you can override `generate_schema_name`, for instance). I think we want to make sure that there aren't two macros with the same name in the same package. I don't believe there's ever a reasonable use case for that.

Thanks!

**Comment by beckjake** [comment]
Fixed in #2045
