### ISSUE TITLE
In projects named `warehouse`, Snowflake warehouse config gets confused

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#1899]
### Describe the bug

If a dbt project is named `warehouse`, almost all Snowflake models running in the 0.15.0 beta release experience the following error:
```
Database Error in model my_model (models/my_model.sql)
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 14 unexpected '{'.
  compiled SQL at target/compiled/my_project/my_model.sql
```

This is caused by the changes in #1788, which allow per-model Snowflake warehouse specification using a `warehouse` config argument. If a dbt project is also named `warehouse`, [confusion ensues](https://i.kym-cdn.com/photos/images/newsfeed/001/462/558/db1.jpg).

In an example `dbt_project.yml`:
```yml
name: warehouse
. . .
models:
  warehouse:
    enabled: true
    materialized: view
    schema: analytics
```

For all models that _do not_ have a `warehouse` config argument specified, Instead of skipping the `use warehouse` statement altogether, dbt is running
```
On my_model: use warehouse {'enabled': True, 'materialized': 'view', 'schema': 'analytics'}
```

I believe the relevant line is [here](https://github.com/fishtown-analytics/dbt/blob/dev/louisa-may-alcott/plugins/snowflake/dbt/adapters/snowflake/impl.py#L65) of `pre_model_hook`, whereby `config.get('warehouse', default_warehouse)` returns... not the `warehouse` we're looking for.

### Steps To Reproduce

Name your dbt project `warehouse`, and run any model on Snowflake without a `warehouse` config.

### Expected behavior

A model with no `warehouse` config should _always_ behave exactly the same as a model configured
```sql
{{config(
    warehouse = target.warehouse
) }}
```

### System information
**Which database are you using dbt with?**
- [x] snowflake

**The output of `dbt --version`:**
```
installed version: 0.15.0-b2
   latest version: 0.14.3

Your version of dbt is ahead of the latest release!
```

### Additional context
The easiest solution here is to rename the dbt project to something other than `warehouse`. For that reason, I would understand if this is a #wontfix

**Comment by beckjake** [comment]
Oh no, this is terrible. I think we need to add `warehouse` to the list of blacklisted project names in `contracts/project.py`, at least.

**Comment by jtcohen6** [comment]
I just tested a project that is not named `warehouse` but which does have a `models` subdirectory named `warehouse`, with config present in `dbt_project.yml`. That also results in this error.

Is there a way to more tightly scope the `{{config.get()}}`? Or enforce that its type must be a `str`?

**Comment by drewbanin** [comment]
@beckjake let's rename `warehouse` to `snowflake_warehouse` to fix this specific problem.

Let's also revisit this question in a future release to figure out how to make dbt's config structure unambiguous. This will all break if people have projects or paths named `sort, `bind`, `dist`, etc etc etc which is not what we want here long term
