### ISSUE TITLE
Enable tagging of sources, not just models

### ISSUE THREAD

**Issue by mferryRV** [fishtown-analytics/dbt#1906]
### Describe the feature
Allow tagging of sources, similar to tagging of models.

### Describe alternatives you've considered
The primary use case for tagging in sources as well as models is to isolate a set of transformations soup-to-nuts. When I do a bunch of work on, say, email data, I want to show people the sources, transformations, and outputs I created. I can do that for one source with DAG commands like `source:braze_segment+`
![image](https://user-images.githubusercontent.com/24232245/68486424-f0d2ea80-0238-11ea-98ec-643e782312d3.png)

But what about when I add Responsys? Mandrill? Now I have multiple sources and I can't display them all at once. I'd need to pick a downstream table and show all the upstream dependencies, but what if some of my source tables aren't being used yet?

It would be easier if I could just tag source tables as related to my models & display this full process for my teammates to understand the work I've done.

### Additional context
This use case is primarily aimed at `dbt docs` functionality, so changes in the flexibility of the Lineage Graph might make this less necessary.

### Who will this benefit?
Anyone trying to onboard someone to a new dataset would benefit from the ability to show _everything_ at their disposal.

**Comment by drewbanin** [comment]
Yep! Great idea - let's do it :) 

There are a couple of semi-related issues here that i think we should consider here too:
 - https://github.com/fishtown-analytics/dbt/issues/1362
 - https://github.com/fishtown-analytics/dbt/issues/1586

**Comment by mferryRV** [comment]
Stoked to see this prioritised!

For the curious as a stop gap, you can highlight multiple sections of the dag by putting a space between the commands, e.g. `source:my_source_1+ source:my_source_2+` like so:
![image](https://user-images.githubusercontent.com/24232245/69138772-2f796800-0ab7-11ea-8f55-93da3baf2fea.png)

Not quite as flexible as tagging, but still useful!

**Comment by beckjake** [comment]
This is fixed in #2039
