### ISSUE TITLE
Capitalization of db name does not work for PostgreSQL

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#1914]
### Describe the bug
My PostgreSQL database has a capital letter, i.e. MyDB

I created a single model and I get

ERROR: Cross-db references not allowed in postgres (mydb vs MyDB)

### Steps To Reproduce
Create a database named MyDB. Add a table named 'address'

Add a model

select * from public.address

### Expected behavior
dbt run should work

### Screenshots and log output
ERROR: Cross-db references not allowed in postgres (mydb vs MyDB)

### System information
**Which database are you using dbt with?**
- [X ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.4
   latest version: 0.14.4

Up to date!
```

**The operating system you're using:**

Windows 10

**The output of `python --version`:**

Python 3.7.3

(Also will fail with any version of Python. )

### Additional context

In Python, when accessing a table or a db or a schema, make sure you put it inside quotation marks "or it won't work".   I'll raise a bug if the same issue also applies to schemas with capital letters or tables with capital letters.

**Comment by drewbanin** [comment]
hey @philippe-lavoie - thanks for the report! This is definitely a bug, we'll check it out.

I dug into this one really quickly:  dbt supports a `quoting:` object in the `dbt_project.yml` file. That would look something like:
```
quoting:
  database: true
```

In this case, it looks like dbt fails to run on pg when database names are mixed-case even when database quoting is enabled.
