### ISSUE TITLE
Webhook for job complete (DBT Cloud)

### ISSUE THREAD

**Issue by chrisgoddard** [fishtown-analytics/dbt#1921]
I'm not sure if there's an existing way to do this - I can't find anything in documentation.

It would be great if you could configure a web-hook to be called when a job completes. 

I guess this could could be part of the DBT core framework but it's probably less necessary for anyone self-hosting, but within DBT cloud, being able to define web-hooks at the project or job-level for when a job is complete would be incredibly useful.

There's a lot of additional processes we would love to kick off from a DBT run job completing (and potentially different actions based on the status of the run).

If there's another way to accomplish this, please let me know!

**Comment by drewbanin** [comment]
Hey @chrisgoddard - cool idea! We track and prioritize features for dbt Cloud separately from this repository. I made a note of your request and would be happy to follow up with you either in dbt Slack (in #dbt-cloud) or over the in-app chat in the dbt Cloud application.

I do agree that this is probably something better suited for dbt Cloud than for dbt Core. 

Thanks!

**Comment by noahjustinsure** [comment]
This feature has been requested multiple times in the Slack and never been addressed AFAIK.

It's been three years since the original request here.

Seems like low hanging fruit with a high reward that adds a lot of value to a cloud service that isn't strictly necessary to use.

Not having this feature pushes users to migrate away from cloud as well...

I'd love to see this feature and if I can help develop it I'm prepared.

I just don't know where to start.

**Comment by barryaron** [comment]
Hey @noahjustinsure - perfect timing, we are working on this feature now (webhook for job completion) and expect it to be in beta this quarter.  Happy to chat more about how you want to use it, and other webhooks you would be interested in seeing!

You can sign up to be kept in the loop and added to the beta [here](https://forms.gle/K9suBjyHx7C5VPu5A)

**Comment by cjcjameson** [comment]
bump -- excited for this!

**Comment by sdepablos** [comment]
Any updates on this? The quarter already passed some time ago

**Comment by elongl** [comment]
Really looking for this feature!

**Comment by nicastelo** [comment]
Hello! Any updates here?

**Comment by ran-eh** [comment]
Gentle ping.  Has this been de-prioritized?

**Comment by shorvath0118** [comment]
Also interested - any update on this feature?
