### ISSUE TITLE
snaphots-paths breaks dbt

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#1929]
### Describe the bug
According to the docs, I should be able to add a snapshots-paths section. When I do so, I get

```
dbt run
Running with dbt=0.14.4
Encountered an error while reading the project:
  ERROR: Runtime Error
  Runtime Error
    Invalid arguments passed to "Project" instance: Additional properties are not allowed ('snapshots-paths' was unexpected)
Encountered an error:
Runtime Error
  Could not run dbt
```

### Steps To Reproduce
Add this to your dbt_project.yml file

```
snapshots-paths:
- snapshots
```
### Screenshots and log output

```
dbt run
Running with dbt=0.14.4
Encountered an error while reading the project:
  ERROR: Runtime Error
  Runtime Error
    Invalid arguments passed to "Project" instance: Additional properties are not allowed ('snapshots-paths' was unexpected)
Encountered an error:
Runtime Error
  Could not run dbt
```

### System information

**The operating system you're using:**
Windows

**The output of `python --version`:**
Python 3.7.3

### Additional context
Trying to follow the documentation instruction in [snapshots](https://docs.getdbt.com/docs/snapshots)

**Comment by drewbanin** [comment]
I think you want `snapshot-paths` here - the docs you linked to correctly state this. Let me know if I'm missing some instance of `snapshots-paths` -- if that's documented, it's incorrect!
