### ISSUE TITLE
snapshot have to be defined in schema file and lineage is wrong

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#1930]
### Describe the bug
The documentation states that I should refer to a snapshot has a source

```
with person as (
    select * 
    from {{source('public','person_snapshot')}}
),
```

But if I only define a snapshot for a person, then the source is 'undefined'. If I add the person_snapshot as a source, then the lineage between person and person_snapshot is not shown in the generated docs.

Can you clarify how to reference/leverage a snapshot properly if my expected behavior is wrong ? I'm trying to find examples where snapshots are used and it's a bit hard.

### Steps To Reproduce
Add a snapshot for a table in the snapshots/ folder, have a model reference it with the source attribute (I'm assuming a ref attribute would also fail)

### Expected behavior
Since snapshots are independently managed inside a dedicated folder, DBT should auto-add the new source and document it properly by adding the new fields (i.e. the source is already documented in schema.yml) and from a lineage perspective, I should see that the snapshot comes from the original source.

```
    - name: dbt_scd_id
    - name: dbt_updated_at
    - name: dbt_valid_from
    - name: dbt_valid_to
```

### System information

**The output of `dbt --version`:**
```
dbt=0.14.4
```

**The operating system you're using:**
Windows

**The output of `python --version`:**
3.7.3

### Additional context
I'm generating all the snapshot files, so it's trivial for me to also modify the schema (still not sure how to carry lineage forward between two sources), but that's because I wrote a tool. Manual interventions should be minimized if possible when not needed.

**Comment by drewbanin** [comment]
Hey @philippe-lavoie - are you aware of our Slack channel (slack.getdbt.com) and Discourse (discourse.getdbt.com)? These are great forums to get help with questions you might have around using dbt.

This is in fact not a bug and I feel badly that you had to make a whole bug report to get this answer!

The docs state that you should _treat snapshots like source data_. That is: they should not be modified directly, and you should clean them up with downstream models. Further, there should only be one copy of a given snapshot in your database -- these don't really make sense in an environment-aware context (eg. where different dbt developers have their own copies of the snapshot).

You can find more information on this topic here: https://blog.getdbt.com/track-data-changes-with-dbt-snapshots/

If you're referring to a snapshot in a downstream model, you can select from it using the `ref()` function. That might look like:
```
select * from {{ ref('person_snapshot') }}
```

Given a snapshot defined like:
```
{% snapshot person_snapshot %}
... 
{% endsnapshot %}
```

Last, the next release of 0.15.0 will include snapshots in the documentation and DAG views of the auto-generated documentation site. That might be helpful here. Snapshots are not currently showin in the documentation site.
