### ISSUE TITLE
Snowflake integration test 050: alternate warehouse (DBT_TEST_ALT) should be configurable

### ISSUE THREAD

**Issue by clausherther** [fishtown-analytics/dbt#1939]
When running integration test, `test/integration/050_warehouse_test/test_warehouses.py::TestModelWarehouse::test_snowflake_override_ok`
dbt uses a hardcoded warehouse name `DBT_TEST_ALT` for the alternate virtual warehouse. 
https://github.com/fishtown-analytics/dbt/blob/099adf9bab908d62e9f07eadb5033051c5c33575/test/integration/050_warehouse_test/test_warehouses.py#L42

This should be configurable in `test.env`, e.g.
```
SNOWFLAKE_TEST_ALT_WAREHOUSE=MY_ALT_WH
```

**Comment by drewbanin** [comment]
Thanks for the report @clausherther - agreed! We'll fix this in a future release
