### ISSUE TITLE
Create a blessed Dockerfile for dbt

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1944]
### Describe the feature
The people want a Dockerfile. Let's give the people what they want :)

We've historically pointed people to [this Dockerfile](https://github.com/davidgasquez/dbt-docker) (thanks @davidgasquez!) but it's worth creating a blessed version that we keep up to date with new dbt releases.

### Describe alternatives you've considered
- Deferring to open source versions of this Dockerfile
  - From Slack: "Blessed official docker images would be great for getting sign-off from corporate security."
  - I buy that :)

**Comment by davidgasquez** [comment]
Heya @drewbanin! I'm happy to move the [Dockerfile](https://github.com/davidgasquez/dbt-docker/blob/master/Dockerfile) over here and point back to it from my repo to keep things unified. 

Happy to send a PR with it if it sounds good.

**Comment by marcuslira** [comment]
I would suggest a smaller base image. Maybe slim?

**Comment by drewbanin** [comment]
@davidgasquez that sounds great! We already have a Dockerfile in the repo that we using for automated testing - curious if y'all think the deployment-oriented Dockerfile should live in the dbt repo or somewhere else. Maybe a subdir? We can get it up on Dockerhub too.

I'm a little out of my depths with all things Docker - let me know if I'm thinking about this the wrong way

**Comment by davidgasquez** [comment]
From what I've seen in other Open Source projects like [fluentd](https://github.com/fluent/fluentd-docker-image), [nginx](https://github.com/nginxinc/docker-nginx) or [vault](https://github.com/hashicorp/docker-vault), seems the standard is to have it on its own repository (`docker-projectname`).

Personally, I think this approach will make it easier to manage (CI/CD) and also isolate possible issues from the main project. How does this sounds?

**Comment by drewbanin** [comment]
@cmcarthur how does @davidgasquez's suggestion sound to you?

**Comment by cmcarthur** [comment]
@drewbanin sounds like the right move. i can create the official docker hub org and registry, and the `fishtown-analytics/docker-dbt` repository. can you give some thought to which versions of dbt we want to maintain docker images for?

**Comment by drewbanin** [comment]
@cmcarthur I think we'll probably want to have docker images for every version >= 0.15.0! Is there a good way to automate (or streamline) the creation of a new image in the dbt release process? Or is that not how these things typically work?

**Comment by cmcarthur** [comment]
@drewbanin that's exactly how this should work, and there's a straightforward way to accomplish that with CircleCI

**Comment by beckjake** [comment]
I'm going to mark this as fixed in #2119. Although we do have to decide still what we're going to do with the dockerfiles/requirements files we create, I think the dockerfile that we generate and push in that PR's script is a good enough basis for this that we can add any relevant issues we want about it. For example, it might make sense to have an issue to `git add` those dockerfiles/requirements files and get them into the repository whenever we get a CI process that does real releases up and running.

**Comment by davidgasquez** [comment]
Sweet! What's the name of official Docker image? I'm happy to deprecate https://github.com/davidgasquez/dbt-docker and point people to this one.

**Comment by beckjake** [comment]
The name is `fishtownanalytics/dbt`, right now 0.16.0rc2 is out! I use it like this:
```
docker run -it --mount 'type=bind,source=/Users/jake/.dbt,target=/home/dbt_user/.dbt' --mount='type=bind,source=/Users/jake/src/fishtown/projects/debug,target=/usr/app' fishtownanalytics/dbt:0.16.0rc2 dbt compile
```

There are probably bugs and my way of setting it up probably has fundamental flaws, I would love feedback!

**Comment by davidgasquez** [comment]
Awesome! I've been tinkering with that image trying to make it work with our workflow. This is how my `Dockerfile` looks in case someone finds it helpful:

```Dockerfile
FROM fishtownanalytics/dbt:0.16.0rc2
USER root
ENV DBT_PROFILES_DIR=/dbt/profile/
COPY buffer/ /dbt/
WORKDIR /dbt
RUN dbt deps
```

I also have a Makefile to manage and run the project.

<details><summary>Makefile</summary>
<p>

```Makefile
IMAGE_NAME := gcr.io/buffer-data/buffer-dbt:latest

GCLOUD_CONFIG_FLAG = -v $(HOME)/.config/gcloud/:/root/.config/gcloud
ENV_FLAG = -e DBT_USER=$(USER) -e DBT_TARGET=dev

build:
	docker build -t $(IMAGE_NAME) .

push: build
	docker push $(IMAGE_NAME)

run: build
	docker run --rm -it $(GCLOUD_CONFIG_FLAG) $(ENV_FLAG) $(IMAGE_NAME) dbt run

dev: build
	docker run --rm -it $(GCLOUD_CONFIG_FLAG) $(ENV_FLAG) -v $(PWD)/buffer:/dbt $(IMAGE_NAME) /bin/bash
```

</p>
</details>

A few interesting things to note:

- Docker permissions for the `dbt` folders (logs, modules, ...). We were using the `root` user and this image uses `dbt_user`, which is probably a better option. While I figure out the permission details I'm adding a using `USER root` to our `Dockerfile`.
- Keeping the `dbt` profile versioned with `DBT_PROFILES_DIR` and a profile folder in the same repo. We're using environment variables to dynamically change the profile (e.g. `schema: "dbt_{{ env_var('DBT_USER') }}"`)
- Getting the dependencies now requires `DBT_TARGET`. I'm not sure if this is related with the new version or with something I'm missing with this new image but I can't run that last `Dockerfile` line anymore. There was no issues with `davidgasquez/dbt:0.15.1` though, and the variable wasn't defined there! :thinking:  

If I can fix any of these issues I'll leave a comment here. Thanks for the new image @beckjake!

**Comment by drewbanin** [comment]
@beckjake can you create this issue?
>  For example, it might make sense to have an issue to git add those dockerfiles/requirements files and get them into the repository whenever we get a CI process that does real releases up and running.

Also, let's get this docker image up on docs.getdbt.com - I can handle that part :)

**Comment by bcdady** [comment]
@drewbanin I just had a colleague send me the link to [hub.docker.com/u/fishtownanalytics](https://hub.docker.com/u/fishtownanalytics), as a suggested alternative to the DBT image we're maintaining internally. I eventually found my way here, as my searches for 'Docker' on [getdbt.com](https://docs.getdbt.com/) and [github.com/dbt-labs/](https://github.com/dbt-labs/dbt#readme) came up pretty empty.

Your last comment here caught my eye ... is there still a possibility of getting Docker Hub steps added here https://docs.getdbt.com/dbt-cli/installation?
