### ISSUE TITLE
Snowflake hang on "SQL access control" error"

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1956]
### Describe the bug
I just encountered an instance where a dbt model failed on Snowflake with a "SQL access control" error. dbt correctly failed the model, but then dbt appeared to hang -- there were subsequent models left to run, but none of them were picked up by the dbt runner.

It remains unclear if this permission error is the cause of the hang that I observed - it might in fact be unrelated.

### Steps To Reproduce
Create a view owned by one role, then try to overwrite it in a model using a different role. dbt should not hang. If it does hang, then dbt is doing something incorrectly when trying to handle the database error.

### System information
**Which database are you using dbt with?**
- Snowflake

**The output of `dbt --version`:**
```
0.14.4
```

**Comment by beckjake** [comment]
Just to update - I was never able to reproduce this issue, so we still do need more information.

**Comment by drewbanin** [comment]
ok - I spent some more time here and was able to see an error message like:
```
  View 'DEBUG_PERMISSIONS' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, con
tact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object.
  compiled SQL at target/run/fishtown_internal_analytics/debug_permissions.sql
```

dbt did not hang, and everything worked as intended. Closing this one.
