### ISSUE TITLE
dbt list does not output valid json

### ISSUE THREAD

**Issue by jkornblum** [fishtown-analytics/dbt#1959]
### Describe the bug
I'm running `dbt ls --output json > models.json` and the output is not valid JSON.
I cannot parse it with Python `json.load` and online JSON validators fail it.

It looks like to me it's just appending list of objects
```
{ ... }
{ ... }
```

but I assume in this format it needs to be a list of objects to be valid JSON
```
[
  { ... },
  { ... }
]
```

### Steps To Reproduce
Run `dbt ls --output json > models.json` on project with two or more models and review output

### Expected behavior
`models.json` to be valid JSON so it may be parsed by standard tools.

### System information

**The output of `dbt --version`:**
```
dbt --version
installed version: 0.15.0
   latest version: 0.15.0

Up to date!
```

**The operating system you're using:**
Mac OSX 10.15.1

**The output of `python --version`:**
`Python 3.7.3`

**Comment by jkornblum** [comment]
I think here, I haven't followed all the code entirely but its `yield`ing each chunk.
Would have to gather all chunks and call `json.dumps` on that.

https://github.com/fishtown-analytics/dbt/blob/e51c942e91a94936f68f2965963d3b46f1257658/core/dbt/task/list.py#L74-L81

**Comment by drewbanin** [comment]
hey @jkornblum - this is the correct behavior - `dbt ls` should emit one json record per line. The benefit here is that you can pipe the output into other bash tools like `grep` or `jq`. This format is commonly referred to as line delimited JSON, or LDJSON for short.

If you'd like, you can load each line in the output as an individual json document, then append them to a list for further processing. Let me know if you have any further questions here!
