### ISSUE TITLE
Can't install dbt v0.14.4

### ISSUE THREAD

**Issue by stetou** [fishtown-analytics/dbt#1965]
### Describe the bug
I've tried to install dbt v0.14.0 and v0.14.4 on windows 10 and get the same error

> Collecting psycopg2<2.8,>=2.7
>   Using cached https://files.pythonhosted.org/packages/63/54/c039eb0f46f9a9406b59a638415c2012ad7be9b4b97bfddb1f48c280df3a/psycopg2-2.7.7.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: 'd:\program files\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-my657x42\\psycopg2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-my657x42\\psycopg2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\pip-egg-info'
>          cwd: C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\
>     Complete output (23 lines):
>     running egg_info
>     creating C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\pip-egg-info\psycopg2.egg-info
>     writing C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\pip-egg-info\psycopg2.egg-info\PKG-INFO
>     writing dependency_links to C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\pip-egg-info\psycopg2.egg-info\dependency_links.txt
>     writing top-level names to C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\pip-egg-info\psycopg2.egg-info\top_level.txt
>     writing manifest file 'C:\Users\Steve\AppData\Local\Temp\pip-install-my657x42\psycopg2\pip-egg-info\psycopg2.egg-info\SOURCES.txt'
> 
>     Error: pg_config executable not found.
> 
>     pg_config is required to build psycopg2 from source.  Please add the directory
>     containing pg_config to the $PATH or specify the full executable path with the
>     option:
> 
>         python setup.py build_ext --pg-config /path/to/pg_config build ...
> 
>     or with the pg_config option in 'setup.cfg'.
> 
>     If you prefer to avoid building psycopg2 from source, please install the PyPI
>     'psycopg2-binary' package instead.
> 
>     For further information please check the 'doc/src/install.rst' file (also at
>     <http://initd.org/psycopg/docs/install.html>).
> 
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

BEfore that I successfully installed v0.15, but I un install it to get 0.14 since the code I'm using is not ready for 0.15 yet
I also tried 
`pip install psycopg2-binary` and try to reinstall dbt v0.14.4, got the same error

### Steps To Reproduce
pip install dbt==0.14.4

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x ] snowflake
- [ ] other (specify: ____________)

**The operating system you're using:**
windows 10

**The output of `python --version`:**
python 3.8.0

### Additional context
Not familiar yet with python and I don't need/have postgres and pg_config

**Comment by drewbanin** [comment]
hey @stetou - it's hard to say what the issue might be from this installation alone. I think your best bet here might actually be to use dbt v0.15.0 if you can. In 0.15.0, we changed dbt to use to `psycopg2-binary` dep by default. In 0.15.0, you won't need to have a compiler on your system to install pyscopg2, which is convenient.

I think the problem you're seeing here is that you have Python 3.8 installed, but there are no [Python wheels](https://pythonwheels.com/) for psycopg2 < 2.8 present for Python 3.8 on PyPi: https://pypi.org/project/psycopg2/2.7.7/#files

As such, pip is trying to install the pyscopg2 dependency from source which unfortunately requires a compiler. So, if you're able to swing dbt v0.15.0, I think/hope it would work well for you. If not, you might need to either 1. set up a compiler ( 😞 ) or 2. downgrade your python installation to 3.7 ( 😞 ).

Hope this helps! Let me know how it goes

**Comment by stetou** [comment]
Thanks, I downgraded to 3.7 for now
