### ISSUE TITLE
Column.is_integer() method

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#1969]
The [Column](https://docs.getdbt.com/docs/api-variable#section-instance-methods-) class has an instance method, `is_numeric()` that returns true if the column is a fixed-precision Numeric type (eg. numeric), else False (including integer and float types).

There are instances where I want to determine:
- Is this column generally numeric? I.e. one of: decimal, float, integer
- Is this column an integer? i.e. one of bigint, smallint, integer (e.g. on Redshift).

The second one is easy: let's add an `is_integer()` method.
But I don't know how to name the first method, since `is_numeric()` is already reserved for numeric (i.e. decimal) columns. Can we rename `is_numeric` to `is_decimal`, or will that mess up too many things?

**Comment by drewbanin** [comment]
I don't think renaming `is_numeric()` is a good idea. Can we instead name this new method `is_number()`? `numeric` is a well-defined type on pg/redshift/snowflake/bigquery/etc. We'll probably also want to add a method for `is_float()`.

The `is_number()` implementation could just check if a column `is_integer() or is_numeric() or is_float()`.

**Comment by drewbanin** [comment]
@clrcrl are you interested in contributing a PR for this issue? It might be a little tricky with differing semantics between each of the databases that dbt supports, but the code will be pretty straightforward to implement after some fact-finding work :)

**Comment by clrcrl** [comment]
Yeah I could do that for sure!

**Comment by clrcrl** [comment]
Happy for @beckjake to take this one!

**Comment by beckjake** [comment]
Fixed in #2046
