### ISSUE TITLE
detect when setuptools is downlevel and abort the isntall with a good error

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1975]
### Describe the feature
dbt requires a version of setuptools greater than `v40.1.0` to install. We should check for this version and raise a useful error message if the user is downlevel.

### Describe alternatives you've considered
We can just ignore this and let users get errors about not finding `find_namespace_packages` at install time.

### Additional context
dbt requires the `find_namespace_packages` function from setuptools, which was introduced in `v40.1.0` (see [here](https://setuptools.readthedocs.io/en/latest/history.html#v40-1-0)). We currently crash with a pretty unhelpful error message about `cannot import name 'find_namespace_packages'`. Instead we should check and raise an error instructing users to run `python -m pip install -U seuptools`.

### Who will this benefit?
Users trying to install dbt, especially those new to python/pip.

**Comment by drewbanin** [comment]
really good idea @beckjake - is this something we can hit for 0.15.1? I just put it in that milestone, but we can change to 0.15.2 if needed

**Comment by beckjake** [comment]
Yeah, totally! It should be a trivial change, just a quick tweak to `setup.py` to catch the `ImportError` I would guess. If it's harder than that we can kick it out.
