### ISSUE TITLE
run dbt with an arbitrary schema

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#198]
Right now we're running into a workflow challenge when folks are reviewing PRs. Here's the sequence of events:

- analyst writes and tests code in a feature branch using his/her development target
- analyst builds an audit report that shows outputs that is pointed to development target
- analyst checks in code and submits a PR, sharing report as well
- analyst moves to implement next feature, creating a new branch off master, continuing to use development target
- reviewer looks at PR and associated report, but report fails because the target is now built against a new feature branch.

Everyone's doing everything almost exactly right here, but really, when the PR is submitted, there should be a dbt run done against a schema that is specific to that PR. That schema should be deleted when the PR is closed. Right now, dbt makes it somewhat annoying to actually do this; it requires adding a new target. This should be a workflow that we encourage, not discourage.

**Comment by drewbanin** [comment]
this is such a good idea. how cool would `dbt pull-request` be? It could 
1. execute `dbt run` against a brand new schema
2. execute `dbt test`
3. create a PR for your branch containing `run` success/fail + test results

^ I'm not sure if the dbt CLI client should be in charge of doing all this, but something to consider....

**Comment by drewbanin** [comment]
Closing this because arbitrary schemas are now supported via [macros](https://github.com/fishtown-analytics/dbt/pull/522)
