### ISSUE TITLE
Database Error messages include `run` sql path instead of `compiled` SQL path

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#1985]
### Describe the bug
Database Error messages include `run` sql path instead of `compiled` SQL path.

### Steps to reproduce
* Run a model with bad SQL

### Expected results
* Database Error returned with a path to the `compiled` file (this was the case for v0.14.4)
```
Database Error in model test_date_trunc (models/cross_db_utils/test_date_trunc.sql)
  000904 (42000): 01908e37-0358-2460-0000-0e690422b63a: SQL compilation error: error line 11 at position 22
  invalid identifier 'UPDATED_AT'
  compiled SQL at target/compiled/dbt_utils_integration_tests/cross_db_utils/test_date_trunc.sql
```
(note: `target/compiled`)

### Actual results
* Database Error returned with a path to the `run` fil
```
Database Error in model test_date_trunc (models/cross_db_utils/test_date_trunc.sql)
  000904 (42000): SQL compilation error: error line 11 at position 22
  invalid identifier 'UPDATED_AT'
  compiled SQL at target/run/dbt_utils_integration_tests/cross_db_utils/test_date_trunc.sql
```
(note: `target/run`)
### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

**The output of `dbt --version`:**
v0.15.0

### Additional context
Reason I don’t love it: I frequently copy the filepath of the failing SQL, type atom [cmd + v] to open the file, copy it into a query runner and try to run it. I in fact _don’t_ want the DDL when I copy it.

**Comment by infused-kim** [comment]
+1. I’m having exactly the same issue and use case. 

Would it be possible to make this configurable?
