### ISSUE TITLE
dbt test should accept standard graph control syntax, like dbt test --models [model_name]

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#199]
`dbt test` should accept standard graph control syntax, like `dbt test --models [model_name]`. as testing gets used more heavily, tests take a long time to run. this is ok on a scheduled basis, but is a poor experience interactively.

**Comment by jthandy** [comment]
another ramification of this that is rather irritating: if you disable a model, the tests for that model will not be disabled, they will run and they will not just fail, they will actually error out the entire batch of tests that they're concurrently run with.

**Comment by drewbanin** [comment]
added in https://github.com/analyst-collective/dbt/pull/279
