### ISSUE TITLE
Adding IAM parameters to redshift adapter

### ISSUE THREAD

**Issue by gfeldman** [fishtown-analytics/dbt#1995]
### Describe the feature
I would the arguments to get_cluster_credentials to be added to the dbt profile configuration. In particular DbGroups to allow the temporary user to be added to a group and AutoCreate to allow auto creation of users that do not exist. 

### Describe alternatives you've considered
Since these are IAM specific configurations the only other alternative is to not use the temporary credentials.

### Additional context
This is a feature specifically for redshift users.

### Who will this benefit?
This feature will be useful for dbt users who want to use temporary and dynamic credentials with redshift.

**Comment by drewbanin** [comment]
Thanks for making this issue @gfeldman! 

If you're interested in contributing a code change for this feature, the relevant code should be around here:
https://github.com/fishtown-analytics/dbt/blob/40839c79fcf1854942f8db44d1a2648bffe0a2ab/plugins/redshift/dbt/adapters/redshift/connections.py#L39-L57

and here https://github.com/fishtown-analytics/dbt/blob/40839c79fcf1854942f8db44d1a2648bffe0a2ab/plugins/redshift/dbt/adapters/redshift/connections.py#L87-L128

It sounds like we'll just need to state these two configs (`DbGroups` and `AutoCreate`) in the set of whitelisted RedshiftCredentials, then pass them through to [boto_client.get_cluster_credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift.html#Redshift.Client.get_cluster_credentials).
