### ISSUE TITLE
syntax highlighting for popular editors?

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#201]
like https://github.com/dmarcotte/idea-handlebars

We should support some popular editors:
- [ ] datagrip
- [ ] atom
- [ ] sublime

**Comment by jthandy** [comment]
I have a pr out for atom syntax highlighting here:

https://github.com/danielchatfield/atom-jinja2/pull/33

**Comment by drewbanin** [comment]
Discussion here: https://discourse.getdbt.com/t/syntax-highlighting-sql-linting/15

**Comment by drewbanin** [comment]
closing this - these should exist, but almost certainly not inside of dbt-core.
