### ISSUE TITLE
Fix docstring for dbt docs generate

### ISSUE THREAD

**Issue by gnilrets** [fishtown-analytics/dbt#2038]
### Describe the bug
The docstring for dbt docs seems to indicate that if you want to use a different target, you would put the `--target` parameter before generate:
```
# dbt docs -h
usage: dbt docs [-h] [--project-dir PROJECT_DIR] [--profiles-dir PROFILES_DIR] [--profile PROFILE] [--target TARGET] [--vars VARS] [--bypass-cache] {generate,serve} ...
```
However, when I try that, it doesn't honor the parameter
```
# dbt docs --target prod generate
Running with dbt=0.14.3
Found 125 models, 207 tests, 15 snapshots, 0 analyses, 254 macros, 2 operations, 3 seed files, 101 sources
19:31:38 | Concurrency: 4 threads (target='dev')
```

However, if I put the flag at the end like this, it works fine:
```
# dbt docs generate --target prod
```

### Steps To Reproduce
See above

### Expected behavior
The docs should be in alignment with the actual commands.

### Screenshots and log output
See above

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.3
```

**The operating system you're using:** Debian GNU/Linux 10 (buster)

**The output of `python --version`:** 3.6.9

**Comment by drewbanin** [comment]
Thanks for the report @gnilrets! I think this should be a quick fix - I just queued this up for our 0.16.0 release. Let me know if it's something you would be interested in contributing a fix for!
