### ISSUE TITLE
Authenticate with postgres using kerberos?

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/dbt#2048]
### Describe the feature

I'm using a Postgres DB with Kerberos authentication. 
Is there any way of using DBT with Kerberos authentication?

**Comment by max-sixty** [comment]
The error is actually unrelated to kerberos; it was raising because I didn't have permission to create schemas. I managed to find that in the log file.

To the extent dbt could display the query that caused the error (rather than just `ERROR:  permission denied for database resdb`), that would really help in debugging.

Closing for now. Cheers.

**Comment by drewbanin** [comment]
Thanks for the update on this one @max-sixty - glad you got it working!
