### ISSUE TITLE
Support for metadata-based object / ETL generation: ETL automation

### ISSUE THREAD

**Issue by bashyroger** [fishtown-analytics/dbt#2091]
### Describe the feature
We store our MySQL source data in Snowflake in a **Key-Variant** 'persistent staging area'. We want DBT to use MYSQL's **schema information metadata** to make it generate a series of _schema-on-read VIEWS_ . This code should be in ONE **meta-model.**
In addition, we would also like this code to generate accompanying **data quality tests** (Unique key, not null) YML files. This is similar to https://github.com/fishtown-analytics/dbt/issues/1082

### Describe alternatives you've considered

Other options are definitely possible. The problem of these is that **these solutions will then be outside of DBT's versioning /CI-CD control**. These options would be:

- Putting this code in Python / Airflow.
- Creating a snowflake stored procedure that does this.

### Additional context
This is a re-post of a similar request: https://github.com/fishtown-analytics/dbt/issues/1418
Even though this might be out of scope for DBT now, **I still think it should support this pattern in the (near) future**: IMO ETL automation capabilities, generating a series of objects based on metadata is a crucial feature to have for any modern data engineering tool! After all, one of the core design patterns of DBT is **DRY** (Don't Repeat Yourself), right? This is a big **DRY** use case!

### Who will this benefit?
Anyone that wants to create **a series of objects** (views, tables, materialisations) based on a set of metadata

**Comment by drewbanin** [comment]
@bashyroger if all of these `create or replace table as (...)` and `create or replace view as (...)` queries can be generated from a single `select` statement in the model .sql file, then you can use a [custom materialization](https://docs.getdbt.com/docs/creating-new-materializations) for this purpose.

Overall, I don't love this approach. You want your logic to live in version control, not in whatever the state of the database is at any given time. If things go wrong, it's going to be totally impossible to understand what the state of the db was at the time that the SQL was generated.

A place where I _do_ think this is a good idea is in #1637 -- this breaks the "one model per relation" paradigm that is the default in dbt, but each created database relation would be a constituent part of the entire model.

I'm adding a #wontfix label here to clarify that this isn't something we intend to build first-class support for in the near future, but I do think it's totally possible to implement in dbt today, and I encourage you to try it out and post back here with your findings!

Also happy to continue the discussion - no need to close this issue out quite yet IMO.

**Comment by drewbanin** [comment]
closing as stale
