### ISSUE TITLE
[BUG] Command line variable ignored when supplied to command in server

### ISSUE THREAD

**Issue by alexbethea22** [fishtown-analytics/dbt#2092]
### Describe the bug
When I run this command against the `cli` method in the server:
```
dbt run --vars '{period_start_date: '2019-04-01', period: 'day'}' -m buildings
```
the command line variables are ignored. Instead I would expect the command line variables to be present in the context. 

Note: partial parsing is enabled in this environment

### Steps To Reproduce
tbd

**The output of `dbt --version`:**
```
O.15.2
```

**Comment by iahelr** [comment]
Hi, this also happens when we run a job and pass to it variables options as part of the dbt run command.
