### ISSUE TITLE
Widen boto3/botocore requirements

### ISSUE THREAD

**Issue by gnilrets** [fishtown-analytics/dbt#2102]
### Describe the bug
Been fighting dependency hell for the last hour trying to upgrade dbt-redshift.  I install dbt-redshift, boto3, and awscli in the same project.  Turns out I had to pin boto3<1.10.0 and  awscli==1.16.267 .

boto3/botocore requirements are currently pinned to a specific [range](https://github.com/fishtown-analytics/dbt/commit/36e12528240c7dbe91e921929665acf1fa49fa22#diff-c553dc00af52e44f247b86ac6b0ff29bR28).  My understanding from a [slack conversation](https://getdbt.slack.com/archives/C50NEBJGG/p1580864794040000) is that the Redshift range needs to be in alignment with the range required for snowflake.  It looks like snowflake [currently has a bit wider range](https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L180), so I think it would be safe for dbt to match.

### Steps To Reproduce
^

### Expected behavior
^

### Screenshots and log output
NA

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.2
   latest version: 0.15.2
```

**The operating system you're using:** Debian Linux

**The output of `python --version`:** 3.6.10

**Comment by drewbanin** [comment]
Adding @beckjake to advise!

**Comment by GuillaumeLegoy** [comment]
Hello, first of all thanks @gnilrets I fought this issue for a while while trying to use dbt and boto3 in the same package. Pinning boto3 like you recommend fixed it.

Second, I'm not sure if it helps, but just in case: I'm using Pipenv for libraries management, following is the pipenv dependencies conflict message and the output of pipenv graph before and after pinning boto3. 

**Conflict message**
`ERROR: ERROR: Could not find a version that matches botocore<1.13.0,<1.15.0,>=1.14.14,>=1.9.23
Tried: 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2 ...`

**Before**
`- dbt-redshift [required: ==0.15.2, installed: 0.15.2]
  - boto3 [required: >=1.6.23,<1.10.0, installed: 1.9.253]
    - >=1.14.14 [required: >=1.12.253,<1.13.0, installed: 1.12.253]
      - docutils [required: >=0.10,<0.16, installed: 0.15.2]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
        - six [required: >=1.5, installed: 1.14.0]
      - urllib3 [required: >=1.20,<1.26, installed: 1.24.3]`

**After fix**
`- dbt-redshift [required: ==0.15.2, installed: 0.15.2]
    - boto3 [required: >=1.6.23,<1.10.0, installed: 1.9.253]
      - botocore [required: >=1.12.253,<1.13.0, installed: 1.12.253]
        - docutils [required: >=0.10,<0.16, installed: 0.15.2]
        - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
        - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
          - six [required: >=1.5, installed: 1.14.0]
        - urllib3 [required: >=1.20,<1.26, installed: 1.24.3]`

**Comment by beckjake** [comment]
Yeah, I landed on this yesterday while doing some local work around versions and `pip install` a lot, so I feel the pain. @drewbanin I think we'll also need to rev the snowflake-connector-python adapter to a newer version while we're at it, in order to get the newer range. I assume it actually installs now, it's been a while.

**Comment by drewbanin** [comment]
sounds good @beckjake - adding this one to Barbara Gittings :)
