### ISSUE TITLE
support meta-data in the models

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#2111]
### Describe the feature
Add a metadata property to models for the columns or tables. That property just allows any data inside it and can then be ignored by DBT.

### Describe alternatives you've considered
Add a file next to the model to map meta-data to column/table (very messy and hard to read)

### Additional context
I'm using a tool to auto-generate models. It's not the best approach, but I typically get involved after a DB was in production for a couple of years. Part of that is making sure that PII information 
is properly tracked. When we do analysis, I want to make sure that aggregate views about
customers are available to some users. However, to know that they only see aggregate of PII information, I have to know what is PII or not. The current approach of tagging only works at the table level.

Additionaly, I'd like to keep track of other metadata about the data without breaking DBT.

### Who will this benefit?
Me.... or other people that want extra information about their data. Ideally, that extra information could be shown in the documentation generated.

**Comment by beckjake** [comment]
@philippe-lavoie have you seen #2015 ? Does that suit your needs? It'll be in the next minor version of dbt, v0.16.0.

**Comment by philippe-lavoie** [comment]
It does, awesome.
