### ISSUE TITLE
compile and run with a single command

### ISSUE THREAD

**Issue by zboldyga** [fishtown-analytics/dbt#2113]
### Describe the feature
It would be great to be able to run dbt in a single step. e.g.
```
dbt run --compile
```
Sometimes I forget to compile before running. And running takes a long time in certain circumstances, and e.g. can't be cancelled on BigQuery. So I imagine this would save a lot of time for some users.

### Describe alternatives you've considered
I could write my own system shortcut for this. Figured it may be a universal problem/want, may be best to add it within DBT itself.

### Additional context
N/A

### Who will this benefit?
General users. Especially beginners to DBT, or junior team members.

**Comment by beckjake** [comment]
Hi @zboldyga! You don't need to `compile` if you want to `run` - `dbt run` will do what `dbt compile` would do for each model (and then runs it as well).

**Comment by zboldyga** [comment]
@beckjake ah awesome, thanks for the quick follow-up. I should have looked into the code further. But hopefully future searches for this problem turn up this thread!

I'll go ahead and close. Thnx again.
