### ISSUE TITLE
Warning should be surfaced if any part of the `--models` specification doesn't exist

### ISSUE THREAD

**Issue by kingfink** [fishtown-analytics/dbt#2115]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Assume `model_a` exists and `model_b` does not exist in a given dbt project.

If you run `dbt run --models model_b` you get an error: `WARNING: Nothing to do...`.

If you run `dbt run --models model_a model_b` you don't get any error since one of the models exists.

It seems like it would make sense to surface an error like `WARNING: Model specification matching model_b not found` or something like that

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

See above

### Expected behavior

See above

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

See above

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Running with dbt=0.15.0
```

**The operating system you're using:**

```
OSX
```

**The output of `python --version`:**

```
Python 3.7.4
```

### Additional context

Definitely not an urgent problem, but figure it's a good one to mention

**Comment by drewbanin** [comment]
Thanks for the report @kingfink - this is a good idea! We should make this a highly visible warning that can be raised to an error using the `--warn-error` flag

**Comment by jeremyyeo** [comment]
@drewbanin seems like this is somewhat related to https://github.com/fishtown-analytics/dbt/issues/1765?

**Comment by drewbanin** [comment]
ha! Thanks @jeremyyeo - I was looking for that one! Just closed #1765 in favor of this issue. Appreciate you digging for it :)
