### ISSUE TITLE
dbt debug cannot handle an empty dbt_project.yml

### ISSUE THREAD

**Issue by nchammas** [fishtown-analytics/dbt#2116]
### Describe the bug

If you call `dbt debug` on a new project that has an empty `dbt_project.yml` file, you get this error:

```
Encountered an error:
'NoneType' object does not support item assignment
```

### Steps To Reproduce

Create a new project directory and place an empty `dbt_project.yml` in it. Run `dbt debug`.

### Expected behavior

dbt should gracefully complain that I have an empty or malformed `dbt_project.yml`.

### Screenshots and log output

```
$ dbt debug
Running with dbt=0.15.2
dbt version: 0.15.2
python version: 3.7.6
python path: .../venv/bin/python
os info: Darwin-18.7.0-x86_64-i386-64bit
Using profiles.yml file at .../.dbt/profiles.yml

Encountered an error:
'NoneType' object does not support item assignment
```

### System information

**Which database are you using dbt with?**
- [x] postgres

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.15.2
   latest version: 0.15.2

Up to date!
```

**The operating system you're using:** macOS

**The output of `python --version`:** Python 3.7.6

**Comment by drewbanin** [comment]
Thanks for the report @nchammas! Adding this to the current milestone. Would you be interested in contributing a fix for the issue? Happy to point you in the right direction if so!
