### ISSUE TITLE
Add SQLite as a supported database

### ISSUE THREAD

**Issue by nchammas** [fishtown-analytics/dbt#2117]
### Describe the feature

It would be handy if dbt supported SQLite as a [backend](https://docs.getdbt.com/docs/supported-databases).

### Describe alternatives you've considered

I am currently using Postgres.

### Who will this benefit?

SQLite would be very useful for people who are tinkering with dbt or putting together a prototype to evaluate the system, and don't want to have to go through the trouble of setting up a database server.

A SQLite database backend would potentially also be useful in simplifying continuous integration tests for your dbt project. Instead of needing to spin up or maintain any database services, you can just use the filesystem to run your dbt models and test that everything works. This is especially handy when running your tests on an external service like Travis CI.

**Comment by drewbanin** [comment]
Thanks for the feature request @nchammas! We tend to use Postgres for dbt's internal integration tests -- the syntax is similar enough to Redshift (and for the most part, BigQuery and Snowflake), plus it's easy to spin up in an isolated CI environment.

I'd be super happy if a community-supported SQLite plugin was brought into existence! We don't have any immediate plans to prioritize that on our side though. Let me know if this is something you might be interested in working on - I'd be happy to point you to the appropriate docs and help out with the initial implementation :)

**Comment by Cheva998** [comment]
I think this a interesting feature, @drewbanin could you please point me in the right direction?

**Comment by drewbanin** [comment]
hey @Cheva998 - check out the docs on building a new adapter here: https://docs.getdbt.com/docs/building-a-new-adapter

This is _slightly_ out of date, and I'd love to get it in sync with our latest release, 0.16.0, asap! For now though, it should serve as a really good starting point

**Comment by drewbanin** [comment]
closing this one - out of scope for core

A SQLite plugin would definitely be interesting for demos / testing! If anyone ends up working on one, please let me know -- I'd be happy to get it listed up on docs.getdbt.com :)

**Comment by codeforkjeff** [comment]
FYI, I've created an adapter for SQLite. It's in the early stages of development but all the basic functionality should be working. https://github.com/codeforkjeff/dbt-sqlite
