### ISSUE TITLE
add user-agent "dbt-{version}" to the BigQuery connection

### ISSUE THREAD

**Issue by fhoffa** [fishtown-analytics/dbt#2121]
### Describe the feature

Add an user-agent "dbt-{version}" to the BigQuery connection.

### Who will this benefit?

Google can keep track of the most popular libraries used with BigQuery - and then use this information to prioritize features and recognize the most useful tools. This is done by populating the user-agent string with the corresponding "application name" and version information.

### Reference

This is a similar issue and code:

- https://github.com/googleapis/google-cloud-python/issues/8696

The API definition for ClientInfo.user_agent:

- https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html

> The client info used to send a user-agent string along with API requests. If None, then default info will be used. Generally, you only need to set this if you’re developing your own library or partner tool.

Where the change would be applied:

- At "google.cloud.bigquery.Client()" - https://github.com/fishtown-analytics/dbt/blob/dev/barbara-gittings/plugins/bigquery/dbt/adapters/bigquery/connections.py#L141

**Comment by drewbanin** [comment]
Thanks @fhoffa - didn't know about that setting. It's a great idea. I just prioritized this one for our next release (v0.16.0 - Barbara Gittings) :)

**Comment by tswast** [comment]
Example of the feature in use to track `%%bigquery` IPython magics usage: https://github.com/googleapis/python-bigquery/blob/3d77a75c86a599f7d36e68fea7979d748819e875/google/cloud/bigquery/magics.py#L491
