### ISSUE TITLE
snowflake oauth: take refresh_token instead of access_token

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#2126]
Instead of just using the `access_token` to make requests (it only lasts 10 minutes), use the `refresh_token` to generate an access token. A reasonable naive solution would be to do this right before creating a handle / issuing a query. Once a connection is open, it should be available for the normal amount of time (4 hours?)

If snowflake returns an error specifically saying that the refresh token is expired, it would be nice if dbt could return that error so that cloud could consume it

**Comment by beckjake** [comment]
Fixed in #2141, merged into the 0.15.3 branch.
