### ISSUE TITLE
Source doesn't allow usage of dataset and project aliases

### ISSUE THREAD

**Issue by preston-hf** [fishtown-analytics/dbt#2133]
### Describe the bug
Most everywhere else in DBT, database is synonymous to project, and dataset is synonymous to schema. In sources, this is not the case, and they are unexpected parameters. This is very confusing to end users looking at code with project and dataset everywhere else, they'll not even be familiar with what database and schema are, as these names don't appear anywhere in bigquery.

### Steps To Reproduce
Attempt to specify the dataset or project of a source in `schema.yml`

### Expected behavior
Schema and dataset should be interchangeable, as should database and project

### Screenshots and log output
`dditional properties are not allowed ('project', 'dataset' were unexpected)`

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.15.2
```

**Comment by drewbanin** [comment]
Thanks for the report @preston-hf! This does appear to be an oversight on our part.

Would you be interested in contributing a fix? If so, happy to help point you in the right direction!

**Comment by drewbanin** [comment]
+let's make sure to improve documentation for these aliases when we make this change
