### ISSUE TITLE
Append query comments instead of prepending

### ISSUE THREAD

**Issue by tayloramurphy** [fishtown-analytics/dbt#2138]
### Describe the feature
The examples in the documentation work just fine in that the query comment is generated and prepended to the query. Snowflake, however, seems to drop comments that come before the actual SQL. 

A simple test of 

```sql
select 1 as test

/* {"app": "dbt", "dbt_version": "0.15.1", "profile_name": "gitlab-snowflake", "target_name": "dev", "node_id": "internal"} */
```

versus 

```sql
/* {"app": "dbt", "dbt_version": "0.15.1", "profile_name": "gitlab-snowflake", "target_name": "dev", "node_id": "internal"} */

select 1 as test
```

shows up in query history as

![Screen Shot 2020-02-14 at 2 56 05 PM](https://user-images.githubusercontent.com/5394188/74566908-2e32cc80-4f3a-11ea-85ff-a7e85e80f1f3.png)

### Describe alternatives you've considered
Is there are way to adjust the macro to append the comment instead of prepending it?

### Additional context
Snowflake

### Who will this benefit?
People using query comments on snowflake 😅

**Comment by drewbanin** [comment]
@tayloramurphy this is really surprising to me, as it's not the behavior that I've observed! 

Do you specifically want the query comment to live at the bottom of the query, or do you just find that this scheme compels Snowflake to actually render the query comments? I'll take a deeper look to see what might be going wrong here...

**Comment by tayloramurphy** [comment]
I wasn't sure to file this as a bug or feature, but I chose feature, hence the proposal. I don't particularly care where the comment is rendered, but this seems like a "fix" to the problem I'm seeing.

If it's a problem with something on the Snowflake end, though, I'd be happy to address that too.

**Comment by lmag-snowflake** [comment]
![image](https://user-images.githubusercontent.com/49885352/74761730-65062c80-5231-11ea-99fa-a341426f6f80.png)
I seem to retain the comments preceding the query. I would still like to see this feature implemented because the query preview would be more informative to me.

**Comment by drewbanin** [comment]
Roger. Let's go ahead and support a dbt_project.yml config that toggles this query comment between the header and footer of the query.

This config should be called `query-comment-location` which should accept the values `header` or `footer`.

**Comment by ilkinulas** [comment]
Just for your information:

As snowflake support team says; since snowflake version 1.9 leading comments are disabled. Because sensitive data could potentially be exposed via leading comments.

With the permission of account owner this restriction can be disabled.

**Comment by tayloramurphy** [comment]
Indeed you're right @ilkinulas ! I found https://docs.snowflake.net/manuals/release-notes/2017-04.html#queries-leading-comments-removed-during-execution after some searching. 

I would still prefer this feature I think though b/c I'd echo  lmag-snowflake's comment that it'll make the query history more useful.

**Comment by ilkinulas** [comment]
> I would still prefer this feature I think though b/c I'd echo lmag-snowflake's comment that it'll make the query history more useful.

I'd prefer this feature too 👍

**Comment by drewbanin** [comment]
wow @ikkisoft and @tayloramurphy thanks for the info! That is.... a design decision... if i have ever seen one.

What kinds of syntax are y'all thinking about for this config? I think a header is the right default, but I'd be happy to use a config to make it a footer instead :)

Maybe:

```
# default comment
query-comment: "executed by dbt"
```

```
# default comment
query-comment:
  comment: "executed by dbt"
  location: bottom
```

Or something like that?

**Comment by tayloramurphy** [comment]
@drewbanin ooo bikeshedding, I was born for this. 

`location` implies multiple options of accepted configs in my mind. I'd advocate for 

```
query-comment:
  comment: "executed by dbt"
  append: true
```

Since there's really only two options. Unless you wanted to have fun and make `location: random` and option 😉

**Comment by ilkinulas** [comment]
@drewbanin I have created a PR for this feature, fyi.

 I signed the CLA  by submitting the form but the`verification/cla-signed` check fails.  Am i missing something?

**Comment by beckjake** [comment]
@ilkinulas There's a manual process on our end (someday we'll automate this!) - let me get you approved.
