### ISSUE TITLE
Add a filter to schema.yml to generate a where Expressions

### ISSUE THREAD

**Issue by dalu610** [fishtown-analytics/dbt#2144]
### Describe the feature
dbt test can test not_null and unique.But i want to test one day's data.

The data in this table is very large, and the query will be very slow

**Comment by drewbanin** [comment]
Hey @dalu610 - thanks for making this issue.

The `not_null` and `unique` tests are working as intended. Checking a single day of data is insufficient to determine if an entire column of data is not null, or contains only unique values.

I do think your idea is a good one, but it's not something we're going to support in dbt core at the present time. Please find instructions on creating your own custom schema tests here: https://docs.getdbt.com/docs/custom-schema-tests

**Comment by dalu610** [comment]
I am very glad to hear from you.
Now more and more data warehouses are full data snapshots.
If there is no choice of slicing period, the data volume will be huge.
Of course, the uniqueness check must be accompanied by the date field, but it will cause a lot of load on the server, and the performance will be particularly poor.
Of course, customization can be implemented, but the configuration of documents is more attractive and easy to promote.
You can add where 1 = 1 to all select statements and then consider whether the filter is configured.
Finally, thank you very much again!











At 2020-02-18 22:28:23, "Drew Banin" <notifications@github.com> wrote:

Hey @dalu610 - thanks for making this issue.

The not_null and unique tests are working as intended. Checking a single day of data is insufficient to determine if an entire column of data is not null, or contains only unique values.

I do think your idea is a good one, but it's not something we're going to support in dbt core at the present time. Please find instructions on creating your own custom schema tests here: https://docs.getdbt.com/docs/custom-schema-tests
