### ISSUE TITLE
Set upper bound on jinja2 dependency

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2147]
### Describe the feature
At the time of this writing, jinja2 v3.0.0a1 is now available [on PyPi](https://pypi.org/project/Jinja2/#history). This version is not compatible with dbt.

We should either:
 - set the upper bound on the jinja2 dependency to be `<3.0.0`, or
 - make dbt compatible with version 3.0.0 when it is released (likely as a part of a future issue)

The proximate error here looks like:
```
No module named 'jinja2._compat'
```

as far as I can tell.

**Comment by beckjake** [comment]
I am pretty sure that since we dropped python 2.x support, we don't need that call anymore.
