### ISSUE TITLE
Use `show schemas` instead of selecting from information_schema.schemata on Snowflake

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2166]
### Describe the feature
Background:

![Screen Shot 2020-02-27 at 1 01 30 PM](https://user-images.githubusercontent.com/1541139/75472336-55899080-5961-11ea-8c24-4ed0a31b4bed.png)
![Screen Shot 2020-02-27 at 1 01 42 PM](https://user-images.githubusercontent.com/1541139/75472340-56222700-5961-11ea-8220-8140c3d68f7a.png)

Let's replace the call to `information_schema.schemata` on Snowflake with a call to `show schemas in <database>`.

Advantages:
 - `show schemas` will not queue, whereas the `select` statement can queue
 - `show schemas` does not require a running warehouse
 - `show schemas` appears to be strictly faster than the information_schema alternative

We should consider applying this approach for other queries, as described in https://github.com/fishtown-analytics/dbt/issues/1877 (the key benefit being that these queries _do not queue_. Let's keep #1877 open and tackle these other queries separately. See also https://github.com/fishtown-analytics/dbt/pull/2157

Disadvantages:
 - `show schemas` requires the database name to be cased and quoted appropriately. I actually think this is the same behavior as selecting from `database.information_schema.<table>`, so that might not be an issue here?

**Comment by beckjake** [comment]
The big drawback of `show schemas` is that it has a 10,000 record limit, so users with 10k schemas in their database (and I assume those users do exist!) will have problems. We can either fail if there are 10k or fall back to querying information_schema.schemata. I'd really rather error out, but I understand the appeal of falling back.
