### ISSUE TITLE
Model intersection syntax

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#2167]
### Describe the feature
Currently, when you provide two args to the model selection syntax, dbt selects the union of the two parts of the graph:
e.g.
```
dbt run --models tag:hourly tag:marketing
```
would run all models that have either the `hourly` or `marketing` tag (or both)

I'd like a way to only run the intersection of these two parts of the graph:
```
dbt run --models [tag:hourly ∩ tag:marketing ]
```
That would only run models that have both the `hourly`AND `marketing` tag. And of course `∩` is a terrible symbol to use here.

### Describe alternatives you've considered
We've seen this come up a few times, normally when people want to run the models in a folder that have a certain tag. Our current advice is to add new tags.

**Comment by drewbanin** [comment]
Let's prioritize this for the Octavius Catto release. We should use a `,` to separate selectors, eg:

```
dbt run --models tag:abc,tag:def tag:ghi,jkl
```

This will select models that have:
 - tags abc AND def, OR
 - tags ghi AND jkl

**Comment by clrcrl** [comment]
do you mean:
```
dbt run --models tag:abc,tag:def tag:ghi,tag:jkl
```

**Comment by eamontaaffe** [comment]
If we are going to use the array syntax can I suggest we use the bash array syntax instead? This would make it easier to populate variables and use them later as tags:

```
TAGS=(tag:abc tag:def)
dbt run --models $TAGS[@] (tag:ghi tag:jkl)
```

**Comment by magnusfurugard** [comment]
Anyone who's in a rush solving this (myself included) can use a bit of shell and jq to solve this when invoking `dbt run`.
```
dbt run -m $(dbt ls --resource-type model --output json | jq '. | select(.tags | index("abc")) | select(.tags | index("def")) .name' -r | tr '\n' ' ')
```

**Comment by drewbanin** [comment]
@Raalsky I think you indicated that you were interested in picking this up -- is that still the case? If not, we're ready to prioritize this on our end :)

**Comment by Raalsky** [comment]
@drewbanin Sorry for being off. Yeah, I'm still interested. I'll post updates after the weekend, ok?
