### ISSUE TITLE
compiled "analysis" code writing to wrong target directory

### ISSUE THREAD

**Issue by ninashayne** [fishtown-analytics/dbt#2173]
### Describe the bug
I have a custom path other than "analysis" for some SQL that I want compiled by not run. I ran
- dbt clean
- dbt deps
- dbt compile
The SQL files that are in my custom analysis path were successfully compiled. However the path where the compiled code lives is: /target/compiled/customer_data_model/analysis. I'd expect it to be in /target/compiled/customer_data_model/custom-analysis-path

### Steps To Reproduce

- I set my analysis path in my dbt_project to "test_paths."
- I created a model in the directory "test_paths" called "test.sql" with "select 1 as test" as the SQL
- I ran dbt clean, dbt deps, dbt compile
- The test.sql model was compiled but the resulting compiled code lives in target/compiled/customer_data_model/**analysis**

### Expected behavior
I'd expect the compiled code to live in target/compiled/customer_data_model/**test_paths**

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [x ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.15.2
```

**The operating system you're using:**
10.15.3

**The output of `python --version`:**
3.7.4

**Comment by drewbanin** [comment]
Thanks for making this issue @ninashayne! I think this is a good suggestion, but I'm sort of on the fence about what the exact behavior should be. Do you think we should:
1. _never_ include resource-type subdirectories (`analysis/`, `tests/`, etc)?
2. _always_ include resource-type subdirectories?

I could either imagine throwing away the top-level folder name, or instead adding it to the path. 

That would mean that models would live in:
```
target/compiled/customer_data_model/models/...
```

And analyses would live in:
```
target/compiled/customer_data_model/analysis/...
```

I think that _always_ adding the top-level dir is probably a good idea, but I'm curious to hear what you think! Whatever we choose, we should just make sure to be consistent.

**Comment by ninashayne** [comment]
I like the idea of always adding it to the path since instinctively that's what i thought would happen. I just reread the initial issue and realize I left the expected subdirectory off in my initial summary (which might've triggered your question). I like the idea of the compiled code mimicking the resource subdirectory structure. 

To give a bit more color to why this even came up -- I want to use the compiled output of some analyses in a downstream process. Keeping them in their own directory helps with organization and standardization (my team can just add additional queries to a given directory without worrying about updating anything else). The downstream process can then just pick up the compiled SQL based on the name of the directory, without needing to know the names of specific analyses and also without picking up everything.

**Comment by ninashayne** [comment]
I realize what happened... the markdown compilation hid the part that said 'custom-analysis-path'

**Comment by drewbanin** [comment]
huh, ok @ninashayne - I read this issue totally differently this morning. I buy what you're saying here and i think we can make it happen :)

**Comment by ninashayne** [comment]
Thanks @drewbanin! Apologies for the confusion :)
