### ISSUE TITLE
[Barbara Gittings]: merge.sql BigQuery macro file shows up in dbt v016.0-b3 pre-release

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2177]
### Describe the bug
See a description of the bug here: https://discourse.getdbt.com/t/pre-release-v0-16-0-barbara-gittings/922/2?u=drew

I'm a little confused at how this is happening - it looks like the 0.16.0-b3 pre-release (on PyPi) includes a `macros/materializations/merge.sql` file which is _not_ present in the source code used to generate this release.

There are two things to check out here:
1. Do we need to do something special to ensure that a `merge.sql` file from a previous release (eg. 0.15.2) does not persist after a user upgrades to 0.16.0?
2. Does our build script for dbt need to be updated to wipe out the `dist/` dir (or similar) to ensure that assets from different releases aren't persisted across releases errantly?

For reference, [this file](https://github.com/fishtown-analytics/dbt/blob/v0.15.2/plugins/bigquery/dbt/include/bigquery/macros/materializations/merge.sql) is includes in `site-packages/dbt` using [this pypi release](https://pypi.org/project/dbt/0.16.0b3/), but no such `merge.sql` file exists in `dev/barbara-gittings`. The code from https://github.com/fishtown-analytics/dbt/pull/2140 _is_ present in the release (which also deletes the `merge.sql` file), so this isn't a question of the `0.16.0-b3` pre-release not mapping to the latest commit on `dev/barbara-gittings`.

### Steps To Reproduce
```
python3 -m venv env
source env/bin/activate
pip install dbt==0.16.0-b3

# This file should not exist!
cat env/lib/python3.7/site-packages/dbt/include/bigquery/macros/materializations/merge.sql
```

**Comment by beckjake** [comment]
This looks like a release issue of some sort - the file exists in a pristine install of `dbt==0.16.0b3` as well, but it's not in the repository. I'll investigate the package-building aspect more thoroughly in the next couple days, but there's code in the package build script that explicitly calls `shutil.rmtree` on the `dist` folder before we start building:
 - when building wheels: https://github.com/fishtown-analytics/dbt/blob/5e1986d54351ddffb9f095fc2e9fa13e50ca0430/scripts/build-wheels.sh#L17
 - In the complete package build/upload script: https://github.com/fishtown-analytics/dbt/blob/5e1986d54351ddffb9f095fc2e9fa13e50ca0430/scripts/build-dbt.py#L252-L253

So I'm a little perplexed about the whole thing 😕

**Comment by beckjake** [comment]
Even worse - it appears in the wheel version, but not the `.tar.gz` version.

**Comment by beckjake** [comment]
I believe I've found a fix for this (though it's super hard to tell, given the nature of the issue) and pushed a corresponding change to my package build script PR in #2119 - when we `rm -rf` the `dist/` folders, also remove the `build/` folders.

**Comment by drewbanin** [comment]
I confirmed that this file is not present in the wheel built for `0.16.0-rc2`. Closing this issue - nice work @beckjake !
