### ISSUE TITLE
Support for source data in another database - Postgres

### ISSUE THREAD

**Issue by jmace006** [fishtown-analytics/dbt#2182]
### Describe the feature

Our staging and reporting tables can be rebuilt easily thanks to dbt - but the source database tables need a lot more protection and thought, especially for db rollbacks, backups and upgrades.

We would like our source data in one Postgres database, and the dbt output to be in another db entirely. 

My understanding is its already supported on the more 'warehousey' databases, but not Postgres. I'm unsure how this works with snapshots - I would imagine these should be able to be loaded into the source db too.

**Comment by beckjake** [comment]
I'll let drew chime in on this if he has any thoughts on alternative paths, but dbt really _can't_ support this in a technical limitations of postgres sense. In postgres (and redshift), queries that cross databases are simply not permitted:

```
postgres=# select * from dbt.dbt_jbeck.foo;
ERROR:  cross-database references are not implemented: "dbt.dbt_jbeck.foo"
LINE 1: select * from dbt.dbt_jbeck.foo;
```

Snowflake and BigQuery both allow queries to cross databases, so dbt allows it on those warehouses.

**Comment by jmace006** [comment]
Thanks @beckjake that entirely makes sense then, love to hear if Drew has any alt ideas of course.

**Comment by drewbanin** [comment]
Hey @jmace006  - I have some bad news! Postgres doesn't allow _any_ queries to cross logical database boundaries. It might be a good idea to consider replicating your source postgres data into an entirely different database, be it something like Postgres also, or Snowflake/BigQuery/Redshift. This is the architecture most dbt users are deploying for analytics, and it's definitely one that I'd recommend!

I'm closing this out as a wontfix because I don't think Postgres gives dbt any way to do this at all! Very happy to discuss this further though - let me know what you think :)

**Comment by dyllan-to-yu** [comment]
@drewbanin Is there any reason why one couldn't use [`postgres_fdw`](https://www.postgresql.org/docs/12/postgres-fdw.html) to link two databases and have a query cross these logical database boundaries?

**Comment by jtcohen6** [comment]
@dyllan-to-yu Sort of! With a foreign data wrapper, it's possible to [`import foreign schema`](https://www.postgresql.org/docs/9.5/sql-importforeignschema.html) and create a schema in the local database that's a pointer to the other one. Then, those "source pointers" are addressable as `schema.identifier`, just like any other relational object in the local database.

I've done this before, using dbt, by wrapping the data wrapper DDL in a macro or two, and then treating the pointers as just one of my `sources`. I will say that, in my experience, data "loading" can be quite slow. It's preferable to use a different architecture if possible.

**Comment by jmace006** [comment]
@dyllan-to-yu we use postgres foreign data wrappers now to support this. It works really well, and we haven't found it slow. Though we have pretty low data volumes (also why we are still on Postgres).

**Comment by brylie** [comment]
Also, what about creating a dbt macro for Postgres `dblink`?

https://www.postgresql.org/docs/10/contrib-dblink-function.html

I believe this issue should be re-opened as there is likely a solution using either FDW or dblink.

**Comment by rupurt** [comment]
+:100: to @brylie comment. I feel like this should be modeled directly in `dbt` using FDW. There's a bunch of server configuration and schema mapping that would be awesome to abstract away.
