### ISSUE TITLE
Add a command line flag to enable or disable color output

### ISSUE THREAD

**Issue by Matt343** [fishtown-analytics/dbt#2192]
### Describe the feature
The use_colors config option enables or disables console escape codes in the DBT command output, but you cannot currently override the value from `profiles.yml` when running a command. Adding `--use-colors` and `--no-use-colors` (similar to how partial parsing is handled) would allow us to be explicit with what output format we need in each environment without needing completely separate `profiles.yml` files.

### Describe alternatives you've considered
We handle other environment specific values in `profiles.yml` using `env_var` Jinja blocks, but the boolean options in the `config` section do not seem to support that mechanism.

### Who will this benefit?
DBT command line users who want to configure color output differently for different commands/contexts, or who want color output usually but occasionally pipe the output of DBT into other tools.

**Comment by drewbanin** [comment]
Thanks for the report @Matt343! I think we'll have a good answer on boolean env vars for 0.17.0, but I'm not opposed to `--use-colors` and `--no-use-colors` flags. Feel free to send through a PR for those flags if you're interested in able!  :D

**Comment by invinceyble** [comment]
I'd be keen to work on this if @Matt343 isn't. I haven't looked too closely at everything, but I suspect it might look similar to this commit, is that right? https://github.com/fishtown-analytics/dbt/commit/c38c8d539bf8f48a8a7306ffdf83441236c89cb9

**Comment by drewbanin** [comment]
hey @invinceyble - I think c38c8d5 is a great source of inspiration for this flag :)

**Comment by rsenseman** [comment]
@invinceyble Are you working on this? If not, I can pick this up this week

**Comment by invinceyble** [comment]
> @invinceyble Are you working on this? If not, I can pick this up this week

Totally slipped off my radar, all yours! :)
