### ISSUE TITLE
The ability to choose a function of a field for a clustering key in the model config

### ISSUE THREAD

**Issue by djayatillake** [fishtown-analytics/dbt#2193]
### Describe the feature
The ability to choose a function of a field for a clustering key in the model config. eg clustering_key = 'left(uuid,3)'. Snowflake allows you to do this which it recommends as strategies for clustering on high cardinality fields.

### Describe alternatives you've considered
Currently, you can do this with a post hook alter table clustering key command.

### Additional context
Snowflake specific I believe.

### Who will this benefit?
This will be useful where you want to cluster by a field that has high cardinality and you want to use part of it or truncate it in some way to reduce that cardinality when clustering. eg casting timestamp to date, or first 2 or 3 characters of a uuid. This reduces automatic clustering costs on Snowflake.

**Comment by drewbanin** [comment]
Hey @djayatillake - thanks for opening this issue!

My understanding of the current clustering config behavior in dbt is that this should.... just work! Are you seeing a particular error when you try something like this?

```
{{ config(materialized='table', cluster_by=["left(uuid, 3)"]) }}

select 'abc123' as uuid
```

I'm seeing this run successfully with log output like:

```
-- build the model
create or replace transient table "ANALYTICS".dbt_dbanin.cluster  as (
  select * from (
            select 'abc123' as uuid
  ) order by (left(uuid, 3))
);
2020-03-18 18:31:54.797051 (Thread-1): SQL status: SUCCESS 1 in 1.17 seconds

-- post-hook
alter table "ANALYTICS".dbt_dbanin.cluster cluster by (left(uuid, 3));

```

Note that dbt automatically orders by the clustering key to make the `alter table` a no-op in this case :)

**Comment by djayatillake** [comment]
Hi Drew, 

Adding the square brackets around the term has fixed this for me, I wasn't doing that previously as if you just use a field without a function around it then it doesn't need the square brackets.

Thanks

**Comment by drewbanin** [comment]
Please do! Thanks for following up :)

**Comment by TrololoLi** [comment]
@djayatillake  I used quotes in wrong place for clustering with function cluster_by=[to_date('zone_created')] instead of cluster_by=['to_date(zone_created)'] and it was very difficult to debug, because I was getting `TypeError: can not serialize 'Undefined' object` and wasn't sure where to look. So I agree, it definitely worth to be added to the docs
