### ISSUE TITLE
Long table names can be truncated on Postgres (at least) silently

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2197]
### Describe the bug
Long table names appear to be truncated by Postgres, but this behavior could also be present on other databases. This was just reproduced with a temp table suffix in a Snapshot query on Postgres, but I imagine this could just happen with exceptionally long table names:

![Screen Shot 2020-03-11 at 6 37 30 PM](https://user-images.githubusercontent.com/1541139/76471010-ed5a9600-63c7-11ea-91e2-e2788b3b3d7e.png)

The truncation will cause _lots_ of problems across dbt, but the proximate issue here is that a subsequent information schema query will return zero rows (it's looking for the wrong identifier) which bricks a snapshot run. The quick user-space fix is to shrink the "base" name of the table, but we should also take action here to:
1. Reduce the length of the table suffix appended by dbt
2. Show a warning (or probably an error!) if a table is created with a name long enough for PG to truncate

More info on this PG constraint [here](https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes).

**Example informations schema query**
```
      select
          column_name,
          data_type,
          character_maximum_length,
          numeric_precision,
          numeric_scale

      from information_schema.columns
      where table_name = 'github_issues_linked_to_open_pull_requests__dbt_tmp20200311221237629328'
      order by ordinal_position

> Returns 0 rows
````

### System information
**Which database are you using dbt with?**
- [x] postgres
- [?] redshift
- [?] bigquery
- [?] snowflake

**The output of `dbt --version`:**
```
Reproduced on 0.14.3
```

**Comment by jtcohen6** [comment]
Add a runtime error to `create table as` that checks for relation identifier length
