### ISSUE TITLE
[Barbara Gittings] Docs generation fails if a database/schema name is numeric-looking

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2206]
### Describe the bug
Tagging this one with the BigQuery label because that's where I've seen it, but it could conceivably happen on any plugin.

If a database or schema name is numeric, then Agate's type inference will make the `database_name` or `schema_name` column (unique to a given agate table) numeric during catalog generation. This causes some calls to `database_name.lower()` or `schema_name.lower()` to fail with an error:
```
encountered an error while generating catalog: 'decimal.Decimal' object has no attribute 'lower'
```

I think I narrowed this down to `_relations_filter_schemas` in the base `impl.py`, but it's possible that there are other places where we assume the database name is going to be a string.

Beyond this first issue, Agate will also be mad about unioning together different agate tables that were fetched in parallel if one of those columns is string-y and the other is number-y in nature.

dbt should ensure that all of the known-string columns are returned as strings (and not numbers, if they look numeric) when fetching information from the system catalog.

### Steps To Reproduce
Use the profile:
```
    dev:
      type: bigquery
      method: oauth
      project: '{project name}'
      dataset: "1991"
      threads: 1
```

Then run:
```
dbt run
dbt docs generate
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.16.0-rc2
```

**Comment by beckjake** [comment]
Fixed in #2208
