### ISSUE TITLE
[Barbara Gittings] Raise minimum google-cloud-bigquery version to 1.22.0

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2213]
### Describe the feature
dbt v0.16.0 uses `table.range_partitioning`, which was added in [google-cloud-bigquery v1.22.0](https://googleapis.dev/python/bigquery/latest/changelog.html#id10). The current range for this dependency is [>= 1.15.0, < 1.25.0](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/plugins/bigquery/setup.py#L44), so some folks could have a successful dbt installation but would be unable to use range partitioning in their incremental models!

Let's bump up the required version to 1.22.0

### Describe alternatives you've considered
If we _really_ wanted to, we could catch this error and show a warning that the installed version of `google-cloud-bigquery` does not support range partitioning.

### Additional context
BigQuery only

### Who will this benefit?
Range partitioners

**Comment by beckjake** [comment]
Fixed in #2214
