### ISSUE TITLE
In dbt cloud, allow a project to use multiple profiles

### ISSUE THREAD

**Issue by ran-eh** [fishtown-analytics/dbt#2216]
### Describe the feature
Currently, the bigquery project to connect to is setup at the dbt project level.  Allow setting it at the environment level.

### Additional context
We are using bigquery, I am assuming the same issue is relevant for other platforms.

### Who will this benefit?
In our setup, the bigquery production datasets and dev/sandbox datasets reside on different GCP projects.  Since dbt profiles are configured at the dbt project level, we are forced to maintain two dbt projects: one for development with no deployment environment, and one for production with a dummy dev environment called "DO NOT USE".  We are forced to have a dummy dev env on the prod project because dbt does not allow you to not have a dev env in a project.  

This is confusing: if you are on the production dbt project , and you select Develop from the hamburger menu, you get to what looks like the dev environment, but is really pointing at the production bigquery project.

### Describe alternatives you've considered
As a stopgap, how about allowing a dbt project to only have a deployment environment and no dev?

**Comment by drewbanin** [comment]
hey @ran-eh - thanks for sending this feedback through.

This is the issue tracker for dbt Core - the Apache 2.0 licensed, open source component of dbt. We don't use this site to track feature requests for dbt Cloud, and while I'm grateful that you sent through this suggestion, I am going to close this issue out as this isn't the right place to track this particular feature request.

In the future, please feel free to send through feedback or suggestions for dbt Cloud:
 - via the in-app chat in dbt Cloud
 - at support@getdbt.com
 - in the #dbt-cloud channel in dbt Slack

Feel free to reach out via one of those platforms and we'll do our best to help you out! For the moment though, I have created a ticket to track this request in our issue tracker for dbt Cloud :)

Thanks!
