### ISSUE TITLE
Use consistent time strings in RPC responses

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2217]
### Describe the bug
In some places, the RPC server is returning ISO-formatted timestrings, and in others, it's returning SQL-formatted timestrings. This makes it challenging to write code that operates on serialized timestamps returned by the RPC server. dbt should always use ISO-formatted timestrings, and we should add tests to ensure that this is the case.

Note: some of these timestrings come from proper rpc method responses, while others are extracted from the structured logs emitted by the server.

Adding @ashnm - can you advise on the places where we're seeing inconsistent timestring formatting in the dbt server responses?

**Comment by beckjake** [comment]
Internally, dbt always formats time in ISO 8601 format - so there's a `T` between date and time (though sometimes it doesn't add a `Z`). There are two places it does so: `hologram` does it by default, and our custom JSON encoder in `dbt/core/utils.py` also does it.

However, dbt cloud overrides `hologram` to space-separate date and time for django reasons, and that causes dbt's behavior to diverge from within dbt cloud based on whether a datetime is serialized with hologram or JSON. We can make the json code reach into hologram and use whatever encoder is registered for `datetimes`, I guess? Sounds awful.

**Comment by drewbanin** [comment]
Closing this one - the change required here isn't one that will take place in dbt Core.
