### ISSUE TITLE
Bump jinja2 minimum version to 2.11

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2227]
### Describe the feature
Some new and exciting functionality exists in jinja2 [v2.11.x](https://jinja.palletsprojects.com/en/2.11.x/changelog/#id1):
- Finding undeclared variables ([docs](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.meta.find_undeclared_variables)). We can use this to warn/error for undeclared variables in dbt models
- Support for `{{ foo if False }}` syntax alongside `StrictUndefined` ([docs](https://github.com/pallets/jinja/issues/710)). This was one of the big holdups with us using `StrictUndefined` IIRC
- A builtin `{% debug %}` extension ([docs](https://github.com/pallets/jinja/issues/174))
- Looks like many other fixes + improvements are included too

**Comment by beckjake** [comment]
Fixed in #2220
