### ISSUE TITLE
Add lower bound on `google-api-core`, or `google-cloud-core`, or both

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2233]
### Describe the bug
From Slack:

```
Just upgraded to dbt=0.16.0 and got the following error message when running:
$ dbt run --models analytics_table
Running with dbt=0.16.0
Error importing adapter: No module named 'google.api_core.client_options'
Encountered an error:
No module named 'google.api_core.client_options'
```

It looks like `client_options` was added in [1.13.0](https://googleapis.dev/python/google-api-core/latest/changelog.html#id15), but the user above had v0.12.0 installed.

Let's check out the requirements of `google-cloud-core` and `google-cloud-bigquery`. I think we may need to bump the minimum version of `google-cloud-core` in order to support:
- `client_options` (via `google-api-core`)
-  the `timeout` argument to `api_request` (also per Slack)

Users' env:
```
$ pip freeze | grep google
google-api-core==1.12.0
google-auth==1.11.3
google-cloud-bigquery==1.24.0
google-cloud-core==1.0.2
google-resumable-media==0.5.0
googleapis-common-protos==1.6.0
```

**Comment by beckjake** [comment]
Fixed in #2249
