### ISSUE TITLE
Update "building a new adapter" guide for 0.16.0

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2236]
Guide: https://docs.getdbt.com/docs/contributing/building-a-new-adapter

- The contents of this document should be updated to reflect any changes since the guide was first written
- The underlying script that generates a stub plugin should either be updated, or removed, from dbt Core

**Comment by drewbanin** [comment]
@beckjake to check if he has an open PR that updates the `create_adapter.py` script, and if so, open the PR

**Comment by beckjake** [comment]
Oops, it turns out I already did that in #2294!
