### ISSUE TITLE
Dynamic freshness specifications

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2240]
### Describe the feature
Freshness configs in sources should be evaluated with jinja, and they should be assigned a sane compilation context. Example:

```
freshness:
    warn_after: {count: "{{ some_expression }}", period: hour}
```

Here, `some_expression` should:
 - be evaluated with a context containing macros (if possible)
 - at the very least, be provided with the base+target context (cli `--vars`, `env_var`, `target`)
 - be coerced to an integer

This will allow for:
 - different freshness constraints in different envs
 - day-of-week-aware freshness checking
 - configuration of sources supplied via a package using variables

**Comment by jtcohen6** [comment]
This is possible with the introduction of native-render-on-command filters in v0.17.1:
```
freshness:
  warn_after: {count: "{{ (2 + 2) | as_number }}", period: hour}
```
