### ISSUE TITLE
dbt server does not correctly scope variables specified in dbt_project.yml

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2247]
### Describe the bug

When using the dbt server, I find that calls to `compile_sql` or `run_sql` are failing with errors indicating that vars are undefined, but they are specified in the `dbt_project.yml` file.

It looks like variables defined at the `models:` level, or the `models/project_name:` level are working, but vars specified beneath those keys (for a specific folder) are weirdly not working as expected.

### Steps To Reproduce

```
# dbt_project.yml

name: debug
version: 1.0.0

models:
  debug:
    path:
      vars:
        abc: 123
```

```
-- models/path/my_file.sql

select {{ var('abc') }}
```

I see the error:
```
Compilation Error in rpc request (from remote system)
  Required var 'abc' not found in config:
  Vars supplied to request = {
  }
```

### Expected behavior
I'd expect the `abc` variable to be in scope in the example above.

### Version

Reproduced with dbt v0.15.x and 0.16.x

**Comment by drewbanin** [comment]
The rpc server should accept a new parameter for the `compile_sql` and `run_sql` methods that contains the file path for the SQL query to compile or run. This path should be converted to a FQN in the dbt server, and then this FQN should be used to define the in-scope variables/configs for the SQL query.

If no file path is provided as a config, then the "default" variable/config scope should be used instead (ie. the current/existing behavior).

The config should be called `path`, and it should be a path relative to the root `dbt_project.yml` file.

Some things to consider:
 - Can we readily convert a file path to an FQN?
 - What if the specified path points inside of the `dbt_modules` dir?

cc @beckjake

**Comment by beckjake** [comment]
>What if the specified path points inside of the dbt_modules dir?

This should not be allowed, I think.

In fact, I think the path should be:
 - relative to the root of the current project
 - a valid model path given the `dbt_project.yml` for the current project.

You can imagine a future where there's an optional project_name parameter and the path restrictions are `s/current project/selected project/g`... but let's keep it simple?

**Comment by drewbanin** [comment]
I truly buy this - think it would work great and is very sensible/easy to explain/document. Let's do it!

**Comment by drewbanin** [comment]
Closing as vars work more sensibly in dbt >= 0.17.0
