### ISSUE TITLE
Add `partitions` to bq AdapterSpecificConfigs

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2256]
### Describe the feature
* Allow the user to define `partitions` in `dbt_project.yml`. This is a necessary config if the user wants to run incremental models with the `insert_overwrite` strategy for a static (user-defined) set of partitions
* Adding/overriding `partitions` in `dbt_project.yml` is the only way to adjust behavior for models imported from a package (e.g. Snowplow)

### Additional context
This is functionality we added in #2198, but forgot to add `partitions` to [`AdapterSpecificConfigs`](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/plugins/bigquery/dbt/adapters/bigquery/impl.py#L141) in `dbt-bigquery`

### Who will this benefit?
BigQuery users

**Comment by drewbanin** [comment]
Cool idea @jtcohen6 - let's do it!

**Comment by beckjake** [comment]
We should do this for 0.16.1, right?

**Comment by drewbanin** [comment]
closed by #2280
