### ISSUE TITLE
Snowflake Describe queries to show columns in a table

### ISSUE THREAD

**Issue by brittianwarner** [fishtown-analytics/dbt#2260]
### Describe the feature
The information_schema is extremely slow in Snowflake and it would be nice to use the describe functionality described here:https://docs.snowflake.com/en/sql-reference/sql/desc-table.html

I noticed that 0.16.0 implemented "show schema" but this only solved part of the problem.
 
I am running many models in parallel and I am seeing issues around the information schema where queries can take around a minute to return table information. 

### Describe alternatives you've considered
I don't know of any alternatives since this is built into DBT. 

### Additional context
This feature is database specific. 

### Who will this benefit?
Anyone using Snowflake.

**Comment by brittianwarner** [comment]
I am also getting these errors quite a bit: `090030 (22000): Information schema query returned too much data.  Please repeat query with more selective predicates.
  compiled SQL at dbt/target/compiled`

**Comment by drewbanin** [comment]
Hey @brittianwarner - thanks for opening this issue! We had a good thread on this topic which is worth checking out if you haven't seen it already: https://github.com/fishtown-analytics/dbt/issues/1877

Let's make this happen. `desc table` sounds like it will work great, and we've implemented a lot of the things we needed to implement to make this particular change tractable.

**Comment by brittianwarner** [comment]
Sounds great!  Let me know if I can help in any way.
