### ISSUE TITLE
Don't render overridden sources twice in docs site

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2284]
### Describe the feature
If a project overrides a source declared in a package, the docs site will render the source twice in the DAG view (and probably the file tree, too). Let's update the docs site to reflect the logical source constructed by dbt.

@beckjake can you advise what changes, if any, should take place in the compiled manifest? I'd be relatively happy with some JS logic in the docs site to merge sources together, but the more work dbt can do here, the better! Any chance we can have sources indicating which other sources they override, or which sources override them?

**Comment by beckjake** [comment]
I've thought about this a bit in the context of `ref`, and `doc` too. When we are parsing, we collect `docrefs`, `refs`, and `sources` - but only the literal arguments received. During compilation, we could either change those values (seems bad) or add new fields indicating the UIDs that were actually selected.

We _almost_ do this with the `depends_on` value, but it only includes `nodes`. Maybe we could extend that to `sources` and `docs` as well?

**Comment by drewbanin** [comment]
The code change here appears to be pretty minimal - AFAICT from testing out #2357 in dev, it looks like we just need to point to `manifest.sources` instead of `manifest.nodes` in some places.

**Comment by drewbanin** [comment]
fix is here: https://github.com/fishtown-analytics/dbt-docs/pull/87

Going to smoke test this change some more, then PR the `index.html` file in dbt
