### ISSUE TITLE
run tests for included packages

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#229]
It would be insanely valuable to be able to write tests for dependencies and have those run when the parent project runs `dbt test`. Right now there is no good way to implement testing within dependencies, even though this is an incredibly high-leverage place to write great tests.

**Comment by drewbanin** [comment]
:+1: good idea

**Comment by drewbanin** [comment]
added in https://github.com/analyst-collective/dbt/pull/279
