### ISSUE TITLE
Improve error message when two data tests have the same name

### ISSUE THREAD

**Issue by johansjob** [fishtown-analytics/dbt#2307]
### Describe the bug
If two data tests have the same file name `dbt compile` fails with:
`local variable 'get_func' referenced before assignment`

### Steps To Reproduce
Simply name two data tests, in different directories,  the same

### Expected behavior
This message is quite confusing and does not describe the issue. I would expect the error message to be similar to the one when you have two models being named the same. 

### System information
**The output of `dbt --version`:**
0.16.0

**The operating system you're using:**
macOS Catalina Version 10.15.3

**The output of `python --version`:**
3.8.2

**Comment by drewbanin** [comment]
Thanks for the report @johansjob! Sounds like a bug to me!

**Comment by jtcohen6** [comment]
Closing this issue, as I believe it is resolved in newer versions of dbt:
```
dbt compile
Running with dbt=0.18.1
Encountered an error:
Compilation Error
  dbt found two resources with the name "my_test". Since these resources have the same name,
  dbt will be unable to find the correct resource when "my_test" is used. To fix this,
  change the name of one of these resources:
  - test.testy.my_test (tests/folder/my_test.sql)
  - test.testy.my_test (tests/my_test.sql)
```
