### ISSUE TITLE
Composite unique_keys break with "merge" incremental_strategy

### ISSUE THREAD

**Issue by fcraposo** [fishtown-analytics/dbt#2309]
### Description of the Bug

Incremental models with composite `unique_key` (not recommended but supposedly [allowed](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional)) and no `incremental_strategy` explicitly defined break when upgrading from (I believe) version `<=0.13.1` to `>=0.14.1` because the default `incremental_strategy` changed from `delete+insert` to `merge` and the `default__get_merge_sql` [macro](https://github.com/fishtown-analytics/dbt/blob/a259f154dae60009b2115189f21ca1ed61061456/core/dbt/include/global_project/macros/materializations/common/merge.sql#L24) doesn't support composite `unique_keys` in any format.

Ex:

```
{{
    config({
        "materialized": "incremental",
        "unique_key": "col_1 || col_2"
    })
}}
```
would result in the following merge clause:
`DBT_INTERNAL_SOURCE.col_1 || col_2 = DBT_INTERNAL_DEST.col_1 || col_2`
which would cause the following error:
`ambiguous column name 'COL_2'`

Using `CONCAT(col_1, col_2)` wouldn't work either:
`Unknown user-defined function DBT_INTERNAL_SOURCE.CONCAT`

### Expected behaviour

The merge working correctly. That is, resulting the merge clause being:
`DBT_INTERNAL_SOURCE.col_1 || DBT_INTERNAL_SOURCE.col_2 = DBT_INTERNAL_DEST.col_1 || DBT_INTERNAL_DEST.col_2`

### Workaround

Specify the `incremental_strategy` as `delete+insert`.

Ex:

```
{{
    config({
        "materialized": "incremental",
        "unique_key": "col_1 || col_2",
        "incremental_strategy": "delete+insert",
    })
}}
```

### System information

dbt version: >=0.14.1
platform: Snowflake (haven't tested others, but I'd guess they would suffer from this issue too)
python version: 3.7.4
OS: macOS Mojave 10.14.6 and dbt cloud

**Comment by drewbanin** [comment]
Thanks for opening this issue @fcraposo! You're totally right - the `merge` strategy on Snowflake incremental models does not support composite `unique_key` configs. Instead, I'd recommend creating a surrogate key in your model, and then using that field as the `unique_key`.

Do you think an approach like that would work for you here? I _could_ imagine making `unique_key` accept a list of fields instead of an expression, but I don't view that as a really high priority change as surrogate keys should work really well here instead.

I'm closing this with the `wontfix` label to indicate that I don't think that code change is required to address this issue, but I would be very happy to update the docs to clarify that Snowflake (and BigQuery!) do not support composite `unique_key` specifications when the `merge` strategy is in use.

Curious to hear what you think. Thanks again!

**Comment by fcraposo** [comment]
Hey @drewbanin,

Thanks for reviewing the issue. 

I wouldn't say it's a "high priority" but it's surely "highly desirable". 🙂 

We don't want to add the complexity of handling surrogate keys in our use case. We receive events from several sources with the same `unique_key`, with possible desired and undesired duplication, among other things... 

We'd be very happy if dbt allowed for a list of fields as `unique_key`.

**Comment by drewbanin** [comment]
ok - thanks for that.

I don't think I can imagine using an expression as the unique key. If you have something like
```
unique_key='col_1 || col_2'
```

then dbt would need to somehow parse out this SQL expression and namespace the fields `col1` and `col2` with an aliased table name! Instead, I _can_ imagine supplying a list of columns, eg:
```
unique_key=['col1', 'col2']
```

here, dbt would compile a series of equalities to merge on, eg:

```
merge into <dest>
using <source>
on DBT_INTERNAL_SOURCE.col_1 = DBT_INTERNAL_DEST.col_1 AND
   DBT_INTERNAL_SOURCE.col_2 = DBT_INTERNAL_DEST.col_2
```

I think this would be functionally equivalent to the string-concat approach you showed above in _most_ cases. You think that would be a good answer for your use case?

**Comment by fcraposo** [comment]
> I think this would be functionally equivalent to the string-concat approach you showed above in most cases. You think that would be a good answer for your use case?

Hey @drewbanin !

Sorry for the delay. Yes. That would be great! 

Thank you for looking into it!

**Comment by lrahal** [comment]
Hi! Did that list of columns in `unique_key` field finally happened? :)
