### ISSUE TITLE
timeout_seconds ignored with dbt snapshot

### ISSUE THREAD

**Issue by rpedela-recurly** [fishtown-analytics/dbt#2323]
### Describe the bug
In `profiles.yml`, `timeout_seconds = 300` but `dbt snapshot` didn't timeout for 6 hours in BigQuery.

### log output
```
> dbt snapshot -s invoices_history --target TARGET

Database Error in snapshot invoices_history (snapshots/invoices_history.sql)
Operation timed out after 6.0 hours. Consider reducing the amount of work performed by your operation so that it can complete within this limit.
compiled SQL at target/run/myproject/invoices_history.sql
```

### System information
**Which database are you using dbt with?**
```
bigquery
```

**The output of `dbt --version`:**
```
0.16.0
```

**The operating system you're using:**
```
Docker image in GCP k8s.
```

**The output of `python --version`:**
```
3.7.3
```

**Comment by drewbanin** [comment]
hey @rpedela-recurly - thanks for opening this issue! The `timeout_seconds` profile config is only used in one _very specific_ place in BigQuery, and we have plans to remove that logic in the near-term future. I just made an issue to track this specific change here: https://github.com/fishtown-analytics/dbt/issues/2332

So, the behavior you're seeing is _intended_, but definitely wonky and confusing! Check out the linked issue, and let me know if you'd be supportive of a dbt-wide `timeout_seconds` config that applies to all queries that dbt runs.

Closing this one, but happy to discuss :)
