### ISSUE TITLE
Ambiguous alias exception should check `database` config

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2326]
### Describe the bug
dbt's [`raise_ambiguous_alias`](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/core/dbt/exceptions.py#L711) exception only takes into account a node's `schema` and `alias` when searching for collisions. It should also take into account a node's custom `database`.

### Steps To Reproduce
1. Create two models with different file names and `database` configs, but the same `schema` and `alias` configs. E.g.:
```
{{
    config(
        materialized = 'table',
        database = 'analytics',
        schema = 'dbt_jcohen',
        alias = 'fct_sprints'
    )
}}
```
```
{{
    config(
        materialized = 'table',
        database = 'not_analytics',
        schema = 'dbt_jcohen',
        alias = 'fct_sprints'
    )
}}
```

2. Run `dbt compile`

```
Encountered an error:
Compilation Error
  dbt found two resources with the database representation "dbt_jcohen.fct_sprints".
  dbt cannot create two resources with identical database representations. To fix this,
  change the "schema" or "alias" configuration of one of these resources:
  - model.fishtown_internal_analytics.fct_sprintssss (models/marts/consulting/fct_sprintssss.sql)
  - model.fishtown_internal_analytics.fct_sprints (models/marts/consulting/fct_sprints.sql)
```

### Expected behavior

dbt's `raise_ambiguous_alias` method should take into account custom databases to determine if two models have identical database representations.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

I have tested on Snowflake. I imagine it could be relevant on BigQuery as well.

**The output of `dbt --version`:**
```
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
```

**Comment by jtalmi** [comment]
hey @drewbanin , i'd be happy to take this on as my first pr. looks like the change is needed here: https://github.com/fishtown-analytics/dbt/blob/5884f7df55f564764939adc736b33331d48aa4cd/core/dbt/parser/manifest.py#L381

**Comment by beckjake** [comment]
Hey, sorry about this collision @jtalmi! I saw this message while I was in the process of writing the CHANGELOG.md entry and opening the PR, but we appreciate your interest!

The fix ended up being a bit more involved than we anticipated because want to support warehouses that don't necessarily have the concept of databases/schemas, so maybe it's for the best that you didn't have to digging around inside the Relations/adapters code in your first PR :)

**Comment by jtalmi** [comment]
ah fair enough! if you see a good starter issue out there, please let me know :)
