### ISSUE TITLE
run_sql command via dbt rpc returns Object of type Decimal is not JSON serializable

### ISSUE THREAD

**Issue by brettgriffin** [fishtown-analytics/dbt#2336]
### Describe the bug
Executing a `run_sql` command via `dbt rbc` against a BigQuery profile returns `Object of type Decimal is not JSON serializable`. The equivalent command against Redshift, Snowflake, and PostgreSQL connections works correctly.

### Steps To Reproduce
A model exists with the body `with source as ( select * from {{source('recharge', 'orders')}} ) select * from source`. 

The query of the model is wrapped in a CTE limiting its results to 100 records:
```
with run_cte as (with source as ( select * from {{source('recharge', 'orders')}} )) select * from run_cte limit 100
```

And converted to base64:

```
d2l0aCBydW5fY3RlIGFzICh3aXRoIHNvdXJjZSBhcyAoIHNlbGVjdCAqIGZyb20ge3tzb3VyY2UoJ3JlY2hhcmdlJywgJ29yZGVycycpfX0gKSkgc2VsZWN0ICogZnJvbSBydW5fY3RlIGxpbWl0IDEwMA==
```

A request is made to the RPC Server with the `run_sql` command, with the following body:

```
{
    jsonrpc: "2.0",
    method: 'run_sql',
    id: 123,
    params:  {
      name: "query",
      timeout: 60,
      sql: d2l0aCBydW5fY3RlIGFzICh3aXRoIHNvdXJjZSBhcyAoIHNlbGVjdCAqIGZyb20ge3tzb3VyY2UoJ3JlY2hhcmdlJywgJ29yZGVycycpfX0gKSkgc2VsZWN0ICogZnJvbSBydW5fY3RlIGxpbWl0IDEwMA==
    }
```

### Expected behavior
I would expect this to return the result set of the underlying sql statement.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.16.01
```

**The operating system you're using:** macOS 10.13.6

**The output of `python --version`:** 3.7

**Comment by drewbanin** [comment]
Thanks for the report @brettgriffin - this error occurs if a `numeric` column is found inside of a struct or array column in BigQuery
