### ISSUE TITLE
dbt gives a misleading error when attempting to install with python 2

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2347]
### Describe the bug
Installing with python 2 and setuptools 44.1.0 (the last that supported python 2) gives an error of `Error: dbt requires setuptools v40.1.0 or higher.`. Instead, it should inform users that their python version is unsupported and instruct them to upgrade to 3.6+.

### Steps To Reproduce
- Install/use python 2
- `pip install dbt`

### Expected behavior
An error saying that I can't install dbt with Python 2.x.

### Screenshots and log output
N/A

### System information
**Which database are you using dbt with?**
N/A

**The output of `dbt --version`:**
N/A, but you can see it when installing 0.16.1

**The operating system you're using:**
Any

**The output of `python --version`:**
2.7.18

### Additional context
This should be very straightforward - before we look for `setuptools.find_namespace_packages`, ensure that `sys.version_info >= (3, 6)`! The only annoying part will be making sure to hit all 6 setup.py files.

**Comment by genos** [comment]
Hi everyone! Since this is marked as a `good first issue` and the above description is extremely helpful, I'd like to tackle this one. PR is forthcoming, if nobody objects.

**Comment by dennisjaheruddin** [comment]
At a glance this code appears to be in the main branch now, however I just tried a few installs on mac, and each still gives the original error. Here are some that I tried:

```
pip install dbt-spark     
pip install dbt-postgres 
pip install dbt-core
```

Also wonder why we recommend pip install and not just pip3 install, this seems to work fine:

`pip3 install dbt-spark`

**Comment by genos** [comment]
On modern systems not using Python 2 (which isn’t even supported by the [Python Foundation](https://www.python.org/doc/sunset-python-2/)), pip _is_ pip3.
