### ISSUE TITLE
Finding schemas / databases / tables no longer managed by dbt

### ISSUE THREAD

**Issue by friendofasquid** [fishtown-analytics/dbt#2359]
### Describe the feature

If we remove something from dbt, it sticks around in our data lake. This can be problematic because

1. it may have storage costs associated with it
2. it may be subject to governance and redaction

What I propose is a built-in way of configuring the behaviour of things no longer managed by dbt. This could be done in the profile.yml, where the default might be to just warn in the logs of unmanaged stuff within (or prefixed by) the profile's schema that doesn't appear in the DAG.

### Describe alternatives you've considered

Manually removing stuff no longer managed by dbt.

**Comment by drewbanin** [comment]
check out this thread from a while back: https://github.com/fishtown-analytics/dbt/issues/1135

I think this is a good idea, and I'd be keen to implement something like this in a future version of dbt. I'm going to close this issue out in favor of #1135, so if you have any further thoughts, feel free to drop them in there!
