### ISSUE TITLE
Split node selection out from graph creation

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2362]
### Describe the feature
Currently, dbt selects tests as a mandatory part of the node selection process: After normal selection is done, dbt just adds every test that descends from the selected nodes.

Instead, dbt should only do that for tests. To accomplish this, dbt should split out node selection into "node selection" and "DAG creation", as discussed in #2203. The DAG creation step for `dbt test` is where test nodes should come into play.

This PR should also try to handle ephemeral nodes, but if that's hard it can wait.

### Who will this benefit?
This will make it easier to explain selection in dbt. This will lay groundwork for some future work with more granular test selection, node selection, and `dbt run+test`

**Comment by drewbanin** [comment]
closing in favor of https://github.com/fishtown-analytics/dbt/issues/2328
