### ISSUE TITLE
Shareable link for data lineage

### ISSUE THREAD

**Issue by ucg8j** [fishtown-analytics/dbt#2380]
### Describe the feature
When creating a data lineage graph, the only option to persist the graph is to export it as a PNG. 
![Screen Shot 2020-04-30 at 17 02 01](https://user-images.githubusercontent.com/6220504/80732515-575c0580-8b04-11ea-9964-c5d77c6eb158.png)

However, it would make collaboration with colleagues or returning to the interactive version of the lineage much easier if you could share a hyperlink to the lineage graph. 

### Who will this benefit?
Users would be able to share with others an interactive version of the chart.
User can returned to a a customised lineage graph they previously organised/customised.
Allow users to embed the lineage graph in other live documents.

**Comment by drewbanin** [comment]
hey @ucg8j - you can currently do this! Check out an example here: 
https://www.getdbt.com/attribution-playbook/#!/model/model.acme.attribution_touches?g_v=1&g_i=%2Battribution_touches%2B

Just share the URL you're viewing when the DAG is open :)

**Comment by ucg8j** [comment]
@drewbanin - mindblown. Ignore me. It was just taking a long time on our stack.... like 15secs. That I assumed it wasn't a feature and closed the tab before it loaded. Thanks.

That said, it would be good to have some sort of indication that the lineage graph is loading. What do you think?

**Comment by drewbanin** [comment]
sure @ucg8j - I buy that! How's your javascript? :D

**Comment by ucg8j** [comment]
haha - sadly weak, but I'm currently improving! 10 days into javascript30.
Honest feedback - are these feature tweaks/suggestions including the
multi-select issue helpful to your product development?
If they are I'll type them up - but if not, I'll focus harder on skilling
up! :)

**Comment by drewbanin** [comment]
Oh that's cool! I love writing javascript -- it's well worth the investment IMO :)

We're going to put a _lot_ of attention towards this docs site soon, but we're big fans of incrementalism too! I always like having an issue to track bugs / requests even if we can't prioritize them immediately. I'd say feel free to create as many issues as you'd like, and I'll pop in to help prioritize and shape the issues as needed :)

Thanks!

**Comment by evan-levy** [comment]
@drewbanin Is URL sharing as you demonstrated above still possible? I'm having a hard time generating the URL for my account running on cloud. When I share the URL straight from my DAG I get a 403 forbidden response. Thanks!

**Comment by leo-ghub** [comment]
same here @evan-levy
