### ISSUE TITLE
Tables with hard-coded values

### ISSUE THREAD

**Issue by BrianLondon** [fishtown-analytics/dbt#239]
It looks like there's code in the repository to support pre-seeded tables, for example in [seeder.py](https://github.com/analyst-collective/dbt/blob/17e553982c8ffc10d56f64375ba3764fb01a277d/dbt/seeder.py) and [seed.py](https://github.com/analyst-collective/dbt/blob/a245bd7c3189183b60846b5d05457805de57373a/dbt/task/seed.py). Is this feature simply not yet documented or does it not do what it appears to do?

**Comment by drewbanin** [comment]
hey @BrianLondon -- this is presently undocumented, but dbt does have a feature to "seed" the db from CSV files.

We'll add some docs for this soon, but in the meantime here's what you need to do to get it working:

1. Make sure you've specified one or more `data-paths` in your `dbt_project.yml` file:
```yml
data-paths: ["data"]
```

2. Put one or more CSVs into your `data-path` directory. The name of the CSV will be the table name. A header is required in these CSV files.
```
./data/some_data.csv
./data/other_data.csv
```

3. Run `dbt seed` to load these CSVs into your data warehouse. They'll show up in the schema that you specified in your `run-target`

```bash
$ dbt seed
Inserting 500 records into table analytics.some_data
Inserting 33 records into table analytics.other_data
```

---------

```bash
$ dbt seed --help
usage: dbt: data build tool seed [-h]
                                 [--profile PROFILE] [--target TARGET]
                                 [--drop-existing]

optional arguments:
  -h, --help            show this help message and exit
  --profile PROFILE     Which profile to load (overrides profile setting in
                        dbt_project.yml file)
  --target TARGET       Which target to load for the given profile
  --drop-existing       Drop existing seed tables and recreate them
```

There's some more information [here](https://github.com/analyst-collective/dbt/releases/tag/v0.2.3.0)  (under "2. Feature: seed tables from a CSV").

FYI: We're typically more responsive on [slack](http://ac-slackin.herokuapp.com/) -- feel free to rech out there too!

**Comment by drewbanin** [comment]
This has been documented [here](https://dbt.readme.io/v0.8/reference#seed) for some time. Closing
