### ISSUE TITLE
Fresh installs create a broken link in ~/.dbt/profiles.yml

### ISSUE THREAD

**Issue by tjwaterman99** [fishtown-analytics/dbt#2394]
### Describe the bug

I ran `pip install dbt` and then `dbt init myproject`. Inside the newly created `~/dbt/profiles.yml` file was this link: 

https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml

That link currently 404s.

### Steps To Reproduce

Delete the `profiles.yml` file and reinstall dbt with pip.

### System information
**Which database are you using dbt with?**

N/A

**The output of `dbt --version`:**

```
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
```

**The operating system you're using:**

Mac OS Mojave.

**The output of `python --version`:**

Python 3.7.7

**Comment by drewbanin** [comment]
ah, thanks for the heads up @tjwaterman99! I think the fix here is just to periodically merge feature branches back into `master`. We don't really use `master` for anything these days, and I think we've just neglected to do this for a while!

We'll get this fixed up - thanks!

**Comment by jtcohen6** [comment]
I think this _should_ have been fixed by https://github.com/fishtown-analytics/dbt/pull/1366, way back when. Failing that, it's definitely been addressed by the changes in https://github.com/fishtown-analytics/dbt/pull/2594. Just tested locally and confirmed the errant link is missing
