### ISSUE TITLE
Aliasing the returned columns of macros to support MS sql server

### ISSUE THREAD

**Issue by mikaelene** [fishtown-analytics/dbt#2397]
### Describe the bug
The pyodbc driver used in https://github.com/mikaelene/dbt-sqlserver doesn't support unnamed columns in the resultset. When issuing a query such as `select count(*) from table` the driver returns an error. However `select count(*) as column_name from table` work just fine. I guess this would apply to a Oracle-adapter using pyodbc as well.

The easiest solution would probably be to aliasing all columns in dbt-core macros to make adapters easier to implement and minimize code copy-paste in adapters.

This change will probably have no effect on other adapters.

### Steps To Reproduce
Run dbt test (0.16 +) with https://github.com/mikaelene/dbt-sqlserver/tree/v0.16.0

### Expected behavior
Everything works without overriding the dbt core macros just for aliasing.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: MS Sql Server)

**The output of `dbt --version`:**
```
installed version: 0.16.1
```

**The operating system you're using:**
mac os

**The output of `python --version`:**
`Python 3.7.3`

### Additional context
I can open a PR to fix this issue.

**Comment by drewbanin** [comment]
Thanks for the report @mikaelene - a PR for this would be very welcomed!

**Comment by mikaelene** [comment]
I would like this in 0.16.x something. Is it possible? Which branch should I open the pull request to?
