### ISSUE TITLE
dbt init is creating outdated config-version file 0.17.0-b1

### ISSUE THREAD

**Issue by swiffer** [fishtown-analytics/dbt#2404]
### Describe the bug
out of interest installed 0.17.0-b1, running `dbt init` to get an idea on config-version: 2 changes still produces showed a v1 config file.

### Steps To Reproduce
`dbt-init`

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0-b1
   latest version: 0.16.1

Your version of dbt is ahead of the latest release!

Plugins: [empty, but dbt-utils and snowflake-spend are installed]
```

**The operating system you're using:**
Windows 10 64bit

**The output of `python --version`:**
Python 3.8.2

**Comment by drewbanin** [comment]
thanks for the heads up @swiffer! This is a sort of tricky thing to navigate, as we want old versions of dbt (which _do not_ support `config-version: 2`) to continue to clone valid starter projects.

I suppose we could either create a branch (not a great idea) or a separate repo. Either way - this is definitely something we should address before 0.17.0 goes live!
