### ISSUE TITLE
Check Columns present when running Schema Tests for a source

### ISSUE THREAD

**Issue by ArafathC** [fishtown-analytics/dbt#2405]
### Describe the feature
When running tests on a source
Check if all the columns specified in the source are present in the source

### Describe alternatives you've considered
We have or will be implementing a is_present check for all fields .. but this would be great if it can be included as part of testing the sources itself

### Who will this benefit?
This will benefit any one testing external sources

**Comment by drewbanin** [comment]
Thanks for opening up this issue @ArafathC. I imagined we would hit something like this in the scope of #1570

**Comment by ArafathC** [comment]
Hey @drewbanin , we can close this one .. i can track the status of #1570
