### ISSUE TITLE
Running dbt with a duplicate test name gives an unhelpful error

### ISSUE THREAD

**Issue by Tbodewes** [fishtown-analytics/dbt#2406]
### Describe the bug
Running `dbt run` when there are multiple tests with the same name leads to an unhelpful error `local variable 'get_func' referenced before assignment`

### Steps To Reproduce
1. Create two tests with the same name (in different folders) of the project. 
2. Run `dbt run`
3. See the below error:
```
Running with dbt=0.16.1
Encountered an error:
local variable 'get_func' referenced before assignment
```

### Expected behavior
To receive a descriptive error like `'path1' and 'path2' give a test/resource with a duplicate name. Please ensure tests/resources have unique names.`

### System information
**Which database are you using dbt with?**
- [x] snowflake

**The output of `dbt --version`:**
```
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
```

**The operating system you're using:**
Windows 10 Pro, version 1909, OS build 18363.778

**The output of `python --version`:**
Python 3.8.0

**Comment by drewbanin** [comment]
Thanks for the report @Tbodewes - should be a quick fix :)
