### ISSUE TITLE
dbt found two macros with the name "test_unique" in the namespace "dbt"

### ISSUE THREAD

**Issue by mingkezhou** [fishtown-analytics/dbt#2423]
### Describe the bug
When run dbt run or dbt test, it always say dbt found two macros with the name "test_unique" in the namespace "dbt", but there is only one file.
tried install and installl dbt and python and dbt-sqlserver which didn't work
dbt test
Running with dbt=0.16.1
Encountered an error:
Compilation Error
  dbt found two macros with the name "test_unique" in the namespace "dbt". Since these macros have the same name and exist in the same namespace, dbt will be unable to decide which to call. To fix this, change the name of one of these macros:
  - macro.dbt_sqlserver.test_unique (macros\schema_tests.sql)
  - macro.dbt_sqlserver.test_unique (macros\schema_tests.sql)

### Steps To Reproduce

Installed dbt
installed dbt-sqlserver
create dbt sqlserver connection
then run dbt test or dbt test. the got the error

### Expected behavior
I should not see this duplicate error

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
sql-server

**The output of `dbt --version`:**
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
<output goes here>
```

**The operating system you're using:**
windows 10 pro

**The output of `python --version`:**
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32



Up to date!
### Additional context
Add any other context about the problem here.

**Comment by jtcohen6** [comment]
Which version of `dbt-sqlserver` are you using?

The most recent stable release is [0.15.1](https://github.com/mikaelene/dbt-sqlserver/releases/tag/v0.15.1), which needs to be run alongside the 0.15.1 version of dbt core. It looks like you're running dbt version 0.16.1. I think you'll want to downgrade to use the 0.15.1 versions of both dbt and the dbt-sqlserver plugin until there is a new stable release.

In the next minor release of dbt (0.17.0):
* This discrepancy will be clearer by including plugin versions in the printout of `dbt --version`
* We've just merged a change to supports a new version of the community-supported `dbt-sqlserver` plugin (#2414)

We have some additional ideas about making this specific problem easier to spot (#2288) and resolve (#2415) in the future.

**Comment by ramgopalan** [comment]
Hi,

Facing the same issue in dbt 17.0 version, any quick fix for 17 version?

**Comment by drewbanin** [comment]
@ramgopalan are you also using dbt-sqlserver?

**Comment by ramgopalan** [comment]
Yeah @drewbanin

**Comment by ramgopalan** [comment]
Hi @drewbanin  Any updates?

**Comment by alittlesliceoftom** [comment]
Hi @drewbanin thanks for your solution. 

I just tried this solution (previously dbt v0.17) and it does work correctly (after realising I really needed to use venvs and not my default conda env for this). 

I have raised an issue on the community plugin for the same.

**Comment by jtcohen6** [comment]
Closing this issue, as I believe it was ultimately resolved by using `adapter.dispatch` within schema test definitions
