### ISSUE TITLE
Hide macro from docs

### ISSUE THREAD

**Issue by alf-mindshift** [fishtown-analytics/dbt#2430]
### Describe the feature

We have some macros in our project that are not relevant to the consumers of our documentation site. Issue #1671 and pr #2179 came very close to delivering the necessary functionality to hide them.

### Describe alternatives you've considered

We can post-process the manifest.json file instead. This would be annoying and only fix the problem for us. A general solution would be better.

### Additional context

This is a trivial change.

### Who will this benefit?

This makes it easier to tweak the documentation site to work for less technical people.

**Comment by drewbanin** [comment]
Thanks for opening this issue @alf-mindshift. I think the root issue here is that the `show` config is not compiled into the `manifest.json` file. Once we make that change, we can make the corresponding change in the docs website to remove these hidden nodes from the file tree.
