### ISSUE TITLE
The create_adapter_plugin script emits a v1 config file

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2451]
### Describe the bug
The create_adapter_plugin emits a v1 config file, but that results in a warning on every dbt run for users.

### Steps To Reproduce
Create a plugin with the script
Try to use it

### Expected behavior
I expect a `dbt_project.yml` with `config-version: 2`.

### System information
**The output of `dbt --version`:**
0.17.0rc1

**Comment by drewbanin** [comment]
@beckjake do you think we should try to make this happen for octavius catto? I think it's not crazy to ask folks to run the script with the latest dev branch, but i'd be happy to incorporate it for 0.17.0 if we can make it happen too!

**Comment by beckjake** [comment]
This is such a tiny change, I'm just going to open a PR for it.

**Comment by beckjake** [comment]
Fixed in #2455
