### ISSUE TITLE
If any v1 configs are present, global-level v2 var declarations do not work

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2469]
### Describe the bug
If you have some v2 project configs with global-level `var` declarations, adding any project with a v1 config breaks them.

### Steps To Reproduce
Create 3 projects:
 - two with v2 configs and global var declarations
 - one with a v1 config

Even if the third project never accesses any vars from the v2 configs and vice-versa, dbt will convert the v2 configs into v1 configs and lose the global level vars.

I have a few test cases to exercise this behavior that I'll add with the fix, but I think basically that this:
```
vars:
  my_var: 1000
```

should become (repeated for seeds/snapshots, too)
```
models:
  project_1:
    vars:
      my_var: 1000
  project_2:
    vars:
      my_var: 1000
...
```

Which can then be overridden with any actual existing per-project config members.

### Expected behavior
dbt should include make any global v2 vars available as a project-level config for each dependency and the root project.

### System information
Any databases, any OS, any supported python, `dbt==0.17.0rc1`

**Comment by drewbanin** [comment]
closed by https://github.com/fishtown-analytics/dbt/pull/2477
