### ISSUE TITLE
[0.17.0rc1] Broken Docker image entrypoint

### ISSUE THREAD

**Issue by dmateusp** [fishtown-analytics/dbt#2470]
### Describe the bug

The entrypoint for the image is invalid

### Steps To Reproduce

1. Pull the image: `docker pull fishtownanalytics/dbt:0.17.0rc1`
2. Run the image: 

```
docker run -it fishtownanalytics/dbt:0.17.0rc1
/bin/sh: 1: [dbt,: not found
```

### Expected behavior

The DBT help command is displayed

### Additional context

I plan on integrating DBT with our Airflow infrastructure as a container (we extend Airflow exclusively through containerized components)

**Comment by drewbanin** [comment]
closed by https://github.com/fishtown-analytics/dbt/pull/2475

Thanks @dmateusp!
