### ISSUE TITLE
The link in the default `profiles.yml` is `Page not found`

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/dbt#2488]
### Describe the bug
The link in the default `profiles.yml` is `Page not found`:

```
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile
```

**The output of `dbt --version`:**
```
0.16.1
```

**Comment by drewbanin** [comment]
thanks for the heads up @max-sixty - we'll get this fixed with a redirect on the docs site :)

**Comment by drewbanin** [comment]
hey - just wanted to close the loop on this - we've since added a redirect that you can see here: https://docs.getdbt.com/docs/profile

Thanks for opening this! And in the future, please feel free to open up an issue in the docs repo: https://github.com/fishtown-analytics/docs.getdbt.com

**Comment by max-sixty** [comment]
Thanks a lot as ever @drewbanin !
