### ISSUE TITLE
capture dbt cli submitted command in run_results.json

### ISSUE THREAD

**Issue by younescha** [fishtown-analytics/dbt#2510]
### Describe the feature
capture dbt cli submitted command in run_results.json,
this is to help with logging/auditing, where we need some way to identify various runs. 

### Describe alternatives you've considered
no proper alternative, all the workarounds are fragile and short living at best, examples:
- if this invocation contains some specific marketing model then this is a marketing dbt run
- if the only tag that is present in my run is equal to 'hourly' then this is the hourly dbt run (depends on a strict set up of tags)

### Additional context
cross databases feature.

### Who will this benefit?
hopefully all dbt users, but main audience is dbt users trying to audit/investigate/optimize their runs

**Comment by drewbanin** [comment]
I'm super supportive of this feature - thanks for opening it @younescha! I added this to the milestone for our next release, `dev/marian-anderson`.
