### ISSUE TITLE
dbt should provide a way to signify that a field is a string at the yaml level

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2531]
### Describe the feature
Currently, in config files in dbt that are rendered in the native environment, we provide an `as_text` filter that dbt uses to identify a value that should not be converted to the native env rendering. We should provide a similar feature at the yaml level, so users can mark fields (perhaps even recursively?) as being "really strings" to either be rendered in the non-native jinja renderer or not rendered at all.

The big issue is that it's pretty tedious to mark all the relevant fields as text right now if you have a lot of them.

### Describe alternatives you've considered
Users can use `"{{ 00 | as_text }}"` instead of `"00"` anywhere. `"'00'"` should work too in most cases.

### Additional context
Any/All dbs

### Who will this benefit?
dbt users who configure a lot of numeric-looking strings.

**Comment by jtcohen6** [comment]
Closing in favor of #2612
