### ISSUE TITLE
Write database-specific sample profiles.yml file in `dbt init`

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2533]
### Describe the feature

Let's add a flag to `dbt init` which controls the sample contents of the `~/.dbt/profiles.yml` file. 

Example usage:
```
dbt init my-project --adapter=bigquery
dbt init my-project --adapter=snowflake
dbt init my-project --adapter=redshift
```

dbt's adapter plugins should provide their own sample profiles .yml contents. Presently, dbt writes out a Redshift-specific profile.

### Additional context
Hi Felipe :)

### Who will this benefit?
BQ/Snowflake/Postgres/Spark/Presto users!

**Comment by brunomurino** [comment]
I'm happy to take this, if still available @drewbanin

**Comment by brunomurino** [comment]
I'm trying to set up a try-catch with the possible adapter options, but can't seem to find a 'list' of possible adapters. I found some stuff in `dbt/core/dbt/include/global_project/macros/adapters/common.sql` but not sure this is it.

My idea is to create a template profiles.yml in each adapter folder and create a dictionary such that `STARTER_PROFILE[sample_adapter]` would get the sample from the adapter.

How does that sound?

**Comment by beckjake** [comment]
>I'm trying to set up a try-catch with the possible adapter options, but can't seem to find a 'list' of possible adapters.

There is no formal list of possible adapters, because users can write their own adapter plugins.

>My idea is to create a template profiles.yml in each adapter folder

In #2590, I added a `get_include_paths` function to `dbt.adapters.factory`, and the first item in the return value of `get_include_paths` is always the given adapter's project. Assuming it gets merged, taht might make this easier. Each adapter plugin could have a `sample_profiles.yml` inside its include path (so alongside the `dbt_project.yml`), and you could use that and the `--adapter` argument to decide what to use.

You'd have to do something like:
```python
factory.load_plugin(args.adapter)
path = factory.get_include_paths(args.adapter)[0]
sample_path = path / 'sample_profiles.yml'
if not sample_path.exists():
    raise RuntimeException(f'No sample profile for {args.adapter}')
shutil.copy_file(sample_path, dest)
```

If the chosen adapter is installed and has a sample profile, it should behave okay.

**Comment by brunomurino** [comment]
makes sense, it would indeed make it easier.

I'm trying to checkout the branch `fix/adapter-macro-namespacing` but can't find it (?).
If I can't check that out, then I'd just wait on your PR to bet merged

**Comment by beckjake** [comment]
@brunomurino you might have to set up `fishtown-analytics/dbt` as a git remote and `git fetch` that, I think like this:

```
git remote add upstream https://github.com/fishtown-analytics/dbt.git
git fetch upstream
git checkout upstream/fix/adapter-macro-namespacing
```
That will probably drop you into a detached HEAD state, so then you'll need to use `git checkout -b` to create a new local branch

**Comment by brunomurino** [comment]
Worked like a charm.

Just created the PR for this: https://github.com/fishtown-analytics/dbt/pull/2594
alongside PRs for [presto](https://github.com/fishtown-analytics/dbt-presto/pull/26) and [spark](https://github.com/fishtown-analytics/dbt-spark/pull/98).
