### ISSUE TITLE
Enhancement: Make it more apparent when model specified in yml configuration does not exist in the project

### ISSUE THREAD

**Issue by christineberger** [fishtown-analytics/dbt#2545]
### Describe the feature
When doing a run or test, a warning is given when a yml file has a model specified to document/test against. This warning is easily missed.

To test this:
1. Create a .yml file and give it some documentation/testing parameters for a model that is not in the project.
2. Do a dbt run or dbt test and see the warning at the top.

Although the warning is there and you will catch this if you're paying attention, this is something that is missed frequently which results in more time spent explaining this, being very diligent in catching this in reviews, and more time for users to pay careful attention to this. I think we can make this easier for all of us. Here's a couple of ideas:

1. Highlight the warning as a different color
2. Throw a line in for the model name specified anyway, but show as an error/warning with more details after the testing is done

### Describe alternatives you've considered
The solution to resolving instances of this issue currently is a matter of training users to be mindful of not just glancing at their dbt run and dbt test outputs.

### Who will this benefit?
Anyone who uses dbt and the docs/testing functionality!

**Comment by drewbanin** [comment]
good idea @christineberger! I think changing the color for this warning would work well. Let me know if this is something you might be interested in working on when you get some spare time 😉

**Comment by christineberger** [comment]
@drewbanin I absolutely would love to take a stab at this! I can't promise I'll get anywhere, but I will definitely try. =)
