### ISSUE TITLE
Implement BigQuery alter column type functionality

### ISSUE THREAD

**Issue by azhard** [fishtown-analytics/dbt#2546]
### Describe the feature
Currently dbt uses the default macro implementation for altering column types which doesn't actually work with BigQuery. This feature would implement a BigQuery specific macro that allows users to alter column types.

### Describe alternatives you've considered
BigQuery currently has two methods user's can use to alter a column type. The first method is done purely in SQL, the second involves uploading data to cloud storage. I believe the SQL specific approach makes more senes for dbt.

https://cloud.google.com/bigquery/docs/manually-changing-schemas#changing_a_columns_data_type

### Additional context
Feature is specific to BigQuery

### Who will this benefit?
BigQuery dbt users who might find themselves in need of a way to alter a column type through dbt.

**Comment by jtcohen6** [comment]
Thanks for this @azhard, I'll leave a comment on the PR.
