### ISSUE TITLE
Unable to override macros in adapter

### ISSUE THREAD

**Issue by mikaelene** [fishtown-analytics/dbt#2548]
### Describe the bug
Some of the standard dbt macros can't be overridden by an adapter. I.e. Test, snapshots. This is present since dbt v0.16.0

### Steps To Reproduce
Create an adapter the aims to override the standard macro snapshot_check_strategy. This has made it impossible for the dbt-sqlserver adapter to follow along with newer dbt verison.

### Expected behavior
Expects that the macro is overridden by the adapter version.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: SQL Server

**The output of `dbt --version`:**
```
installed version: 0.17.0
```

**The operating system you're using:**
Osx and windows

**The output of `python --version`:**
Python 3.7.7

**Comment by drewbanin** [comment]
thanks for opening this issue @mikaelene! The issue you ran into specifically was around overriding the `snapshot_check_strategy` macro specifically, right? Or were there other specific macros that you were unable to override in the `dbt-sqlserver` plugin?

**Comment by mikaelene** [comment]
it was specifically snapshot_check_strategy. But I had the same issue for all tests macros in 0.16. I solved that with a workaround solution in https://github.com/fishtown-analytics/dbt/pull/2414. But I think that there is probably a general problem that some macros can't be overridden since 0.16

**Comment by swanderz** [comment]
@mikaelene looks like the bugfix is slated for `0.18.0` https://github.com/fishtown-analytics/dbt/pull/2590
Perhaps I'll pull dbt's `dev/master` and see if things are working properly?
