### ISSUE TITLE
persist_docs functionality doesn't persist descriptions on nested bigquery columns

### ISSUE THREAD

**Issue by bodschut** [fishtown-analytics/dbt#2549]
### Describe the bug
With the release of dbt 0.17.0, the persist_docs functionality was enhanced to also apply column descriptions to bigquery when they are supplied in a schema.yml file. However, it seems that it only takes into account top-level columns and there is no way to persist a description to a nested column (ie a field that is part of a RECORD type bigquery column).

### Steps To Reproduce
Suppose you create a simple test model using dbt in bigquery:
``` SQL
SELECT
    STRUCT(
        STRUCT(
            1 AS level_3_a,
            2 AS level_3_b
        ) AS level_2
    ) AS level_1
```

This will create a view/table in bigquery with the following schema:
![image](https://user-images.githubusercontent.com/1922169/84779953-4ea48d80-afe5-11ea-98ea-18d7a686647e.png)

We can describe this table in a schema.yml file and add descriptions as follows:
```yaml
version: 2

models:
  - name: test_nested
  
    columns:
      - name: level_1
        description: level_1 description
      - name: level_1.level_2.level_3_a
        description: level_3_a description
```

When we now perform a `dbt run` on this model, only the description on the top level field is added and no warnings or errors are generated by dbt:
![image](https://user-images.githubusercontent.com/1922169/84780414-d5f20100-afe5-11ea-869a-386b8518dd3f.png)

### Expected behavior
When providing descriptions for nested fields (preferably using the dotted syntax as shown above), the descriptions should be correctly persisted on nested fields.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.17.0

Up to date!

Plugins:
  - snowflake: 0.17.0
  - postgres: 0.17.0
  - bigquery: 0.17.0
  - redshift: 0.17.0
```

**The operating system you're using:**
Mac OS 10.15.3

**The output of `python --version`:**
Python 3.7.5

**Comment by bodschut** [comment]
Should we close this issue @beckjake ?

**Comment by drewbanin** [comment]
closed by https://github.com/fishtown-analytics/dbt/pull/2550

Thanks for your contribution @bodschut!
