### ISSUE TITLE
BigQuery project alias is ignored in config

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2557]
### Describe the bug
A user reported that a config like:
```
{{ config(project='myproject') }}

...
```

has regressed in dbt v0.17.0. While this config worked in a BQ project in dbt v0.16.1, they reported that they needed to change `project` to `database` to apply the configuration in dbt v0.17.0.

This issue needs to be reproduced - there may be other factors that impact the incidence of this regression.

### Steps To Reproduce
```
-- models/my_model.sql

{{ config(project='custom_project') }}

select 1 as id
```

```
dbt run
```

Confirm that the model was _not_ build into the custom project override

### Expected behavior
The model should be built into the project defined in the `project` config. Database-specific aliases should applied to config names.

### System information
**Which database are you using dbt with?**
- [x] bigquery

**The output of `dbt --version`:**
```
0.17.0
```

**The operating system you're using:** Windows
**The output of `python --version`:** Unknown

**Comment by beckjake** [comment]
I can reproduce this in a test.
