### ISSUE TITLE
dbt run gives different output than running with DataGrip

### ISSUE THREAD

**Issue by rbval** [fishtown-analytics/dbt#2573]
Running my sql with DataGrip gives the correct timestamps:
![image](https://user-images.githubusercontent.com/6399810/85127066-63785f80-b237-11ea-87ba-1510f5a0fa23.png)

Running the same sql with `dbt run` gives everything 3 hour earlier:
![image](https://user-images.githubusercontent.com/6399810/85126924-201df100-b237-11ea-8822-b2e051100342.png)

I have my database in UTC, timestamps in UTC, DataGrip in UTC. I can't seem to figure out why the sql ran by dbt doesn't land as UTC. Is there a way to explicitly configure that?

**Comment by jtcohen6** [comment]
@rbval DataGrip and dbt are both tools that run exactly the SQL you tell them to. Any discrepancy here is going to be the result of:
* running different SQL between the different tools
* DataGrip trying to convert the timezone of timestamps it shows you in its UI

I think we'll need a little more context to figure out what's amiss here:
* Which database are you using?
* What is the exact SQL expression that defines `yearly_timestamp`?
* Which non-UTC timezones do you regularly encounter, if any?
