### ISSUE TITLE
Support for custom types in PostgreSQL

### ISSUE THREAD

**Issue by sgoley** [fishtown-analytics/dbt#2619]
### Describe the feature
Support for object types in Postgresql

Example: 
`create type prod.log_level as enum ('error', 'warn', 'debug', 'info');`

### Describe alternatives you've considered

Currently the only way to work this is with a cast to text type column

### Additional context

Postgresqlspecific feature:
https://www.postgresql.org/docs/12/sql-createtype.html

### Who will this benefit?
I'd like to perform additional validation and even tests based around specific custom type values. Etc.
This is relatively low priority since it only impacts data warehouses built in true postgresql.

**Comment by jtcohen6** [comment]
@sgoley Interesting idea! I think this is totally possible with existing dbt functionality.

If I understand correctly, you could code up a macro to template out the `create type` DDL, and call it in a [hook or operation](https://docs.getdbt.com/docs/building-a-dbt-project/hooks-operations/).

I'm going to close this issue, but feel free to re-open if you have a specific dbt code change in mind.

**Comment by sgoley** [comment]
@jtcohen6 What would be the appropriate way to contribute this if I was able to successfully develop it?

I was thinking this was something that should be contributed to this document:
https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/plugins/postgres/dbt/include/postgres/macros/adapters.sql ? 

Thanks.

**Comment by jtcohen6** [comment]
Got it. The functions in that file are:
1. Building blocks that dbt needs to execute its standard behavior (creating schemas, tables, views, etc).
2. Postgres-specific implementations of those core building blocks (hence the `postgres__` prefix), with the expectation that [other](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/plugins/redshift/dbt/include/redshift/macros/adapters.sql) [databases](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/plugins/snowflake/dbt/include/snowflake/macros/adapters.sql) [implement](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/plugins/bigquery/dbt/include/bigquery/macros/adapters.sql) the same functionality differently.

I don't see a hypothetical `create_type` macro fitting those criteria:
1. Not an essential building block for standard dbt behavior
2. Unique to Postgres (as far as I'm aware)

That is to say, it's an _additive_ feature. You should absolutely leverage a custom macro/hook/operation in your own project, and you don't need to wait for a dbt code change to do so.

If, after writing that macro in your own project, you want to open source your work, here are two places I could imagine:
* A package for Postgres-specific functionality, e.g. `postgres-utils` (a la [snowflake-utils](https://hub.getdbt.com/montreal-analytics/snowflake_utils/latest/)). I don't think such a package exists yet.
* Written up in a [Discourse post](https://discourse.getdbt.com/)!

The package-based approach makes sense if the code powering your macro is so tangled that users would want to install and run it directly, without needing to copy-paste, alter, or deeply understand the code.

As it is, I don't think that applies here; I think the code for this macro would be quite concise. What's much more interesting is the context and strategy surrounding this: When would you want to leverage custom types in Postgres? What does it get you, what are the trade-offs?

**Comment by sgoley** [comment]
Thanks Jeremy - Going to give it my best shot!
https://github.com/sgoley/dbt-postgres-utils
