### ISSUE TITLE
RPC methods should exclude Jinja comments from compiled SQL

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2621]
### Describe the bug

The `compile_sql` and `run_sql` methods of `dbt rpc` currently include Jinja comments `{# #}` in their compiled SQL.

### Steps To Reproduce

1. Run an RPC server per [docs](https://docs.getdbt.com/reference/commands/rpc/)

2. Send a request (method `compile_sql` or `run_sql`) where the SQL contains a Jinja comment
```json
{
    "jsonrpc": "2.0",
    "method": "compile_sql",
    "id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d",
    "params": {
        "timeout": 60,
        "sql": "c2VsZWN0IHsjIDEgKyAxICN9IGFzIGlkCg==",
        "name": "my_first_query"
    }
}
```

3. Poll for result
```json
...
"raw_sql": "select {# 1 + 1 #} as id\n",
"compiled_sql": "select {# 1 + 1 #} as id\n",
...
```

### Expected behavior
```json
"raw_sql": "select {# 1 + 1 #} as id\n",
"compiled_sql": "select  as id\n",
```

**The output of `dbt --version`:**
```bash
$ dbt --version
installed version: 0.17.1-rc4
   latest version: 0.17.0

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.17.1rc4
  - snowflake: 0.17.1rc4
  - redshift: 0.17.1rc4
  - postgres: 0.17.1rc4
```

**Comment by beckjake** [comment]
I missed this until just now, but this is in fact the same as #2707 - closing as it's fixed by #2718
