### ISSUE TITLE
Regression in accepted_values quote behavior on Postgres & Snowflake

### ISSUE THREAD

**Issue by norton120** [fishtown-analytics/dbt#2626]
### Describe the bug
as recent as v0.16.1  `quote:` property in accepted_values schema tests would determine the _outermost_ quote for a given value. So: 

``` 
tests:
    - accepted_values:
          values: ['`BIGQUERY`','"SNOWFLAKE"','"postgres"']
          quote: true
```
would compile to  

```
where value_field not in (
    '`BIGQUERY`','"SNOWFLAKE"','"postgres"'
)
```
With 0.17.0 the same schema.yml compiles to:

```
where value_field not in (
    '`BIGQUERY`','SNOWFLAKE','postgres'
)
```

### Steps To Reproduce
With dbt 0.17.0 use nested quotes and set `quote: true` for an accepted_values test. The result in Snowflake and Postgres will only respect the outer quotes. This does not appear to impact backticks in BigQuery.

### Expected behavior
`quote: true` determines if the value is wrapped as a literal, without impacting the internal values of the string.

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [x] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
tested in 0.16.0, 0.16.1, and now failing in 0.17.0

**The operating system you're using:**
Debian (python:3.7 docker image)

**The output of `python --version`:**
Python 3.7.8 
(dockerfile [here](https://github.com/Health-Union/dbt-xdb/blob/master/Dockerfile))

**Comment by jtcohen6** [comment]
Thanks for the writeup @norton120. You're right that this is a regression in v0.17.0.

I'm hopeful that this will be resolved by the rollback of by-default native env rendering in 0.17.1 ([related discourse](https://discourse.getdbt.com/t/coming-soon-v0-17-1/1406)). Would you be able to try running with the release candidate `v0.17.1-rc4`?

**Comment by norton120** [comment]
Can do, I'll try pinning it up tomorrow and report back

**Comment by norton120** [comment]
Looks like `v0.17.1-rc4` solves the problem in PG, Snowflake, and BigQuery! happily closing dis.
