### ISSUE TITLE
Enable snowflake-connector-python debug logging with environment variables

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2633]
### Describe the feature
dbt should support an environment variable to enable debug logging for the `snowflake-connector-python` library. This will help dbt users track down issues that arise like:
```
Apache Arrow format is not supported
```

Snowflake support requires these logs to diagnose and resolve issues that occur using their platform.

### Describe alternatives you've considered
We could enable these logs by default. `snowflake-connector-python` debug logs are pretty verbose though, so it might be wise to restrict this logging behind an env var.

### Additional context
Relevant to intermittent errors like `The result set in Apache Arrow format is not supported for the platform.`

### Who will this benefit?
Snowflake users; snowflake support

**Comment by jtcohen6** [comment]
Closed by #2635
