### ISSUE TITLE
Option to move the written files (target/*, logs/*, dbt_modules/*) out of the source tree

### ISSUE THREAD

**Issue by TjrGithub** [fishtown-analytics/dbt#2636]
### Describe the feature
I would love to have an option to move all the files DBT write to, out of the project's source tree.

### Describe alternatives you've considered
I'm working inside Docker, with the source directory shared between host (for easy dev access) and container (for testing).
I've tried mounting a separate docker volume onto the dbt/target directory, but docker-compose does not support nested mount points. Writing by DBT gives all kinds of user and permissions mismatch problems, in a bind-mount intended to be read-only.
I've also tried symlinks, but that is hacking around DBT and risks breakign with each upgrade.

### Additional context
It's not database-specific.

### Who will this benefit?
Anybody who is developing (and testing) a dockerized DBT application

### Are you interested in contributing this feature?
Sorry, please don't wait for me in this respect.

Issue #2617 (splitting log directories) may or may not be closed by the same fix.

**Comment by TjrGithub** [comment]
Also, I'd like an idiomatic way to install DBT and its modules in the Dockerfile, without rebuilding everything if the rest of the code tree changes. That means both packages.yml and profiles.yml should live in a separate subdirectory, and still work if the rest of the source tree does not get copied into the Dockerfile before running dbt deps.

**Comment by jtcohen6** [comment]
@TjrGithub Thanks for the writeup. I want to clarify what you're after, because I think some of it is possible in dbt today.

All three of [`target-path`](https://docs.getdbt.com/reference/project-configs/target-path/), [`modules-path`](https://docs.getdbt.com/reference/project-configs/modules-path/), and [`log-path`](https://docs.getdbt.com/reference/project-configs/log-path/) will accept any relative or absolute directory path.

So in `dbt_project.yml` you can have:

```yml
target-path: ".../other_target"
```
Or:
```yml
target-path: "/Users/me/any/file/path/target"
```

Does that get you what you need from a Docker deployment perspective?

**Comment by TjrGithub** [comment]
There are no log-path nor modules-path in the example dbt_project.yml generated by "dbt init", so I assumed it wasn't possible.

Now I have a Rube Goldberg system of symlinks.

**Comment by jtcohen6** [comment]
Got it—best to always check docs.getdbt.com! We don't want to overwhelm people with more case-specific configurations in the starter project.

I'm going to close this issue, but feel free to re-open if there's a specific change to existing functionality that you need to get this working.
