### ISSUE TITLE
catalog.json file empty when custom schema names used

### ISSUE THREAD

**Issue by Plamen8780** [fishtown-analytics/dbt#2653]
https://github.com/fishtown-analytics/dbt/blob/3ec911b62c736e7b5ae26e624b9a981dc3fb177f/plugins/redshift/dbt/include/redshift/macros/catalog.sql#L46
The line above does not take into account custom schema names and it always refers to the default schema name.
This results in an empty catalog.json file whenever the target uses custom schema names.
This issue appeared first appeared in v.0.17.0

**Comment by jtcohen6** [comment]
Thanks for raising this! The straightforward solution here should be to include all `schemas` in the filter, along the lines of the approach we take in postgres:
https://github.com/fishtown-analytics/dbt/blob/5b40cc4a01d1ce3ef06e60d70bc7d293cd193855/plugins/postgres/dbt/include/postgres/macros/catalog.sql#L33-L37

We'll try to get this in for 0.17.2.

**Comment by jtcohen6** [comment]
Closed by #2654
