### ISSUE TITLE
JSON artifact updates

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2671]
### Describe the feature
There are a number of changes we should make to dbt's JSON artifact outputs to make some new features easier to develop:
- We should combine the various SQL fields in the manifest. I can see some value in the `raw_sql` field existing, but we should change `injected_sql` to overwrite `compiled_sql` instead of adding a new field.
- Include the dbt version that produced JSON artifacts.
- Include the `invocation_id` in produced JSON artifacts.
- Accept a `run_id` as an environment variable and include that in produced JSON artifacts.
- All output artifacts should have common metadata

On the behavior side of things, dbt should write compiled manifests at the end of the dbt run. Currently we only write a compiled manifest after running the internal compilation phase in `dbt docs generate`.

### Describe alternatives you've considered
Status quo

### Who will this benefit?
Consumers of dbt's JSON files.

**Comment by beckjake** [comment]
I've split this into separate issues, except for the dbt version part, which is already captured in #2670

**Comment by jtcohen6** [comment]
Resolved!
