### ISSUE TITLE
reopen: pip-compile DBT requires contradictory packages #2674

### ISSUE THREAD

**Issue by TjrGithub** [fishtown-analytics/dbt#2676]
A new bug because I don't have the permissions to reopen #2674. I've got it reproduced as requested - the detailed steps are at https://github.com/jazzband/pip-tools/issues/1196. Would you please verify that this is indeed not a DBT bug? Thank you.

**Comment by jtcohen6** [comment]
I see your comment on that issue:
> `# bug disappears without psycopg2`

That may be it. By default, dbt requires [psycopg2-binary](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/plugins/postgres/setup.py#L32), though this behavior can be overridden via an environment variable (`DBT_PSYCOPG2_NAME`). You can read about our rationale for that behavior [here](https://github.com/fishtown-analytics/dbt/issues/1221#issuecomment-511546464). It may well be that `pip-compile` cannot reconcile `psycopg2` and `psycopg2-binary` dependencies.

In any case, this isn't a bug in dbt or a behavior that we're going to change. While we are committed to `pip install dbt` working properly, we can't make any guarantees about third-party software like `pip-compile`.
