### ISSUE TITLE
Expose state and defer arguments to RPC run method

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2678]
### Describe the feature
The new `--state` and `--defer` arguments are available via the CLI and the environment, but aren't available to RPC `run` method. It should be!

We should also add tests for using it via the RPC server - it happens to work for `cli_args` now, but that's just because of how that method handles arguments.

### Describe alternatives you've considered
`cli_args` works with `--state` and `--defer`, so you can use that.

### Who will this benefit?
RPC users.

**Comment by jtcohen6** [comment]
Resolved by #2736
