### ISSUE TITLE
track deprecations

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2688]
### Describe the feature
Currently, dbt tracks anonymized information about a few metrics on dbt runs (package installs, invocations, running models, ...). It would be nice to add tracking around deprecation warnings triggering.

As a dbt developer, I'd like to know how many people are using deprecated behavior so we can inform our decision making on when to remove it.

### Describe alternatives you've considered
Right now we guess about it.

### Who will this benefit?
Anyone making product/feature decisions.

**Comment by jtcohen6** [comment]
I agree this is valuable, especially as we look to make good on deprecating some long-overdue things.

I think there are two viable Snowplow implementations:

1. Structured event, one per distinct deprecation:
category: 'dbt'
action: 'deprecation'
label: [named deprecation, per [this list](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/core/dbt/deprecations.py#L165-L173)]

2. Unstructured event, fired once per invocation, containing all `active_deprecations` as an array. We can flatten it in the database. I think that would require a new custom context, though.

I lean toward the latter, though I know it's more setup. @drewbanin Do you have a preference either way?

**Comment by drewbanin** [comment]
yep - let's do it. I'd like to make an unstructured event with a single field in it's schema for the deprecation name. I think this is a more sustainable long-term approach than using a bunch of untyped structured events. If there are multiple deprecation warnings in a run, we should just fire one event per deprecation IMO!
