### ISSUE TITLE
Support CopyJobs in BigQuery via a macro 

### ISSUE THREAD

**Issue by kconvey** [fishtown-analytics/dbt#2696]
### Describe the feature
Support a `copy_table` macro in BigQuery, which takes advantage of BigQuery's [CopyJob](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.CopyJob.html) which is better optimized than, for instance `select * {{source('my_source')}}`.

The write disposition on the resulting table can be either `append` or `truncate` corresponding to materializations of `incremental` or `table` here, depending on how you want to modify the resulting table.

This should look like the following in a model:

```
{{ config(materialized='table') }}

{{ copy_table(ref('my_table')) }}
``` 

### Describe alternatives you've considered
Just use `select *` here.

### Additional context
Only interested in BigQuery for this issue, but if there are analogous features in other databases, they can be implemented as well, and possible this can become a global macro.

### Who will this benefit?
Any BigQuery users who have step(s) in their SQL pipeline which simply copy data (ex. a release step, or curation that may leave some tables unchanged)

### Are you interested in contributing this feature?
I have already written this and maintained it as a patch on a fork of dbt, but would love to upstream & share with anyone who can take advantage.

**Comment by jtcohen6** [comment]
Thanks for the issue @kconvey, I'm supportive of adding this as an adapter method for BigQuery. I completely agree that it should take a relation as its argument. I imagine there should also be a check to confirm that the relation exists as a table (as opposed to a view or ephemeral model).

I'd be curious to hear a little more about the ways in which this is better optimized than `select * from table`, if you know them. I couldn't find anything after briefly checking the docs.

I think the closest comparable feature in another database is zero-copy cloning on Snowflake. The two feel different enough that we shouldn't try to implement them as adapter-specific versions of the same macro. (Also, Snowflake has a DDL interface for cloning, so it doesn't _need_ to be an adapter macro.)

**Comment by kconvey** [comment]
+1 to checking that the relation is `table` or `incremental`. 

I don't know of any specific BigQuery implementation details that make `copy_table` taster than `select * from table`, but several months back I found it was a bit better when trying to speed up a pipeline which had an initial model that was a massive copy step, from which all other models derived. The pipeline also was originally written in python (before conversion to dbt), and included both BQ sql jobs and copy jobs at various points, so it was useful to have this feature parity in our fork of dbt when convincing the pipeline owners to switch to dbt.

Going to create a PR for this. Thanks for the triage!
