### ISSUE TITLE
Redshift table size estimates gigabytes as kilobytes.

### ISSUE THREAD

**Issue by vogt4nick** [fishtown-analytics/dbt#2702]
### Describe the bug

The data catalog offers a feature to estimate table size. For Redshift tables, this estimate reports GB as KB.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/31822672/90257543-52059b00-de15-11ea-97cc-d5441d504697.png">

I can verify this references a table that is 44 GB, not 44 KB. 

https://github.com/fishtown-analytics/dbt/blob/03010ecde71634d11f80949018c39a63070f1008/plugins/redshift/dbt/include/redshift/macros/catalog.sql#L150

The problem behavior appears to be in this line of code where the bytes are divided by 1e6.

### Steps To Reproduce

AFAICT this bug is created by adding a Redshift table to dbt and building the data catalog.

### Expected behavior

It should report the correct estimate.

### Screenshots and log output

<img width="362" alt="image" src="https://user-images.githubusercontent.com/31822672/90257543-52059b00-de15-11ea-97cc-d5441d504697.png">

I can verify this references a table that is 44 GB, not 44 KB. 

### System information

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```
installed version: 0.17.2
   latest version: 0.17.2

Up to date!

Plugins:
  - postgres: 0.17.2
  - redshift: 0.17.2
  - snowflake: 0.17.2
  - bigquery: 0.17.2
```

**The operating system you're using:** Docs are built with Docker image `python:3.7.7-slim-buster`. Docs are served with Docker image `nginx:1.19.0-alpine`.

**The output of `python --version`:** 3.7.7

### Additional context

https://github.com/fishtown-analytics/dbt/blob/fb8065df2711d5f5978865a45cc0725a06e670f1/core/dbt/utils.py#L445

Noting because it's related: I'm reasonably confident the issue is not in the `format_bytes` usage.

**Comment by jtcohen6** [comment]
Nice catch! Thanks for opening the PR as well. I'll take a look now.

**Comment by vogt4nick** [comment]
I minor update: 

https://github.com/fishtown-analytics/dbt/blob/03010ecde71634d11f80949018c39a63070f1008/plugins/redshift/dbt/include/redshift/macros/catalog.sql#L150

> The problem behavior appears to be in this line of code where the **mega**bytes are divided by 1e6.

Correction is to multiply by 1e6, not to remove the arithmetic entirely.
