### ISSUE TITLE
Add last modified info to catalog for snowflake

### ISSUE THREAD

**Issue by Mr-Nobody99** [fishtown-analytics/dbt#2728]
### Describe the feature
Currently when connecting to Snowflake db's the catalog.sql is querying for Row count, Approximate size, and clustering key. It would be nice if last modified info was included as well, then it could show up in the docs site as well.

### Describe alternatives you've considered
I originally thought this could be done by modifying the dbt-docs source, however I realized the info needed to exist in the docs artifacts somewhere for it to be accessible.

### Additional context
This feature would be database specific for Snowflake, at least it would be as I would implement it currently. With Snowflake specifically having the information schema, which has the last_altered column readily available it would be a rather simple change. I'm am sure there are other ways to make the same idea work with other databases however.

### Who will this benefit?
This would primarily benefit anyone who would like another useful bit of documentation, in an easily accessible and intuitive way.

### Are you interested in contributing this feature?
I am interested in contributing this feature, I have already made the changes locally and tested with them and it works as intended.

**Comment by jtcohen6** [comment]
Sure! I'm on board with this. After quickly checking the Redshift and Bigquery docs, I think `last_altered` is indeed unique to Snowflake.

The trickiness I can anticipate is around timezones. It looks from Snowflake's docs like `last_altered` is in `timestamp_ltz`. Should we assume that the Snowflake account-level local timezone is the timezone we want to display for all dbt-docs viewers? I think we'll want to either include the timezone in dbt-docs, somehow, or standardize to UTC.

**Comment by Mr-Nobody99** [comment]
@jtcohen6 Glad to hear it, and that is a good point about the time-zone. I think there may be 2 ways to handle that one being in the sql changes the other being some "post-processing" in the dbt-docs code for loading the docs artifacts(should be in the project service for loading catalog i'd think.) I will go ahead and create a pull request with what the implementation as I have it now, and maybe you can look at it and tell me what you think would be best.
