### ISSUE TITLE
Cannot bring up postgresql when running make test-unit

### ISSUE THREAD

**Issue by heisencoder** [fishtown-analytics/dbt#2738]
### Describe the bug
I'm following the instructions in `contributing.md` to get a local dbt development setup, and am running into the following error:

```
$ make test-unit
Unit test run starting...
Creating fishtown-dbt_database_1 ... 
Creating fishtown-dbt_database_1 ... error

ERROR: for fishtown-dbt_database_1  Cannot start service database: driver failed programming external connectivity on endpoint fishtown-dbt_database_1 (7e47771a8eca024021670590bc830ca4009cbc09a20294043ccf38127a917c1c): Bind for 0.0.0.0:5432 failed: port is already allocated

ERROR: for database  Cannot start service database: driver failed programming external connectivity on endpoint fishtown-dbt_database_1 (7e47771a8eca024021670590bc830ca4009cbc09a20294043ccf38127a917c1c): Bind for 0.0.0.0:5432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Command exited with non-zero status 1
0.54user 0.05system 0:00.85elapsed 69%CPU (0avgtext+0avgdata 56204maxresident)k
0inputs+0outputs (0major+14387minor)pagefaults 0swaps
make: *** [Makefile:14: test-unit] Error 1
```

### Steps To Reproduce
* Follow instructions in `CONTRIBUTING.md`:
  * Install the recommended tools, including postgres, docker-compose
  * Create a venv: `python3 -m venv env && source env/bin/activate`
 * Run `make test-unit`

### Expected behavior
The unit tests to run against a local postgres instance.

### System information
**Which database are you using dbt with?**
- [x] postgres

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.18.0-rc1
   latest version: 0.17.2

Your version of dbt is ahead of the latest release!

Plugins:
  - postgres: 0.18.0rc1
  - redshift: 0.18.0rc1
  - snowflake: 0.18.0rc1
  - bigquery: 0.18.0rc1
```

**The operating system you're using:**
Debian 10

**The output of `python --version`:**
Python 3.8.5

### Additional context

This error was caused because I already had a postgres instance running in docker.  I ran the following commands to find and close the previous instance:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
7ede2de7c867        postgres            "docker-entrypoint.s…"   17 hours ago        Up 17 hours         0.0.0.0:5432->5432/tcp   dbt_database_1
(env) 

$ docker stop 7ede2de7c867
7ede2de7c867
```

**Comment by jtcohen6** [comment]
@heisencoder Did you mean to close this?

**Comment by heisencoder** [comment]
I meant to open this for others who run into the same issue, but found that the solution is to bring down the existing postgres database, so no action is needed until it is to update the docs to mention this possible failure mode.

**Comment by jtcohen6** [comment]
Got it! I think that's the right approach. Thanks for the thoughtfulness :)

**Comment by heisencoder** [comment]
Actually, I just tried the setup guide again on a fresh computer, and ran into this same issue, but there wasn't an existing docker process running:  

```$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

What I discovered is that port 5432 is the default postgres port, and that when I originally installed postgres a while back, it automatically brings up a server on port 5432 (probably on reboot).  dbt test needs postgres to run in a docker image with test credentials, so there's port contention.

I can bring down the existing postgres server with these commands (although I'll probably have to re-run them after a reboot):

Find existing postgres servers: 

```
$ pg_lsclusters
Ver Cluster Port Status Owner    Data directory              Log file
10  main    5432 online postgres /var/lib/postgresql/10/main /var/log/postgresql/postgresql-10-main.log
11  main    5433 online postgres /var/lib/postgresql/11/main /var/log/postgresql/postgresql-11-main.log
12  main    5434 down   postgres /var/lib/postgresql/12/main /var/log/postgresql/postgresql-12-main.log
```

Shut down the postgres server with the conflicting port.  For example:

```
$ sudo pg_ctlcluster 10 main stop
```

Verify that it stopped:

```
$ pg_lsclusters
Ver Cluster Port Status Owner    Data directory              Log file
10  main    5432 down   postgres /var/lib/postgresql/10/main /var/log/postgresql/postgresql-10-main.log
11  main    5433 online postgres /var/lib/postgresql/11/main /var/log/postgresql/postgresql-11-main.log
12  main    5434 down   postgres /var/lib/postgresql/12/main /var/log/postgresql/postgresql-12-main.log
```

So, overall, I think to avoid contention with default PostgreSQL installs, dbt tests should pick a different port than 5432.  This could be accomplished by doing a global search-and-replace of 5432 with something else (maybe a random number between 17008 and 49151, which would be an unused Registered Port).

**Comment by jtcohen6** [comment]
> So, overall, I think to avoid contention with default PostgreSQL installs, dbt tests should pick a different port than 5432.

This seems reasonable to me! Is this a change you'd be interested in contributing @heisencoder?

**Comment by heisencoder** [comment]
No problem!  It's a straightforward change for the search-and-replace.  My
only concern would be if the GitHub actions are already expecting a
Postgres database running on port 5432.  However, it looks like a new
Postgres instance is brought up each time, so I'm guessing it won't be a
concern.

**Comment by heisencoder** [comment]
I did the search-and-replace of the port number, but now I can't get docker-compose to bring up Postgres on any port other than 5432.  At this point, I'm in favor of just leaving this bug as a breadcrumb for others who run into the same issue and closing it.
