### ISSUE TITLE
dbt as a query generator

### ISSUE THREAD

**Issue by fabrice-etanchaud** [fishtown-analytics/dbt#2771]
### Describe the feature

Given a dbt project with models layered in sources, staging and business levels; given an analysis built ontop the business models. I would need to compile the analysis down to the sources' models, using dbt as a super query generator, building queries I can then play on the backends.

### Describe alternatives you've considered

I suspect a simple solution is to change all materialized configurations to `cte` - provided that no intermediate models is calling get_columns_in_relation - and compile my analysis.
Is it possible to override a configuration parameter for all models ? The usual behavior is that configuration at a deeper level will override configuration made before. I thought I could  create a macro like generate_materialized_conf(custom_materialized_conf) that override the custom_materialization with `cte` then target.name is something like `query_builder`, and use this macro to configure the materialization instead of a static string like `table` or `view`.

### Additional context

Trying to change an ETL hell in a engineered analytics paradise.

Not database specific.

### Who will this benefit?

All dbt's lovers who face others' relunctancy in dbt's adoption, as a way to prove the correctness of the solution.

### Are you interested in contributing this feature?

Yes!

**Comment by jtcohen6** [comment]
Oh boy! Honestly, I could see this being very useful, but it's hacky enough that I don't think we'd want to support it as a native dbt feature. That said, it should be simple enough to put this together with existing functionality.

> provided that no intermediate models is calling get_columns_in_relation

This is the crucial caveat—ephemeral models should work well enough for vanilla dbt modeling, but they don't support several patterns enabled by adapter + dbt-utils macros.

> Is it possible to override a configuration parameter for all models ? The usual behavior is that configuration at a deeper level will override configuration made before.

Correct. If you just tried setting top-level config in `dbt_project.yml`:
```yml
models:
  my_project:
    +materialized: "{{ 'ephemeral' if var('generate_super_query', false) else 'none' | as_native }}"
```
This would work for many of your models, but it wouldn't work for models that more tightly specify their materializations with in-file `config()`.

> I thought I could create a macro like generate_materialized_conf(custom_materialized_conf)

I think this is the right track, loosely inspired by `generate_x_name` macros for database/schema/alias. Imagine a macro like:
```
{% macro generate_materialized_conf(custom_materialized_conf=none) %}
    {% if var('generate_super_query', false) %}
      {{ return('ephemeral') }}
    {% elif custom_materialized_conf %}
      {{ return('custom_materialized_conf') }}
    {% else %}
      {{ return(none) }}
    {% endif %}
{% endmacro %}
```
Any time you set a materialization via an in-model `config()` block, you'd need to specify it as:
```sql
{{ config(
    materialized = generate_materialized_conf('table')
}}
```

Combined with the top-level config in the project file, that just might work!

I'm going to close this issue, as I don't think it requires a code change to dbt itself, but happy to keep thinking through the options available.

**Comment by fabrice-etanchaud** [comment]
Thank you Jeremy for your feedback.
I thought about this 

> "Configurations made in your dbt_project.yml file will override any configurations in a package (either in the dbt_project.yml file of the package, or in config blocks)."

: [configuring-packages](https://docs.getdbt.com/docs/building-a-dbt-project/package-management/#configuring-packages)

So, if I create a new project, reference my 'business universe' project and override the materialized configuration as stated, maybe that could do the trick ? I will tell if that works. 

Thanks again !

**Comment by jtcohen6** [comment]
Now that's clever thinking!
