### ISSUE TITLE
gain access to profile's name, for example in the target context ?

### ISSUE THREAD

**Issue by fabrice-etanchaud** [fishtown-analytics/dbt#2772]
### Describe the feature

To my understanding, target.name is used to distinguish between managed (prod,preprod) and unmanaged (devs) environments.
Using dbt ontop a federation tool, I can potentially manage all my environments in the same place. not in terms of un/managed, but as a way to group resources (input sources, target collections...) by environment.

I thought about using the profile's name, but I dit not find how to access it for example in the generate_XXXX_name macros.
Could it be possible to have access to the profile's name for example in the target context ?

### Describe alternatives you've considered

I added an extra `environment` attribute to my adapter credentials, but imho it's a disguised profile's name...

### Additional context

Maybe dremio related ?

### Who will this benefit?

me...

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

Yes !

**Comment by jtcohen6** [comment]
If I understand you correctly, @fabrice-etanchaud, you'd like `profile_name` to be a value exposed in dbt's Jinja context? Similar to how (e.g.) [`target`](https://docs.getdbt.com/reference/dbt-jinja-functions/target/) and [`project_name`](https://docs.getdbt.com/reference/dbt-jinja-functions/project_name/) are accessible today.

In the meantime, I could _probably_ argue that you could _probably_ accomplish any + all env-aware logic with just `target.name`. I think what you're asking for is reasonable and doable, but all the same I'd be curious to know a little more about your use case / deployment / how Dremio works (?) to understand exactly what this gets you.

**Comment by fabrice-etanchaud** [comment]
As a 'mature' ;-) organization, my employer - a life insurance company - has several software environments, preproduction, production and at least one for each current project (as there are software developments, but many human validations). Each environment has its own source's versions that dbt should select correctly. And for each of these environments, I would also like dbt to switch seemlessly from managed (read from the environment sources, write on the managed dremio's space) to unmanaged (read from the environment sources, write on developer's home space). 

imho it would be logical for dbt to find all the required configuration in the profile. So if target is used to switch from managed to unmanaged behavior, I would need an extra configuration parameter to set the environment (the prefix to apply on sources' databases) independently. I thought profile_name could do the trick. I ended up adding a extra environment credential parameter.

But you are right I can use target.name as a composite key containing both environnement name and managed/unmanaged flag, and split it when needed (in the get database/schema name functions and when prefixing source's databases.

Does that make sense to you ? I will be glad to have your feeling about that !

**Comment by fabrice-etanchaud** [comment]
Thank you @beckjake , yes, it worked !

**Comment by jtcohen6** [comment]
@beckjake Very nice. Is there any reason we shouldn't document that?

**Comment by beckjake** [comment]
@jtcohen6 I can't think of one.
