### ISSUE TITLE
Rename `reports` to `exposures`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2777]
### Describe the feature
We've had several conversations internally since #2730. While concrete, `report` names only a subset of the intended functionality of the new node type. We're going back to the original name, `exposure`, because:
- it accords with the intended superset of use cases
- it better communicates to dbt developers the _why_ of this feature

### Describe alternatives you've considered
Other names we considered:
- interfaces: good, but too vague/broad. This is a word we use often when training and talking about dbt, e.g. the way it interfaces with different databases.
- contracts: good; related but slightly different. Each dbt model might have its own contract; that one model could be _exposed_ in different ways, however, in different downstream dashboards/reports/notebooks/applications.

### Additional context

All functionality is identical. The only proposed change is replacing all instances of `report(s)` with `exposure(s)`.

Future functional changes to the `exposures` node, out of scope here:
- Add support for `tags`, such that `dbt ls -s tag:common_tag` will return all sources, models, tests, _and_ exposures that have `common_tag`

### Who will this benefit?
Names are important, naming things is hard. We want to be using the best words we can when it's time to put this in front of dbt developers.

**Comment by beckjake** [comment]
Fixed in core with #2780
