### ISSUE TITLE
dbt test [--models|--exclude] config.materialized:view does not seem to work

### ISSUE THREAD

**Issue by tpilewicz** [fishtown-analytics/dbt#2806]
### Describe the bug
I tried to run `dbt test --exclude config.materialized:view`, and got the output "Nothing to do". I then tried to run `dbt test --models config.materialized:view`, and all tests ran. Yet `dbt test --models config.materialized:table` runs only 24 models.

### Steps To Reproduce
In a project that has models materialized as a view and others materialized as a table / or `'incremental'` ones, run `dbt test --exclude config.materialized:view`, or `dbt test --models config.materialized:view`.

### Expected behavior
`dbt test --exclude config.materialized:view` should run all models that are not materialized as a view.

`dbt test --models config.materialized:view` should run only models materialized as a view.

### Screenshots and log output
```
$ dbt test --exclude config.materialized:view
Running with dbt=0.18.0
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_utils
 - redshift

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0

* Deprecation Warning: The "adapter_macro" macro has been deprecated. Instead,
use the `adapter.dispatch` method to find a macro and call the result.
adapter_macro was called for: dbt_utils.type_string
Found 198 models, 295 tests, 0 snapshots, 0 analyses, 340 macros, 0 operations, 3 seed files, 0 sources
WARNING: Nothing to do. Try checking your model configs and model specification args
```

Then:

```
$ dbt test --models config.materialized:view
Running with dbt=0.18.0
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_utils
 - redshift

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0

* Deprecation Warning: The "adapter_macro" macro has been deprecated. Instead,
use the `adapter.dispatch` method to find a macro and call the result.
adapter_macro was called for: dbt_utils.type_string
Found 198 models, 295 tests, 0 snapshots, 0 analyses, 340 macros, 0 operations, 3 seed files, 0 sources
14:48:36 | Concurrency: 4 threads (target='staging_dev')
14:48:36 |
14:48:36 | 1 of 295 START test not_null_account_attributes_d_uuid............... [RUN]
...
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.0

Up to date!

Plugins:
  - bigquery: 0.18.0
  - snowflake: 0.18.0
  - redshift: 0.18.0
  - postgres: 0.18.0
```

**The operating system you're using:**
OSX

**The output of `python --version`:**
Python 3.6.8

**Comment by jtcohen6** [comment]
Thanks for the bug report @tpilewicz. You're right, this does not work the way we intended. I believe it's limited to tests and `config.materialized:view` in particular. I have to imagine this is because view is the default materialization type, and because of the wonkier things we do around test selector expansion. I'd love to get this resolved for the next version of dbt.

**Comment by jtcohen6** [comment]
Right now, tests inherit all model `node.config` properties. We should trim those down to only the properties that apply directly to tests. This will also trim noise from the manifest.

There's a larger related conversation about how test selection should work: does it make sense that dbt performs a final "jump" from its `--models` criteria to tests that depend on those models?
