### ISSUE TITLE
compile fewer artifacts for each invocation

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#283]
for large projects, dbt commands take a long time (15s-ish for one project I'm working on). the step that takes a long time is compilation. I believe that every dbt invocation compiles all objects. it would be useful if invocations could only compile the artifacts that are relevant to that invocation—nothing sophisticated like only compiling specific models, more only compiling tests if the command is `test`, etc. could cut the compilation time significantly.

**Comment by drewbanin** [comment]
TODO: re-evaluate timing after this PR is merged https://github.com/analyst-collective/dbt/pull/292
