### ISSUE TITLE
dbt clean does not respect the project-dir if provided

### ISSUE THREAD

**Issue by feluelle** [fishtown-analytics/dbt#2840]
### Describe the bug

If I am not in the project directory and run `dbt clean --project-dir <path>`. DBT won't clean the directories starting from the project directory. It cleans it from the current directory.

### Steps To Reproduce

go out of the project directory and pass the path to directory to the `--project-dir` flag.
```
dbt clean --project-dir <path>
```

### Expected behavior

I expect dbt to clean the directories recursively defined in `clean-targets` of `dbt_project.yml`.

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.18.0
  - snowflake: 0.18.0
  - redshift: 0.18.0
  - postgres: 0.18.0
```

**The operating system you're using:** macOS 10.15.6

**The output of `python --version`:** Python 3.7.2

**Comment by jtcohen6** [comment]
Good find, @feluelle! I'm not sure if this has worked in the past, but I agree it's the intended (and expected) behavior.

I'm hopeful that this would be a straightforward fix, involving the addition of [`move_to_nearest_project_directory`](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/core/dbt/task/base.py#L141) to the [clean task](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/core/dbt/task/clean.py). The contributor should also look to add a test [here](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/test/integration/015_cli_invocation_tests/test_cli_invocation.py#L166).

Is this something you'd be interested in contributing?

**Comment by feluelle** [comment]
Yes, I would love to work on that @jtcohen6 :)
