### ISSUE TITLE
Snowflake dbt test error

### ISSUE THREAD

**Issue by springcoil** [fishtown-analytics/dbt#2861]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
When I run `dbt test` on snowflake I get an error.

```16:44:26 | 1 of 2 START test accepted_values_handshake_tracks_parsed_organization____mindful_affirmations__aflorithmic__audiofunnel [RUN]
16:44:26 | 2 of 2 START test not_null_handshake_tracks_parsed_timestamp......... [RUN]
16:44:28 | 1 of 2 ERROR accepted_values_handshake_tracks_parsed_organization____mindful_affirmations__aflorithmic__audiofunnel [ERROR in 1.98s]
16:44:28 | 2 of 2 ERROR not_null_handshake_tracks_parsed_timestamp.............. [ERROR in 2.08s]
16:44:28 |
16:44:28 | Finished running 2 tests in 3.59s.

Completed with 2 errors and 0 warnings:

Database Error in test accepted_values_handshake_tracks_parsed_organization____mindful_affirmations__aflorithmic__audiofunnel (models/example/schema.yml)
  000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

  compiled SQL at target/compiled/analytics_handshake/models/example/schema.yml/schema_test/accepted_values_handshake_tracks_parsed_6b71fc6578ab3e8fc25252a71ddc89b5.sql

Database Error in test not_null_handshake_tracks_parsed_timestamp (models/example/schema.yml)
  000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

  compiled SQL at target/compiled/analytics_handshake/models/example/schema.yml/schema_test/not_null_handshake_tracks_parsed_timestamp.sql
```
### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Expected behavior
Confused about this expecting tests to run. 
### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ -] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
(base) user@MacBook-Air analytics_handshake % dbt --version
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1

```

**The operating system you're using:**
Mac OS catalina
**The output of `python --version`:**
```Python 3.8.3```
### Additional context
It works with ```dbt run``` just not with ```dbt test```

**Comment by springcoil** [comment]
Hi Fishtown-Analytics/Dbt,
I specify a warehouse in profiles.yml.

Its confusing!

**Comment by springcoil** [comment]
So it seems I was calling the wrong warehouse. I had `load_warehouse` where I needed `LOADWAREHOUSE`

**Comment by lukeclarke** [comment]
I had this same error and I resolved in the end. It was a problem of the user not having the privileges to access the warehouse specified.

Simply, log into Snowflake as the accountadmin and grant the privileges to the role in question.
