### ISSUE TITLE
Investigate deepcopying done during parsing because of performance

### ISSUE THREAD

**Issue by gshank** [fishtown-analytics/dbt#2863]
In a large project we have been profiling, the deepcopying of config consumed 14% of the parsing time. The deepcopying was added to fix issues that developed with executing in multiple threads, where the structures got confused. We should investigate and determine more precisely (if possible) what was causing the data confusion and determine what other options we have for making the data thread safe. Other possibilities are limiting the deepcopying to only those attributes that are causing issues, casting to dictionaries instead of using full copies, and other ways to limit the data to avoid the overhead of deepcopy.

**Comment by jtcohen6** [comment]
@gshank I know that #3034 removed deepcopy from `fqn_search`:
https://github.com/fishtown-analytics/dbt/blob/e5568a111d152e0adb4249cf3fc503919b2308d9/core/dbt/utils.py#L542-L543

What % of total load time is now attributable to deepcopying config, after this first round of improvements?

I'm inclined to close this issue and reopen more targeted ones later on, if/when we find especially slow instances of deepcopying to investigate further.
