### ISSUE TITLE
“materialized” as a cli parameter

### ISSUE THREAD

**Issue by dubravcik** [fishtown-analytics/dbt#2867]
### Describe the feature
add `materialized` as cli parameter for `dbt run` with options for materialization (table, view...). It would overwrite settings from project.yaml and also from a model.sql config.

### Describe alternatives you've considered
We can add conditional materialization based on environment in project.yaml or model config https://discourse.getdbt.com/t/faq-configuring-models-based-on-environments/463 
But one have think about it all the time because explicit config in model.sql will overwrite it.

### Who will this benefit?
Anybody who would like to `dbt run` in test environment  materialized as views and ignore materialize settings in model.sql config.

**Comment by jtcohen6** [comment]
Hey @dubravcik, the traditional approach would look like using a `var` to set the baseline in `dbt_project.yml`:
```yml
models:
  materialized: "{{ var('materialized', 'view') }}"
```

Then if you have specific models that use in-file config blocks to set materializations, and you want to be able to override them:
```sql
{{ config(
    materialized = var('materialized', 'ephemeral')
) }}
```

Finally from the CLI:
```
dbt run --vars 'materialized: table'
```

You would manage to override the materializations of all models which have the `var` provided to their config.

There's another wackier and possibly more effective approach proposed in a similar recent issue (#2771), leveraging [package-level configs](https://docs.getdbt.com/docs/building-a-dbt-project/package-management/#configuring-packages):

> Configurations made in your dbt_project.yml file will override any configurations in a package (either in the dbt_project.yml file of the package, or in config blocks).

So if you import your entire project as a package into another project, then you can just get away with:

```yml
models:
  my_actual_project:
    materialized: "{{ var('materialized', 'view') }}"
```
And override on the CLI as you see fit, without needing to worry about more explicit in-model config.

In any case, I don't think we'd add `materialized` as its own special CLI flag, given all the options available with CLI `vars`.

**Comment by Gonzalo933** [comment]
Does this still work? (using dbt cloud 1.5)

I added 

```
{{
    config(
        materialized=var('materialization', 'view')
    )
}}
```

to my model and then run
`dbt build --vars 'materialization: table' --select my_model`

and it still gets materialized as a view. And if I remove the default value for `materialization` I get an error.
