### ISSUE TITLE
Include database name in "schemas" jinja on-run-end variable

### ISSUE THREAD

**Issue by dmateusp** [fishtown-analytics/dbt#2880]
### Describe the feature

I would like the "[schemas](https://docs.getdbt.com/reference/dbt-jinja-functions/schemas/)" jinja variable, available in the `on-run-end` configuration, to include the database name (e.g. [`my_database.schema_1`, `my_database2.schema2`])

### Additional context
Our project creates schemas in multiple databases

### Who will this benefit?
Folks that want to automate granting permissions to schemas created by DBT, where their project uses multiple databases

**Comment by jtcohen6** [comment]
Hey @dmateusp, check out [`database_schemas`](https://docs.getdbt.com/reference/dbt-jinja-functions/on-run-end-context/#database_schemas)!

**Comment by dmateusp** [comment]
Thanks! I missed it in the docs :(
