### ISSUE TITLE
dbt ls should return a zero exit code when no models are selected

### ISSUE THREAD

**Issue by Limess** [fishtown-analytics/dbt#2886]
### Describe the bug
`dbt ls` returns an exit code of `1` when no models are selected.

### Steps To Reproduce
Run `dbt ls` with a model selector which returns no models, e.g. `my_model,config.materialized:incremental` where `my_model` is not incremental.

### Expected behavior
I'd expect a warning message, and an exit code of `0`. `--warn-error` could be used to opt back in to the current behaviour.

### Log output

```
The selector 'current_concepts+,config.materialized:incremental' does not match any nodes and will be ignored
No nodes selected!
```

JSON (separate run):

```
{"timestamp": "2020-11-12T18:40:54.899662Z", "message": "No nodes selected!", "channel": "dbt", "level": 13, "levelname": "WARNING", "thread_name": "MainThread", "process": 58352, "extra": {"run_state": "internal"}}
```

### System information
**Which database are you using dbt with?**
n/a

**The output of `dbt --version`:**
```
0.18.1
```

**The operating system you're using:**

n/a

**The output of `python --version`:**

n/a

### Additional context

We're using this to programatically inspect the DBT graph and would expect an empty list rather than an error here. An error means we need to either string match against the output or ignore any errors, neither of which are desirable.

Slack thread I raised this in: https://getdbt.slack.com/archives/CJARVS0RY/p1605206141123400

**Comment by jtcohen6** [comment]
Agree! I don't think it makes sense for `dbt ls` to ever return a nonzero exit code.
