### ISSUE TITLE
Variable 'prefix' is out of scope

### ISSUE THREAD

**Issue by tonussi** [fishtown-analytics/dbt#2898]
https://github.com/fishtown-analytics/dbt/blob/5f8efc3aa81479a634c2715a36cc1fcc44010155/core/scripts/create_adapter_plugins.py#L260

Some variable called 'prefix' needs to be declared in the outer scope in order to be seen inside the else scope.

Thank you.

**Comment by jtcohen6** [comment]
@tonussi You're right! Unless I'm missing something major, I think we could just move line 254 up, i.e.

```
if parsed.set_dependency:
        prefix = '\n        '
        if parsed.dependency:
            # ['a', 'b'] => "'a',\n        'b'"; ['a'] -> "'a',"

            parsed.dependency = prefix + prefix.join(
                "'{}',".format(d) for d in parsed.dependency
            )
        else:
            parsed.dependency = prefix + '<INSERT DEPENDENCIES HERE>'
```

Does that look right to you? If so, is it a change you'd be willing to contribute?

**Comment by jtcohen6** [comment]
Closing in favor of https://github.com/fishtown-analytics/docs.getdbt.com/issues/541
