### ISSUE TITLE
Docs blocks don't work in exposures - `'doc' is undefined`

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/dbt#2913]
### Describe the bug
Exposures containing a docs block don't compile in dbt Cloud because doc is undefined. 

### Steps To Reproduce
Create an exposure which references a doc block: 
```
exposures:
  - name: licence_status_stats
    description: '{{ doc("licence_status_stats_descr") }}'
    type: dashboard
...
```

```
{% docs licence_status_stats_descr %}

A high-level answer to the question: _How many students/departments/schools/countries use EP?_
----------------------------------------------------------------------------------------------

You can find the definitions of each licence status [here](https://sites.google.com/educationperfect.com/epeeps-hub/must-read/data-definitions). 

{% enddocs %}
```

### Expected behavior
The docs block to be rendered

### Screenshots and log output
`Compilation Error Failed to render models/exposures/licence_status_stats.yml from project educationperfect: Compilation Error Could not render {{ doc("licence_status_stats_descr") }}: 'doc' is undefined`

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.18.1
```

**The operating system you're using:**
dbt Cloud
**The output of `python --version`:**

**Comment by jtcohen6** [comment]
Nice find @joellabes! This was definitely an oversight for v0.18.1; I imagine the fix to be quite straightforward, and I'd love to get it into v0.19.0.

In particular, I think a prospective contributor may find it fruitful to:

1. Add exposures to the list of documentable resources:
https://github.com/fishtown-analytics/dbt/blob/fec0e31a25d5b922cb1833cffcb5095eb4ee642b/core/dbt/node_types.py#L40-L49

2. Add exposures as a step within `process_docs`, after first defining `_process_docs_for_exposure`, with the existing methods as a helpful guide:
https://github.com/fishtown-analytics/dbt/blob/fec0e31a25d5b922cb1833cffcb5095eb4ee642b/core/dbt/parser/manifest.py#L625-L649

3. After doing those, they may stumble upon a new error message like: `Invalid exposures config... Additional properties are not allowed ('original_file_path', 'package_name', 'yaml_key' were unexpected)`. After some initial trepidation, they may be delighted to learn that they need change only [one more line of code](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/core/dbt/contracts/graph/unparsed.py#L414):
```yml
class UnparsedExposure(HasYamlMetadata, Replaceable):
```

That's just some wild speculation, though :)
