### ISSUE TITLE
Not support mac0S 11.0.

### ISSUE THREAD

**Issue by Kobe-Wang** [fishtown-analytics/dbt#2914]
### Describe the bug

When I install the dbt latest version(0.18.1) in mac0S 11.0. version, I got the error messages as the followings:

```
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
```

### Steps To Reproduce

Run the command as the followings:
```
$ brew install dbt@0.18.1
```

### Expected behavior

Should be installed in macOS 11.0. version.

### Screenshots and log output

```
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
None
```

### Additional context
None

**Comment by jtcohen6** [comment]
Hey @Kobe-Wang, I think this is an issue with Homebrew <> Big Sur, not specific to dbt in any way:
- https://github.com/Homebrew/brew/issues/8797
- https://discourse.brew.sh/t/macos-big-sur-issue/8407

If you do manage to find a compelling resolution, I'd love to hear it here. In the meantime, you may need to install dbt via pip.

**Comment by Kobe-Wang** [comment]
Hi @jtcohen6 , thank you for your reply. I will try to install dbt via pip.

**Comment by Kobe-Wang** [comment]
Hi @jtcohen6 , it works when I change to install dbt via pip. Thank you.
