### ISSUE TITLE
Configurable application connection parameter on Snowflake

### ISSUE THREAD

**Issue by jesusenlanet** [fishtown-analytics/dbt#2916]
My organization is working with several DBT instances that connects to the same snowflake account.

The connection have an `application` parameter right now, hardcoded to `dbt`. 
https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/plugins/snowflake/dbt/adapters/snowflake/connections.py#L211

### Additional context
That parameter can be used only by snowflake partners as described in their documentation (my organization is a snowflake partner):
https://docs.snowflake.com/en/user-guide/odbc-parameters.html#additional-connection-parameters

### Who will this benefit?
If you have several DBT instances working against different databases into an account, you will be able to identify the application that is connected by it connection parameters, right now is `dbt`. 

### Are you interested in contributing this feature?
I'm working in a solution for that, soon I'll ready to push the changes.

**Comment by jtcohen6** [comment]
@jesusenlanet As I understand it, the information passed to the `application` parameter is only accessible to Snowflake, and it's what they use to determine how many of their accounts/users are also usinng dbt. Could you say a bit more about your use case for overriding this value:
- Are you a consultancy using dbt?
- Are you creating software that wraps around dbt?

If you just want the ability to examine query history based on multiple  dbt instance, you could use [query tags](https://docs.getdbt.com/reference/resource-configs/snowflake-configs/#query-tags), or [query comments](https://docs.getdbt.com/reference/project-configs/query-comment/), or filter based on the Snowflake user associated with each dbt instance.

**Comment by jesusenlanet** [comment]
Hi @jtcohen6, the company I'm working for is a Snowflake partner.

We are building software that wraps around DBT, and we want to specify the application that connects (snowflake docs for that parameter) instead of `dbt`, because of that we want to make that parameter configurable, that's not intended to filter queries on the history.

**Comment by jtcohen6** [comment]
@jesusenlanet This is an important input for our partnership with Snowflake, so I don't think we're going to make it user-configurable. As long as you're using the version of `dbt-snowflake` that we maintain, we want to report it as `dbt`.

If this is something you really need, you're well within your rights to fork dbt, or adapt the dbt-snowflake plugin.
