### ISSUE TITLE
dbt-redshift pins an old version of boto3/botocore

### ISSUE THREAD

**Issue by pacificsky** [fishtown-analytics/dbt#2931]
### Describe the bug
With the new dependency resolver in pip 20.3, mismatched dependencies are raised as an error. I spent many hours last night fighting dbt-redshift's [pin of an old version of boto3/botocore](https://github.com/fishtown-analytics/dbt/commit/c6ab6459fb69a6746982b2416f3f26da78f41fec) - it conflicted with the boto3 requirements of other packages we use. 

It looks like this was done to [match the boto3/botocore versions used by snowflake-connector-python](https://github.com/fishtown-analytics/dbt/commit/c6ab6459fb69a6746982b2416f3f26da78f41fec). That project now has a larger range (snowflake-connector-python==2.3.6 depends on boto3<1.16,>=1.4.4), so I suspect it would be safe to bump up the range supported by dbt-redshift as well. 

### Steps To Reproduce
^

### Expected behavior
^

### Screenshots and log output
pip fails to install packages with conflicting boto3/botocore dependencies.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1
```

**The operating system you're using:**
OSX 11.0.1

**The output of `python --version`:**
Python 3.8.2

**Comment by jtcohen6** [comment]
Thanks for this @pacificsky! Agree, let's bump boto3 + botocore to coordinate with the version ranges supported by `snowflake-connector-python==2.3.6`, as bumped by #2922.

Is this a PR you'd be interested in submitting?

**Comment by pacificsky** [comment]
Yeah, happy to do it. Will send out something later tonight.

**Comment by tyang209** [comment]
Also ran into this dependency issue. I'm happy to submit a PR so this doesn't get lost in the shuffle.

**Comment by jtcohen6** [comment]
yes please!
