### ISSUE TITLE
ClickHouse Adapter for DBT

### ISSUE THREAD

**Issue by vintageplayer** [fishtown-analytics/dbt#2947]
### Describe the feature
DBT Adapter for Clickhouse

### Describe alternatives you've considered
NA

### Additional context
The data team in my company (Zeta) actively leverages DBT for their BA and DE workflows. One of our data-services is in the process to setup click house database, and it would be nice to have a DBT adapter for it as well.

### Who will this benefit?
This will benefit anyone already using clickhouse, or comfortable with DBT and wants a wider set of database options.

### Are you interested in contributing this feature?
I have read through the guide on writing your own adapter and would like to contribute the same here once done. Would request for your help in reviewing once it's created, or in case I'm stuck implementing a particular aspect of the adapter.

**Comment by jtcohen6** [comment]
Hey @vintageplayer, very cool to hear that you're thinking about building a Clickhouse adapter!

The docs on [building a new adapter](https://docs.getdbt.com/docs/contributing/building-a-new-adapter) are definitely the place to start, and you can use the `create_adapter_plugins.py` script for the initial scaffolding.

I also recommend that you check out [dbt-spark](https://github.com/fishtown-analytics/dbt-spark), [dbt-presto](https://github.com/fishtown-analytics/dbt-presto), and the other [community-maintained adapter plugins](https://docs.getdbt.com/docs/supported-databases/#community-plugins) to see how they've handled issued ranging from:
- different connection methods
- different namespaces (e.g. no separation of schema/database)
- needing to reimplement or override core behavior

We no longer keep issues for adapter plugins in the core repo, so I'm going to close this one. (I know the docs previously said to open an issue here first; sorry about that! We _just_ updated that page.) That said, I encourage you to post questions in the #dbt-core-development channel in the [dbt Slack community](https://community.getdbt.com/); I or another community maintainer will do our best to help you out.
