### ISSUE TITLE
Cryptography dependency conflict

### ISSUE THREAD

**Issue by amin-nejad** [fishtown-analytics/dbt#2950]
### Describe the bug
Running `pip-compile` from `pip-tools` on `dbt` (alone) fails due to a a dependency conflict with the `cryptography` library.

### Steps To Reproduce
`pip install pip-tools && echo dbt > requirements.in && pip-compile requirements.in`

### Expected behavior
A `requirements.txt` file generated with the pinned dependencies.

### Screenshots and log output
<img width="1439" alt="Screenshot 2020-12-14 at 22 03 51" src="https://user-images.githubusercontent.com/44096034/102141319-89826380-3e58-11eb-83f2-038dd7c78bd6.png">

### System information

**The operating system you're using:** macOS Big Sur 11.0.1

**The output of `python --version`:** 3.8.5

**`pip-tools` version:** 5.4.0

### Additional context
Appears related to #2896

**Comment by jtcohen6** [comment]
Right on @amin-nejad, I believe this will be resolved in the next version of dbt, which upgrades both the `snowflake-connector-python` and `cryptography` dependencies of `dbt-snowflake` (#2922).

In the meantime, we don't have any commitments around officially supporting `pip-tools` or `pip-compile` (#2674, #2676). Our assurances are just around your ability to run `pip install dbt`.

From looking quickly at the error message, it appears that `pip-compile` is picking up pyOpenSSL==20.0.0, which requires cryptography>=3.2, whereas [snowflake-connector-python@2.2.10](https://github.com/snowflakedb/snowflake-connector-python/blob/d0116887d16cfaecf1b61fdc58e03af02c14c77c/setup.py#L181) requires pyOpenSSL anywhere between 16.2.0 and 21.0.0.
