### ISSUE TITLE
exit codes should be significant

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#297]
if "errors" occur, dbt should exit with a non-zero exit code.

```
Exit codes:
0: completed without error
1: completed with non-SQL error (eg. bad conn info, invalid command, etc)
2: completed with SQL error
3: unhandled exception causes dbt to exit
```

**Comment by igrayson** [comment]
This is our preferred way to detect when our `dbt` models are failing.

Today we run regular tasks like `dbt` as cron jobs, and wrap them in a script to send metrics on duration/exit code for monitoring.

**Comment by adamhaney** [comment]
That would be perfect, we've started to run dbt with airflow and it would be awesome to be able to have calling scripts know if the command succeeded or not.

**Comment by adamhaney** [comment]
One more thing, it's not quite clear if there are specific complexities for each command (compile, test, clean, etc). The main ones that introduce hurdles for my team specifically are dbt run and dbt test not returning error codes. We'd really like to be able to run and test in an automated way and respond/notify on failure.
