### ISSUE TITLE
Security vulnerability - Insufficient Entropy (CWE ID 331)

### ISSUE THREAD

**Issue by YashKanodia1996-AIS** [fishtown-analytics/dbt#2977]
Random number generator in following files do not have sufficient entropy. Can random number generator be replaced from trusted source?

* /test/integration/base.py 132
* /test/rpc/conftest.py 48
* /core/dbt/task/seed.py 71
* /test/unit/test_cache.py 328
* /.../test_docs_generate.py 66
* /test/.../100_rpc_test/test_rpc.py 116
* .../test_simple_bigquery_view.py 63
* .../test_simple_presto_view.py 66
* /test/rpc/util.py 460

**Comment by drewbanin** [comment]
not relevant - dbt does not use pseudorandom numbers for any cryptographic purpose
