### ISSUE TITLE
Security Vulnerability:- Use of a Risky Cryptographic Algorithm (CWE ID 327)

### ISSUE THREAD

**Issue by YashKanodia1996-AIS** [fishtown-analytics/dbt#2978]
The cryptographic algorithms used in the following files have been classified as risky by a security scanner used. Can the algorithm used be replaced by another one from a trusted source?

* /core/.../dbt/contracts/files.py 89
* /core/dbt/deps/git.py 22
* /core/dbt/config/project.py 634
* /.../schema_test_builders.py 48
* /test/.../test_events.py 51
* /core/dbt/utils.py 247
* /core/dbt/utils.py 251
* /core/dbt/utils.py 255

**Comment by drewbanin** [comment]
not relevant - dbt does not use md5 or sha hashes for cryptographic/security purposes
