### ISSUE TITLE
Security Vulnerability:- Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS) (CWE ID 80)

### ISSUE THREAD

**Issue by YashKanodia1996-AIS** [fishtown-analytics/dbt#2979]
A call in the following file contains a cross-site scripting (XSS) issue. The application populates the HTTP response with untrusted input, allowing an attacker to embed malicious content, such as Javascript code, which will be executed in the context of the
victim's browser. How can this be prevented or is there a way to make this call more secure?

* /converter.py 36

**Comment by drewbanin** [comment]
not relevant
