### ISSUE TITLE
dbt should never exit with a stacktrace

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#298]
cc @cmcarthur

**Comment by jthandy** [comment]
- throw stacktrace in logfile
- report error

**Comment by drewbanin** [comment]
wishful thinking. let's make issues for specific stack traces as they pop up. closing

**Comment by drewbanin** [comment]
This hasn't been an issue for some time, and we're now logging the backtrace to `logs/dbt.log`. Closing
