### ISSUE TITLE
Our main build is showing as queued in the dashboard (going back several days) despite it being successful

### ISSUE THREAD

**Issue by rommymode** [fishtown-analytics/dbt#2983]
### Describe the bug
Logged into dbt and our dashboard is showing our main build is showing as queued going back several days' previous runs. But the job is clearly running successfully when we look at our Snowflake instance

### Steps To Reproduce
Log into the dbt dashboard and look at the statuses for all the builds. Only the main build is showing as "queued" going back several days, even though it was successful.

### Expected behavior
A success status

### Screenshots and log output
![image](https://user-images.githubusercontent.com/74013682/103253594-cf0e5880-494f-11eb-981d-a420fd7bc4b2.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1

**The operating system you're using:**
MacOS Catalina

**The output of `python --version`:**

**Comment by kwigley** [comment]
@rommymode something doesn't look right here! Can you please report this issue via dbt Cloud support? (https://docs.getdbt.com/docs/guides/getting-help/#dbt-cloud-support)

**Comment by jtcohen6** [comment]
@kwigley is right on, this looks like an issue for which dbt Cloud support is best suited to help. I'm going to close it here in the meantime, since I don't think there's a change to make in dbt core.
