### ISSUE TITLE
Snapshot_merge: 'WHEN MATCHED' cannot appear more than once in a 'UPDATE' clause of a MERGE statement

### ISSUE THREAD

**Issue by mikaelene** [fishtown-analytics/dbt#3003]
### Describe the feature
The SQL generated for updating records in merge statements generated by snapshots does not work on SQL Server. 

### Describe alternatives you've considered
I want it to work on SQL Server as well as all other databases.

### Additional context
This applies to SQL Server, but it could be better written anyway to not confuse developers.

### Who will this benefit?
SQL Server dbt users

### Are you interested in contributing this feature?
I can make a PR solving this

**Comment by mikaelene** [comment]
https://github.com/fishtown-analytics/dbt/blob/a4280d7457c32dce072d3224190a4779abc77d77/core/dbt/include/global_project/macros/materializations/snapshot/snapshot_merge.sql#L14-L24

could be rewritten as 
```
    when matched
     and DBT_INTERNAL_DEST.dbt_valid_to is null
     and DBT_INTERNAL_SOURCE.dbt_change_type in ('update', 'delete')
        then update
        set dbt_valid_to = DBT_INTERNAL_SOURCE.dbt_valid_to
```

**Comment by jtcohen6** [comment]
Agree that the more concise version is preferable, anyway!
