### ISSUE TITLE
debug exit code does not match connection test

### ISSUE THREAD

**Issue by sdebruyn** [fishtown-analytics/dbt#3017]
### Describe the bug
When I run `dbt debug`, I would expect a successful exit code (0) when the connection test succeeds and an error code (>0) when the connection test fails. In `0.18.1` the exit code is always 0, regardless of the result of the test.

### Steps To Reproduce
1. Make sure your profile works
2. Run `dbt debug` (connection test should succeed)
3. Run `echo $?` - observe that the output is `0`
4. Mess up your profile (e.g. change the port to an invalid one)
5. Run `dbt debug` (connection test should fail)
6. Run `echo $?` - observe that the output is still `0`

### Expected behavior
A strictly positive exit code when the connection test fails.

### Screenshots and log output
Mentioned in repro

### System information
Any database

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - sqlserver: 0.18.1
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - postgres: 0.18.1
  - redshift: 0.18.1
```

**The operating system you're using: Debian Buster

**The output of `python --version`:**
Python 3.8.7

**Comment by jtcohen6** [comment]
@sdebruyn I agree. If `dbt debug` manages to detect an error in your path, project, connection profile—or that you're not running from a dbt project at all—it feels like it should return `1` ("handled error") as the exit code instead of `0`. I imagine could be useful for plugin maintainers who want to check various connection methods in CI (e.g. https://github.com/dbt-msft/dbt-sqlserver/issues/65).

Is this a change you'd be interested in contributing?

**Comment by sdebruyn** [comment]
Sure :) Am I correct to assume that these 2 files are the only ones I'd need to change?
- https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/test/integration/049_dbt_debug_test/test_debug.py
- https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/core/dbt/task/debug.py

**Comment by jtcohen6** [comment]
That sounds right to me! We define an `ExitCodes` enum here:
https://github.com/fishtown-analytics/dbt/blob/1f927a374c8bd52a12a20d892fed9d59cffd04f4/core/dbt/utils.py#L32-L35

(`ModelError` sounds narrow; we might consider renaming someday to something more generic like `HandledError`.)

I think you'd want to pull that into `task/debug.py`, and conclude the `run` method by calling `sys.exit()` with the appropriate enum value.
