### ISSUE TITLE
doc() function does not work in exposure description

### ISSUE THREAD

**Issue by fuchsst** [fishtown-analytics/dbt#3030]
When i place 
`{{ doc('my_docs_name') }}` in a description field in the `schema.yml` of a model, it gets inserted as expected.
Doing the same in the description field of an exposure throws an error:

`'doc' is undefined`

**Comment by jtcohen6** [comment]
Hey @fuchsst, this fix is coming in v0.19.0! Check out https://github.com/fishtown-analytics/dbt/pull/2913, https://github.com/fishtown-analytics/dbt/pull/2920
