### ISSUE TITLE
git.bat not picked up on dbt deps

### ISSUE THREAD

**Issue by majidaldo** [fishtown-analytics/dbt#3035]
ref. https://github.com/fishtown-analytics/dbt/pull/1110

```
> dbt deps
Encountered an error:
Could not find command, ensure it is in the user's PATH: "git"
```

I have reasons to wrap my executables. On Windows I wrap my executables in `.bat` scripts (to get a similar effect to `.sh`). But then[ `Popen( ['git'] )`](https://github.com/fishtown-analytics/dbt/blob/42a85ac39f34b058678fd0c03ff8e8d2835d2808/core/dbt/clients/system.py#L419) doesn't work. `Popen( ['git.bat'])` works. 

So the platform-independent way to get `git` to work is to use  `shutil.which` to get the full path to the exe. `Popen([ which('git') ], )` works.

**Comment by jtcohen6** [comment]
@majidaldo Just to clarify, you're encountering an error when you run `dbt deps`?

**Comment by jtcohen6** [comment]
Ok! And if I understand your original message, are you saying that you're able to resolve the `dbt deps` error by changing line 420 below from `cmd` to `shutil.which(cmd)`?
https://github.com/fishtown-analytics/dbt/blob/42a85ac39f34b058678fd0c03ff8e8d2835d2808/core/dbt/clients/system.py#L419-L424

**Comment by majidaldo** [comment]
...well, depend on how you guys want to structure subprocess calls. The way you have it is that `cmd` is a list of strings (shell=False). So you'd only need to change the first element in the list: `cmd` --> `[which(cmd[0])] + list(cmd[1:])`.

**Comment by majidaldo** [comment]
FYI, with `shell=True`, your wouldn't have to use `which`. You'd have to consider security implications but I think it's safe here.

**Comment by jtcohen6** [comment]
Ok, this one is a little bit beyond me. @kwigley When you have a moment, could I ask for your sense-check here?

**Comment by majidaldo** [comment]
bump. this should be straightforward.

**Comment by jtcohen6** [comment]
@majidaldo Is this a fix you'd be interested in contributing? I'd welcome a PR for it, if you don't mind explaining the system/security implications of the proposed changes.
