### ISSUE TITLE
Installing dbt on GCP Cloud Composer image composer-1.14.0-airflow-1.10.14 fails with requests package error

### ISSUE THREAD

**Issue by svirs** [fishtown-analytics/dbt#3046]
### Describe the bug
Installing `dbt==0.19.0` on Cloud Composer image `composer-1.14.0-airflow-1.10.14` fails with:

> ERROR: dbt-core 0.19.0 has requirement requests<2.24.0,>=2.18.0, but you'll have requests 2.25.0 which is incompatible.
> ERROR: snowflake-connector-python 2.3.6 has requirement requests<2.24.0, but you'll have requests 2.25.0 which is incompatible.

### Steps To Reproduce
Create a GCP cloud composer instance (https://cloud.google.com/composer) using the image `composer-1.14.0-airflow-1.10.14`, navigate to the PYPI Packages tab and attempt to install `dbt` with version `==0.19.0`

### Expected behavior
should install properly without errors

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
Bigquery

**The operating system you're using:**

**The output of `python --version`:**
Cloud Composer runs 3.6.6 by default: https://cloud.google.com/composer/docs/concepts/python-version

**Comment by svirs** [comment]
This was on a fresh instance of cloud composer with only `airflow-dbt==0.3.0` previously installed which has `apache-airflow >= 1.10.3` as its only dep

**Comment by jtcohen6** [comment]
@svirs The reason this doesn't work is exactly as the error message states: `dbt-snowflake==0.19.0` depends on `snowflake-connector-python==2.3.6`, which requires `requests<2.24.0,>=2.18.0`, whereas `composer-1.14.0-airflow-1.10.14` requires `requests==2.25.0`.

I know that the `snowflake-connector-python` team have been working to remove upper bounds on popular packages, and `2.3.8` vendored pieces of `requests` and bumped the requirement to `'requests<3.0.0'`. In the next minor version of dbt, we'll bump the `snowflake-connector-python` pin to the latest available stable release, and that should ease installation for everyone.

In the meantime, since you're using dbt with BigQuery, you should be able to get around this by installing `dbt-bigquery` in particular:
```
pip install dbt-bigquery==0.19.0
```

**Comment by svirs** [comment]
For anyone else running into this issue you can likely get by by using Cloud Composer image: `composer-1.14.0-airflow-1.10.9` as it's the only one in the list that has jsonschema < 3.2 and requests < 2.25 (see included pypi packages): https://cloud.google.com/composer/docs/concepts/versioning/composer-versions

**Comment by svirs** [comment]
Hmm, but GCP doesn't let me install that image version in my zone... so I think I'm out of luck here? dbt-bigquery still requires requests<24 from dbt-core and the airflow versions supported in Cloud Composer all rely on requests being ==2.25 (as well as jsonschema==3.2 which is equally problematic for fishtown-analytics/hologram which is <3.2,>=3.0)

**Comment by jtcohen6** [comment]
Ah, you're right, `dbt-core==0.19.0` also pins that `requests` version to match the requirement from `snowflake-connector-python==2.3.6` (via `dbt-snowflake==0.19.0`). Sorry about that—we're not thrilled about these aggressive pins, we err on the side of safe-not-sorry when coordinating dependencies. This _will_ be resolved in the next version of dbt, when we're able to bump the version of `snowflake-connector-python` to at least `2.3.8`, which removed the stringent upper bound on `requests`.

In the meantime, you could look into orchestrating dbt together with Airflow/Cloud Composer via Docker (i.e. [KubernetesPodOperator](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator)). We maintain [Docker images for the latest versions](https://hub.docker.com/r/fishtownanalytics/dbt/tags?page=1&ordering=last_updated).

**Comment by svirs** [comment]
Yup that's exactly the plan, found a nice demo of it as well over here: 
https://medium.com/analytics-vidhya/adapting-a-real-world-data-pipeline-for-my-pet-project-ca536d545409
https://gitlab.com/snowboard-analysis/analytics/-/tree/master/
https://gitlab.com/snowboard-analysis/data-image/-/tree/master
