### ISSUE TITLE
Spelling error in config not caught

### ISSUE THREAD

**Issue by steve0629** [fishtown-analytics/dbt#3051]
spelling error, missing 'i' for 'incremental_strategy' not caught and results in wrong incremental strategy. 
{{
     config (
          materialized='incremental',
          ncremental_strategy = 'insert_overwrite',
          partition_by = {"field": "timestamp","data_type": "timestamp"},
          )
}}

Result is that _dbt_max_partition is not defined since it doesn't use 'insert_overwrite' strategy.

**Comment by jtcohen6** [comment]
Hey @steve0629, where did you find the code that you linked above?
