### ISSUE TITLE
[Q1C2] More consistent, configurable tests

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3066]
The next version of dbt is going to focus on improving `dbt test`, along the lines of:
- More consistency between schema and data tests
- More consistency between tests and other dbt resources
- Straightforward, compelling extensions around filters, limits, expectation thresholds
- Improved development-time debugging by storing failing records in the database
- Rethinking, as appropriate, the YAML specs currently used to define tests

There are many open issues in the [v0.20.0 milestone](https://github.com/fishtown-analytics/dbt/milestone/62) with the [`tests`](https://github.com/fishtown-analytics/dbt/issues?q=is%3Aopen+is%3Aissue+label%3Atests) tag. This epic will track our broader initiative over the next several weeks, as it's likely we'll consolidate several open issues and close/rewrite others.

**Comment by joellabes** [comment]
> * Should we add/expand builtin generic tests (i.e. upstream some of the functionality from [dbt-utils](https://github.com/fishtown-analytics/dbt-utils#schema-tests))?

At a minimum, I'd love to see the `_where` versions of each of the core tests brought in as first-class citizens
