### ISSUE TITLE
Table materialization specified in parent dbt_project.yml causes incremental models in package to materialize as tables

### ISSUE THREAD

**Issue by NiallRees** [fishtown-analytics/dbt#3068]
### Describe the bug
The behaviour I'm seeing is that when I create incremental models in a package and do a `dbt run` inside that package with the models defined in the package's `dbt_project.yml` as tables, everything works as expected. Non incremental tables run as full tables, and incremental models run incrementally.

When I then use that package in a parent project, and specify the models as tables in the exact same way, the package's incremental models always run as tables, never incrementally.

### Steps To Reproduce
Example using https://github.com/tailsdotcom/dbt_artifacts package which contains two incremental models, `fct_dbt__run_results` and `fct_dbt__model_executions`.

When I configure in the parent project the materializations for that directory as a table:

```
models:
  dbt_artifacts:
    +schema: mart_engineering
    +materialized: table
    staging:
      +schema: base
      +materialized: view
```

All the models run as tables with `dbt run -m dbt_artifacts`, not incrementally.

From inside parent project, note the `"materialized": "table",`:

```
dbt ls -m fct_dbt__run_results --output json
{"package_name": "dbt_artifacts", "name": "fct_dbt__run_results", "resource_type": "model", "alias": "fct_dbt__run_results", "config": {"enabled": true, "materialized": "table", "persist_docs": {}, "post-hook": [], "pre-hook": [], "vars": {}, "quoting": {}, "column_types": {}, "alias": null, "schema": "mart_engineering", "database": null, "tags": [], "full_refresh": null, "unique_key": "command_invocation_id"}, "tags": [], "depends_on": {"macros": ["macro.tails_core_data.ref", "macro.dbt_utils.get_column_values", "macro.dbt.is_incremental"], "nodes": ["model.dbt_artifacts.stg_dbt__run_results_env_keys", "model.dbt_artifacts.stg_dbt__run_results"]}}
```

Adding the exact same dbt_project.yml materialization configuration inside the package itself, note the `"materialized": "incremental"`:

```
dbt ls -m fct_dbt__run_results --output json
{"package_name": "dbt_artifacts", "name": "fct_dbt__run_results", "resource_type": "model", "alias": "fct_dbt__run_results", "config": {"enabled": true, "materialized": "incremental", "persist_docs": {}, "post-hook": [], "pre-hook": [], "vars": {}, "quoting": {}, "column_types": {}, "alias": null, "schema": "mart_engineering", "database": null, "tags": [], "full_refresh": null, "unique_key": "command_invocation_id"}, "tags": [], "depends_on": {"macros": ["macro.dbt_utils.get_column_values", "macro.dbt.is_incremental"], "nodes": ["model.dbt_artifacts.stg_dbt__run_results_env_keys", "model.dbt_artifacts.stg_dbt__run_results"]}}
```

### Expected behavior
When a materialization configuration is set to table in a parent project of a package, any incrementally materialized models should stay that way, just like they were a part of the parent project.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.19.0
```

**The operating system you're using:**
Mac OS
**The output of `python --version`:**
3.8.6

**Comment by jtcohen6** [comment]
Hey @NiallRees, I'd say this is a feature, not a bug!

From the [docs on configuring packages](https://docs.getdbt.com/docs/building-a-dbt-project/package-management/#configuring-packages):

> Configurations made in your `dbt_project.yml` file will override any configurations in a package (either in the `dbt_project.yml` file of the package, or in config blocks).

Since you can't edit the package model files, the root `dbt_project.yml` is the only lever you have to control the behavior of the installed package. This does require you to provide more granular configuration in `dbt_project.yml` for installed packages, maybe more like:
```yml
models:
  dbt_artifacts:
    +schema: mart_engineering
    fct_dbt__critical_path:
      +materialized: table
    fct_dbt__latest_full_model_executions:
      +materialized: table
    +materialized: table
    staging:
      +schema: base
      +materialized: view
```
Since you're also the maintainer of that package: it's all the more reason to set reasonable defaults within the package, or to organize models in such a way that they can be conveniently grouped together, knowing that the installer is fully capable of reconfiguring at will.

**Comment by NiallRees** [comment]
Thanks for the detailed response @jtcohen6! Will update the package.
