### ISSUE TITLE
Parsing performance:  jinja  environment.py compile

### ISSUE THREAD

**Issue by gshank** [fishtown-analytics/dbt#3094]
A lot of parsing time is spent in the Jinja environment.py 'compile' method. Investigate to see if we can speed this up or refactor to use static parsing, or make a custom code path that skips overhead that we don't need.

**Comment by gshank** [comment]
There are a number of options to speed this up. One we have looked at is doing templating in Rust (using nom and/or borrowing from existing packages). Another option is to use something like Tree-sitter which will generate a grammar for Jinja. Tree-sitter also has the long term advantage of eventually allowing parsing of SQL with all of the advantages that might bring.

**Comment by jtcohen6** [comment]
I just opened https://github.com/fishtown-analytics/dbt/issues/3215 to pick up from where this issue is leaving off, and make concrete our next steps investigating tree-sitter
