### ISSUE TITLE
How do I execute Mathematical Operations as transformations

### ISSUE THREAD

**Issue by PetrykowskiM** [fishtown-analytics/dbt#3097]
### Describe the bug
Hey there, I was wondering wether it is possible to perform mathematical operations like a subtraction between 2 columns of a row to define a new column for the transformation. 

I tried to find some hints in the documentation, but was unsuccessful.

**Comment by jtcohen6** [comment]
Hey @PetrykowskiM, welcome! It sounds like you might be new to dbt. Do you mean this in the sense of writing SQL within your models?

Let's say I have a raw source table, `fruits.inventory`, like:

fruit | picked | eaten
-- | -- | --
apple | 6 | 3
pear | 7 | 3
quince | 3 | 2
kumquat | 1 | 0

I want to model this data to see how many of each fruit is remaining, by adding a column called... well, `remaining`. I could create a model file, **models/stg_fruit_inventory.sql**, like:

```sql
select

  fruit,
  picked,
  eaten,
  picked - eaten as remaining

from fruits.inventory
```

When I `dbt run`, it will [materialize](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/materializations) that model as a view (or a table!) that, when queried, will return:

| fruit   | picked | eaten | remaining |
|---------|--------|-------|-----------|
| apple   | 6      | 3     | 3         |
| pear    | 7      | 3     | 4         |
| quince  | 3      | 2     | 1         |
| kumquat | 1      | 0     | 1         |

From there, we could think about adding a test to **stg_fruit_inventory**, perhaps to ensure that `remaining` is always a natural number or 0—I should never have negative apples, or a fraction of apples. (Unless I used half an apple in a pie, but let's be honest, I probably ate the other half while baking it!) To define that test, I could write a custom data test, or use a preexisting test from the dbt-utils package, [`expression_is_true`](https://github.com/fishtown-analytics/dbt-utils#expression_is_true-source):
```yml
# packages.yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
```
```yml
# fruits.yml
version: 2

models:
  - name: stg_fruit_inventory
    tests: dbt_utils.expression_is_true:
      expression: remaining >= 0 and (remaining - floor(remaining) = 0)
```

This is just the beginning. I'd encourage you to join our [Slack community](https://community.getdbt.com/), read more about dbt in [discourse](https://discourse.getdbt.com/), and try out our ["dbt Fundamentals" course](https://discourse.getdbt.com/). If you do have tactical questions or need technical help, I recommend posting on [StackOverflow with the tag `dbt`](https://stackoverflow.com/tags/dbt). As this repository is a place to report bugs or propose enhancements in dbt, and there's no code change required for what you're after, I'm going to close this issue.

**Comment by PetrykowskiM** [comment]
Hi Jeremy,

thanks for the detailed reply. That already helps. I think those examples would be positioned nicely in the dbt docs. I also did not come across your referenced course when I went through the docs. 

Thanks! :)
