### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#311]
Currently all data tests are tagged with `data`, and all schema tests are tagged with `schema`. The test selector supports selecting tests by tag -- that's how schema-only and data-only test runs work in development.

YAML has some notion of tags for schema tests. For data tests (and possibly models?) we'll need a way to configure tags with Jinja.

Finally we'll need a way to select tags via the CLI.

Some thought should be given to how tags behave -- a good naive approach given a tag `t` is to include any node that has tag `t`, even if it has other tags, and to exclude any node without tag `t`. So given tags `data,schema`, run all tests. This doesn't let you exclude tags or do boolean logic on which tags to run.

**Comment by atjones0011** [comment]
This would be incredibly useful for me and my team. Here's a transcript of what I posted in the DBT Slack group on this topic:

> We have 50+ models that are organized by the area of business that they support. We are currently working on splitting up our `dbt run` into multiple runs that are organized by how frequently the data is needed. With this setup, some models would run multiple times per hour and some would run once per day. We would be able to accomplish this goal by reorganizing our sql files, but we don’t want to lose our current organization.
> 
> Proposal:
> Support for a new parameter in the project YAML named `tags` which will have a value that is a list of strings. When performing `dbt run`, have a parameter `--tags` which allows us to run any models that have the tag provided.

**Comment by cmcarthur** [comment]
@atjones0011 can you elaborate a little bit on this part?

> Support for a new parameter in the project YAML named tags which will have a value that is a list of strings.

My brain is interpreting that as applying tags to models from the `dbt_project.yml` file, like so:

```
models:
  project_name:
    accounting:
      tags: accounting
    product:
      tags: product
    common:
      tags: accounting, product
```

Is that what you had in mind?

**Comment by atjones0011** [comment]
That's exactly what I was thinking. The tags I have in mind for my particular use case are `frequent`, `daily`, `weekly`.

**Comment by cmcarthur** [comment]
Oh, that is cool. Thanks @atjones0011 !

**Comment by drewbanin** [comment]
We should do this soon. The primary blocker is https://github.com/fishtown-analytics/dbt/issues/550, which handles the _selection_ of tags. Once that's implemented, it should be exceedingly straightforward to implement this feature
