### ISSUE TITLE
dbt runs slowly on Redshift RA3 nodes due to excessive commits

### ISSUE THREAD

**Issue by tconbeer** [fishtown-analytics/dbt#3112]
### Describe the bug
This is similar to #2748, but is Redshift-specific. However, I think users of other databases would benefit from slightly faster runs.

The next-gen Redshift RA3 nodes seem to have very slow COMMITs, due to the fact that:
- Redshift only processes a single transaction/COMMIT at a time, and
- RA3 nodes write their commits to S3; this makes each COMMIT take about a second (🤮)

[Many dbt users](https://getdbt.slack.com/archives/CJARVS0RY/p1609958080328900) have reported excessively slow runs creating views on RA3 nodes. In my experience, creating views while running dbt in multiple threads can take upwards of 20 seconds of clock time (see logs below).

There are at least 4 transactions as part of the [view materialization](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/materializations/view/view.sql):
1. Drop the intermediate relation
2. Drop the temp relation
3. Create new view; swap names with old view
4. Drop old view

Best case, on RA3, this sequence will take 4 seconds per view; in multiple threads, as these sequences stack up in the transaction queue, it will take much longer (in clock time).

### Steps To Reproduce
On a Redshift cluster with RA3 nodes (I'm on RA3.xplus x4), execute `dbt run` in multiple threads in a project with many views.

### Expected behavior
Views should ideally take at most a second or two to be materialized. 

Above, the four transactions to create a view could be compressed into a single transaction. I don't think this would have other side-effects, as any one of these operations failing would cause the run step to fail anyway.

To achieve this, I think we would have to modify the materialization macro(s) so dropping the other relations happens inside the same commit. It may be sufficient to add an explicit BEGIN in the materialization.

### Potential workarounds
On dbt v0.18+, we can avoid rebuilding views using the new selection syntax. However, this introduces some complexity and the potential for deployment errors when views change.

As an alternative, we can use more ephemeral models and fewer views, if the views do not need to be exposed in other contexts; this can make debugging more difficult.

### Screenshots and log output
Here's a recent run in dbt cloud:
![image](https://user-images.githubusercontent.com/705906/108251543-c26add00-7114-11eb-8637-c4cf2c2ce87d.png)

Investigating the logs, it's clear the bottleneck is committing the transaction. This is each statement to execute the `START view model analytics.logistics_ops_sectors` line above:
![image](https://user-images.githubusercontent.com/705906/108251498-b54dee00-7114-11eb-81f1-390ee2bac925.png)

Source for logs is `svl_statementtext`:
```sql
with 
    statements as (

        select 
            *,
            (datediff(milliseconds, starttime, endtime)::float / 1000)::numeric(10, 3) as dur_s,
            (datediff(milliseconds, lag(endtime, 1) over (order by starttime), starttime)::float /
            1000)::numeric(10, 3) as wait_s

    from svl_statementtext
    where 
        -- matches specific prod run above
        starttime >= '2021-02-17 08:04:17.124262'
        and starttime <= '2021-02-17 08:04:44.216802'
        and pid = 17738
        and sequence = 0

    order by starttime asc

),
    totals as (

        select
            null::int, 
            null::int, 
            null::int, 
            null::varchar, 
            getdate()::timestamp, 
            null::timestamp, 
            null::int, 
            null::varchar,
            ' --------- TOTAL ---------'::varchar,
            sum(dur_s), 
            sum(wait_s)

        from statements

 ),
    unioned as (

         select * from statements
         union all
         select * from totals

)
select * from unioned order by starttime
```
### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.17.1
```

**The operating system you're using:**
Windows, but reproduces on dbt cloud
**The output of `python --version`:**
3.7.9

**Comment by jtcohen6** [comment]
Wow! Thanks for bringing this to our attention @tconbeer. I did _not_ realize there is such a fixed cost for transactions on RA3 nodes. Of all the idiosyncrasies we've had to grapple with over the years, this is a particularly frustrating one.

I mocked the proposed single-transaction approach to atomic view replacement. Setup:
```sql
create view dbt_jcohen.my_view as (select 1 as fun);
```

```sql
begin;
drop view if exists dbt_jcohen.my_view__dbt_tmp;
drop view if exists dbt_jcohen.my_view__dbt_backup;
create view dbt_jcohen.my_view__dbt_tmp as (select 2 as fun);
-- run other query
alter table dbt_jcohen.my_view rename to my_view__dbt_backup;
alter table dbt_jcohen.my_view__dbt_tmp rename to my_view;
drop view dbt_jcohen.my_view__dbt_backup;
commit;

Midway through, I run a read-only query from a separate connection:
```sql
select * from dbt_jcohen.my_view
```

Because the view I'm querying is dropped _within_ the other transaction, this actually returns an error:
```
An error occurred when executing the SQL command:
select * from dbt_jcohen.my_view

[Amazon](500310) Invalid operation: could not open relation with OID 1190941;
1 statement failed.

Execution time: 8.63s
```

However, if I move the `drop` of the old (backup) view _after_ the transaction, everything works seamlessly:
```sql
begin;
drop view if exists dbt_jcohen.my_view__dbt_tmp;
drop view if exists dbt_jcohen.my_view__dbt_backup;
create view dbt_jcohen.my_view__dbt_tmp as (select 3 as fun);
alter table dbt_jcohen.my_view rename to my_view__dbt_backup;
alter table dbt_jcohen.my_view__dbt_tmp rename to my_view;
commit;
drop view dbt_jcohen.my_view__dbt_backup;
```

So: I think we could safely speed up the Redshift view materialization on RA3 nodes by consolidating steps 1-3, thereby reducing the materialization from four transactions down to two. This will return errors if users are concurrently querying `my_view__dbt_tmp` or `my_view__dbt_backup`, explicitly by name, but there's no reason they should be. I don't think we can get all the way away from having multiple transactions, however, and views will still have a fixed cost of 2+ seconds :(

Is this code you'd be interested in contributing?

**Comment by tconbeer** [comment]
Thanks for the follow-up and analysis, Jeremy!

Running your toy example (with other, regular workloads on my cluster):
- 4 commits:
- 1 commit:
- 2 commits: 6.83s

**Comment by tconbeer** [comment]
Thanks for the follow-up and the analysis, Jeremy! I agree that the 2-commit solution seems like the right path forward.

Running your toy example on my cluster, with other workloads in the background, so best 3 out of 5 (the clock time speedup should be much greater if running multiple threads in parallel):

4 commits: 5.6s, 5.8s, 8.0s
2 commits: 3.1s, 3.6s, 4.6s
1 commit: 2.6s, 2.6s, 2.9s

I'd like to contribute to this; digging a little deeper I'm worried it's going to get complicated. There is this [note](https://github.com/fishtown-analytics/dbt/blob/38f278cce0a5ccd2f92cc3381f3f0d02d30babe8/plugins/redshift/dbt/adapters/redshift/impl.py#L30) in the redsfhit adapter's `drop_relation` method that explicitly wraps it in a new transaction to avoid issues with `cascade`. So not really sure what can be done to work around that.

**Comment by jtcohen6** [comment]
Good point calling out the `drop_relation` safety wrappers in the adapter and connection manager. This is one of those not-great-feeling times when we can only pick two among performance, consistency, and intuitive code on Redshift.

Here's a minimum viable hack to think about:

https://github.com/fishtown-analytics/dbt/blob/49b8693b1111c34fc3b134237b0f2ef7046582bf/core/dbt/include/global_project/macros/materializations/view/view.sql#L35-L37

Ninety-nine times out of 100, the `intermediate_relation` and `backup_relation` should not exist, and they should not have any bound dependencies to be cascade-dropped. (All dbt-redshift projects should probably use late-binding views to avoid this, anyway.) To avoid running unnecessary transactions, which are baked into standard `drop_relation` behavior, dbt could try one of the following:

1. Check the [relational cache](https://github.com/fishtown-analytics/dbt/blob/49b8693b1111c34fc3b134237b0f2ef7046582bf/plugins/postgres/dbt/adapters/postgres/impl.py#L81-L86) to see if there are any linked dependencies for the backup or temp relation. Assuming there aren't, try running `drop view`/`drop table` (without `cascade`). If not, open a locked transaction for `drop ... cascade` (standard behavior today).
2. Try running `drop view`/`drop table` (without `cascade`). If it works, great; otherwise, catch the database error if it fails on account of having dependencies, and open a locked transaction for `drop ... cascade` (standard behavior today).

Neither of these approaches brings me a lot of joy, but at the point where it cuts the time it takes to materialize views on RA3 nodes nearly in half, it's a thread worth pulling on.

**Comment by tconbeer** [comment]
Coming back to this with some fresh eyes. I think instead of modifying the `cascade` or transaction behavior, I think a better solution is for the materialization to:

1. check the relational cache to see whether these temp relations exist, 
2. try to `drop ... cascade` them if they do. 
 
I think this would be simple and fast using `adapter.get_relation` on the "intermediate" and "backup" relation names. 

This would introduce a race condition if there was another process modifying the same relations at roughly the same time. But that problem exists with the current implementation, since the drop is done before the temp relation is needed (in a different transaction). And I think if you have multiple processes running dbt on the same models at the same time, all bets are off, anyway.

We may as well make the same change in the table materialization, since the mechanics are the same.

Redshift and Postgres use the materializations from the `global_project`, so I propose we change it there; Snowflake and BQ have their own materializations.

I can open a PR with this change if we're good on this solution.

**Comment by jtcohen6** [comment]
Great thinking, @tconbeer, and thanks for opening the PR to do it.

> And I think if you have multiple processes running dbt on the same models at the same time, all bets are off, anyway.

Right you are!

**Comment by Limess** [comment]
I'm unsure what the expected outcome of this change is - it'd be great if someone could clarify. 

Is this expected to improve view creation times by a significant margin? We've just started testing ra3 instances (2 x `ra3.xlplus`), using `dbt 0.21.0b1` and we're seeing view creating taking 9-20 seconds as with the original description.

**Comment by tconbeer** [comment]
Yes, it's still "slow" after this change, but not as bad... should be up to 50% reduction in clock time. Best case creating a view still requires 2 commits, which should take ~2 seconds without any other workloads on the cluster, but more likely 2-4x that if you're running dbt in multiple threads or have concurrent workloads.
