### ISSUE TITLE
Override staging table macro specific to check_delete strategy

### ISSUE THREAD

**Issue by rajeshmese** [fishtown-analytics/dbt#3127]
We have overridden macro for 'check_delete' strategy with macro snapshot_staging_table also overriden for it.
But when we use the other 'check' strategy it was using the overridden macro snapshot_staging_table.
How to limit the overridden macro snapshot_staging_table only to 'check_delete' strategy and using the default strategy for others.

**Comment by jtcohen6** [comment]
Hey @rajeshmese, when overriding a built-in macro by reimplementing it in your own project, you can still access the original macro by specifying the `dbt` namespace. In this case, you could do something like:
```sql
{% macro snapshot_staging_table(strategy, source_sql, target_relation) -%}

    {% if strategy.invalidate_hard_deletes %}
    
        ... your custom logic ...
    
    {% else %}
    
        {{ dbt.snapshot_staging_table(strategy, source_sql, target_relation) }}
    
    {% endif %}

{% endmacro %}
```

I'm going to close this issue. I don't believe it's a bug, but rather one of the complexities you can reasonably account for when overriding built-in behavior. Let me know if you disagree!
