### ISSUE TITLE
Put macros into the flat "graph"

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#314]
Macros don't belong in the actual "graph", but they belong in the state file. Move them there, then remove the DBTSource code that loads Macros.

As we move in this direction it's going to make more and more sense for the flat representation of all the nodes to look like:

```
{
  macros: [... all macros ...],
  nodes: [... all models, tests, operations ...]
}
```

**Comment by drewbanin** [comment]
💯
