### ISSUE TITLE
Broken link to code of conduct in "read the rules" community sign up page

### ISSUE THREAD

**Issue by pvonglehn** [fishtown-analytics/dbt#3141]
### Describe the bug
The link to code of conduct in the read the rules part of the sign up page community.getdbt.com/#step-4 gives a 404 error. The linked URL is community.getdbt.com/TODO.

### Steps To Reproduce
Start sign up process to join the community at community.getdbt.com. Click on code of conduct link in step 4 (read the rules)

### Expected behavior
To be taken to the code of conduct page community.getdbt.com/code-of-conduct

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.
![image](https://user-images.githubusercontent.com/42738386/109790733-016b5900-7c12-11eb-9f93-9d1f1f0d25fe.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
Thanks @pvonglehn, and nice catch! We'll take care of it :)

**Comment by jtcohen6** [comment]
This should be fixed imminently
