### ISSUE TITLE
Refactor partial parsing to cover more startup costs

### ISSUE THREAD

**Issue by gshank** [fishtown-analytics/dbt#3163]
The current implementation of partial parsing saves a pickle file during parsing, before the 'create_manifest' step in which the following occurs 1) patch_sources (where source tests are processed), 2) patch_nodes, 3) patch macros, 4) process_sources, 5) process_refs, and 6) process_docs. If we refactor parsing so that the parsing state is saved after these things happen, then startup costs when using partial parsing will be substantially reduced. In our large parsing test project, those steps take 70 seconds out of a total of 193 in a sample run. We wouldn't be able to eliminate all of that time, but eliminating most of it would result in almost a 1/3 reduction in time.

Because the current implementation does not have to handle re-processing sources, refs, and docs, we would need to create new code to handle doing those tasks for only the changed files.

At some point we may also look at whether a pickle file is the best alternative for saving and restoring state, but that is not currently part of this project.

**Comment by jtcohen6** [comment]
We've narrowed the scope of this issue:
- Switch to using the Manifest, instead of the ParseResult, _without_ moving the save point

Will open another issue to cover:
- Moving the save point

**Comment by gshank** [comment]
Have opened #3217 for moving the save point.
