### ISSUE TITLE
Redshift error in `get_columns_in_relations` macro

### ISSUE THREAD

**Issue by chodera** [fishtown-analytics/dbt#3168]
### Describe the bug
Models using the `get_columns_in_relations` started to fail after the latest update of our Redshift instance on 2021-03-15. The issue is related with the return value count of the `pg_get_late_binding_view_cols()` function. Since the latest update of redshift on 2021-03-15, the pg_get_late_binding_view_cols() function returns 6 columns instead of 5 before the update.

### Steps To Reproduce
Run `select * from pg_get_late_binding_view_cols() cols(view_schema name, view_name name, col_name name, col_type varchar, col_num int);` as used in the [macro](https://github.com/fishtown-analytics/dbt/blob/2b48152da66dbd7f07272983bbc261f1b6924f20/plugins/redshift/dbt/include/redshift/macros/adapters.sql#L127).

### Expected behavior
The function `pg_get_late_binding_view_cols()` now returns 6 columns of metadata for all late-binding views, thus there needs to be added a column in the function call. Our hotfix was to override the macro by adding `unknown_column int` to the function call. 

### Screenshots and log output
```
2021-03-16 07:29:00.464247 (Thread-1): Using redshift connection "model.sevdesk_dbt_models.exchange_rates".
2021-03-16 07:29:00.464530 (Thread-1): On model.sevdesk_dbt_models.exchange_rates: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "newenv", "target_name": "dev", "node_id": "model.sevdesk_dbt_models.exchange_rates"} */

      with bound_views as (
        select
          ordinal_position,
          table_schema,
          column_name,
          data_type,
          character_maximum_length,
          numeric_precision,
          numeric_scale

        from information_schema."columns"
        where table_name = 'intermediate_exchange_rates'
    ),

    unbound_views as (
      select
        ordinal_position,
        view_schema,
        col_name,
        case
          when col_type ilike 'character varying%' then
            'character varying'
          when col_type ilike 'numeric%' then 'numeric'
          else col_type
        end as col_type,
        case
          when col_type like 'character%'
          then nullif(REGEXP_SUBSTR(col_type, '[0-9]+'), '')::int
          else null
        end as character_maximum_length,
        case
          when col_type like 'numeric%'
          then nullif(
            SPLIT_PART(REGEXP_SUBSTR(col_type, '[0-9,]+'), ',', 1),
            '')::int
          else null
        end as numeric_precision,
        case
          when col_type like 'numeric%'
          then nullif(
            SPLIT_PART(REGEXP_SUBSTR(col_type, '[0-9,]+'), ',', 2),
            '')::int
          else null
        end as numeric_scale

      from pg_get_late_binding_view_cols()
      cols(view_schema name, view_name name, col_name name,
           col_type varchar, ordinal_position int)
      where view_name = 'intermediate_exchange_rates'
    ),

    external_views as (
      select
        columnnum,
        schemaname,
        columnname,
        case
          when external_type ilike 'character varying%' or external_type ilike 'varchar%'
          then 'character varying'
          when external_type ilike 'numeric%' then 'numeric'
          else external_type
        end as external_type,
        case
          when external_type like 'character%' or external_type like 'varchar%'
          then nullif(
            REGEXP_SUBSTR(external_type, '[0-9]+'),
            '')::int
          else null
        end as character_maximum_length,
        case
          when external_type like 'numeric%'
          then nullif(
            SPLIT_PART(REGEXP_SUBSTR(external_type, '[0-9,]+'), ',', 1),
            '')::int
          else null
        end as numeric_precision,
        case
          when external_type like 'numeric%'
          then nullif(
            SPLIT_PART(REGEXP_SUBSTR(external_type, '[0-9,]+'), ',', 2),
            '')::int
          else null
        end as numeric_scale
      from
        pg_catalog.svv_external_columns
      where
        schemaname = 'dev_dwitkowski'
        and tablename = 'intermediate_exchange_rates'

    ),

    unioned as (
      select * from bound_views
      union all
      select * from unbound_views
      union all
      select * from external_views
    )

    select
      column_name,
      data_type,
      character_maximum_length,
      numeric_precision,
      numeric_scale

    from unioned
    
    where table_schema = 'dev_dwitkowski'
    
    order by ordinal_position
  
2021-03-16 07:29:00.784493 (Thread-1): Postgres error: query-specified return row and actual function return row do not match

2021-03-16 07:29:00.785223 (Thread-1): On model.sevdesk_dbt_models.exchange_rates: ROLLBACK
2021-03-16 07:29:00.813607 (Thread-1): Error running SQL: macro get_columns_in_relation
2021-03-16 07:29:00.814220 (Thread-1): Rolling back transaction.
2021-03-16 07:29:00.820376 (Thread-1): On model.sevdesk_dbt_models.exchange_rates: Close
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift (cluster version 1.0.24470)
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.19.0
```

**The operating system you're using:** Windows 10

**The output of `python --version`:** 3.6.9

**Comment by jtcohen6** [comment]
Gross! Ok, thanks for the report here @chodera. This isn't yet noted in Redshift's own [documentation](https://docs.aws.amazon.com/redshift/latest/dg/PG_GET_LATE_BINDING_VIEW_COLS.html). The current query still works on my sandbox/testing Redshift cluster, which hasn't yet updated (still version 1.0.24265).

I figure we should try to get this fix out as soon as possible. In the meantime, I think your hotfix of overriding `redshift__get_columns_in_relation` is quite a good one.

It feels like the ideal resolution would check the Redshift version, and then template `get_columns_in_relation` according to whether the version is `>= 1.0.24470`. Unfortunately, because dbt uses Postgres logic to connect to Redshift (i.e. via `psycopg2`), there isn't anything useful available to the python/Jinja context:
```python
>>> connection._handle.server_version
80002
```

So I see three possible implementations here:
- Straightforward: Edit the macro `redshift__get_columns_in_relation` to first call a statement, `select version();`, and template itself according to the result.
- Complex: A new method on `RedshiftConnectionManager` or `RedshiftAdapter` that, after initializing, runs `select version();` once, stores the result, and offers a method that exposes the value to the Jinja context.
- Disengaged: We game this fix around the Redshift release schedule, and tell users to manually patch this macro in the meantime.

What do you think? Is this a change you'd be interested in contributing?

**Comment by chodera** [comment]
Since a couple of days, the function does work the same way as it did before! So we reverted our override and are back to normal. I did not see anything related in the [Redshift Forum Announcements](https://forums.aws.amazon.com/forum.jspa?forumID=155&start=0) which makes me doubt Redshift's update policy...

I will close the issue for now, but feel free to reopen it in case you still see the need to take action

**Comment by jtcohen6** [comment]
That's great news @chodera! Glad this is back to working as documented
