### ISSUE TITLE
Upgrade Snowflake Connector dependency version to >= 2.4

### ISSUE THREAD

**Issue by willsthompson** [fishtown-analytics/dbt#3170]
### Describe the feature
Upgrade the version of `snowflake-connector-python` required by the DBT snowflake plugin to at least `2.4`: https://github.com/fishtown-analytics/dbt/blob/6a5ed4f41877bdcb3bd9b561ac0af2d197d234d1/plugins/snowflake/setup.py#L50

In addition to bugfixes and features in the connector itself, the 2.4 release pins to the latest stable version of PyArrow, 3.0, while the latest pinned version in the 2.3.x releases is [`<0.18.0`](https://github.com/snowflakedb/snowflake-connector-python/blob/6bc0248c99637c7df64cf88fbf063f93e358b0f5/setup.py#L44). For anyone using PyArrow in their application, a major version release is necessary for format stability and, practically speaking, general stability from 100s of bug fixes.

### Describe alternatives you've considered
At the moment, we are freezing the the version of pip in our builds so we can use the legacy dependency resolver (that's been removed in current versions). We're essentially able to force install the latest version of PyArrow and ignore dbt's requirement. However, this conflict is last one preventing us from being able to use a current pip.

### Additional context
Is this feature database-specific? 
Yes, this is Snowflake-only (afaik)

### Who will this benefit?
Anyone using dbt who also needs to use PyArrow. The version of PyArrow required by dbt (by virtue of its snowflake-connector-python version requirement) is unstable.

### Are you interested in contributing this feature?
Yes!

**Comment by willsthompson** [comment]
For reference:

https://arrow.apache.org/blog/2020/07/24/1.0.0-release/
https://arrow.apache.org/release/2.0.0.html
https://arrow.apache.org/release/3.0.0.html

**Comment by jtcohen6** [comment]
Thanks @willsthompson, I completely agree! This is absolutely something we'll be doing before the next minor version of dbt (v0.20.0). It's a prerequisite for us to officially support python3.9 in the standard `dbt` installation (https://github.com/fishtown-analytics/dbt/issues/2985).

This will be resolved by #3148. We're planning to test it fully and merge it ahead of the first beta prerelease of v0.20.0.

**Comment by willsthompson** [comment]
Great to hear, thanks @jtcohen6!
