### ISSUE TITLE
Document the desired future state of dbt's "parse" step

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#3178]
### Description

Today, dbt has a step we call "parsing". This step has quite a few problems:

1. The code is difficult to reason about, because there is inherent ordering, and lots of different codepaths that end up being followed.
2. It runs serially. There are opportunities to parallelize everywhere.
3. A corollary to number 2 -- it is slow.
4. We'd like to evolve the code under the hood dramatically. To do so, we need to build a shared mental model for how it _could_ work.

So, let's build a new mental model for how parsing works.

### Outputs

The outputs of this work should definitely be written down. Internally at first, but eventually I am _100% sure_ we'll want to make this part of dbt's docs.

We need to make _some_ progress on this in two weeks, so we go into the next phase of work with some shared mental model for where we want to go.

There are two categories of things I'd like to see here:

1. Concrete problem statements: what, specifically about parsing today does not work well? How does that inform what we're going to do differently?
2. Mental models for how this should work. What are the stages? What are the interfaces between the stages? How should data flow, and what order should steps run in? This mental model can be leaky -- it does _not_ need to encapsulate all of the detail involved with parsing in dbt. But, it should be opinionated!

The goal is to make real progress on this by April 1, when we'll hope to embark on some experimental work in dbt's parsing code.

**Comment by gshank** [comment]
A number of internal documents have been produced that document the desired future state of dbt parsing. These documents are ongoing and will continue to be updated as we explore various issues and tickets.
