### ISSUE TITLE
Support commit hashes in dbt deps coming from a Git source

### ISSUE THREAD

**Issue by dmateusp** [fishtown-analytics/dbt#3268]
### Describe the feature

Ability to specify a commit hash as the `revision` for a dbt package coming from git.

### Describe alternatives you've considered

Use a branch or tag.

### Additional context

We are restructuring the way we use `dbt` at Earnest, part of it is having multiple autonomous teams with their own isolated `dbt` project (in team-specific GitHub repositories) depending on some common macros and conformed dimensions.

Right now we would have to create a new GitHub release to make a revision "available", and we would like to avoid that overhead. 

### Who will this benefit?

Teams that have private dbt libraries and don't want the overhead of releases.
Or folks that need a specific feature existing in a public library but pending release.

### Are you interested in contributing this feature?

Yes! I just worked on a [similar PR](https://github.com/fishtown-analytics/dbt/pull/3267), and I think the change would be relatively straightforward.
The code [here](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/clients/git.py#L13) needs to change.

**Comment by jtcohen6** [comment]
Thanks @dmateusp, this makes a lot of sense!

> Right now we would have to create a new GitHub release to make a revision "available", and we would like to avoid that overhead.

I buy it. Of course, some teams may choose to semantically version and release all internal packages, or develop detailed branch-naming conventions, but I agree that it's overkill for many—and I can see lots of situations (e.g. development, integration testing) where referencing a specific commit could come in handy.

I'd love to review a contribution for this, just as soon as I get a few minutes to review #3267 :)

**Comment by dmateusp** [comment]
This one should be ready to review too :) I'll probably have some conflicts with https://github.com/fishtown-analytics/dbt/pull/3267 to resolve so I'd suggest looking into https://github.com/fishtown-analytics/dbt/pull/3267 first
