### ISSUE TITLE
Issue with v0.19.1 BQ partitioning clause for incremental models

### ISSUE THREAD

**Issue by walshie4** [fishtown-analytics/dbt#3284]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

We have some models which are partitioned in BQ using the following config:
```
{{
    config(
      materialized='incremental',
      incremental_strategy = 'insert_overwrite',
      partition_by = {
        "field": "timestamp",
        "data_type": "timestamp"
      },
      cluster_by = "user_id",
      partitions = partitions_to_replace
    )
}}
```

Where `partitions_to_replace` is defined as the return value from a call to:
```
{% macro previous_dates_array(num_days) %}
  {% set date_array = ["CURRENT_DATE"] %}
  {% for i in range(1, num_days + 1) %}
    {{ date_array.append("DATE_SUB(CURRENT_DATE, INTERVAL " + i|string + " DAY)") }}
  {% endfor %}
  {{ return(date_array) }}
{% endmacro %}
```

The model has the incremental clause of:
```
{% if is_incremental() %}
    -- recalculate yesterday + today
    AND date(TIMESTAMP_MILLIS(ts)) in ({{ partitions_to_replace | join(',') }})
    {% endif %}
```

With version 0.19.0+ we see a new failure when running these models which seems to be because of code that looks like this getting compiled into our final SQL code:
```sql
    -- recalculate yesterday + today
    AND date(TIMESTAMP_MILLIS(ts)) in (CURRENT_DATE,DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY),DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY))
    
        ) as DBT_INTERNAL_SOURCE
        on FALSE

    when not matched by source
         and timestamp_trunc(DBT_INTERNAL_DEST.timestamp, day) in (
              CURRENT_DATE, DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY), DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY)
          ) 
        then delete

    when not matched then insert
```

The final `IN` clause there is the issue.  Here is another stand-alone query which fails for the same reason:
```sql
select timestamp_trunc(timestamp, day) in (
              CURRENT_DATE, DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY), DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY)
          ) 
from (select TIMESTAMP_MILLIS(1603430441147) as timestamp)
```

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Create a model which uses partitioning as described above and attempt to run that model.

### Expected behavior

That the model should compile and run without issue.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

Error:
```
  No matching signature for operator IN for argument types TIMESTAMP and {DATE} at [60:64]
  compiled SQL at target/run/honey_dbt/models/staging/stg_ext_heartbeat.sql

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:**
MacOS 10.15.7

**The output of `python --version`:**
Python 3.8.2

### Additional context
I've tried playing with `granularity` but that didn't uncover anything helpful.  Are we doing something incorrect here?

**Comment by jtcohen6** [comment]
Hey @walshie4, thanks for opening, and sorry for the confusion this caused!

The introduction of timestamp-partition granularity on BigQuery also heralded the introduction of real, honest-to-goodness timestamp-type partition columns. Previously, if you wanted to partition by a timestamp column, BigQuery required it to be `partition by date(timestamp_column)`, i.e. an expression that returns a `date` type. With the advent of granularities, BigQuery now accepts `partition by timestamp_trunc(timestamp_column, day)`, i.e. an expression that returns an actual `timestamp` type.

When implementing granularities, we decided that it made sense to keep the types of partition expressions consistent with the partition column's type. So if you're partitioning by a timestamp column, you should filter it by a timestamp value, too. I didn't appreciate at the time how this would be a breaking change for users who set static partition values via SQL expressions that explicitly return a `date` type—my apologies there.

We updated the docs site (https://github.com/fishtown-analytics/docs.getdbt.com/pull/578) to reflect the change for `insert_overwrite` + static partitions [here](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#static-partitions):

<img width="827" alt="Screen Shot 2021-04-22 at 2 30 13 PM" src="https://user-images.githubusercontent.com/13897643/115767707-61ab8b00-a377-11eb-8846-46e7696a09ca.png">


In any case, I'm hopeful that this is a really simple fix. Your model is partitioned by a timestamp-type column:
```
    partition_by = {
        "field": "timestamp",
        "data_type": "timestamp"
      },
```

Could you try rewriting the `previous_dates_array()` macro to return a `TIMESTAMP` type instead, by casting `DATE` values to `TIMESTAMP`:

```sql
{% macro previous_dates_array(num_days) %}
  {% set date_array = ["CAST(CURRENT_DATE AS TIMESTAMP)"] %}
  {% for i in range(1, num_days + 1) %}
    {{ date_array.append("TIMESTAMP_SUB(CAST(CURRENT_DATE AS TIMESTAMP), INTERVAL " + i|string + " DAY)") }}
  {% endfor %}
  {{ return(date_array) }}
{% endmacro %}
```

And let me know if that works?

**Comment by walshie4** [comment]
Interesting.  This all makes sense, and is what I had suspected was going on here, thanks for all the info.  I noticed the other caveat which was that we were using this same array for the clause:
```sql
{% if is_incremental() %}
  AND DATE(timestamp) IN ({{ partitions_to_replace|join(',') }})
{% endif %}
```

Which will cause a new error with the suggested change.  Have any ideas as to how we could still use this array for selecting partitions via an `IN` clause approach, but use `TIMESTAMP` functions to avoid the other error?

Thinking about this made me realize I should ask do we even need this clause?  Wouldn't that be basically the same thing as the `partitions_to_replace` generated clause?  Or is that being used on a different table?

**Comment by jtcohen6** [comment]
The `is_incremental()` is still necessary to limit the table scan when creating the (temp) table of new records. I think you could switch this out to be:
```sql
{% if is_incremental() %}
  AND TIMESTAMP_TRUNC(timestamp, DAY) IN ({{ partitions_to_replace|join(',') }})
{% endif %}
```
Or:
```sql
{% if is_incremental() %}
  AND DATE(timestamp) IN (
      {% for part in partitions_to_replace %}
          date({{ part }}) {{ ',' if not loop.last }}
      {% endfor %})
{% endif %}
```
