### ISSUE TITLE
docs block usage outside of description field in YAML fails to render ('doc' is undefined)

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt#3287]
### Describe the bug
If I try to reference a docs block outside of a description field, in this case, a parameter needed for `dbt-external-tables`, `LOCATION`, I get this error.
```
Failed to render models/source/src_schema.yml from project mart_ml: Compilation Error
  Could not render {{ doc("munge_headcount") }}: 'doc' is undefined
```

#### `models/source/blob_paths.md`
```
{% docs munge_headcount %}
N'/azureml/f4a1a8bd-f0c3-424d-a2ed-d1273ab6bdcb/munged_hc/HeadcountMunged.tsv'
{% enddocs %}
```

#### `models/source/src_schema.yml`
```yml
version: 2
sources:
  - name: ret_mng
    schema: munged
    description: blahblah
    tables:
      - name: headcount
        description: |
          the output file from `munge_headcount.py`
          blob path: {{ doc("munge_headcount") }}  # <- this works
        external:
          data_source: AttritionPipeline
          FILE_FORMAT: TabDelimited
          LOCATION: '{{ doc("munge_headcount") }}' # <- this does not
        columns: ...
```

### Expected behavior

I expect it to render and for the doc function to be found?

#### stacktrace
```python
 Failed to render models/source/src_schema.yml from project mart_ml: Compilation Error
    Could not render {{ doc("munge_headcount") }}: 'doc' is undefined
2021-04-22 18:22:16.416451 (MainThread): Traceback (most recent call last):
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/dbt/clients/jinja.py", line 501, in catch_jinja
    yield
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/dbt/clients/jinja.py", line 533, in render_template
    return template.render(ctx)
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/dbt/clients/jinja.py", line 187, in render
    return self.environment.handle_exception()
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/dbt/clients/jinja.py", line 138, in quoted_native_concat
    head = list(islice(nodes, 2))
  File "<template>", line 1, in top-level template code
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/Users/anders.swanson/opt/miniconda3/envs/dbtenv/lib/python3.6/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'doc' is undefined
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: Azure Synapse)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - sqlserver: 0.19.0.1
  - synapse: 0.19.0.1
```

**The operating system you're using:** macOS

**The output of `python --version`:** Python 3.6.12 :: Anaconda, Inc.

### Additional context

Perhaps I'm misappropriating the intended purpose of `doc()` and that this is really a better use case for `var()`?

### Update

If I had a variable to `dbt_project.yml`
```yaml
vars:
  headcount_path: '{{ doc(munge_headcount) }}'
```
then this will render properly...
```yaml
LOCATION: '{{ var("headcount_path") }}' 
```

**Comment by jtcohen6** [comment]
@swanderz Appreciate your thought process here! I agree with your assessment at the end:

> Perhaps I'm misappropriating the intended purpose of `doc()` and that this is really a better use case for `var()`?

The intended purpose behind docs blocks is that dbt'ers can write Markdown code, in Markdown files, and pass it into any `description` fields they want. They're not intended a way to share information across different types of properties.

By contrast, vars are usable almost anywhere. As soon as you want to share a value beyond `description` fields, vars are a reasonable way to do it. So I think this will actually work, no docs blocks needed:

```yml
vars:
  headcount_path: "N'/azureml/f4a1a8bd-f0c3-424d-a2ed-d1273ab6bdcb/munged_hc/HeadcountMunged.tsv'"
```

```yml
version: 2
sources:
  - name: ret_mng
    schema: munged
    description: blahblah
    tables:
      - name: headcount
        description: |
          the output file from `munge_headcount.py`
          blob path: {{ var("munge_headcount") }}  # <- this works
        external:
          data_source: AttritionPipeline
          FILE_FORMAT: TabDelimited
          LOCATION: '{{ var("munge_headcount") }}' # <- this does not
        columns: ...
```

Just be advised that vars must take literal values—string literals, numeric literals, or dict/array literals. They are _not_ Jinja rendered. So if you set a var to:
```
vars:
  headcount_path: '{{ doc(munge_headcount) }}'
```
The value of the `headcount_path` var will be the string literal `{{ doc(munge_headcount) }}`. Those aren't Jinja curlies, they're just the characters `{{` and `}}`.

**Comment by swanderz** [comment]
ok cool. I figured as much. Perhaps this change would prevent another newb like me from misconstruing `doc()`? We never say that `doc()` is only intended for the `description` key.
https://github.com/fishtown-analytics/docs.getdbt.com/pull/647
