### ISSUE TITLE
folders in compiled code

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#329]
All compiled code used to be nested in a folder named according to the name of the package it was a part of. Now that layer of nesting is gone and it makes it challenging figuring out what i'm looking at. If we didn't have a good reason to change this, we should ideally change it back... 

<img width="273" alt="screen shot 2017-03-14 at 6 04 01 pm" src="https://cloud.githubusercontent.com/assets/2341841/23924379/d184f212-08e0-11e7-88a5-2efc5453f0cf.png">

**Comment by cmcarthur** [comment]
One other thing I noticed here is we no longer print `target/` at the beginning of compile error output. Working on both of these now.

**Comment by cmcarthur** [comment]
Fixed by #331, now in development
