### ISSUE TITLE
 Mixed case-json keys not recognized in Redshift `SUPER`

### ISSUE THREAD

**Issue by karlanka** [fishtown-analytics/dbt#3290]
### Describe the bug
I am trying to parse a Redshift `SUPER` column that contains a json-struct where the keys are in mixed cases. I am supplying `sql_header="SET downcase_delimited_identifier TO FALSE;"` in the model's config but the value is not being picked up in the model.  It seems that the sql-header is not having any effect.

### Steps To Reproduce
I am able to reproduce the bug following the [Redshift documentation on querying Super](https://docs.aws.amazon.com/redshift/latest/dg/super-configurations.html).

I create a model `downcase_bug.sql` like this:
```
{{ config(
    materialized='table',
    sql_header="SET downcase_delimited_identifier TO FALSE;"
) }}

SELECT json_table.data."ITEMS"."Name",
       json_table.data."price"
FROM
  (SELECT json_parse('{"ITEMS":{"Name":"TV"}, "price": 345}') AS data) AS json_table
```

The table being created looks like this:

| name | price |
| ---- | ----- |
| NULL | 345   |

If I run this query in my sql client:
```
SET downcase_delimited_identifier TO FALSE;
SELECT json_table.data."ITEMS"."Name",
       json_table.data."price"
FROM
  (SELECT json_parse('{"ITEMS":{"Name":"TV"}, "price": 345}') AS data) AS json_table
```
The output is:
| Name | price |
| ---- | ----- |
| "TV" | 345   |

### Expected behavior
I expect the model being created to look like this:
| Name | price |
| ---- | ----- |
| "TV" | 345   |

### Screenshots and log output
Creation statement from running with `--debug`:
```
2021-04-23 08:32:49.359486 (Thread-1): On model.my_datamart.downcase_bug: /* {"app": "dbt", "dbt_version": "0.19.1", "profile_name": "dwh_developer", "target_name": "developer", "node_id": "model.my_datamart.downcase_bug"} */
SET downcase_delimited_identifier TO FALSE;

  create  table
    "dev"."dbt_karlanka_prototyping"."downcase_bug__dbt_tmp"


  as (


SELECT json_table.data."ITEMS"."Name",
       json_table.data."price"
FROM
  (SELECT json_parse('{"ITEMS":{"Name":"TV"}, "price": 345}') AS data) AS json_table
  );
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift 
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

Detailed version: `PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.25599`

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - postgres: 0.19.1
  - redshift: 0.19.1
  - snowflake: 0.19.1
```

**The operating system you're using:**
```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363
```
**The output of `python --version`:**
`Python 3.7.5`

**Comment by jtcohen6** [comment]
@karlanka It seems the session parameter must be set in separate query that runs prior to the SUPER-using query. It cannot be run together (semicolon-delineated) in the same query. I was able to confirm this with a local SQL-running tool.

For that reason, `sql_header` will not work for this purpose, but `pre_hook` will:

```sql
{{ config(
    materialized='table',
    pre_hook="SET downcase_delimited_identifier TO FALSE"
) }}

SELECT json_table.data."ITEMS"."Name",
       json_table.data."price"
FROM
  (SELECT json_parse('{"ITEMS":{"Name":"TV"}, "price": 345}') AS data) AS json_table
```

Name | price
-- | --
"TV" | 345
