### ISSUE TITLE
Generate run_results.json even when no nodes are selected

### ISSUE THREAD

**Issue by panasenco** [fishtown-analytics/dbt#3313]
### Describe the feature
I'd like the file `target/run_results.json` to be generated with an empty results list even when the selector selected no nodes. The current behavior is to not generate a new `run_results.json` when the selector returned no nodes.

A test run with no nodes selected is a legitimate occurence when using the `state:modified` selector.

### Describe alternatives you've considered
Parsing `dbt test` output for the string `WARNING: Nothing to do. Try checking your model configs and model specification args`. This is a bit hacky and unreliable though.

### Additional context
Using `dbt test` with the `state:modified` selector in my CI pipeline. I parse `run_results,json` to get the test outcome, but that file doesn't get generated when there are no model differences between the branch and PROD. However, the absence of `run_results.json` could also mean the test process somehow failed...

### Who will this benefit?
Anyone who depends on `run_results.json` - for example CI pipeline devs.

### Are you interested in contributing this feature?
I'll browse the source code and give it a shot, but no promises.

**Comment by jtcohen6** [comment]
@panasenco I buy it! Thanks so much for opening the issue, and for laying out your rationale so clearly. It looks like this was a super simple change, too.
