### ISSUE TITLE
Incomplete SQL compiled in dbt 0.20.0b1

### ISSUE THREAD

**Issue by swiffer** [fishtown-analytics/dbt#3317]
### Describe the bug
Running `dbt compile` results in partly incomplete sql generated where WITH() clauses are missing for ephemeral models when the table to built is also ephemeral

### Steps To Reproduce
with colors_flat.sql as
```sql
{{
    config(
        materialized='ephemeral'
    )
}}

with colors as (
    select * from {{ ref('base_colors') }}
),

colorclassifications as (
    select * from {{ ref('base_colorclassifications') }} where is_leaf
)

select * from ....
```

gets compiled to

```sql
with colors as (
    select * from __dbt__cte__base_colors
),

colorclassifications as (
    select * from __dbt__cte__base_colorclassifications where is_leaf
)
```

where `base_colors` and  `base_colorclassifications` are ephemeral models as well.

### Expected behavior
The compiled SQL for __dbt__cte__base_colors and __dbt__cte__base_colorclassifications is missing, it should be inlined instead

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0-b1
   latest version: 0.19.1

Your version of dbt is ahead of the latest release!

Plugins:
  - snowflake: 0.20.0b1
```

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.9.4

**Comment by kwigley** [comment]
This is addressed by https://github.com/fishtown-analytics/dbt/issues/3056, but it looks like the fix only made it in 0.19.*! I will pull the fix over into the current development branch and include in the next release. Thank you for testing the beta and catching this @swiffer!
