### ISSUE TITLE
Need a more recent version of git, and ssh-client installed in the dbt Docker image

### ISSUE THREAD

**Issue by dmateusp** [fishtown-analytics/dbt#3337]
### Describe the feature

I would like `ssh-client` to be added, and `git` to be updated in the dbt Docker image.

### Describe alternatives you've considered

Right now, at Earnest, we modify the dbt Docker image as part of the CI process

### Additional context

Now, dbt deps supports [using a subdirectory](https://github.com/fishtown-analytics/dbt/pull/3267) and using a specific [commit hash](https://github.com/fishtown-analytics/dbt/pull/3270), and we integrated those features into our CI.

However we need to install `ssh-client` and update `git` in order to be able to pull our shared dbt package which is hosted in a private GitHub repository.

### Who will this benefit?

People using the dbt image and pulling dependencies from repositories using ssh.

### Are you interested in contributing this feature?

Yes! However, since I last had a look, the Docker image changed quite a bit.

If someone could just help me out building the Docker image locally, I could test this with our Earnest CI and also check that the packages installed don't increase significantly the size of the image.

**Comment by jtcohen6** [comment]
Thanks for opening the issue @dmateusp, I buy it!

**Comment by kwigley** [comment]
@dmateusp I totally understand this! I'm asking a few more questions for my understanding 😄 

I'm just wondering what you mean by "we modify the dbt Docker image as part of the CI process"? Do you use `fishtownanalytics/dbt` as a base image for an image you manage? Is the goal to avoid having to manage your own Dockerfile similar to the example below?

```dockerfile
FROM fishtownanalytics/dbt:0.19.1

RUN printf "deb http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list.d/backports_git.list && \
    apt update && \
    apt install -y --no-install-recommends \
    git-man/buster-backports \
    git/buster-backports \
    ssh-client
```

**Comment by kwigley** [comment]
I was able to remove this in https://github.com/dbt-labs/dbt/pull/3785 after updating the base image of the docker image to use the latest stable debian release (https://github.com/dbt-labs/dbt/commit/b37f6a010e549f1f0150846e9f74526099e55a3f) 😎
