### ISSUE TITLE
Non-JSON response from Snowflake connection attempt results is not handled

### ISSUE THREAD

**Issue by barberscott** [fishtown-analytics/dbt#3350]
It is possible via the Snowflake OAuth/SSO pathway that our attempt to obtain an access_token will fail for a variety of reasons.  The resultant response may or may not be in JSON but this code assumes it always will be:

https://github.com/fishtown-analytics/dbt/blob/d8c261ffcfab0da7974310760a74d7858756c3ed/plugins/snowflake/dbt/adapters/snowflake/connections.py#L128-L132

and errors out with `Expecting value: line 1 column 1 (char 0)` when receiving a non-JSON response.

**Comment by jtcohen6** [comment]
Thanks for opening @barberscott, and for pointing to the relevant spot in the code!

I bet this is an easy thing to check and handle, the question will be doing it as quickly and reliably as possible. This is hardly my area of expertise, but from reading a bit online (i.e. [this SO post](https://stackoverflow.com/questions/44012811/python-requests-quickly-know-if-response-is-json-parsable)), it sounds like we _might_ be able to check the `requests` response metadata to see if the content type is JSON:
```python
result = requests.post(token_url, headers=headers, data=data) 
if result.headers.get('content-type') == 'application/json':
  result_json = result.json()
```
If the response isn't JSON, we should call `_get_access_token` again, until we have a response that is.

Any chance this is a fix you'd be interested in contributing? :)
