### ISSUE TITLE
dbt crashes: library libcrypto could not be found

### ISSUE THREAD

**Issue by GuillaumeDesforges** [fishtown-analytics/dbt#3366]
### Describe the bug
dbt command fails with `The library libcrypto could not be found`:

```
Running with dbt=0.19.1
Found 69 models, 0 tests, 0 snapshots, 0 analyses, 317 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

Encountered an error:
The library libcrypto could not be found
```

### Steps To Reproduce
```
python -m venv .venv
pip install dbt
dbt run
```

### Expected behavior
dbt should not crash

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - postgres: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - bigquery: 0.19.1
```

**The operating system you're using:**
NixOS

**The output of `python --version`:**

```
$ python --version
Python 3.8.7
```

### Additional context

Note that I have in my environment:
```
$ echo $LD_LIBRARY_PATH 
/nix/store/sipmc4wnbcws4vahqlf5i06zz7xgnp23-gcc-10.2.0-lib/lib:/nix/store/wmhdjm0x0n4ffqh908gkhah3zr1d29fd-openssl-1.1.1i/lib
$ ls /nix/store/wmhdjm0x0n4ffqh908gkhah3zr1d29fd-openssl-1.1.1i/lib
engines-1.1  libcrypto.so  libcrypto.so.1.1  libssl.so  libssl.so.1.1
```

which did the trick for the same kind of issue when I tried to use singer snowflake target.

**Comment by GuillaumeDesforges** [comment]
Thanks @jtcohen6 , indeed the code snippet above raises the error.

**Comment by GuillaumeDesforges** [comment]
To whomever might encounter this issue.

Turns out my system did not have `objdump`, which is required by `ctypes`, which otherwise *fails silently*. (??!)

On NixOs, installing `binutils-unwrapped` solves the issue.

**Comment by jtcohen6** [comment]
@GuillaumeDesforges Glad you were able to get to the bottom of it!

**Comment by parshvms** [comment]
hello - i;m getting `oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto` when i try to run the snowflake-sqlalchemy python connection in a docker image. Is there a solution to this problem? I'm using a docker desktop on windows machine.

**Comment by matwalk** [comment]
Hi! I've got the same error: oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto.
Any news about this?

**Comment by parshvms** [comment]
Apparently when i switched from conda to the python venv, this issue was gone. Try it out. I don't know the resolution.

**Comment by uberj** [comment]
This was my issue: https://github.com/Nitrokey/pynitrokey/issues/431
