### ISSUE TITLE
Tests with `severity: warn` are upgraded to errors with `--warn-error`

### ISSUE THREAD

**Issue by mirosval** [fishtown-analytics/dbt#3369]
### Describe the bug
We run dbt with `--warn-error` to avoid issues such as incorrectly specified model selector not selecting anything and then still returning successfully.

However this flag also causes the tests, that would otherwise return warnings thanks to their severity settings, return errors.

### Steps To Reproduce
1. have tests with `severity: warn` in them
2. `dbt --warn-error test`

### Expected behavior
The status of tests with `severity: warn` should be `warning` and not `failure` in the log and in `target/run_results.json`

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
﻿﻿﻿﻿﻿❯ dbt --version > pbcopy
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1

```

**Comment by jtcohen6** [comment]
@mirosval I appreciate you opening the issue! I don't think we're going to change the behavior here, however; this is exactly what the `--warn-error` flag exists to do. In "warn-as-error" mode, _anything_ that would be returned as a warning is instead returned as an error—whether that's an internal warning, a deprecation warning, or a warn-severity test.

If what you're after specifically is strictness for node selection and leniency for test results, you could try out a workflow like:

```
$ dbt --warn-error ls -s <selection criteria>
$ dbt test -m <same selection criteria>
```

**Comment by mirosval** [comment]
@jtcohen6 Thank you for your prompt response! 

My thinking was that the warnings from dbt are of a different kind as the warnings from the tests. The former representing a possible misconfiguration or misuse of dbt, the latter being a conscious decision taken by the user to downgrade the severity of a test. This thinking was based on the reading of the `dbt --help` which states:

```
  --warn-error          If dbt would normally warn, instead raise an exception. Examples include --models that selects nothing,
                        deprecations, configurations with no associated models, invalid test configurations, and missing sources/refs
                        in tests.
```

It is very specific about what kind of things are promoted to errors, but omits to mention the tests themselves.

Since this scenario arises only in case of tests and freshness, I think one solution might be to offer an additional flag on the test level, e.g. `dbt --warn-error test --warn no-upgrade -m <spec>` with values being `no-upgrade` and `upgrade`.

Otherwise maybe the documentation should state that the tests are included in the error upgrades

**Comment by jtcohen6** [comment]
Good call! I think the current implementation is the behavior we want, but we should definitely clarify this in the `--help` documentation, and in our [docs](https://docs.getdbt.com/reference/global-cli-flags#warnings-as-errors) as well.
