### ISSUE TITLE
[Tracking] Partial parsing polish

### ISSUE THREAD

**Issue by leahwicz** [fishtown-analytics/dbt#3371]
This is the list of work we want to complete to polish off partial parsing before we put it down and GA the v0.20.0 release

Todo:
- [x] add test coverage (https://github.com/fishtown-analytics/dbt/issues/3449)

**Comment by leahwicz** [comment]
This is the list of work we want to complete to polish off partial parsing before we put it down and GA the v0.20.0 release

Todo:
- [ ] TBD: @gshank and @kwigley to create checklist

**Comment by gshank** [comment]
- Handle doc references
- Test macros
- Test data tests, analyses
- Test snapshots
- Test seeds -- what happens with big files?
- Test disabled/enabled
- More logging, event data, including flag that partial parsing is actually happening
- More granular handling of dbt_project.yml file (hooks, etc)
- Minimum validation of yaml file: expected keys point to lists containing dictionaries with 'name' key
- Figure out what's going on with to_dict and schema_source_file (pp_dict is supposed to be skipped but isn't)
- Make all file_id methods properties so we are consistent in how they're called

**Comment by jtcohen6** [comment]
Thanks so much for the enumeration @gshank. Let's organize these into three priority groups:
- **p0:** Add test cases, handle buggy behavior (i.e. errors that brick entire parse)
- **p1:** Fast-but-wrong edge cases (e.g. changes to `docs`, nested macros, vars, env vars, "volatile" Jinja context variables)
- **p2:** Correct-but-slower-than-strictly-necessary cases (e.g. changes to profile/target, certain behavior around vars)

**Comment by jtcohen6** [comment]
Some known edge cases:
- Nested macro dependencies ([gist](https://gist.github.com/jtcohen6/0cf551655dd2d3e415da8252ce82c386))
- Volatile Jinja variable dependencies ([gist](https://gist.github.com/jtcohen6/00a17710341ff3f6f83e0c17be705c1f))

**Comment by jtcohen6** [comment]
> Handling of vars, env variables, etc.

We should split this up into more subtasks, and I think some of those subtasks should actually be p1s: dependencies on nested macros, env vars, and volatile Jinja variables are fast-and-incorrect today.

**Comment by jtcohen6** [comment]
I'm going to close this, given that it's the end of the cycle and we managed to hit all our P0s. Nice work team!
