### ISSUE TITLE
Error installing dbt from develop branch on M1

### ISSUE THREAD

**Issue by mvtemple** [fishtown-analytics/dbt#3375]
### Describe the bug
I'm trying to install dbt on my M1 mac (python 3.9.1) and need to use the Snowflake connector. Based on other issues I saw, I tried to install dbt from the develop branch until the 0.20 release. I got this error:
```
ERROR: Command errored out with exit status 1: /Users/meeravalliath/.pyenv/versions/3.9.1/envs/dbt/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/br/htcj0kr57lsb3s83p4ydqzzh0000gn/T/pip-install-dc7n96yz/grpcio_206327e5a6db4d8d8b8ce737a6021074/setup.py'"'"'; __file__='"'"'/private/var/folders/br/htcj0kr57lsb3s83p4ydqzzh0000gn/T/pip-install-dc7n96yz/grpcio_206327e5a6db4d8d8b8ce737a6021074/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/br/htcj0kr57lsb3s83p4ydqzzh0000gn/T/pip-record-k7do0l8o/install-record.txt --single-version-externally-managed --compile --install-headers /Users/meeravalliath/.pyenv/versions/3.9.1/envs/dbt/include/site/python3.9/grpcio Check the logs for full command output.
```

### Steps To Reproduce
>> pip install git+https://github.com/fishtown-analytics/dbt.git@develop

### Expected behavior
Dbt to install without error and be able to connect to Snowflake on my M1 mac.

### Screenshots and log output
![image](https://user-images.githubusercontent.com/83354336/118902132-fb1c7d00-b8e2-11eb-8215-16c0538ee605.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
zsh: command not found: dbt
```

**The operating system you're using:**
macOS Big Sur v11.2.3
**The output of `python --version`:**
Python 3.9.1

**Comment by jtcohen6** [comment]
Hey @mvtemple, thanks for opening the issue!

Could you paste the error message text? It's a bit hard to read the screenshot.

Also, are you using the latest versions of pip + setuptools?
```
pip --version
```
```
python3
>>> import setuptools
>>> setuptools.__version__
```

**Comment by mvtemple** [comment]
Hey @jtcohen6, attaching the output of the install command [here](https://github.com/fishtown-analytics/dbt/files/6512330/log.txt) as the output is _quite_ long. The error occurs while trying to install `grpcio`.

Confirmed I've updated pip and setuptools to the latest version and am still getting this error.

**Comment by jtcohen6** [comment]
@mvtemple I believe the dependency on `grpcio` may be coming from `google-api-core` [here](https://github.com/googleapis/python-api-core/blob/c4ff747db17cdeedb0eb2741b308c7b2d2a596fb/setup.py#L43). Could you try installing just the plugin you need:
```
# from PyPi
pip install dbt-snowflake==0.20.0b1

# from source
git clone https://github.com/fishtown-analytics/dbt.git
cd dbt
pip install -r plugins/snowflake
```

**Comment by mvtemple** [comment]
@jtcohen6 That worked!! Thank you so much for looking into this!
