### ISSUE TITLE
Rename _dbt_internal_test subquery alias

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3398]
Let's rename `_dbt_internal_test` here:

https://github.com/fishtown-analytics/dbt/blob/0f018ea5dd678d37668c819552328b3254c2f220/core/dbt/include/global_project/macros/materializations/test.sql#L4-L7

So that it doesn't start with an underscore. Believe it or not, this is a deal-breaker for some SQL syntaxes.

**Comment by vijaybalebail** [comment]
for Oracle , Nonquoted identifiers must begin with an alphabetic character from your database character set. Quoted identifiers can begin with any character.. Its recomended not to start with a _
