### ISSUE TITLE
dbt test understands dependencies incorrectly

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#340]
ever since we hooked tests on to models, `dbt test` now seems to believe that _tests depend on each other_, not just on their corresponding models. when I run `dbt test`, I no longer get consistent groups of 8 tests running simultaneously, I get groups of varying sizes, seeming to indicate that tests are running in some type of dependency order. but tests do not depend on each other.

**Comment by jthandy** [comment]
@cmcarthur @drewbanin I think this is a regression--this used to work correctly prior to recent changes.

**Comment by cmcarthur** [comment]
ha! this makes sense. I'll look at it.

**Comment by drewbanin** [comment]
![look at it](https://i.ytimg.com/vi/A0Lgv94QE_Q/hqdefault.jpg)

**Comment by cmcarthur** [comment]
Fix is in development, see #343
