### ISSUE TITLE
IDE creates checkpoint files with duplicated information that dbt does not ignore

### ISSUE THREAD

**Issue by eric-czech** [fishtown-analytics/dbt#3402]
### Describe the bug

I am using jupyter to edit files for a dbt project and by default, it saves checkpoint files in a directory along side all edited files.  For example, `schema.yml` file will have a copy made at `.ipynb_checkpoints/schema-checkpoint.yml`.  This then causes errors like:

```bash
> dbt run
Running with dbt=0.19.1
Encountered an error:
Compilation Error
  dbt found two schema.yml entries for the same resource named my_model. Resources and their associated columns may only be described a single time. To fix this, remove the resource entry for my_model in one of these files:
   - models/example/.ipynb_checkpoints/schema-checkpoint.yml
  models/example/schema.yml
```

How can I configure dbt to ignore everything under any `.ipynb_checkpoints` directory?

### Steps To Reproduce

- Bootstrap the tutorial project 
- Edit the schema.yml file in jupyter
- Try to execute `dbt run`

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - postgres: 0.19.1
  - redshift: 0.19.1
  - snowflake: 0.19.1
```

**The operating system you're using:**

Debian buster

**The output of `python --version`:**

Python 3.8.8

**Comment by jtcohen6** [comment]
Hey @eric-czech, this is the first I've ever heard of this. Out of curiosity, is there a reason why you prefer jupyter to other IDEs or text editors?

My understanding of `.ipynb_checkpoints` files is that they offer a simple form of version control, in the sense of "don't lose my work": jupyter auto-saves your changes into the checkpoint file, but only updates the actual file when you save manually. We highly, highly recommend that you save your files often (dbt invocations will only use the last-saved version of your files!), and version control your dbt project using git, which is very good at maintaining history and (so long as you commit early & often) preventing lost work.

Suffice to say, dbt doesn't know to ignore hidden files or directories if they're located within paths it cares about, in this case the [`source-paths`](https://docs.getdbt.com/reference/project-configs/source-paths) (`models/` directory). I could see us making a change to dbt, such that it ignores hidden files and folders by default, or updating the `-paths` project configs to support [glob-style syntax](https://docs.python.org/3/library/glob.html).

But my honest feeling is that the root of this issue has more to do with jupyter than to do with dbt. I'm open to being wrong about that, if this is a practice common to other IDEs or an experience shared by others members of the community.

In the meantime, I'm going to close this issue, and recommend a different solution: [It sounds like it's possible](https://stackoverflow.com/questions/51887758/is-there-a-way-to-disable-saving-to-checkpoints-for-jupyter-notebooks) to configure the `.ipynb_checkpoints` files to land in a totally separate folder, outside the resource paths that dbt cares about.

**Comment by eric-czech** [comment]
> Out of curiosity, is there a reason why you prefer jupyter to other IDEs or text editors?

We would like to use dbt alongside spark/pandas pipelines for which jupyterlab is a natural fit.  Using a different IDE just for dbt would be a minor nuisance.

> Suffice to say, dbt doesn't know to ignore hidden files or directories

Sounds good, that's the answer I was mostly looking for (so thanks).

> I could see us making a change to dbt, such that it ignores hidden files and folders by default

+1 to ignoring hidden paths by default.

> In the meantime, I'm going to close this issue, and recommend a different solution: It sounds like it's possible to configure the .ipynb_checkpoints files

That's a fine workaround (what I've been using).  I'm sure other jupyterlab users would hit the same issue though if there every comes a more compelling reason to support them better.  I'm surprised I'm the first to try it but 🤷‍♂️.

**Comment by jtcohen6** [comment]
Appreciate the quick answers!

> We would like to use dbt alongside spark/pandas pipelines for which jupyterlab is a natural fit. Using a different IDE just for dbt would be a minor nuisance.

Neat! I don't think this is a common practice today, but it certainly makes sense.

> +1 to ignoring hidden paths by default.

If there's general consensus that this would be A Good Thing, I'm open to it.

**Comment by terzieff** [comment]
I have a similar issue, just started exploring dbt today and I'm ending up with twice as many models being created/executed, because of these hidden Jupyter checkpoints directories in each model directory 😩  So +1 from me to ignoring hidden paths by default.

![image](https://user-images.githubusercontent.com/11526532/147488261-37bc4954-c5e6-4ba2-9aea-8e8ec842ac33.png)

**Comment by derycck** [comment]
I bring a solution to resolve the case of checkpoints generated by jupyter lab, with folders named ".ipynb_checkpoints".

Create a `.dbtignore` file at the root of the DBT project and insert the line bellow:
```
*.ipynb_checkpoints/
```
