### ISSUE TITLE
Add "tags" and "meta" attributes to Exposure schema

### ISSUE THREAD

**Issue by stkbailey** [fishtown-analytics/dbt#3404]
### Describe the feature
I would like to be able to tag and add metadata to exposures, so that dbt can serve as a system of record for major data-related initiatives. The current options are solid, but we have additional metadata we would like to add -- primarily so that we can use the exposure data in downstream systems.

### Describe alternatives you've considered
We can use some of the existing data fields but additional flexibility would be nice.

### Additional context
This feature is mentioned by a few commenters in issue [2835](https://github.com/fishtown-analytics/dbt/issues/2835) but it does not look like action has been taken.

### Who will this benefit?
This will be useful for people using exposures and will also bring the object into closer alignment with other resources.

### Are you interested in contributing this feature?
Yes, I will link the PR.

**Comment by jtcohen6** [comment]
@stkbailey I so agree. Adding `tags` and `meta` feels totally uncontroversial to me. There are lots of other directions I could see `exposures` heading in; this change wouldn't close any doors for us, and it would definitely represent an improvement over status quo.

Thanks for splitting this out from #2835, where it was getting lost in some very interesting discussion :)
