### ISSUE TITLE
Can't init project

### ISSUE THREAD

**Issue by rnestertsov** [fishtown-analytics/dbt#3406]
### Describe the bug
Getting an error while trying to init a project via `dbt init`.

### Steps To Reproduce
Run `dbt init proj1`.

### Expected behavior
Project is created.

### Screenshots and log output
```sh
~/w/dbt_play ❯❯❯ dbt init proj1                                                                                                    ⏎
Running with dbt=0.19.1
Creating dbt configuration folder at /Users/rnestertsov/.dbt
With sample profiles.yml for redshift
Encountered an error:
Runtime Error
  Could not find adapter type redshift!
```

### System information
**Which database are you using dbt with?**
- [x] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
```

**The operating system you're using:**
Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**The output of `python --version`:**
Python 3.9.5

### Additional context
DBT were installed using homebrew.

**Comment by jtcohen6** [comment]
Hey @rnestertsov, this sounds like an issue installing dbt. When running `dbt --version`, you don't seem to have any plugins installed. That would explain your error `Could not find adapter type redshift!` when running `dbt init`.

I believe the issue, in this case, is that you're installing dbt in a py39 environment, and one of the plugins does not yet support py39 (`dbt-snowflake==0.19.1`). That's okay, though: it sounds like you're only using Postgres and Redshift, and the latest version of both supports py39.

So your options are:
- Install via Homebrew in a py38 environment
- Install via pip in a py39 environment:
```
pip install dbt-postgres
pip install dbt-redshift
```

**Comment by rnestertsov** [comment]
Installing dbt-redshift adapter via pip in a py39 environment resolved the problem.

Thanks for your help on this!
