### ISSUE TITLE
Partial parsing: do minimal validation on schema file content

### ISSUE THREAD

**Issue by gshank** [fishtown-analytics/dbt#3426]
The partial parsing manipulation of schema file dictionaries (derived from yaml) depend on a few things being correct, such as the top level keys ('models', 'seeds', etc) having values that are lists, that the lists contain dictionaries, and the dictionaries have a 'name' key. If these condition are not correct the errors will not be clear or helpful ('key error', etc).

We should do some minimal validation on new schema file content to verify that the above conditions are true. (More specific validation is done in the schema parser itself.)

**Comment by jtcohen6** [comment]
Resolved by #3460
