### ISSUE TITLE
Update project load tracking for v0.20 parsing changes

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3438]
### Describe the feature

Let's add fields to `track_project_load` so we can account for / disambiguate between:
- Whether partial parsing is enabled (we use `is_partial_parse_enabled` for this today)
- Total number of files in the project (we use `path_count` for this today)
- Number of files actually re-parsed by partial parsing (this is what `path_count` represents in v0.20rc1, we should keep these separate)
- Whether the experimental parser is enabled
- Number of files eligible to be parsed by experimental parser (just models today, but could be more in the future)
- Number of files actually parsed by experimental parser

https://github.com/fishtown-analytics/dbt/blob/abe8e839458d0288f76cb6950e79c77e3b1627cc/core/dbt/parser/manifest.py#L599-L617

**Comment by kwigley** [comment]
adding:
- `parsed_path_count` -> `path_count` can represent the size of the project and amount of files eligible to be parsed while `parsed_path_count` will be the actual amount of files parsed
- `is_static_analysis_enabled` -> set if flag for experimental parser is turned on
- `static_analysis_path_count` -> number of files eligible to be parsed by experimental parser
- `static_analysis_parsed_path_count` -> number of files actually parsed by experimental parser
