### ISSUE TITLE
allow subset of new test materialization to be dispatched

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt#3465]
### Describe the feature
create a shim-able macro just the small part that might need adapter-specific tweaks.

https://github.com/fishtown-analytics/dbt/blob/9589dc91fa9dc3f29eaccc2f42c420833126919e/core/dbt/include/global_project/macros/materializations/test.sql#L42-L49

### Describe alternatives you've considered
overriding the entire `test` materialization. The downside with is a larger code footprint in community adapters that is a liability over time.

### Additional context
TSQL-dialect databases are impacted here.

### Who will this benefit?
Adapter maintainers!

### Are you interested in contributing this feature?
Already done :)

**Comment by jtcohen6** [comment]
Thanks for opening as an issue, too :)
