### ISSUE TITLE
add optional SSL parameters to the Postgres connector

### ISSUE THREAD

**Issue by JLDLaughlin** [fishtown-analytics/dbt#3472]
### Describe the feature
Add `sslcert`, `sslkey`, and `sslrootcert` parameters to the `PostgresCredentials` class, allowing their values to be used when connecting to a Postgres database.

### Describe alternatives you've considered
I guess an alternative is to not allow this! I don't think there's a specific alternative that would achieve the same goal.

### Additional context
This was originally requested for the community-supported `dbt-materialize` adapter. I [implemented this change for that adapter](https://github.com/MaterializeInc/materialize/commit/fb7f4aac10b310833608ae5ad6e93f9fe3c70e9f), but since it borrows heavily from the Postgres adapter, I thought it would be best to submit the change here as well! (Folks need this in order to connect to Materialize Cloud, which requires certificates.)

### Who will this benefit?
It will at least benefit dbt + Materialize users, but hopefully folks using dbt + Postgres, as well!

### Are you interested in contributing this feature?
Yes, I am!

**Comment by jtcohen6** [comment]
@JLDLaughlin Definitely in favor! Thanks for upstreaming the change :)
