### ISSUE TITLE
in-model config getting overwritten for packages

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#359]
This is only occurring in development. If I set a default materialization for an entire project, this is overriding in-model materialization config. It should not, and it does not in 0.7.1.

**Comment by cmcarthur** [comment]
oddly enough, the code that generates this has not changed in 8 months.

**Comment by cmcarthur** [comment]
@drewbanin is there some model specificity here that i'm missing? comment in source config reads:

```
   64 │         Config resolution order:
   65 │
   66 │          if this is a dependency model:
   67 │            - own project config
   68 │            - in-model config
   69 │            - active project config
   70 │          if this is a top-level model:
   71 │            - active project config
   72 │            - in-model config
   73 │         """
```

**Comment by drewbanin** [comment]
@cmcarthur unsure -- tbh i think the current implementation makes sense! Can look into whether or not this is actually a regression

**Comment by cmcarthur** [comment]
@drewbanin maybe it was not working properly before then? in any case, i think there's a specificity problem here. for example, I think it's weird that an own project config at the top level of a package like:

```yaml
models:
  snowplow:
    materialized: view
```

would override an in-model config, however this one feels like it should override the in-model config for `specific_model`:

```yaml
models:
   snowplow:
      specific_model:
        materialized: view
```

cc @jthandy are you expecting this to work like the second example?

**Comment by jthandy** [comment]
I agree with @drewbanin that it has been working this way all along. There is a reasonable debate to be had about which of these two is better--I don't have an extremely strong opinion as there have been instances where I could see both sides. However, I don't think we should change this at the current time—it is not a regression IMO.

**Comment by drewbanin** [comment]
ok, closing this. I think it's part of the bigger topic of making model configurations less onerous
