### ISSUE TITLE
when git is not installed, exit dbt and say so

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#360]
when git cli is not installed, `dbt deps` fails with:

```
`https://github.com/package` is not a valid dbt project
```

**Comment by cmcarthur** [comment]
alternatively, don't rely on git cli to pull dependencies at all

**Comment by cmcarthur** [comment]
cc @drewbanin i think this fits in with the Documentation & Usability milestone -- whatchu think

**Comment by drewbanin** [comment]
Sure, i buy that @cmcarthur
