### ISSUE TITLE
Experiment with "alter table append"

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#395]
http://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE_APPEND.html

This may be well suited for incremental models

**Comment by drewbanin** [comment]
Both source and dest tables must be permanent and must share identical schemas. This is impractical because of things like column expansion, column encodings, etc. Closing this, but let's keep this functionality in mind as it's super cool and occasionally useful

**Comment by davehowell** [comment]
I don't like that it can't be done in a transaction, but it is very fast as just a metadata operation.

I feel like it could be useful in these scenarios:
* Archiving historic data
* Migrating tables to another schema
* Some kind of bush-mechanic partitioning regime (view over union of date-specific tables or similar)
* Incremental loading, although the no-transactions is disconcerting
