### ISSUE TITLE
Document event tracking + opt-out

### ISSUE THREAD

**Issue by atharvai** [fishtown-analytics/dbt#399]
Currently DBT sends tracking events to fishtown-analytics' snowplow instance. How can we disable this tracking?

sample  log:
`Sending event: {'category': 'dbt', 'action': 'run_model', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000000078A01D0>]....}`

**Comment by drewbanin** [comment]
Hey @atharvai -- great question! This used to be documented, but I can't seem to find it over on Read The Docs.

You can disable anonymous event tracking by adding these lines to your `~/.dbt/profiles.yml` file.

```yml
config:
    send_anonymous_usage_stats: False
```

You can find more info about this [here](https://github.com/fishtown-analytics/dbt/blob/development/CHANGELOG.md#3-event-tracking-httpsgithubcomfishtown-analyticsdbtissues89)

I'll make sure to update the docs with this information. Thanks!

**Comment by drewbanin** [comment]
@atharvai FYI, we're moving our docs over to readme.io. Check out the updated usage statistics info [here](https://dbt.readme.io/v0.8.0/docs/configure-your-profile)

**Comment by userbradley** [comment]
@drewbanin the page comes back as blank on both chrome and safari
![image](https://user-images.githubusercontent.com/41597815/215148414-e6c0cd98-4089-40b3-b5b2-d5f64750037a.png)


Also can we please make this more well known as we don't exactly want to be sending back usage data when we dont even know what it's sending. Doesn't feel right, epsecially on internal instances

@TColl

**Comment by jtcohen6** [comment]
@userbradley Sorry about that, the links above are from several years ago. You can see updated docs here: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats

You can also see all the tracking code in this file: https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/tracking.py

**Comment by userbradley** [comment]
Thanks @joevandyk

**Comment by polmonso** [comment]
The documentation page doesn't mention how to turn the anonymous data usage off. Is still adding the snippet

```yaml
config:
    send_anonymous_usage_stats: False
some_dbt_project:
    ...
```

to the `.dbt/profiles.yml` the way to do it?

**Comment by dbeatty10** [comment]
@polmonso Here's the docs:
https://docs.getdbt.com/reference/global-configs/usage-stats

👍 Yep, adding the following within your `profiles.yml` is the way to go:
```yaml
config:
  send_anonymous_usage_stats: False
```

Then after you run your next `dbt` command, you can check your logs at `logs/dbt.log`. You should be able to find something like this to show that it worked:
```
'send_anonymous_usage_stats': False
```

**Comment by graydenshand** [comment]
I'm disappointed that this is the default behavior for the open source part of this project; I never opted into to your marketing emails, which you clearly are using this information for based on an email I got from your team today.
