### ISSUE TITLE
stacktrace when incomplete test schema - dbt test not called

### ISSUE THREAD

**Issue by eogilvy12** [fishtown-analytics/dbt#402]
Stacktrace error provided when dbt run command initiated for specific model due to incomplete schema.yml test

```
model_name:
  unique:
     -
```
field was left empty but dbt test was not called

**Comment by drewbanin** [comment]
This should raise a [compiler error](https://github.com/fishtown-analytics/dbt/blob/development/dbt/exceptions.py#L102) with a helpful message indicating the test name

**Comment by drewbanin** [comment]
We're making dbt use a json schema to validate `schema.yml` files. Closing this, as we'll fix this error, and most other types of malformed schema.yml issues
