### ISSUE TITLE
Packages / projects / repositories naming convention

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#405]
As we continue to focus more on user onboarding and growing the community, naming matters. Reading this is painful:

https://dbt.readme.io/docs/adding-a-package

We use the words package, project, and repository to refer to the exact same thing: the logical unit of code that is described in a `dbt_project.yml` config file. I feel strongly that we need to use a single noun everywhere. I have a slight preference for "package", but I care less about the specific noun than that there is a _single_ noun. Whatever that noun is, we should rename `dbt_project.yml` to `[noun].yml`—so, my suggestion is `package.yml`.

**Comment by cmcarthur** [comment]
I agree with the idea. I seem to remember that, in a previous conversation, @drewbanin and I came to the conclusion that package was the right noun (maybe I'm misremembering)

**Comment by drewbanin** [comment]
I wholly agree with the premise here. I like `package`! Let's:

- add a deprecation warning for `dbt_project.yml` and instead support a `package.yml` file
- add a deprecation warning for the `repositories:` config and instead support `packages:`
- change `dbt_modules` to `dbt_packages`?

anything else I'm missing?

**Comment by jthandy** [comment]
Can we do `packages` instead of `dbt_packages`? More consistent... I don't feel like we need to put `dbt_` in front of everything...

**Comment by sinter-demo** [comment]
Yes, let's get rid of the dbt prefixes!

**Comment by cmcarthur** [comment]
Hah this was me:

> Yes, let's get rid of the dbt prefixes!

**Comment by drewbanin** [comment]
Two words: packages, and projects. We nixed `repositories:`. Closing this
