### ISSUE TITLE
use latest versions of dependencies

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#423]
psycopg2 > 2.7.1?
sqlparse > 0.2.3?
csvkit > 1.0.2?
celery? do we even use this?
voluptuous > 0.10.5
snowflake-connector-python > 1.3.16

there are other, non-explicit dependencies that should be upgraded:

cryptography > 1.8.1

**Comment by drewbanin** [comment]
Changelogs:

[psycopg2](http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-7-2)
[sqlparse](https://github.com/andialbrecht/sqlparse/blob/master/CHANGELOG)
[csvkit](https://csvkit.readthedocs.io/en/1.0.2/changelog.html)
 - this is a major upgrade with some breaking changes to the CLI -- need to evaluate how that impacts the API
celery - we definitely don't use this directly -- it's a dep of the snowplow module. I'll investigate if we can remove it (I think we can)
[voluptuous](https://github.com/alecthomas/voluptuous/blob/master/CHANGELOG.md#0105)
[snowflake-connector-python](https://pypi.python.org/pypi/snowflake-connector-python/)

@cmcarthur i don't wholly understand the cryptography note -- should we add that to `install_requires`?

**Comment by drewbanin** [comment]
We can remove the `celery` dep if we upgrade `snowplow-tracker` to `0.8.0` but [it looks like](https://github.com/snowplow/snowplow-python-tracker/pull/186) there's a dep on `six=1.9.0` which makes things hard. Let's leave the celery requirement for now and revisit in the future.

**Comment by drewbanin** [comment]
Looks like csvkit's api is deprecated and we should use [agate](https://github.com/wireservice/agate) instead? Let's leave this alone for now

```
Help on package csvkit:

NAME
    csvkit

DESCRIPTION
    This module contains csvkit's superpowered alternative to the standard Python
    CSV reader and writer. It can be used as a drop-in replacement for the standard
    module.

    .. warn::

        Since version 1.0 csvkit relies on `agate <http://agate.rtfd.org>`_'s
    CSV reader and writer. This module is supported for legacy purposes only and you
    should migrate to using agate.

PACKAGE CONTENTS
...
```
