### ISSUE TITLE
package listing & description

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#426]
we don't maintain a central reference of which packages exist. we should at least document the key ones (snowplow, stripe, etc.)

**Comment by jthandy** [comment]
@cmcarthur @drewbanin I just updated this page: 

https://dbt.readme.io/docs/adding-a-package

I think this is good enough for now; not sure it's a great use of time to go a lot deeper on this for the moment. LMK if you disagree.

**Comment by drewbanin** [comment]
This is awesome! Great work @jthandy. I still think it would be good to make a microsite for this, but I'm ok holding off on that for now. Closing
