### ISSUE TITLE
macros should be able to call other macros

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#469]
This works if the macros are in the same file, but I think we can make this work across files by putting the underlying macro functions into the jinja context and parsing the macro sql twice. Agree @cmcarthur?

This will double down on our requirement that macros do not use `this`, `ref`, etc. I think that's ok though

**Comment by cmcarthur** [comment]
fixed by #466

**Comment by jranks123** [comment]
@cmcarthur @drewbanin I can't figure out from your subsequent PR how to call a macro from inside another macro when they aren't in the same file - do you have any pointers?

**Comment by drewbanin** [comment]
heya @jranks123! Sure thing, this is definitely possible today. Just make sure that both of these macros live inside of files in the `macros/` directory. For example:

```
-- macros/my_first_macro.sql

{% macro my_first_macro() -%}

  Hi {{ get_name() }}

{%- endmacro %}
```

```
-- macros/my_second_macro.sql

{% macro get_name() -%}

  Drew

{%- endmacro %}
```


Then, from a model:
```
-- models/my_model.sql

select '{{ my_first_macro()' as greeting
````

You should see the compiled SQL looks like:
```
select 'Hi Drew' as name
```

**Comment by darious** [comment]
This works great, but your final example is missing the closing }} so should be
```
-- models/my_model.sql

select '{{ my_first_macro() }}' as greeting
```

**Comment by drewbanin** [comment]
ha! you are very right - sorry about that one 😅

**Comment by jranks123** [comment]
@drewbanin @darious is it possible to pass down parameters through to the nested macro? I can't make it work!
