### ISSUE TITLE
Documentation for how to make materializations / schema tests

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#472]
- [x] Materialization docs [here](https://dbt.readme.io/v0.8/docs/creating-new-materializations)
- [x] Schema test docs [here](https://dbt.readme.io/v0.8/docs/custom-schema-tests)

**NOTE:** Make these pages public once this issue is closed

**Comment by drewbanin** [comment]
@jthandy mind taking a look at these?

**Comment by jthandy** [comment]
These are great! I made a tiny change to example model and field names for your schema test; I found your examples confusing so I just picked some really boring ones.

👍

**Comment by drewbanin** [comment]
Good idea @jthandy. Merging
