### ISSUE TITLE
--drop-existing doesn't work with dbt seed

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#515]
when attempting to recreate tables that had previously been built with `dbt seed`, an error message shows saying that the table already exists.

**Comment by drewbanin** [comment]
This can happen if there's a `view` with the same name as the `csv` file. Do you think that's what's happening here @jthandy?

**Comment by jthandy** [comment]
totally possible, i'm not sure.

**Comment by drewbanin** [comment]
`--drop-existing` is now deprecated, use `--full-refresh` instead.

We overhauled dbt's implementation of `seed` -- This particular error is handled by alerting the user that they're running a seed file with the same name as a view in the database.

https://github.com/fishtown-analytics/dbt/blob/development/dbt/adapters/default.py#L637
