### ISSUE TITLE
minimize downtime for incremental models with full-refresh

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#525]
incremental models should:
1. build
2. drop
3. rename

0.8.3 and 0.9.0a1 instead do drop, build, rename, leading to a potentially significant amount of time during which the model is unavailable for querying

**Comment by igrayson** [comment]
Should this be labeled as a bug? As of 0.8.3, the new behavior doesn't match our docs @ https://dbt.readme.io/v0.8/reference#section-refresh-incremental-models ; specifically, `--full-refresh` doesn't cause dbt to treat models as table models (table models continue to have the desired behavior of build/drop/rename in 0.8.3).

**Comment by drewbanin** [comment]
Thanks @igrayson

**Comment by drewbanin** [comment]
see also: https://github.com/fishtown-analytics/dbt/issues/653

**Comment by drewbanin** [comment]
The 0.13.x/0.14.0 implementation of incremental models for redshift/postgres is not transactionally consistent if an error occurs in an incremental model in `--full-refresh` mode. We should try to fix that at the same time we make minimize the incremental downtime for rebuilds
