### ISSUE TITLE
don't permit multiple models with the same name

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#527]
- at most one **enabled** model can occupy a given model name in a run

**Comment by drewbanin** [comment]
The cycle code lives in the [linker](https://github.com/fishtown-analytics/dbt/blob/development/dbt/linker.py#L29) -- I suspect that not all cycles are properly identified. Let's also write a test to confirm that cycles are handled correctly.

We can add a check for duplicate models [here](https://github.com/fishtown-analytics/dbt/blob/development/dbt/compilation.py#L253). If there are duplicated model names, we should raise a [compiler error](https://github.com/fishtown-analytics/dbt/blob/development/dbt/exceptions.py#L102)

**Comment by mturzanska** [comment]
I could work on this one over the weekend. Anyone working on it already / any blockers ?

**Comment by drewbanin** [comment]
@mturzanska nope, no one is working on this, but @jthandy and I just encountered it again today :)

The only catch is that multiple models can exist with the same name, but only one of them can be `enabled`. Each node adheres to [this](https://github.com/fishtown-analytics/dbt/blob/development/dbt/contracts/graph/parsed.py#L20-L45) contract.

It would be great to write a descriptive error message out to the user. Something like `Error: model 'events' is duplicated` works, but something like:

```
Error:
Found 2 models with the same name:
 - in package snowplow, models/base/events.sql
 - in package stripe: models/transformed/events.sql
```

(or similar) would be really great! New error functions can be created here [these](https://github.com/fishtown-analytics/dbt/blob/development/dbt/exceptions.py#L154).

Let me know if there's anything I can do to help!

**Comment by drewbanin** [comment]
This is going out in 0.9.1
