### ISSUE TITLE
hooks for tests

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#549]
Tests should begin/end with `on-run-start` and `on-run-end`

**Comment by norton120** [comment]
I'm trying to think of a schema test that would be sensitive to environmental variables.. I can't.

**Comment by drewbanin** [comment]
thanks @norton120 -- updated the description accordingly

**Comment by danielerapati** [comment]
`pre-hook`s or `post-hook`s could be really useful for data tests: often to fix a failing test it is not enough to know that it affects a certain number of rows, you also have to manually lookup which rows it affects.
For that a `post-hook` like `SELECT <failing rows> INTO <errors table> FROM {{ref(<model>) }} WHERE <test condition>` could be useful.

I believe this would be a change to the [TestRunner](https://github.com/fishtown-analytics/dbt/blob/b4480cb88f49bbaad30c77d25338cbfc4c0e9f85/dbt/node_runners.py#L434) somehow adding in the [hooks capability from ModelRunner](https://github.com/fishtown-analytics/dbt/blob/b4480cb88f49bbaad30c77d25338cbfc4c0e9f85/dbt/node_runners.py#L298): looks like a big change for a newcomer like myself, any useful tips or things I should really know before trying? e.g. Why was `class TestRunner(ModelRunner)`  discarded?

**Comment by drewbanin** [comment]
Hey @danielerapati - this is a great idea. I think that this would be an incredible feature, and I'd like to integrate it deeper into dbt than just as a post-hook. Presently, post-hooks are kind of a catch-all for things like grants, warehouse operations, etc. This feature is core enough to testing that it would make sense to just build the functionality right into dbt.

I made an issue for this over here: https://github.com/fishtown-analytics/dbt/issues/903

Feel free to comment on that with any further thoughts!

**Comment by drewbanin** [comment]
I'm going to close this, as hooks are intended for statements like grants, vacuums, etc. There's some merit to inserting audit records, but I imagine there's a better solution to that than inserting one record at a time... I'm really happy we were able to pull #903 out of this, as I think that will be a really great feature to add some day.

Happy to discuss if anyone feels inclined to re-open it!

**Comment by trevor-petach** [comment]
@drewbanin I know there has been a lot of discussion around audit logs for tests and the recent PR #3316 by @jtcohen6. However, 4 years have passed since this issue, and there is still no way to write an audit log of which tests were executed when and what the results were.

Is there any reason *not* to have pre- and post-hooks for tests?

**Comment by erenelci** [comment]
This is still highly needed, especially when tests require access to views that are only available through a secondary role, i.e. if "USE SECONDARY ROLES ALL;" is required as pre_hook.

**Comment by jtcohen6** [comment]
@erenelci Someone just opened a related issue over in `dbt-snowflake`: https://github.com/dbt-labs/dbt-snowflake/issues/449
