### ISSUE TITLE
enable jinja line statement syntax

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#552]
http://jinja.pocoo.org/docs/2.9/templates/#line-statements

This could improve code aesthetics significantly over the standard `{% ... %}` syntax.

**Comment by jthandy** [comment]
It's not clear to me what the correct line statement character should be. What's important is that the following interact together well:

- jinja line statement
- jinja comment
- sql comment
- sql multi-line comment

**Comment by drewbanin** [comment]
see also: https://github.com/fishtown-analytics/dbt/issues/458

**Comment by cmcarthur** [comment]
related to package management (namespacing import syntax)

**Comment by drewbanin** [comment]
this doesn't really solve any problems and it would be a _nightmare_ to implement with packages (ie. each package could use its own line statement prefix). Closing it
