### ISSUE TITLE
dbt --version should handle alpha releases gracefully

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#557]
This is obviously not correct :) 

```
λ dbt --version
installed version: 0.9.0a1
   latest version: 0.8.3
Your version of dbt is out of date! You can find instructions
    for upgrading here:

    https://dbt.readme.io/docs/installation
```

**Comment by mturzanska** [comment]
@drewbanin correct my if I'm wrong (very likely):
- the above version mismatch was caused by `.bumpversion.cfg` not being updated
- the real issue is [the regex](https://github.com/fishtown-analytics/dbt/blob/development/dbt/version.py#L18) in `__parse_version` that leaves out letters

**Comment by drewbanin** [comment]
Hey @mturzanska - I generally think dbt should handle versions a little better/smarter. Right now, `dbt --version` will check if the local version == the remote version (on Github master). If the versions are not equal, then dbt says "your version is out of date".

So yeah, part of this is improving the regex, and part is just tweaking the ux a little. Ideally, dbt would say something more helpful, or nothing, when you're ahead of master.
