### ISSUE TITLE
users should be able to call config multiple times within the same model

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#558]
### Issue

dbt's clobber configuration fields (eg. `materialized', `bind', etc) can be currently be specified in multiple `config()` blocks. This looks like:

```
{{ config(materialized='view') }}
{{ config(materialized='table') }}
```

Here, the model is correctly built as a table. A more realistic use case might involve a macro that _itself_ calls `config()` with some default arguments. Subsequent calls to `config()` may override some of this behavior. Eg:

```
-- macros/config.sql
{% macro base_config() %}
  {{ config(materialized='table', sort='timestamp', dist='id') }}
{% endmacro %}

-- models/some_model.sql

{{ base_config() }}
{{ config(dist='all') }}
```

While the paradigm works for dbt's clobber configs, it does not currently work for the append- and extend- configs (like `post-hooks` and `vars`, for instance).

### Append configs

Given:
```
{{ config({"post-hook": 'select 1 as id'}) }}
{{ config({"post-hook": 'select 2 as id'}) }}
```

Expected:
```
post-hooks == ["select 1 as id", "select 2 as id"]
```

### Extend configs
Given:
```
{{ config({"vars": {"abc": 123}) }}
{{ config({"vars": {"def": 456}) }}
```

Expected:
```
vars == {"abc": 123, "def": 456}
```

Todo:
 - [ ] Support the specification of append configs multiple times
 - [ ] Support the specification of extend configs multiple times
 - [ ] add test for multiple specifications of clobber, append, and extend configs

**Comment by cmcarthur** [comment]
@drewbanin in the context we've been discussing lately, i think configs like `post_hook` are very similar to `description`s should be processed in a very similar way. `description` is essentially a "clobber field." i have some ideas on how to implement this, i think it should be straightforward.
