### ISSUE TITLE
write docs on how to build a new dbt adapter

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#560]
If someone wants to write a new adapter, they should have clearly documented guidelines on what needs to be done.

**Comment by jrandrews** [comment]
This would be helpful for me if I'm able to help write the Hive adapter in #559

**Comment by drewbanin** [comment]
@jrandrews that's great! I will put some time into building out these docs soon!

**Comment by drewbanin** [comment]
preliminary docs are here: https://docs.getdbt.com/docs/building-new-database-adapters

These aren't perfect, but going to leave this issue open so we can revisit with recent changes to dbt

**Comment by drewbanin** [comment]
This page is pretty far out of date. Let's update it as a part of this issue: https://docs.getdbt.com/v0.12/docs/building-new-database-adapters

**Comment by drewbanin** [comment]
New docs are here: https://docs.getdbt.com/docs/building-a-new-adapter

Closing this
