### ISSUE TITLE
allow seeded files to be inserted into specific schemas

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#561]
Since 0.9.0 we have had the ability to build models to specific schemas. Enhance `dbt seed` to allow the same.

**Comment by alanmcruickshank** [comment]
I'd also love this feature. Would it be best to achieve this by filling out the `seed` command, or is it worth integrating that functionality as part of `run` so that we can use the schema functionality there (and bonus point of being able to seed and run concurrently)?

**Comment by drewbanin** [comment]
@alanmcruickshank our plan is to treat csv files as a special type of model. As such, they could be seeded with `dbt run`, tested, `ref`'d, and configured in the `dbt_project.yml` file. I think `dbt seed` will stick around, but it will essentially be a wrapper around `dbt run` with only CSV files selected. This would also permit concurrent CSV loading and model creation.

You can check out or progress on this feature here: https://github.com/fishtown-analytics/dbt/pull/618

**Comment by drewbanin** [comment]
added in 0.9.2. see https://github.com/fishtown-analytics/dbt/pull/668
