### ISSUE TITLE
snowflake - uppercase model names?

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#567]
This is a little confusing for new dbt users on snowflake. @cmcarthur should we default to uppercase model names? Or is uppercasing model names sufficient in your opinion?

**Comment by rbkleung** [comment]
Per my conversation with one of Snowflake's sales engineer today, here's what I learned:
- if you create table/view with double-quotes, then one must use double-quotes when referencing the table/view during its query.
- if you create table/view **without** double-quotes, Snowflake will automatically _transform_ the name to upper-case.  However, one can still query against the table/view using lower-case (even thought Snowflake's UI describes it as upper-case).

My current conclusion, Snowflake is case **insensitive** unless you make it explicit with double-quotes.

**Comment by drewbanin** [comment]
this is fixed in 0.10.1 with quoting config settings. Closing!
