### ISSUE TITLE
calling a macro in a package that calls another macro in that package

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#569]
In dbt_utils, the macro `get_url_parameter` calls macro `split_part`, also in the same package. Right now, attempting to use this in another package returns:

```
dbt.exceptions.CompilationException: Compilation Error in macro get_url_parameter (web/get_url_parameter.sql)
  'split_part' is undefined
```

**Comment by drewbanin** [comment]
This works correctly now, but the macro call must be prefixed with the package name, eg:

```sql
{% macro get_url_parameter %}
  {{ dbt_utils.split_part(....) }}
{% endmacro %}
```
