### ISSUE TITLE
cycle-detection finds cycles in commented-out code

### ISSUE THREAD

**Issue by HarlanH** [fishtown-analytics/dbt#584]
To my surprise, if you create a file called `asdf.sql`, this will throw a compile-time error:

```
-- {{ ref('asdf') }}

SELECT 1;
```

My expectation is that commented-out code is commented out for the purposes of compilation. I can see why that may be not something you'd want to fix, technically, but at a minimum a smarter error message would be helpful.

Still on dbt 0.8.3...

**Comment by drewbanin** [comment]
@HarlanH the `--` is a sql comment, but the jinja parser in dbt doesn't know anything about sql and does not treat that comment with any significance. You should instead use jinja comments to comment out jinja code:

```
{# 
  {{ ref('asdf') }}      <------ this won't throw an error because it won't be parsed 
#} 
```

If you do need to refer to the currently-running model, you can use the `{{ this }}` variable which will not build a self-edge in the graph, avoiding the cycle, but will interpolate `"schema"."table"`, 

We've discussed making `--` work as a "line comment" [1](https://github.com/fishtown-analytics/dbt/issues/552) [2](https://github.com/fishtown-analytics/dbt/issues/458) in the past, but we haven't implemented that yet.

I think we need better docs around sql/jinja comments, as this is often tricky and unintuitive. Let me know if you think there's anything else for us to do here.

Thanks!

**Comment by HarlanH** [comment]
ah, gotcha. Yeah, not sure what stopgap would help. Will ponder.

**Comment by drewbanin** [comment]
@HarlanH I'm going to close this issue, but please re-open if you think there's something that needs to change in dbt here!

**Comment by brandon-benchling** [comment]
I ran into this problem today when commenting out code to remove a dependency... by the dependency was still there. It left me pulling out my hair for a bit. Glad I ran across this thread.

**Comment by awshepard** [comment]
Ran across this as well - was about to file a bug report when I went deep into the issues list and found this thread. It's not just cycle detection, nonexistent nodes, etc. also run into this. Would a note about this be a worthwhile addition to the core documentation?
