### ISSUE TITLE
Hooks execution order

### ISSUE THREAD

**Issue by PhilLavoie** [fishtown-analytics/dbt#590]
We've recently encountered a scenario where we defined two global hooks in our project config:
```
on-run-start:
    - <hook1>
    - <hook2, depends on hook1> 
```
And found out to our dismay that `hook2` could run before `hook1` sometimes. 
Shouldn't the order be guaranteed? Intuitively, I would say yes, as this is a YAML list.

**Comment by drewbanin** [comment]
hey @PhilLavoie -- thanks for creating this issue. Which version of dbt are you using?

**Comment by PhilLavoie** [comment]
Hi :wave:,
version 0.9.0

**Comment by drewbanin** [comment]
Thanks @PhilLavoie. This looks to me like a regression in dbt.

I think some of the responsible code is [here](https://github.com/fishtown-analytics/dbt/blob/development/dbt/node_runners.py#L276-L277). We store the hooks as "operations" in the graph in an unordered way. When we pull them out, the order is possibly different than specified in the `dbt_project.yml` file.

Thanks for bringing this to our attention!

**Comment by PhilLavoie** [comment]
Ok @drewbanin! Thanks for taking care of it :)
