### ISSUE TITLE
csvkit 0.9.1 dependency - update to current version (1.0.2)

### ISSUE THREAD

**Issue by haylo75** [fishtown-analytics/dbt#597]
I just started using dbt and really like it so far.  We have a good handle on EL in our data pipeline to Redshift, with a need to tool out & template the T.  With that said, I manage a large suite of pip packages for our pipeline.  I tried adding dbt to my pip-compile package list but have come across a dependency conflict.

I noticed in setup.py there is a version-pegged dependency on csvkit==0.9.1.  From what I can see, this package is referenced solely in seeder.py, importing table and sql.  csvkit 0.9.1 was released on 2015-03-30.  The current version is 1.0.2, released on 2017-04-28.  Would it be possible to update this dependency?

**Comment by drewbanin** [comment]
Hey @haylo75 -- dbt uses `csvkit` as a library which, last I checked, it not really not how it's supposed to be used anymore.

dbt imports [table](https://github.com/wireservice/csvkit/blob/0.9.1/csvkit/table.py) and [sql](https://github.com/wireservice/csvkit/blob/0.9.1/csvkit/sql.py) from `csvkit`, but these modules don't exist in [newer releases](https://github.com/wireservice/csvkit/tree/master/csvkit) of csvkit anymore!

Our plan is to drop the `csvkit` dependency entirely and instead use [agate](https://github.com/wireservice/agate) directly for CSV-related things.

I just created a proper issue for this here: https://github.com/fishtown-analytics/dbt/issues/598. We intend to tackle this in the relatively short term.

Thanks for writing -- lmk if there's anything else I can help with!

**Comment by haylo75** [comment]
Thanks a lot for the quick response @drewbanin - I thought based on the CSV tagged tickets I read you might be moving away from csvkit.  agate is definitely a good move IMO.  I'll keep an eye on #598, thanks!

**Comment by drewbanin** [comment]
no prob @haylo75! Not sure if you've seen, but we have a pretty active [slack community](https://slack.getdbt.com/) -- feel free to pop in there if you have any other quick questions.

**Comment by haylo75** [comment]
Thanks, I didn't know about the slack community!
