### ISSUE TITLE
Replace csvkit with agate

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#598]
- [x] remove csvkit dep
- [x] return tablular data as agate dataframes
- [x] make `dbt seed` use `agate` + `csv` modules for reading csv files

**Comment by drewbanin** [comment]
This is going out in 0.9.2

1. Replaced by agate
2. https://github.com/fishtown-analytics/dbt/pull/665
3. https://github.com/fishtown-analytics/dbt/pull/618

**Comment by haylo75** [comment]
@drewbanin that's great news, thanks!  I'll be able to run dbt along with all my other pip packages now in a single virtualenv, now that the csvkit dependency is removed.

**Comment by drewbanin** [comment]
@haylo75 awesome!
