### ISSUE TITLE
drop models which no longer exist in a project

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#615]
How do we implement this? I'm afraid of dropping models too aggressively but this might be one of those "great power, great responsibility" scenarios. Some sort of dry-run + a confirmation dialog would go a long way to making me feel better about this.

A stopgap here is to just drop the entire schema, then re-run from scratch.

**Comment by atjones0011** [comment]
I made a suggestion in the Slack channel to DROP and CREATE the target schema. I think this is quite dangerous because of dependent objects. If there are any dependent objects, we'd have to run a DROP...CASCADE which could cause problems in other schemas.

**Comment by drewbanin** [comment]
Some updated thinking:

This isn't something that we think dbt should actually do. dbt projects should be built s.t. entire schemas can be dropped and recreated at any time. That's the approach we recommend. If folks want to selectively find "stale" relations, they can do so using system catalog tables, or by querying dbt's compiled `catalog.json` and `manifest.json` files.

Happy to discuss if anyone from the future finds this issue.
