### ISSUE TITLE
issues with concurrent transaction

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#653]
The proper way to atomically replace a view/table in Postgres/Redshift is:

1. begin transaction
2. rename model to "model_old"
3. rename new model to "model'"
4. commit
5. drop table "model_old"

Currently, dbt drops the table inside of the transaction, which can lead to errors like:

```
ERROR: table 12345 dropped by concurrent transaction
```

or 

```
could not complete because of conflict with concurrent transaction
```

Via @teej
See also: [this SO post](https://stackoverflow.com/questions/20692518/how-can-i-ensure-synchronous-ddl-operations-on-a-table-that-is-being-replaced)

To fix this, dbt's [table](https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/materializations/table.sql) and [view](https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/materializations/view.sql) materializations need to be updated to drop the old model _outside_ of the transaction.

This PR will ultimately require < 5 lines of code change, but since it involves the table and view materializations, we should be very cautious here. Is there a good way to write an integration test for this?

**Comment by abelsonlive** [comment]
you might be able to simulate this behavior by:

* starting a dbt run which builds a model in one thread
* in a concurrent thread attempt to access the result of this model

however i think the model would have to take long enough to build to ensure that the test doesn't sporadically pass.

**Comment by teej** [comment]
You can force this condition to trigger by adding a sleep in the model's SQL. You can sleep in Redshift with:

```SQL
CREATE OR REPLACE FUNCTION f_sleep (x float)
RETURNS bool IMMUTABLE
AS
$$
  from time import sleep
  sleep(x)
  return True
$$ LANGUAGE plpythonu;
```

**Comment by abelsonlive** [comment]
oooh nice idea @teej

**Comment by igrayson** [comment]
We only started seeing this issue when updating from `0.8.0` to `0.9.1`.

Is there any workaround? And, do we know which version introduced this issue?

**Comment by drewbanin** [comment]
@igrayson we overhauled how model materializations work in 0.9.0, but it looks like the core SQL logic was unchanged.

Ultimately, this is going to be a small code change, but it's a little daunting to make because Redshift's transaction management is pretty finicky.

Happy to point someone in the right direction if they're interested in tackling this, and if not, I think we'll be able to hit it pretty soon. @igrayson @teej @abelsonlive are you folks able to help test an alpha version of this fix when one is ready? That would go a long way towards making me feel good about any prospective fix.

**Comment by abelsonlive** [comment]
@drewbanin can definitely help test anything you put out... have been a bit swamped but might still take a stab at this if my schedule clears up

**Comment by drewbanin** [comment]
thanks @abelsonlive -- we're focused on getting 0.9.2 out, we'll tackle this one for 0.9.3

**Comment by allanw** [comment]
Sounds good - as discussed on the Slack channel, this could potentially also fix an issue I've been having where DBT is forced to wait indefinitely due to Redshift failing to execute some statements (e.g. `DROP VIEW`) within a transaction block. When I check the `stv_recents` Redshift table, the query is left in a 'running' state and doesn't complete.

**Comment by cmcarthur** [comment]
This change is going to apply to Redshift / Postgres / Snowflake

**Comment by louisguitton** [comment]
I could reproduce that bug when specifying a pre-hook at the model level like so [docs](https://docs.getdbt.com/docs/hooks#section-configuring-hooks) 

![image](https://user-images.githubusercontent.com/7823843/68283438-d69fdd80-007b-11ea-87ea-9dfe5b9ea80c.png)


`Running with dbt=0.14.3`

**Comment by drewbanin** [comment]
@louisguitton that's surprising -- can you tell me which database you're using? We have _definitely_ seen this issue when grants are applied to a _schema_, but i've never seen it happen when grants are applied to a specific model.

Eg, this can fail:
```
models:
  project-name:
    post-hook: "grant select on all tables in schema {{ this.schema }} to db_reader"
```
or
```
models:
  project-name:
    post-hook: "grant usage on schema {{ this.schema }} to db_reader"
```

What's the exact error message that you're seeing from the database?

**Comment by louisguitton** [comment]
Thanks for following up @drewbanin .
I'm using Redshift, and a pre_hook that creates 1 UDF.
I'm running `dbt run --models model_1 model_2` with 8 threads and I get 
```
Completed with 1 error and 0 warnings:

Database Error in model stg_localytics__users_match_viewed (models/staging/localytics/stg_localytics__users_match_viewed.sql)
  could not complete because of conflict with concurrent transaction
  compiled SQL at target/compiled/of_models/staging/localytics/stg_localytics__users_match_viewed.sql
```

Due to the error message, I assume this is to be expected: the UDF is created twice (once for model_1 and once for model_2) on separate threads so they end up being conflicting concurrent transactions.

If I run `dbt run --models model_1 && dbt run --models model_2` it works fine.

I guess then I'm approaching creating the UDFs wrong.

**Comment by drewbanin** [comment]
Ah! ok - are you able to use something like an [operation](https://docs.getdbt.com/docs/using-operations) to create these UDFs? Ideally Redshift would let you create UDFs transactionally, but I suppose there isn't a ton of merit to creating the same UDF once for each model anyway
