### ISSUE TITLE
don't use `master` connection for on-run-start|end

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#657]
This can lead to timeout errors on Snowflake and Redshift, eg:

```
DatabaseException: Database Error
  server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

The `master` connection is used throughout the run, so it's a little perplexing that it somehow gets disconnected. In particular, it looks like this happens when dbt calls

```
adapter.clear_transaction(profile)
```

in the ModelRunner. The line that fails is a `BEGIN` statement.

**Comment by cmcarthur** [comment]
fixed by #693
