### ISSUE TITLE
investigate snowplow-tracker dependency

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#692]
This hasn't been updated in a while -- should we contribute back to, or fork this dep to get it up-to-date?

**Comment by tayloramurphy** [comment]
I ran into a dependency issue with dbt using [pipenv](https://github.com/pypa/pipenv). I'm unable to generate a lockfile with dbt because the snowplow tracker is pinned to celery v3.1.11 (almost 4 years old at this point) and dbt requires 3.1.23. 

I'm attempting to make a PR to the main repo, but it's a bit tedious to say the least.

**Comment by tayloramurphy** [comment]
Unfortunately, trying to simply get the tests up and running for the repo without changing any of the code has been a nightmare. 

So far I've deleted all of the references to `pip install -r requirements.txt` in `run-tests.sh`, updated the celery dependency in `setup.py` to 3.1.23, and I've updated the requirements-test.txt file to the following (note that gevent is an upgrade too):

```
celery==3.1.23
coveralls==1.1
freezegun==0.3.7
gevent==1.1.2
greenlet==0.4.10
httmock==1.2.5
pycontracts==1.7.6
pytest-cov==2.3.1
pytest==3.0.2
redis==2.9.1
requests==2.2.1
six==1.9.0
```

I'm able to get the `./run-tests.sh deploy` and `./run-tests.sh test` commands to run with the following errors 

<details>
============================================= FAILURES ==============================================
___________________________ IntegrationTest.test_integration_redis_custom ___________________________

self = <snowplow_tracker.test.integration.test_integration.IntegrationTest testMethod=test_integration_redis_custom>

    def test_integration_redis_custom(self):
        r = redis.StrictRedis(db=1)
        t = tracker.Tracker([emitters.RedisEmitter(rdb=r, key="custom_key")], default_subject)
>       t.track_page_view("http://www.example.com")

snowplow_tracker/test/integration/test_integration.py:252:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<decorator-gen-33>:2: in track_page_view
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/tracker.py:212: in track_page_view
    return self.complete_payload(pb, context, tstamp)
<decorator-gen-32>:2: in complete_payload
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/tracker.py:189: in complete_payload
    return self.track(pb)
<decorator-gen-31>:2: in track
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/tracker.py:154: in track
    emitter.input(pb.nv_pairs)
<decorator-gen-22>:2: in input
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/emitters.py:431: in input
    self.rdb.rpush(self.key, json.dumps(payload))
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/client.py:1107: in rpush
    return self.execute_command('RPUSH', name, *values)
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/client.py:464: in execute_command
    connection.send_command(*args)
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/connection.py:334: in send_command
    self.send_packed_command(self.pack_command(*args))
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/connection.py:316: in send_packed_command
    self.connect()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Connection<host=localhost,port=6379,db=1>

    def connect(self):
        "Connects to the Redis server if not already connected"
        if self._sock:
            return
        try:
            sock = self._connect()
        except socket.error:
            e = sys.exc_info()[1]
>           raise ConnectionError(self._error_message(e))
E           ConnectionError: Error 61 connecting localhost:6379. Connection refused.

../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/connection.py:253: ConnectionError
__________________________ IntegrationTest.test_integration_redis_default ___________________________

self = <snowplow_tracker.test.integration.test_integration.IntegrationTest testMethod=test_integration_redis_default>

    def test_integration_redis_default(self):
        r = redis.StrictRedis()
        t = tracker.Tracker([emitters.RedisEmitter()], default_subject)
>       t.track_page_view("http://www.example.com")

snowplow_tracker/test/integration/test_integration.py:244:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<decorator-gen-33>:2: in track_page_view
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/tracker.py:212: in track_page_view
    return self.complete_payload(pb, context, tstamp)
<decorator-gen-32>:2: in complete_payload
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/tracker.py:189: in complete_payload
    return self.track(pb)
<decorator-gen-31>:2: in track
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/tracker.py:154: in track
    emitter.input(pb.nv_pairs)
<decorator-gen-22>:2: in input
    ???
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/contracts/main.py:280: in contracts_checker
    result = function_(*args, **kwargs)
snowplow_tracker/emitters.py:431: in input
    self.rdb.rpush(self.key, json.dumps(payload))
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/client.py:1107: in rpush
    return self.execute_command('RPUSH', name, *values)
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/client.py:464: in execute_command
    connection.send_command(*args)
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/connection.py:334: in send_command
    self.send_packed_command(self.pack_command(*args))
../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/connection.py:316: in send_packed_command
    self.connect()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Connection<host=localhost,port=6379,db=0>

    def connect(self):
        "Connects to the Redis server if not already connected"
        if self._sock:
            return
        try:
            sock = self._connect()
        except socket.error:
            e = sys.exc_info()[1]
>           raise ConnectionError(self._error_message(e))
E           ConnectionError: Error 61 connecting localhost:6379. Connection refused.

../../../../.pyenv/versions/2.7.12/envs/tracker27/lib/python2.7/site-packages/redis/connection.py:253: ConnectionError
___________________________________ TestTracker.test_flush_timer ____________________________________

self = <snowplow_tracker.test.unit.test_tracker.TestTracker testMethod=test_flush_timer>

    def test_flush_timer(self):
        e1 = Emitter("d3rkrsqld9gmqf.cloudfront.net", method="post", buffer_size=10)
        t = Tracker(e1, namespace="cloudfront", encode_base64=False, app_id="AF003")
        e1.set_flush_timer(3)
        t.track_page_view("http://snowplowanalytics.com/blog/2016/09/22/introducing-sauna-a-decisioning-and-response-platform/")
        t.track_page_view("http://snowplowanalytics.com/blog/2016/03/17/2015-2016-winternship-wrapup/")
        t.track_page_view("http://snowplowanalytics.com/blog/2016/07/31/iglu-r5-scinde-dawk-released/")
        self.assertEqual(len(e1.buffer), 3)
        time.sleep(4)
>       self.assertEqual(len(e1.buffer), 0)
E       AssertionError: 3 != 0

snowplow_tracker/test/unit/test_tracker.py:86: AssertionError
================================ 3 failed, 28 passed in 6.25 seconds ================================
-> [1]
</details>

Which makes it seem like redis isn't running / exposed on the vagrant instance - so who knows what tests would pass or fail if it was able to connect. But I've got to switch to other things unfortunately so I can't devote much more time to this. Sorry!

**Comment by tayloramurphy** [comment]
I just did a new `vagrant up` and redis is running based on me running `redis-cli ping` and getting `PONG` back. It may not properly exposed to port 6379.

I'll admit though I'm stumbling in the dark here as I'm kind of haphazardly running things to see if things are working - I don't have the full context/understanding of how everything is supposed to plug together.

**Comment by drewbanin** [comment]
I'm going to either try to make a PR against the repo, or just fork it and remove the celery and redis deps. I think this is a big source of dep incompatibility for dbt users, and it doesn't sound like the Snowplow folks have cycles to work on it at the moment

**Comment by cmcarthur** [comment]
@beckjake discovered that this package is incompatible with Python 3.7 due to use of `async` as a variable name: https://github.com/snowplow/snowplow-python-tracker/blob/master/snowplow_tracker/tracker.py#L638

we should address this for the betsy ross release

**Comment by cmcarthur** [comment]
let's maintain a fork 🍴

**Comment by drewbanin** [comment]
A fork of the repo with a PR to trim down the requirements list is here:
https://github.com/fishtown-analytics/snowplow-python-tracker/pull/1

Let's get that PR merged, then use this issue to point dbt to the fork

**Comment by drewbanin** [comment]
We switched dbt to use a fork of `snowplow-python-tracker` with more flexible deps here: https://github.com/fishtown-analytics/dbt/pull/848/files
