### ISSUE TITLE
use psycopg2-binary dep

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#704]
via http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

**Comment by michael-erasmus** [comment]
Hey @drewbanin! I installed just `psycopg2` (not the binary distribution)

**Comment by drewbanin** [comment]
great, thanks @michael-erasmus. I think that's what we'll do for the next release. Check the above PR for more info :)

Thanks for your help!

**Comment by michael-erasmus** [comment]
That's awesome, thanks @drewbanin!

**Comment by drewbanin** [comment]
Merged in #807 - closing
