### ISSUE TITLE
optional quoting for CSV column names?

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#707]
this should probably be off by default, but could be configurable on a per-seed basis

**Comment by joevandyk** [comment]
Yes, this would be nice. I have a spreadsheet with column headers like `1/1/2016`.

**Comment by drewbanin** [comment]
dbt seed is well suited for static mapping files which change infrequently. In those cases, I imagine dbt users have the ability to manually edit their csv column names. If new seeds are being added with such regularity that their header columns can't be feasibly updated, then `dbt seed` is probably the wrong tool for the job.

Closing, but happy to discuss!

**Comment by joevandyk** [comment]
Hm, it would be nice to be able to have column headers in the database like "1/1/2016" for some things. Without quoting, that's not possible.

**Comment by joevandyk** [comment]
Is there a reason to not always quote the column headers?

**Comment by drewbanin** [comment]
Yeah, quoting can be a big pain cross-database. On Snowflake, quoting [can be a real pain](https://docs.getdbt.com/docs/configuring-quoting#section-snowflake) for instance. I'm unsure why `1/1/2016` would be at all preferable to `1_1_2016`, for instance. On BigQuery, field names that start with numbers aren't even allowed!

I don't think that your desire to do this is unreasonable, but it's not something I'm that I think dbt should support. The right way to do this is to optionally allow quoting, and that's just a whole lot of code (and bug surface area!) for a relatively narrow use case IMO
