### ISSUE TITLE
Implement atomic swap for Snowflake

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#724]
Snowflake doesn't have a concept of transactions as Redshift does. If it succeeds in creating a `MODEL_NAME__dbt_tmp` view/table but encounters an error before renaming it to `MODEL_NAME`, the tmp view/table sticks around. The user must manually drop the tmp view/table, or the next run will fail (as below), in either case yielding a disruption to the workflow.

```
Snowflake error: 002002 (42710): SQL compilation error:
Object 'SCHEMA.MODEL_NAME__DBT_TMP' already exists.
```

This has been caused by failing post-hooks, which cannot currently be after-committed due to [this issue](https://github.com/fishtown-analytics/dbt/issues/723).

A simple solution could be to replace
```
On MODEL: create view "SCHEMA"."MODEL__dbt_tmp" as (
```
with
```
On MODEL: create or replace view "SCHEMA"."MODEL__dbt_tmp" as (
```
but after a cursory look I'm not sure where that code is generated within dbt.

**Comment by cmcarthur** [comment]
look into snowflake atomic swap. then instead of doing: 

create temp, drop old, rename

do:

create temp, atomic swap, drop old

**Comment by jthandy** [comment]
@cmcarthur It seems possible in the flow that you're suggesting that there could still be a leftover temporary table in certain error conditions. I had kind of assumed that we would need to explicitly check for the existence of such a temporary table in the materialization code and drop it if it existed. thoughts on that?

**Comment by drewbanin** [comment]
@jthandy yeah, i think you're right. The more direct approach might be to use
```
create or replace table/view ...
```

as noted above by @jtcohen6

**Comment by cmcarthur** [comment]
This may not be an issue right now, because of quoting changes and improvements to how we drop tmp relations before running models.

But there is a bigger issue around Snowflake transactions. We write materialization code assuming transactional DDL is possible. Snowflake does not have any transactional DDL. So while this code might work fine today, it would be easy for us to make a simple seeming change that actually creates major dbt bugs.

Kicking this out of 0.10.2 but we should review this later on.

**Comment by drewbanin** [comment]
We don't need to atomic swap _ever_ on Snowflake, as the best option is to use `create or replace {table|view}`. If we do need to do a drop/swap in the future, we should use the atomic swap functionality. For the time being though, I don't think there's anything to do here. Going to close this.

**Comment by jthandy** [comment]
@drewbanin is that what we're doing right now--`create or replace (...)`? 

that's new-ish, right?

**Comment by drewbanin** [comment]
@jthandy yeah - this is (relatively) new. I think we added it in 0.11.0, as we had _tons_ of issues with Snowflake relations when switching models from table <--> view materializations. You can find more info about this in the PR https://github.com/fishtown-analytics/dbt/pull/940
