### ISSUE TITLE
pull out static refs during compilation

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#746]
Presently, dbt needs to compile jinja macros twice: once during parsing and again when the macro is actually invoked by a model.

Since the parsing step doesn't run statements, the results of statement calls in parsing do not match the expected values for the runtime execution. This means that pretty reasonable looking code will fail during parsing. For example:
```
{% macro my_macro() %}
  {% call statement('some_statement', fetch_result=True) %}
    select count(*) from public.data
  {% endcall %}


  {% set results = load_result('some_statement') %}
  {% set count = results.table[0] %} <------ this fails, as `results` is `none`
{% endmacro %}
```

Instead, dbt should statically analyze the macro AST to determine if `ref` calls exist in the macro. The macro won't actually be invoked in parsing, and this class of errors will disappear. Further, macro code like this can be greatly simplified

**Comment by drewbanin** [comment]
we can revisit this someday, but I don't imagine us tackling this in the 6-month time horizon. Closing as wontfix
