### ISSUE TITLE
Add an expiry date to models

### ISSUE THREAD

**Issue by pierredilauro** [fishtown-analytics/dbt#748]
Hi,

It would be nice to have the possibility to put an expiry date to models. I would come very handy for short-lived models like AB tests. Once the expiry date has been reached, the model would stop running when executing dbt run.

This could be a config option.

**Comment by drewbanin** [comment]
cool idea - thanks @pierredilauro :)

**Comment by HarlanH** [comment]
I just implemented a data test with a hard-coded date where it takes effect, to give us time to fix the underlying bug. 🙄 So yeah, `enabled_before` or `enabled_after` might be generally useful?

**Comment by drewbanin** [comment]
I'd recommend using jinja templating to achieve this:

```
{% set currentDate = modules.datetime.date.today() %}
{% set disabledAfter = modules.datetime.date(2019, 1, 1) %}

{{ config(enabled=currentDate < disabledAfter) }}
```

I just noticed that these modules aren't currently documented. I'm going to close this issue, but will add the docs shortly! The two modules available are:
```
modules.datetime
modules.pytz
```
