### ISSUE TITLE
dbt describe

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#749]
This would be an interesting precursor to `dbt docs generate`. Essentially, functionality to run a set of descriptive statistics on an existing source or model node and output the results on the command line. I don't have super-strong feelings about specifically what descriptive statistics this should provide by default. Both R and Pandas have similar functions to generate a whole set of descriptive statistics based on a data frame input; these act as convenience functions for analysts that are just beginning to learn about a particular data set and want to do so quickly. Here's an [example](https://www.statmethods.net/stats/descriptives.html).

This implementation could later be used in the documentation features to provide the summary statistics that would be included in the docs.

I think one of the things we might want to consider here is whether we actually write all of the queries in SQL to do this and run them against the warehouse or whether we retrieve some randomized dataset and run the stats on that in memory. There are drawbacks to both approaches.

**Comment by drewbanin** [comment]
I think it's more likely that we implement this as a macro (a la [audit-helper](https://github.com/fishtown-analytics/dbt-audit-helper)) than as a top-level command in dbt. Closing this.
