### ISSUE TITLE
use IAM auth for Redshift

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#757]
We can use boto3's `get_cluster_credentials` to get temp creds, then auth with those

**Comment by danielchalef** [comment]
I'd be happy to contribute this. Would you recommend I subclass and extend `RedshiftAdapter` or modify `RedshiftAdapter`?

**Comment by drewbanin** [comment]
hey @danielchalef - that's great! I would just modify the `RedshiftAdapter`. We have [different methods](https://github.com/fishtown-analytics/dbt/blob/development/dbt/adapters/bigquery/impl.py#L110) for authing with BigQuery -- you may be able to use some of that code as an example.

Happy to help here however I can!

**Comment by danielchalef** [comment]
See PR #769 . Let me know if you'd like any mods. I noticed that the PR did not pass a codeclimate check.

**Comment by drewbanin** [comment]
Just merged #818 to add support for this feature. Thanks for the suggestion and the initial implementation @danielchalef :)
