### ISSUE TITLE
dbt's handle_and_check should return a set of run results

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#759]
we don't have a standard way of writing out invocation results. an example result might be:

```
{
  "node": "models.redshift.columns",
  "started_at": "...",
  "ended_at": "...",
  "duration_seconds": 0.01
  "status": "success",
  "result": "CREATE TABLE"
}
```

we want to standardize this so it can be easily written to disk.

__tasks:__
- create the object, and wire it up everywhere we execute dbt nodes.

__questions:__
- is there an invocation result for a model compilation?
- how much detail do we store for errors?

**Comment by cmcarthur** [comment]
in RunnableTask (`task/base_task.py`), we have both the set of results, as well as the project (`self.project`). this seems like the appropriate place to write the invocation result object out to disk.

the path that it writes to should be `target/invocations/{timestamp}.json`

each node_runner returns a RunModelResult object. `runner.py` does a thread pool parallel map over the nodes and spits out a list of these objects. so we need to do things:

- modify RunModelResult to include a start and end timestamp
- add serialize to RunModelResult
- write the list of RunModelResults out to disk

**Comment by cmcarthur** [comment]
envelope:

```
{
  "task_type": "run",
  "started_at": "...",
  "finished_at": "...",
  "status": "...",
  "results": [
  ]
}
```

**Comment by cmcarthur** [comment]
child_map is depends_on, parent_map is the inverse

```
"child_map": {
    "model.fishtown_internal_analytics.dependent": [
      "model.fishtown_internal_analytics.estimates"
    ]
}
```

```
"parent_map": {
    "model.fishtown_internal_analytics.estimates": [
      "model.fishtown_internal_analytics.dependent"
    ]
}
```

**Comment by drewbanin** [comment]
closing this in favor of a more actionable issue describing a stable API for dbt as a library. `handle_and_check` will probably remain undocumented forever. Let's revisit the spec above when we do get to an API for running dbt
