### ISSUE TITLE
dbt task to build the "catalog"

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#763]
## catalog.json

```
[
  {
    "database": "dbt",
    "schema": "public",
    "identifier": "orders",
    "type": "table",
    "column_name": "order_id",
    "column_type": "INT",
  },
  ... one entry here for every column we care about ...
]
```

**general structure**

we want a new dbt task -- `dbt catalog generate`

tasks/??.py

the end goal of this task is to:

- select all the columns that we care about
- may involve running multiple queries / multiple api calls > use adapter.execute with fetch=True, this will return a data frame as the second return value
- this data needs to unioned back together into one big list
- finally, dump that thing to disk

**what do we care about?**

for the first pass, i think this should just be the result of:

```sql
select database, schema, identifier, type, column_name, column_type from information_schema.columns
-- maybe join information_schema.tables
```

**concrete API stuff**

- new adapter function: `adapter.get_catalog_for_schemas(cls, profile, schemas: [str]) ->[dict]`

**future work**

there are two dimensions that we plan to filter / expand this on:

1. we plan to filter this down to specific schemas / tables
   - for now this isn't a big issue, because we can just throw irrelevant data away in the docs frontend
   - in the future, as we add more complex statistics and other things to this dataset, these queries actually will become slower, and it will be important to filter down to the schemas that dbt cares about

2. we plan to add statistics that may be expensive to compute so that they are easily available in the docs
   - redshift: dist skew, unsorted %, current compression vs ideal compression, etc
   - snowflake: ???
   - bigquery: ???

**Comment by cmcarthur** [comment]
schema name: analytics
table name: orders

```json
{
    "analytics": {
        "orders": {
            "metadata": {
                "name": "orders",
                "type": "BASE TABLE"
                "comment": null
            },
            "columns": [
                {
                    "type": "TIMESTAMP WITHOUT TIME ZONE",
                    "index": 1,
                    "name": "_sdc_batched_at",
                    "comment": null
                },
...

**Comment by drewbanin** [comment]
Query for postgres:
```sql
with tables as (

	select
		table_schema,
		table_name,
		table_type
		
	from information_schema.tables

),

columns as (

	select
		table_schema,
		table_name,
		null as table_comment,
		
		column_name,
		ordinal_position as column_index,
		data_type as column_type,
		null as column_comment
		
		
	from information_schema.columns
	  
)

select *
from tables
join columns using (table_schema, table_name)

where table_schema != 'information_schema'
  and table_schema not like 'pg_%'
```

**Comment by drewbanin** [comment]
Added in #768 - closing
