### ISSUE TITLE
catalog: use an Operation to generate the SQL result

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#765]
right now, we have a SQL query inline in the adapter that we use to generate the catalog. we want this to be a SQL script that's included in the global project and that is executed via a dbt "Operation."

there's an Operation node type in node_types.py -- that is the thing we want to use.

there's no OperationRunner in node_runners.py. we'll need one of those.

an operation is just arbitrary sql that gets run, committed, and has the result optionally returned. operations can be selected from the dbt graph just like any other node. but note that there is no CLI syntax for selecting operations right now. you can use dbt internal code to do that.

so the task flow would be:

- generate parsedmanifest
- generate schemas list
- find this special operation in the graph
   - this should probably be done inside the adapter function that you added previously so that we can add bigquery support later on. it's a good idea to add a helper function to dbt that allows us to find and call an operation by name very simply, because there could be other places in dbt that we want to create similar behavior
- call it and fetch the result
- process the result into the catalog

**Comment by drewbanin** [comment]
Added in #768 - closing
