### ISSUE TITLE
first time project configuration

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#77]
- [x] create ~/.dbt/profiles.yml on `dbt init` (if it doesn't exist)
- [x] clone a starter repo (cc @jthandy)
- [x] show/open profiles dir/file at end of setup
  - [x] `dbt debug --config-dir` ?

**Comment by jthandy** [comment]
david krevitt recently had the excellent suggestion that `dbt init` go through a series of interactive prompts to set up the config file. I don't think that's a must for this round, but it's a solid suggestion.

**Comment by jthandy** [comment]
@drewbanin I think we should remove this from the Minor improvements milestone. This is one that I think would benefit from @cmcarthur's input, so would rather leave it for just a bit longer if you're ok with that.

**Comment by drewbanin** [comment]
@jthandy sure, sounds good

**Comment by drewbanin** [comment]
let's think about the optimal first-time flow for dbt
