### ISSUE TITLE
"Item in ... must be str, not type"

### ISSUE THREAD

**Issue by cpdean** [fishtown-analytics/dbt#777]
I'm currently working on a personal project adding static typing to existing python code bases and I've found a type error in a few places regarding the use of the `__all__` variable in a couple submodules.

Here's an example in dbt/adapters/default/__init__.py

```
from dbt.adapters.default.impl import DefaultAdapter
from dbt.adapters.default.relation import DefaultRelation

__all__ = [
    DefaultAdapter,
    DefaultRelation,
]
```

If you `from dbt.adapters.default import *` you will get the following error:

```
TypeError: Item in dbt.adapters.default.__all__ must be str, not type
```

The typechecker `mypy` finds the same error statically:

```
- ❯❯❯ mypy --ignore-missing-imports dbt
...
dbt/adapters/default/__init__.py:6: error: Type of __all__ must be "Sequence[str]", not "List[type]"
```

I'm happy to submit the PR to fix this.  Is this something that the project wants?

**Comment by cmcarthur** [comment]
Oh, good catch. Yeah, if you can replicate the error, and then submit a PR, I'll take a look. Thanks @cpdean !

**Comment by cpdean** [comment]
@cmcarthur the above two things were replicated locally on my computer using a python REPL and the pasted `mypy` command.  Is that enough or do you want me to write a test for a star import?

**Comment by drewbanin** [comment]
PR merged here: https://github.com/fishtown-analytics/dbt/pull/780

closing!
