### ISSUE TITLE
dbt run fails if there are external BigQuery tables in same dataset

### ISSUE THREAD

**Issue by improbable-benfischer** [fishtown-analytics/dbt#791]
Besides views and tables, BigQuery also supports [tables of external type](https://cloud.google.com/bigquery/external-data-sources). When dbt materializes a model of a dataset (schema) that has external tables, it fails with
```
Invalid arguments passed to "BigQueryRelation" instance: property "type", 'external' is not one of ['table', 'view', 'cte', None]
```

# Steps to reproduce

1. In a BigQuery project, create an external table `foo.external_table` (for [example](https://cloud.google.com/bigquery/external-data-drive), use "Google Drive" as location and "Google Sheets" as file format).
1. Create a dbt project for this BigQuery project. Use `foo` as default schema.
1. Add a model `models/foo/dbt_table.sql` with any query, say `SELECT 1 as bar`.
1. Run
```
dbt run --models foo.dbt_table
```

# Log message

```
Found 0 analyses, 56 macros, 0 tests, 55 models, 0 operations, 0 seed files, 0 archives

16:16:20 | Concurrency: 8 threads (target='development')
16:16:20 | 
16:16:20 | 1 of 1 START table model foo.dbt_table............................... [RUN]
16:16:21 | 1 of 1 ERROR creating table model foo.dbt_table...................... [ERROR in 0.72s]
16:16:21 | 
16:16:21 | Finished running 1 table models in 2.06s.

Completed with 1 errors:

Runtime Error in model dbt_table (models/foo/dbt_table.sql)
  Invalid arguments passed to "BigQueryRelation" instance: property "type", 'external' is not one of ['table', 'view', 'cte', None]

Done. PASS=0 ERROR=1 SKIP=0 TOTAL=1
```

# Workaround

If there are no external tables in dataset `foo`, this works. So, moving `foo.external_table` to `baz.external_table` resolves the issue.

**Comment by drewbanin** [comment]
Thanks @improbable-benfischer, we'll take a look

**Comment by drewbanin** [comment]
Fixed in https://github.com/fishtown-analytics/dbt/pull/828, closing
