### ISSUE TITLE
Don't execute directives that are sql-commented out

### ISSUE THREAD

**Issue by vaughnkoch** [fishtown-analytics/dbt#812]
I had this at the top of a model file:
```
-- {{ config(materialized='view') }}
```

I tried adding an index via postgres like so:
```
{{
config({
    "post-hook": [
      "{{ postgres.index(this, 'external_id')}}",
    ],
    })
}}
```

Of course, I got an error effectively saying that you can't add an index to a view. I figured out that the config was still being executed even though it was commented out.  This is because jinja has a different commenting style. However, maybe dbt could check for the presence of comments and not run configs that are sql-commented out.

Side note: if you have a field like this:
``` 
-- {{ my_macro_which_should_be_commented_out() }}
```

and the macro file looks like
```
{% macro my_macro_which_should_be_commented_out() %}
   (your code here)
```
Because of the newline after the macro directive, the sql comment won't comment out the macro output since it will look like this:
```
--
  (your code here)
```
Massaging the macro to remove newlines would solve that problem. Although, it would make compiled files harder to read. I don't know what the best side of that tradeoff is.

**Comment by drewbanin** [comment]
Hey @vaughnkoch - yeah, jinja comments are your best bet here. Link for anyone else searching around: http://jinja.pocoo.org/docs/2.10/templates/#comments

In your example above, this would look like:

```
{# note: commented out because of business logic change blah blah blah
{{ my_macro_which_should_be_commented_out() }}
#}
```

Check out [this (somewhat related) issue](https://github.com/fishtown-analytics/dbt/issues/552), and feel free to add your thoughts on line statement comments over there. Also, I just added a note to update our docs to clarify sql vs. jinja comments. Closing this, but let me know if you have any questions.

**Comment by vaughnkoch** [comment]
Yeah, I'm familiar with jinja comments. The only thing is that because the model files are sql, it's really easy to think you're commenting out a line (including syntax highlighting that shows it's commented out), when it's really getting run anyways. Maybe a warning would work?

**Comment by theBull** [comment]
Part of the issue - while seemingly small - is that IDEs often bind comment hotkeys to specific files. `Cmd+/ ` on a Mac will comment out lines in VS Code, for example, which streamlines development. When using that hotkey one or more lines, VS Code will use the `.sql` file extension to add or remove `-- ` characters before the selected lines. 

Having to hunt and peck for where to put the cursor and manually remove a bunch of manually-added comments becomes a bit cumbersome. There may be a way, such as some extension or other means, to configure the IDE to handle different comments, but that's difficult when jinja and SQL are mapped to the same file extension.

Maybe its an issue I need to take up with Jinja...

**Comment by LukeFerris** [comment]
For what it's worth - this confused the living hell out of me for the best part of three months. It kept making me question how DBT was working at all. I suspect I'm not alone :)
