### ISSUE TITLE
Interpret JSON schema validator errors

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#822]
As part of #820, I implemented an attempt to clean up the schema validation error output. It was pretty messy and involved a bunch of regex matches so we removed it. 

Currently missing attributes each are a separate message, and extra attributes get combined into one. There is an actual object involved that lets you identify if it's an error about attributes being extra vs missing, but _what_ attribute is extra or missing is only available as part of the error text itself. It would be nice to have it be consistent, one way or the other.

**Comment by drewbanin** [comment]
we don't use json schemas directly anymore and we do a pretty good job of rendering these error messages anymore :)
