### ISSUE TITLE
catalog generation for redshift

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#831]
@drewbanin do we have incomplete code for this somewhere?

**Comment by drewbanin** [comment]
The version I have for redshift is identical to the existing postgres implementation. We'll need to update it for Redshift to account for:
 - views
 - late binding views?
 - sort/dist keys, column encoding, table size, etc

If I remember correctly, Redshift makes joining to some of these system table really painful. Let's see how much we can do for the v1

**Comment by beckjake** [comment]
Closed in #866
