### ISSUE TITLE
Allow archival of tables from one database.schema to a different database.schema

### ISSUE THREAD

**Issue by sborker** [fishtown-analytics/dbt#838]
I am trying to create archive tables on the raw tables that are currently in one database schema on Snowflake into a different database and schema and currently DBT does not allow for this.

**Comment by drewbanin** [comment]
Thanks for the report @sborker! This isn't currently supported, but I think we'll be able to tackle this along with https://github.com/fishtown-analytics/dbt/issues/706

In general, dbt assumes that every relation will be created in a single database. This is sort of a vestige of our initial Redshift-centric approach, where cross-db queries are not supported. I'm very much in favor of adding support for cross-db models/archives/seeds/etc, as this is applicable for both Snowflake and BigQuery.

**Comment by beckjake** [comment]
I think we resolved this while ago in #1202, which should be in 0.13.0. We've even got [tests](https://github.com/fishtown-analytics/dbt/blob/0.13.latest/test/integration/004_simple_archive_test/test_simple_archive.py#L193) for it, so if they are not right I would like to understand what's wrong!
