### ISSUE TITLE
Non-postgres tests require postgres

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#841]
Because of how the integration test setUp method works, our tests currently require postgres to be accessible even when we're only testing BigQuery, Snowflake, or Redshift. This became apparent when I split up the tests to run in parallel on circleci 2.0 (so no longer just running `tox` to get all the tests).

We should remove that dependency, and if possible preserve the current convenience offered by setUp.

**Comment by drewbanin** [comment]
Closed by #1107
