### ISSUE TITLE
Add unique_id to catalog entries to join the catalog and manifest together

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#847]
Entries in the catalog should have a unique_id for the model that created it, if applicable. Presently, we're joining the two together on simple string equality for `model_name == table_name`, but this pattern will not hold with aliases, or Snowflake casing.

dbt should find the model responsible for creating a table by comparing the schema name and alias name for each model to each schema name and relation name in the catalog.

**Comment by cmcarthur** [comment]
check that unique_id is actually unique across all of the items in the catalog.
