### ISSUE TITLE
Docs: mention configuration with env vars when introducing dbt_project.yml

### ISSUE THREAD

**Issue by butla** [fishtown-analytics/dbt#855]
I think it'd be good to mention [env var configuration](https://docs.getdbt.com/v0.10/reference#env_var) immediately in [here](https://docs.getdbt.com/docs/creating-a-project#section-dbt_project-yml) for people who don't have a lot of time for evaluating DBT, but are concerned with DevOps stuff (like managing secrets).

At first I was afraid that I'll need to put in some effort so that the secrets find their way into the YML file without being stored in our source control.

**Comment by drewbanin** [comment]
Thanks @butla. I ended up linking to the docs for this on the "[Configure your profile](https://docs.getdbt.com/docs/configure-your-profile)" page, as I thought it was a little more relevant over there. Thanks for the heads up!

**Comment by butla** [comment]
@drewbanin Thanks, I'm sure it'll help the other newcomers :)
