### ISSUE TITLE
objects not found during dbt run on Snowflake

### ISSUE THREAD

**Issue by bobzoller** [fishtown-analytics/dbt#868]
According to [Snowflake docs](https://docs.snowflake.net/manuals/sql-reference/transactions.html#scope-of-a-snowflake-transaction) and our manual testing:

> DDL statements are always autocommitted, regardless of the AUTOCOMMIT setting.

This means that the two `ALTER TABLE ... RENAME` statements in the [view](https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/materializations/view/view.sql#L55-L58) and [table](https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/materializations/table/table.sql#L69-L72) materializations are not atomic, and there is some period of time between them where the object does not exist.

Though I'm sure the window is small, we actually hit it on a regular basis and our usage on the query side is almost non-existent right now. (eg we think we're going to hit this more and more)

Has this been discussed before?

/related to #653
/cc @swettk @jthandy 

---

In parallel, I'm reaching out to Snowflake support as a workaround is not immediately obvious.  They have a [`CREATE OR REPLACE TABLE ... CLONE`](https://docs.snowflake.net/manuals/sql-reference/sql/create-clone.html) that smells viable, until you learn that `CLONE` is not atomic.  Our sales engineer suggested [`ALTER TABLE ... SWAP`](https://docs.snowflake.net/manuals/sql-reference/sql/alter-table.html#parameters), but it has some semantics around grants that make it less ideal.

**Comment by jthandy** [comment]
Yep--this is something we're aware of and have been paying attention to. In our upcoming patch release (0.10.2) I believe we're moving to the swap methodology, but I'm not plugged in enough to know that for sure. Feel free to PM Drew in slack about this. I think that this is the only mechanism to accomplish this given Snowflake's lack of transactional support for DDL. If you have some reason to believe that the swap mechanism won't work, I'd be interested to hear it. As far as I know it's worked out ok for us in testing...

**Comment by bobzoller** [comment]
my concern with swap is this bit from [their alter table docs](https://docs.snowflake.net/manuals/sql-reference/sql/alter-table.html#parameters):

> Also swap all access control privilege grants.

So if I'm reading that right, I think swap could work but you'd have to copy all grants on the target to intermediate before you issue the rename, otherwise just after the rename the target table exists but is no longer accessible (YMMV depending on your particular grants setup).

I'm hoping Snowflake support can give a definitive answer to all of this as it seems like a pretty common use case.

**Comment by jthandy** [comment]
Yep! That's right. The new table needs to have all privileges granted to it every time dbt runs. This happens already with how dbt works given that all table and view materialization models are created from scratch each time. We are already set up for this in our project. It wouldn't be copying all grants, it's just that every time dbt creates a table it re-executes all grants from scratch on that table based on config within the project.

**Comment by drewbanin** [comment]
We did investigate `alter table ... swap ...` and I think it's definitely the right approach here. There's a somewhat relevant discussion over [here](https://github.com/fishtown-analytics/dbt/issues/724) too.

This isn't in the 0.10.2 milestone, but I'm super open to adding it for 0.11.0!

**Comment by bobzoller** [comment]
In our current setup the grants happen in a posthook though, which means there's again some period of time (small though it may be) where the tables are inaccessible.  If you could clone the grants on the target table to the intermediate table just _before_ the `alter table ... swap ...`, that seems the closest you could come to an atomic rename in Snowflake.  (though we'll see if their support has any more ideas)

**Comment by jthandy** [comment]
@bobzoller that actually is the ordering currently--the grants get executed before the rename :) Going to send you some logs via PM.

**Comment by bobzoller** [comment]
:+1: ah nice.  unexpected that something called `post-hooks` actually runs before the rename, but I'll take it ;)

seems like I'll close this in favor of #724 ... and yes, would love to see this in 0.11.0.  (perhaps I can find time to help with a PR)
