### ISSUE TITLE
add flag to fail on first error, or to print the error inline when it occurs

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#871]
It's presently tedious to debug a long-running dbt invocation. If a failure occurs, you need to wait until the invocation completes to see the error. This is prettier for most runs, but can be frustrating for long-running development runs.

Proposed flags:
- add a `-x` command to fail on first error
- add a `--nocapture` command to spit out errors as they occur?

**Comment by cmcarthur** [comment]
I like `-x, --fail-on-error`
