### ISSUE TITLE
fetch rich catalog information about table stats

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#875]
All adapters:
- relation owner
- created/modified at (if exists)

BigQuery (via api):
 - Table Size
 - Number of Rows
 - Created
 - Table Expiration
 - Last Modified
 - Data Location
 - Partitioned by (if partitioned)
 - Partitioned on field (if partitioned)
 - We probably also need to account for date-sharded tables.....

Redshift:
- via svv_table_info:
  - size
  - pct_used
  - empty
  - unsorted
  - stats_off
- via pg_table_def
  - sort key
  - dist key
  - encoded?

Snowflake (via information_schema.tables):
 - clustering key
 - row count
 - bytes
 - created
 - last_altered

Should this hide behind a flag? Fetching from svv_table_info can be really slow on Redshift, and I think it requires admin creds

**Comment by cmcarthur** [comment]
you can also get `tbl_rows` from redshift (unvacuumed row count)

does this look right:

|   | Postgres | Redshift | Snowflake | Bigquery |
| - | - | - | - | - | 
| __GENERAL__ | | | |
| Owner | ✅ | ✅ | ✅ | ✅ |
| Created at | ? | ? | ✅ | ✅ |
| Last modified at | ❌ | ❌ | ✅ | ✅ |
| Size in Bytes | ? | ✅ | ✅ | ✅ |
| Row Count | ? | ✅ | ✅ | ✅ |
| __SORT, DIST, PARTITION__ | | | |
| Sort Key | ❌ | ✅ | ❌ | ✅ |
| Partition / Clustering Key | ❌ | ✅ | ✅ | ✅ |
| Partition / Clustering Skew | ❌ | ✅ | ❌ | ❌ |

Adapter-specific:

__Redshift__: encoding, (last vacuumed at?)
__Snowflake__: none
__Bigquery__: date-sharding
__Postgres__: none

**Comment by drewbanin** [comment]
@cmcarthur I had a hard time getting `created at` and `last modified at` at to work correctly, so I left them out for now. I think that's ok, as these fields would probably be confusing. Tbh I was unable to find reliable docs on which exact times they refer to (last time the table was altered? last time the table was inserted into?).

I also couldn't find the BigQuery partitioning field. I could see that a given table is partitioned by `DAY`, but not that the field was eg. `collecor_tstamp`. I think we _might_ need to bump out version of google-cloud-bigquery to see it.

Otherwise, this matrix looks right to me!
