### ISSUE TITLE
DBT should link to schema.yml documentation when parsing fails

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#886]
### Feature description
In the upcoming isaac-asimov release, we merged a new schema.yml format. In the parser, we do a version check, but if the version and format don't match we should point users at some documentation - currently we just error out. (see https://github.com/fishtown-analytics/dbt/pull/880#discussion_r205296017)

### Who will this benefit?
People who write an invalid schema.yml and try to run dbt.

**Comment by drewbanin** [comment]
Check out a preview of the 0.11.0 docs here: https://docs.getdbt.com/v0.11/docs/schemayml-files

You should be able to link to a specific section of the docs. Let me know what anchor you end up using, and I'll make sure that it doesn't change between now and when the docs go public

**Comment by beckjake** [comment]
I get a 404 on that link (and on any link involving `v0.11`).

**Comment by drewbanin** [comment]
ah, sorry, had to make it public. It should be up now

**Comment by beckjake** [comment]
Fixed in #926
