### ISSUE TITLE
Roadmap/plan for caching relations

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#894]
### Feature description
Write up a roadmap / feature plan for caching relations.

In dbt, we currently pull the entire list of relations from the database in every materialization. We would like to implement caching on the list of relations, but cache invalidation is pretty tricky and dbt (especially via hooks, etc) can potentially invalidate or modify existing relation data. Since pulling the list of relations costs the same whether it's everything in a schema or just one relation, we want to be judicious about when we decide to actually pull new relation data (not just every time anything is invalidated). This is a big deal on some databases that have very slow metadata queries.

Things I know we need for this:
 - some way for end users/materializations to manually invalidate the cache
 - some level of smarts around `drop_relation` and similar that invalidates the relation in the cache
 - some way of determining that we are only dealing with valid relations in a given materialization and do not need to query the database

This is also to some degree a research spike for me to learn more about how all this works currently.

### Who will this benefit?
This will benefit the developers when we go to implement this feature!

**Comment by cmcarthur** [comment]
@beckjake can this be closed?

**Comment by beckjake** [comment]
@cmcarthur yup
