### ISSUE TITLE
Raise Hard Stop

### ISSUE THREAD

**Issue by norton120** [fishtown-analytics/dbt#898]
### What? 
An error condition that can be raised in the Jinja context that causes the entire run to exit (not just the current model). 

### Who will this benefit?
Sometimes an error condition is so severe that we want the entire transform process to stop. For example, if 200 stores all report 0 sales for last week something is probably wrong with the EL process, and we don't want to continue updating production tables knowing the source data is in question. Better to stop the entire run at the point a 'Halt' level error is identified.

**Comment by cmcarthur** [comment]
@norton120 hey! let's say there was a `{{raise(...)}}` function you could call from dbt jinja -- can you provide some example code you might use to halt your run?

**Comment by norton120** [comment]
So my thought right now would be to run it at the beginning of guarded models hitting our `error_event_fact` table. Each error event has a severity level - ignore, flag, remove, or halt. 
- ignore does just what it sounds like, but still makes note as a row in the table
- flag adds a flag to the record that an error was detected
- remove eliminates the record
- halt *should* stop warehouse processes. Let's say `error_event_fact` generates a row if daily sales is more than 5 standard deviations from the prior year. it would look like this: 

`{% call statement('check_for_halt', fetch_result=True) %}
             SELECT * FROM error_event_fact WHERE severity = 'Halt' AND audit_key = (SELECT MAX(audit_key) FROM error_event_fact)
{% endcall %}                                              
{% if load_result('check_for_halt')['data'] | length > 0 %}
     {% raise('stop the presses!!') %} 
{% endif %}
-- Then go about your model code and not worry about bad source data`

**Comment by drewbanin** [comment]
This isn't something we plan to prioritize, and I think dbt does a decent enough job of approximating this today. If a model fails, then any models which depend on this model will be skipped. See also the discussion of "run modes" over here: https://github.com/fishtown-analytics/dbt/issues/1054

Closing, but happy to discuss!
