### ISSUE TITLE
Redshift external table definitions

### ISSUE THREAD

**Issue by martinmelin** [fishtown-analytics/dbt#901]
### Feature description

Context from Slack: https://getdbt.slack.com/archives/C2JRRQDTL/p1533315273000059?thread_ts=1533246671.000100&cid=C2JRRQDTL

We use [Redshift Spectrum](https://docs.aws.amazon.com/redshift/latest/dg/c-using-spectrum.html) external tables to read data from S3. The table definition needs a place to live, and would ideally be updated ahead of every `dbt` run. However, to execute `CREATE EXTERNAL TABLE` the user needs to either be a superuser or the owner of the schema the table is being created in. It would be great to be able to have a place to put a hook that runs with different credentials than the rest of the `dbt` run.

Alternatively, this could be solved with a `dbt` command that would execute a particular SQL file with a given `dbt` target, which would let us script this like:
```
dbt exec --target=spectrum-owner redshift-spectrum-setup.sql
dbt run
```

### Who will this benefit?

Helpful for all kinds of initialization that needs to be run to prepare for a `dbt` run with different credentials.

**Comment by drewbanin** [comment]
Thanks for the writeup @martinmelin!

Is there any penalty for having _many_ external tables that all point to the same data in S3? I think the dbt way of doing this is for each dbt user to have their own external schema, containing their own external tables. That way, devs can make changes in their own (external) schemas without affecting the work of other devs, or the production dbt user.

In order for dbt to properly support Spectrum, I think we'll need:
1. the ability to create `external schema`s
2. the ability to create `external table`s

I'm unsure of how to best implement external schemas, but I think there are definitely a couple of options. One might be to just create these schemas in the `on-run-start` hooks for the project. Another implementation might look more like configuration (in `dbt_project.yml`?)

For external tables, I think we pretty easily account for those with a [materialization](https://docs.getdbt.com/docs/creating-new-materializations). This should be pretty straightforward based on the documentation [here](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_EXTERNAL_TABLE.html).

I'm not super interested in maintaining all of the external table options in dbt, eg:
```
partitioned by (saledate date)
row format delimited
fields terminated by '|'
stored as textfile
location 's3://awssampledbuswest2/tickit/spectrum/sales_partition/'
table properties ('numRows'='170000');
```

I think a good approach might be to just make a `raw` materialization which accepts `create table` SQL like this:
```
create external table spectrum.sales_part(
salesid integer,
listid integer,
sellerid integer,
buyerid integer,
eventid integer,
dateid smallint,
qtysold smallint,
pricepaid decimal(8,2),
commission decimal(8,2),
saletime timestamp)
partitioned by (saledate date)
row format delimited
fields terminated by '|'
stored as textfile
location 's3://awssampledbuswest2/tickit/spectrum/sales_partition/'
table properties ('numRows'='170000');
```

Last we'd have to think through partitioning.... The more of this issue, the more involved I realize this feature is! So, lots to discuss here. Keen to hear your thoughts!

**Comment by drewbanin** [comment]
@martinmelin I'm going to close this issue, as I think external tables should (probably) be created manually (there should only be one in your Redshift!). That said, I think it's a great idea to version the DDL along with your dbt models!

This might be a good way to accomplish something similar in the future: https://github.com/fishtown-analytics/dbt/issues/582
