### ISSUE TITLE
dbt downloads bumpversion.cfg when it doesn't need it

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#907]
### Issue description
In `main.py`, dbt imports `version.py`. At the bottom of `version.py`, dbt will _always_ fetch the `.bumpversion.cfg` file to determine the latest version of dbt.

dbt should instead only fetch the latest version from github if `dbt --version` is run.

This happens on dbt v0.10.2.

**Comment by thenaturalist** [comment]
This behaviour currently completely breaks dbt when trying to run it offline.

**Comment by beckjake** [comment]
Fixed in #949
