### ISSUE TITLE
Provide a mechanism for granting usage to schemas in on-run-end

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#908]
### Feature description
If a user makes use of custom schemas, then `on-run-end` cannot currently be used to grant usage to the schemas on Redshift/Snowflake/Postgres. This problem arises because there are N schemas, but the only schema available in the context is the schema defined in the target.

dbt should provide in it's context a list of schemas that were built into during the dbt run.

Example usage:
```
on-run-end:  {% for schema in schemas %}grant usage on {{ schema }} to PUBLIC;{% endfor %}
```

We probably will want to namespace `schemas`, but this is the general idea.

### Who will this benefit?
This will be useful specifically for Redshift users. Currently, granting usage to a schema must happen in `post-hook`s, and Redshift appears to raise concurrent transaction errors if usage is granted to a schema while other models are being created/dropped in that schema (ie. with threads > 1)

**Comment by beckjake** [comment]
Fixed in #1028
