### ISSUE TITLE
enhance `Unique` vaildation in schema.yml

### ISSUE THREAD

**Issue by hui-zheng** [fishtown-analytics/dbt#912]
Please make sure to fill out either the issue template or the feature template and delete the other one!

## Feature
Enhance `Unique` condition test in schema.yml to test uniqueness across mulitple fields. 

### Feature description
In current schema validation, `Unique` Validates that there are no duplicate values present in a field. 
for example, 
```People
  constraints:
    unique:
      - id
```
In many situations,  the uniqueness presents not in a single filed, but the combination of multiple fields. 
For example, A account contact is unique in a combination of (account_id, email).
However, the current `unique` does not support validation on a fields combination.  
the validation below 
``` account_contact:
  constraints:
    unique:
      - master_account_id, email
```
after compile turns into SQL statement below

```    select
      master_account_id, email
    from account_contact
    where master_account_id, email is not null
    group by master_account_id, email
    having count(*) > 1;
```

which throws an error when it runs because `where master_account_id, email is not null` is not valid SQL.

###
We could make a simple code change to allow this happens, by adding () to the fields pairs in SQL. make it look like this `where (master_account_id, email) is not null` . This condition evaluates to true when both master_account_id and email are null. 

The full SQL statement will become like below
```
select
      master_account_id, email
    from account_contact
    where master_account_id, email is not null
    group by master_account_id, email
    having count(*) > 1;  
```

With the current design, this is possible with a simple code change. 

### Who will this benefit?
Any tables with a combination of multiple fields as a unique key and those who build and develop data marts on top of these tables will benefit from this.

**Comment by drewbanin** [comment]
hey @hui-zheng - I think an easy way to work around this is to just provide the parentheses yourself! I think this should work:

```
account_contacts
  constraints:
    unique:
      - (master_account_id || email)
```

**Comment by drewbanin** [comment]
I'll add - I think the best practice here is to create a surrogate key for the column, then test the uniqueness of _that_ key.

This is a really slick implementation @hui-zheng and I'm glad you shared it with us! That said, I don't think we're going to build it, as it's possibly _too_ clever (will it work on all databases?), and there are a number of other workarounds (override the test locally, build a custom test, built a surrogate key, pass an expression in schema.yml).

Going to close this, but feel free to re-open if you'd care to discuss!
