### ISSUE TITLE
support clustering on BigQuery

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#918]
### Feature description
BigQuery recently announced support for table clustering. With this new feature, a list of up to four "clustering columns" can be supplied to a `create table as (...)` statement. BigQuery will use the clustering columns to colocate similar data. This should speed up filters and aggregations, and BigQuery can both skip scanning whole blocks of data, as well as avoid shuffling data between nodes for certain aggregations. Docs: https://cloud.google.com/bigquery/docs/creating-clustered-tables

### Who will this benefit?
This feature will benefit users of BigQuery. It will work in concert with table partitioning.

### Proposed Implementation
This feature can be implemented in the BigQuery implementation of [create_table_as()](https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/adapters/bigquery.sql#L14). It's implementation will look similar to the `partition_by` implementation.

**Comment by beckjake** [comment]
`cluster_by` can't be used without `partition_by`. Should we enforce that in the macro, or let the database return the error when a user doesn't specify both?

**Comment by drewbanin** [comment]
Yeah, I'm fine with letting BQ return an error in that scenario

**Comment by beckjake** [comment]
Fixed in #978
