### ISSUE TITLE
Ephemeral models injected in the wrong order

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#927]
### Issue description
We caught this one in the wild using an 0.11.0 prerelease (development) in sinter.

dbt errantly injected ephemeral models in the wrong order, leading to an error like:
```
relation "__dbt__cte__model_name" does not exist
```

The issue was that `__dbt__cte__model_name` was defined _below_ where it was called from. The compiled SQL looked something like this:

```
with __dbt__cte__dependent_model as (

  select * from __dbt__cte__model_name

),  __dbt__cte__model_name as (

  select * from public.data

)

select ....
```

It appears that this is a regression in `development` (the same code works in 0.10.2) but I can't immediately identity any changes we made to this part of the codebase.

**Comment by beckjake** [comment]
I probably caused this in the PR where I changed things from using the flat_graph to using the manifest. In particular, `dbt.compilation.prepend_ctes`.

Is the trick to have ephemeral models that depend upon each other?

**Comment by cmcarthur** [comment]
Could very well be either of these:
- https://github.com/fishtown-analytics/dbt/commit/74b33f483bf50a2ab1d6143f778113bb30cdedbe#diff-31186f2642031d69b53e5db816518cc3
https://github.com/fishtown-analytics/dbt/commit/2690b5098662063f7d9bbc57049d5cf6cca07f56#diff-31186f2642031d69b53e5db816518cc3R57

**Comment by beckjake** [comment]
I'll look into this next, I have a couple ideas around it. One possibility is that the OrderedDict is getting turned into a regular dict somehow and the order is getting lost. We'll probably want to create a failing test case to help track it down.

**Comment by cmcarthur** [comment]
@beckjake yes, this does look like a case where an ephemeral model depends on another. should be relatively easy to repro
