### ISSUE TITLE
Statement Runs out of DAG Order In 0.10.2

### ISSUE THREAD

**Issue by norton120** [fishtown-analytics/dbt#933]
### Issue description
We have rather complex business logic executed in models that depend on updated results from the previously run model in the DAG. Before upgrading to 0.10.2 the statement returns reflected the previous model's transforms; after upgrading to 0.10.2 statement returns pre-transform results. 

### Results
Statement running in `dbt run` seems to be executed during compile, before previous models in the dag to where it is declared are run? 

### System information
The output of `dbt --version`:
```
installed version: 0.10.2
latest version: 0.10.2

Up to date!
```

The operating system you're running on:
Ubuntu 16.04
The python version you're using (probably the output of `python --version`)
2.7
### Steps to reproduce
Our statement grabs the max row from the table created by the previous model with some predicates and uses values from that row as predicates in the current model. Before upgrading to 0.10.2 the predicates accurately reflected the updated table from the previous model in production db query history. after the upgrade the statement returns 0 rows when run with a full `dbt run`. 

If we run the first dbt run using `--models` and then run the remaining models excluding the first model, the statement functions as expected and the run is a success. 
```
/// this fails
dbt run

// this works! 
dbt run --models AUDIT;
dbt run --exclude AUDIT
```

**Comment by drewbanin** [comment]
Thanks for the report @norton120. I don't know that I totally understand the behavior that you're describing here. Can you share an example model with me? In particular, I'm confused about this part:
> Our statement grabs the max row from the table created by the previous model with some predicates and uses values from that row as predicates in the current model

I don't really understand what you're describing here, and an example would be really helpful

**Comment by norton120** [comment]
Sure, here's model pseudocode: 

```
---------- model AUDIT.sql
SELECT 
         generated_new_unique_id,
         'In Process' AS status

---------- model DEPENDS_ON_A_NEW_AUDIT.sql
{%- call statement('get_in_process_audit', fetch_result=True) -%}
          SELECT
                    generated_new_unique_id
          FROM
                    AUDIT
          WHERE
                    status = 'In Process'
{%- endcall -%} 
{% set audit_response_data_object = load_result('get_in_process_audit')['data']%}
#}
{% if audit_response_data_object | length > 0 %}
         ---- do all the things here
{%- else -%}
       ---- create an insert set that is typed correctly with 0 rows
        SELECT
                NULL::integer AS primary_key,
                NULL:varchar AS hamburger
         WHERE 1=0
{%- endif -%} 

----------- THIS_RUNS_LAST.sql
SELECT
...
--- lots of things happen here

---- then in the post-hook it goes back and completes all the audits.
{{config({ "post-hook" : "UPDATE audit SET status = 'Completed';" })}}
```

So.... before we upgraded to 0.10.2 this worked as expected. Now it looks like maybe the statement runs on compile, so there is no "In Process" row waiting and it returns 0. :( 

Let me know what you think

**Comment by drewbanin** [comment]
@norton120 indicated that there was a missing `ref`, so the graph was misshapen. Closing this
