### ISSUE TITLE
Expose version In Model Jinja Context

### ISSUE THREAD

**Issue by norton120** [fishtown-analytics/dbt#934]
### Feature description
We have a required param in `dbt_project.yml` for version, but that param is not available anywhere in the model context. For audit tables this would be really nice to reference directly. 

### Who will this benefit?
Right now we are manually assigning a version number, dbt version and release name as vars in `dbt_project.yml`. Then on audit records we end up calling 
```
{{var(dbt_version)}} AS dbt_version,
{{var(app_version)}} AS app_version
```
instead of `{{this.dbt_version}}` and `{{this.app_version}}`. One of the team members updated the app version yesterday and accidentally updated the required version param at the top of `dbt_project.yml` instead - very confusing :(

**Comment by boxysean** [comment]
Hi folks I started looking into this one to understand the dbt code.

It looks like I need to add something like `this` or `version` to the `context` variable in `dbt.context.common.generate_base`, either as a attr or a function. 

I can't tell what file I would test this in. I think both the `runtime` and `parser` contexts will need to be able to handle this -- is there something that tests the common case where I can pass in a model file that looks like `select {{ this.version }}` and see the version number as a result?

Anyways, tips for where to add test cases to implement the code would be helpful. Thanks! :-)

**Comment by boxysean** [comment]
@drewbanin Okay so it sounds like you want to expose absolute and relative version numbers. I've [made a gist of all the files](https://gist.github.com/boxysean/dc782cdc1b1942cf95ac69366d263a37) in the example you mentioned.

Here's what I suggest we do:

### Absolute version numbers

Suppose we're running dbt version `0.12.1` and we have the following model in {{ my_project }}:

```
# absolute_version_check.sql
select
  {{ dbt_version }} as dbt_version,
  {{ project.my_project.version }} as my_project_version,
  {{ project.snowplow.version }} as snowplow_version,
  {{ project.dbt_utils.version }} as dbt_utils_version;
```

The result of this model would be:

```
+-------------+--------------------+------------------+-------------------+
| dbt_version | my_project_version | snowplow_version | dbt_utils_version |
+-------------+--------------------+------------------+-------------------+
| 0.12.1      | 1.0                | 0.1.0            | 0.0.1             |
+-------------+--------------------+------------------+-------------------+
```

### Relative version numbers

How about using [python's magic method syntax](https://rszalski.github.io/magicmethods/#comparisons)? This is a good indicator to the developer that something special is going on. Do you have any conventions like this in dbt? I don't think SQL has any conventions like this.

Suppose we have the following model in each of the projects `my_project`, `snowplow`, and `dbt_utils`:

```
# relative_version_check.sql
select
  {{ project.__current__.name }} as project,  -- could add a name in here as well
  {{ project.__current__.version }} as current_project_version,
  {{ project.__root__.version }} as root_project_version;
```

Then the results of the `relative_version_check` model will be, in the respective projects:

```
+------------+-------------------------+----------------------+
| project    | current_project_version | root_project_version |
+------------+-------------------------+----------------------+
| my_project | 1.0                     | 1.0                  |
+------------+-------------------------+----------------------+

+------------+-------------------------+----------------------+
| project    | current_project_version | root_project_version |
+------------+-------------------------+----------------------+
| snowplow   | 0.1.0                   | 1.0                  |
+------------+-------------------------+----------------------+

+------------+-------------------------+----------------------+
| project    | current_project_version | root_project_version |
+------------+-------------------------+----------------------+
| dbt_utils  | 0.0.1                   | 1.0                  |
+------------+-------------------------+----------------------+
```

**Comment by drewbanin** [comment]
@boxysean i really like this! I'm not certain that the magic underscores are the right approach, but I'm also not opposed to it. I think this is spec is complete enough to write some code off of -- do you feel like you're well equipped to start on it? Let me know if there's any info I can provide that would help you out here.

**Comment by drewbanin** [comment]
Check out the docs for [dbt_version](https://docs.getdbt.com/docs/writing-code-in-dbt/jinja-context/dbt_version).

We haven't added support for grabbing a project/package's version from the context, and that's something we can do in the future, but I'm going to close this issue until we decide to prioritize that change.

**Comment by melaanya** [comment]
I fully agree that it would be great to have `version` exposed!
