### ISSUE TITLE
Skip profile validation when not necessary

### ISSUE THREAD

**Issue by elexisvenator** [fishtown-analytics/dbt#947]
When running `dbt deps`, dbt will first call the profile validation code. As dbt deps does not actually use the profile for anything, it should not actually need to validate the profile, or even check if one exists. Other commands such as `dbt clean` can benefit from this as well.

Example use case:
Calling `dbt deps` as part of docker build, at which point the environment variables are not yet set (they are only set at runtime)

**Comment by drewbanin** [comment]
Thanks for the report @elexisvenator!

**Comment by beckjake** [comment]
This was actually fixed as part of #973, I did not realize there was a separate issue for this!
