### ISSUE TITLE
Error with var validation code

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#956]
### Issue description
During compilation, dbt runs some asserts on `var`s to ensure that they're well defined. One such check, [assert_var_not_none](https://github.com/fishtown-analytics/dbt/blob/development/dbt/context/common.py#L239), calls out to [dbt.utils.get_model_name_or_none](https://github.com/fishtown-analytics/dbt/blob/development/dbt/utils.py#L65) passing in a `ParsedNode` as the `model`. The parsed node falls through to the `else` block (intended for the very old-school `Model` object I think) where an error like this occurs:

```
Encountered an error:
'ParsedNode' object has no attribute 'nice_name'
```

Instead, dbt should should call `.name` on the ParsedNode to get its name.

**Comment by beckjake** [comment]
fixed in #958
