### ISSUE TITLE
Rethink rendering of fields in dbt_project.yml and profiles.yml

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#960]
### Feature description
dbt is not very explicit about which fields in config files support jinja, and which jinja functions they support. We can do a better job of breaking this up into groups, for example:

- essentially all fields in dbt_project.yml and profiles.yml should support {{env_var(..)}} and {{var(..)}} and should be rendered immediately
- specific fields in dbt_project.yml support a larger context, for example `on-run-end` accepts a fuller context

### Who will this benefit?
everyone

**Comment by cmcarthur** [comment]
depends on #953

**Comment by beckjake** [comment]
implementation note: rendering of all hooks really has to wait for runtime. I think all other fields can and should be rendered immediately, though some (like models/seeds/archive) will be tricky since they're pretty free-form.
