### ISSUE TITLE
Add dataset location config to BigQuery profile

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#969]
### Feature description
BigQuery doesn't allow data to be transferred between locations (eg. `EU` to `US`). To remedy this, dbt should allow a `location` config in BigQuery profiles. That value should be supplied when creating datasets [here](https://github.com/fishtown-analytics/dbt/blob/development/dbt/adapters/bigquery/impl.py#L475).

This can be implemented by setting the `location` argument in `google.cloud.bigquery.client.Client()` as described [here](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client). If I understand this correctly, all subsequent API actions will be location-aware. We will know this works when `table`s fetched from the BQ API have a `location` attribute that is not `None`.

The `location` field should be a parameter in a BigQuery profile.

### Who will this benefit?
BQ users with their data in non-US regions.

**Comment by darrenhaken** [comment]
Is this in now?

**Comment by drewbanin** [comment]
@darrenhaken this is currently unreleased, but will be going out in our Grace Kelly release in January, 2019. You can always consult our [Milestones](https://github.com/fishtown-analytics/dbt/milestones) to understand which release a given issue is shipping with.

**Comment by paulooctavio** [comment]
Has the feature already been released?
