### ISSUE TITLE
[Regression] hooks defined in models (with config()) are not run in 0.11.0

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#984]
### Issue description
I think that in 0.11.0, hooks defined inside of models, eg.
```
{{
  config({
    "post-hook": "select 1"
  })
}}
```

don't actually run. I tried tracing this down, but got lost where dbt generates the context. Hooks defined in `dbt_project.yml` look like they still work.

### Env
python 3.7
dbt 0.11.0

**Comment by beckjake** [comment]
Fixed in #985
