### ISSUE TITLE
Specify target on a per-model basis

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#986]
### Feature description
dbt should support the configuration of targets on a per-model basis. This would make it possible to use different logical databases or logical warehouses for different models. One particularly compelling use case is on Snowflake, where a really expensive model could run against a more powerful logical warehouse.

I'm unsure if it makes sense to reference a target in `profiles.yml` by name, or if models should just accept database-specific config keys like `warehouse: ` or `database: ` as . they currently do with `schema`.

I don't think it's specifically important (or desired) to make it possible to support the building of models in different physical databases, but that would certainly be an interesting paradigm.

### Who will this benefit?
Primarily Snowflake users, though the ability to render models into different logical databases is compelling on all warehouses.

**Comment by tayloramurphy** [comment]
Maybe a little off-topic, but I would like to see dbt / Fishtown come out with a strong opinion on how to name/refer to some of these pieces. I've found Snowflake's language around Databases and Warehouses to be confusing so I would advise against using their language to define this feature.

It feels wrong to say that Redshift/Snowflake/BigQuery are both databases and data warehouses, while Snowflake has an internal concept of Databases and Warehouses. Postgres has language around a server managing multiple databases so maybe "database" it just used inconsistently.

Adding new config keys like database and warehouse would add to the initial confusion of what dbt is doing, but I think it's a useful feature, particularly for snowflake. Maybe `compute` and `storage`?

**Comment by drewbanin** [comment]
Configuring model target databases is covered here: https://github.com/fishtown-analytics/dbt/issues/1183

While I still think that configuring warehouses are interesting, I don't think it's something we intend to build in the near future. If we did, it certainly would be through a `warehouse` model config, and not via a target. Closing this.

----

@tayloramurphy I think I missed this! If you check out https://github.com/fishtown-analytics/dbt/issues/1183, you can find some info about config "aliasing" that's coming to dbt. I think you're right that the database/warehouse terminology is a little muddied at the moment, especially on Snowflake. We're tackling the lower hanging fruit now, which includes calling mapping dbt's internal configs to the proper names on BQ. That is:

- project --> database
- schema --> dataset

I think this is one of those cases where no abstraction is better than an incorrect abstraction. `compute` and `storage` is pretty clever for Snowflake, but as we enter into a Presto world, these lines become even more blurred! So, happy to give this more thought (and chat on Slack if you're still interested) but closing this particular issue.
