### ISSUE TITLE
better handling of git errors in `dbt deps`

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#994]
### Feature description
`dbt deps` can fail for myriad git-related reasons (git isn't installed, the repo can't be cloned, the branch doesn't exist, etc).

dbt currently shows an error like this:
```
$ dbt deps
Encountered an error:
[Errno 2] No such file or directory: '/var/folders/ql/lb0scpz112lfpcq497_mm3gc0000gn/T/dbt-downloads/18bf9a8e7f78e7bc3bd5414483d4e3f1'
```

whereas it should instead show the relevant git operation which failed.

The failure is usually visible in the logs, but I got the error above because of a bad spec in `packages.yml`, which was confusing.

### Who will this benefit?
folks who use packages

**Comment by beckjake** [comment]
Resolved in #1110
