### ISSUE TITLE
Seed csv table behaviour has changed since 0.10.2

### ISSUE THREAD

**Issue by elexisvenator** [fishtown-analytics/dbt#996]
Handling of nulls and column types appears to have changed in dbt 0.11

For example, given this csv file:
```csv
text_column,int_column_1,int_column_2,int_column_3,int_column_4,date_column_1,date_column_2,date_column_3
a,1,1,1,1,2012-01-01,2012-01-01,2012-01-01
b,2,2,2,2,2012-01-01,2012-01-01,2012-01-01
c,3,3,,3,2012-01-01,,2012-01-01
,,4,4,4,,2012-01-01,2012-01-01
```

In 0.10.2, `dbt seed` will output:
![seed_dbt_0 10 2](https://user-images.githubusercontent.com/2984373/45396113-f9538380-b67c-11e8-85ca-7f5b4d22d207.PNG)

In 0.11, `dbt seed` will output:
![seed_dbt_0 11 0](https://user-images.githubusercontent.com/2984373/45396251-c3fb6580-b67d-11e8-98f5-ee5e16416938.PNG)

Every date and integer column with a blank ('null') column has been misinterpreted as a text column.

**Comment by drewbanin** [comment]
thanks @elexisvenator! I beat you to it with this issue: https://github.com/fishtown-analytics/dbt/issues/993

Which was fixed here: https://github.com/fishtown-analytics/dbt/pull/995

It would be _super_ helpful if you could try installing from that branch and letting us know if it fixes this issue for you!

**Comment by elexisvenator** [comment]
Just installed from that branch, both the example above and my project which had the issue work fine now. Thanks!
